from playwright.sync_api import sync_playwright
import pathlib,atexit,json
url='file://'+str(pathlib.Path('preview.html').resolve())
log=[];atexit.register(lambda: print('\n'.join(log)))
with sync_playwright() as p:
    b=p.chromium.launch()
    for W,stage in ((390,'A'),(1280,'B')):
        pg=b.new_page(viewport={'width':W,'height':860})
        pg.on('pageerror',lambda e:log.append('PAGEERR '+str(e)))
        pg.route("**/pinyin-pro*/**",lambda r:r.fulfill(path='pinyin-local.js',content_type='application/javascript'))
        pg.goto(url);pg.wait_for_timeout(500)
        if pg.locator('#asGuest').count():pg.click('#asGuest')
        pg.evaluate("s=>{localStorage.setItem('wiw2-stage:guest',JSON.stringify(s))}",stage);pg.reload();pg.wait_for_timeout(600)
        ov=lambda h: log.append(f'{W} OV {h}') if pg.evaluate("document.documentElement.scrollWidth>innerWidth+1") else None
        pg.evaluate("location.hash='en-home'");pg.wait_for_timeout(500);ov('home')
        log.append(f'{W}{stage} startcard {pg.locator(".startcard").count()} badges {pg.locator(".lvbadge").count()} try5: '+pg.evaluate("[...document.querySelectorAll('.try5 .chip')].map(c=>c.textContent).join(' | ')"))
        pg.screenshot(path=f'r14-home-{W}.png')
        pg.evaluate("location.hash='en-today'");pg.wait_for_timeout(500)
        log.append(f'{W} visible models: '+str(pg.evaluate("[...document.querySelectorAll('#main .model')].filter(m=>m.offsetParent).length")))
        pg.evaluate("location.hash='en-studio'");pg.wait_for_timeout(400);log.append(f'{W} studio: '+pg.inner_text('#main .cnt'))
        pg.evaluate("location.hash='en-climax'");pg.wait_for_timeout(400);ov('climax');log.append(f'{W} jumpbar {pg.locator(".jumpbar").count()} stack {pg.locator(".tbl.stack").count()}')
        pg.screenshot(path=f'r14-climax-{W}.png')
        pg.evaluate("location.hash='en-feelings'");pg.wait_for_timeout(400);log.append(f'{W} feel pills visible '+str(pg.evaluate("[...document.querySelectorAll('.emo-pill')].filter(p=>p.offsetParent).length")))
        pg.evaluate("location.hash='en-essays'");pg.wait_for_timeout(400);log.append(f'{W} picked {pg.locator(".picked .esscard").count()}')
        pg.evaluate("window.scrollTo(0,1500)");pg.wait_for_timeout(100)
        pg.locator('.esslist .esscard').nth(12).click();pg.wait_for_timeout(400)
        log.append(f'{W} tools: '+pg.evaluate("[...document.querySelector('#main .row').querySelectorAll('button')].map(b=>b.className+':'+b.innerText).join(' / ')"))
        pg.go_back();pg.wait_for_timeout(500)
        log.append(f'{W} after back: hash {pg.evaluate("location.hash")} essay? {pg.locator("article.essay").count()} y {pg.evaluate("scrollY")}')
        pg.click('#lang-zh');pg.wait_for_timeout(500)
        pg.evaluate("location.hash='zh-chuxue'");pg.wait_for_timeout(1500)
        log.append(f'{W} chuxue py chips: '+str(pg.locator('.chip[data-py]').count())+' ruby '+str(pg.locator('#main ruby').count()))
        pg.screenshot(path=f'r14-chuxue-{W}.png')
        pg.evaluate("location.hash='zh-memo'");pg.wait_for_timeout(500);log.append(f'{W} memo bar hidden: '+str(pg.evaluate("(document.querySelector('.memo .bar')||{}).hidden"))+' s: '+pg.inner_text('.memo .shown'))
        pg.evaluate("location.hash='zh-games'");pg.wait_for_timeout(400);log.append(f'{W} first game: '+pg.evaluate("(document.querySelector('#main h3, #main h4')||{}).innerText"))
        pg.evaluate("location.hash='zh-dictation'");pg.wait_for_timeout(2600);log.append(f'{W} voicewarn {pg.locator(".voicewarn").count()}')
        pg.evaluate("location.hash='zh-kantu'");pg.wait_for_timeout(400);log.append(f'{W} kantu h2: '+pg.inner_text('#main h2'))
        if W==390:
            pg.click('#menuBtn');pg.wait_for_timeout(200);pg.keyboard.press('Escape');pg.wait_for_timeout(200);log.append('drawer hidden after esc: '+str(pg.evaluate("document.querySelector('#index').hidden")))
        pg.close()
    b.close()
