window.CONTENT_PARTS = window.CONTENT_PARTS || [];
window.CONTENT_PARTS.push({ lang: "en", units: [

{ id: "en-sentencebank", group: "Word banks", order: 85, cat: "phrases",
  title: "Descriptive sentence bank",
  intro: "Whole sentences you can borrow to describe people, places and scenes. Read them, notice how they paint a picture, then link two together and change the details to fit your own story.",
  blocks: [
  { type: "text", title: "How to use this bank",
    html: "Each list below is full of <b>ready-made descriptive sentences</b>. One good sentence is nice, but two sentences <b>linked together</b> sound even better. Look at the example under each list: it shows how to join two sentences with a small word such as <b>and</b>, <b>as</b>, <b>while</b>, <b>but</b> or <b>when</b>, or by turning one of them into an <i>-ing</i> phrase." },
  { type: "tip",
    html: "<b>Tip: borrow, don’t copy blindly.</b> A sentence only works if it fits YOUR story. Before you use one, change at least one detail: the name, the place, the colour, the sound. If your story is about a library, a sentence about the market will look odd. And never paste in five borrowed sentences in a row: mix them with your own ideas so the writing still sounds like you." },

  { type: "chips", title: "Describing a person by type",
    groups: [
    { title: "Grandparents",
      words: ["Grandma’s silver hair was pinned into a neat bun at the back of her head.",
        "Deep laugh lines fanned out from the corners of Grandpa’s eyes.",
        "Her hands were soft and wrinkled, with veins like thin blue rivers.",
        "Grandpa shuffled along in his old leather slippers, humming a tune from long ago.",
        "Ah Ma pressed a red packet into my palm and gently closed my fingers over it.",
        "He peered at the newspaper through glasses perched on the tip of his nose.",
        "She smelt faintly of medicated oil and baby powder.",
        "Every morning, Grandpa did his slow, careful stretches at the void deck.",
        "Grandma’s kitchen was her kingdom, and nobody was allowed to touch her wok.",
        "When he smiled, his whole face crinkled like a paper bag.",
        "She spoke slowly, as if each word were a precious coin.",
        "Nai Nai never let anyone leave her flat without a bag of fruit.",
        "Though his back was bent, his eyes were still sharp and full of mischief."],
      ex: "<b>Linked:</b> Grandpa shuffled along in his old leather slippers, peering at the newspaper through glasses perched on the tip of his nose.",
      note: "Notice how the second sentence became an <i>-ing</i> phrase (peering...) so the two ideas flow as one." },
    { title: "Teachers",
      words: ["Mrs Tan swept into the classroom with a stack of exercise books in her arms.",
        "Her reading glasses hung from a beaded chain around her neck.",
        "Mr Lim had a voice that could reach the back row without him ever shouting.",
        "She raised one eyebrow, and the whole class fell silent.",
        "He tapped the whiteboard marker against his palm as he waited for an answer.",
        "Her red pen hovered over my work, and I held my breath.",
        "Madam Rahimah greeted us at the door every morning with a warm smile.",
        "When someone was struggling, he knelt beside the desk and patiently explained it again.",
        "Her handwriting on the board was neat, round and easy to read.",
        "He had a habit of pacing up and down the rows while we worked.",
        "Even on her busiest days, she found time to ask how we were doing.",
        "A small smile tugged at the corners of his mouth when I finally got it right."],
      ex: "<b>Linked:</b> Mrs Tan swept into the classroom with a stack of exercise books in her arms, and when she raised one eyebrow, the whole class fell silent." },
    { title: "Toddlers and babies",
      words: ["My baby cousin toddled across the floor on wobbly, chubby legs.",
        "His cheeks were round and pink, like two little apples.",
        "She clutched a soggy biscuit in one fist and her favourite blanket in the other.",
        "Wisps of fine hair stuck up on the top of his head.",
        "He babbled happily to himself in a language only he understood.",
        "Without warning, her bottom lip wobbled and she burst into tears.",
        "He pointed at everything and shouted “Dat!” at the top of his voice.",
        "Her tiny fingers wrapped tightly around my thumb.",
        "Within seconds, he had pulled every book off the bottom shelf.",
        "She giggled so hard that she toppled over onto the cushion.",
        "Crumbs and grains of rice were scattered all around his high chair.",
        "He fell asleep in the pram with his mouth open and one sock missing."],
      ex: "<b>Linked:</b> My baby cousin toddled across the floor on wobbly, chubby legs, clutching a soggy biscuit in one fist and her favourite blanket in the other." },
    { title: "Best friends",
      words: ["Aisha could always tell when something was bothering me.",
        "Jun Hao’s laugh was so loud that it made everyone around him laugh too.",
        "We had our own secret handshake that nobody else knew.",
        "She saved me a seat at recess every single day.",
        "He was the first person I wanted to tell whenever something good happened.",
        "Mei Ling was never too busy to lend me a pencil, or a listening ear.",
        "We could sit together without saying anything, and it never felt awkward.",
        "Her eyes lit up whenever she talked about her pet hamster.",
        "He always had a silly joke ready when I needed cheering up.",
        "Even when we argued, we never stayed angry for more than a day.",
        "Priya stood up for me when the others were teasing me.",
        "We knew each other so well that we often finished each other’s sentences."],
      ex: "<b>Linked:</b> Aisha could always tell when something was bothering me, and she always had a silly joke ready to cheer me up." },
    { title: "Strangers",
      words: ["A tall man in a faded grey cap stood alone at the bus stop.",
        "Her face was half hidden behind large, dark sunglasses.",
        "He glanced over his shoulder every few seconds, as if he was expecting someone.",
        "A thin, scruffy beard covered most of his chin.",
        "The woman clutched her handbag tightly to her chest.",
        "His voice was low and gravelly, and he did not smile.",
        "She wore a bright yellow raincoat even though the sky was clear.",
        "He carried a battered brown suitcase held together with string.",
        "The stranger’s eyes darted from face to face across the platform.",
        "A kind-looking lady in a floral blouse bent down and asked if I was lost.",
        "He nodded at me politely, then disappeared into the crowd.",
        "Something about the way he lingered near the gate made me uneasy."],
      ex: "<b>Linked:</b> A tall man in a faded grey cap stood alone at the bus stop, glancing over his shoulder every few seconds as if he was expecting someone.",
      note: "Describe a stranger by what you can SEE and HEAR. You do not know their thoughts, so use “as if” or “seemed to”." },
    { title: "Athletes and sporty people",
      words: ["Her ponytail swung from side to side as she sprinted down the track.",
        "Beads of sweat glistened on his forehead.",
        "Every muscle in his legs was tense, ready to spring.",
        "She bent low at the starting line, her fingertips resting lightly on the ground.",
        "He dribbled the ball past two defenders as if they were standing still.",
        "Her jersey was soaked through, but she refused to slow down.",
        "He crouched at the edge of the pool, swinging his arms to warm up.",
        "She gritted her teeth and pushed through the last painful lap.",
        "His running shoes were caked with mud from the cross-country route.",
        "The captain clapped her hands and shouted encouragement to her team.",
        "He threw his arms up in triumph as he crossed the finishing line.",
        "Even after losing, she shook her opponent’s hand with a genuine smile."],
      ex: "<b>Linked:</b> Her jersey was soaked through and beads of sweat glistened on her forehead, but she gritted her teeth and pushed through the last painful lap." },
    { title: "Shopkeepers and stallholders",
      words: ["The provision shop uncle sat behind the counter, flicking through a newspaper.",
        "She counted my change coin by coin into my waiting palm.",
        "His shop was crammed from floor to ceiling with biscuits, batteries and brooms.",
        "The auntie at the drinks stall remembered exactly how I liked my Milo.",
        "He wiped his hands on his apron and asked, “What can I get you, boy?”",
        "A small radio crackled with old songs in the corner of the shop.",
        "She waved a paper fan lazily as she waited for customers.",
        "The stallholder called out his prices in a loud, sing-song voice.",
        "He wrapped the fish in newspaper with quick, practised hands.",
        "Every morning at seven, she rolled up the metal shutter with a loud clatter.",
        "He slipped an extra sweet into my bag and gave me a wink.",
        "Her little shop had stood in the same spot for over forty years."],
      ex: "<b>Linked:</b> The provision shop uncle sat behind the counter flicking through a newspaper while a small radio crackled with old songs in the corner." }
    ] },

  { type: "chips", title: "A person’s mood at a glance",
    groups: [
    { title: "Happy and cheerful",
      words: ["She skipped down the corridor, humming her favourite song.",
        "A huge grin spread across his face.",
        "Her eyes sparkled, and she could not stop smiling.",
        "He bounced on his toes as he waited for his turn.",
        "She laughed so hard that tears rolled down her cheeks.",
        "He whistled a cheerful tune as he packed his bag.",
        "She practically floated into the classroom.",
        "His face glowed with pride as he held up the trophy."],
      ex: "<b>Linked:</b> A huge grin spread across his face, and he whistled a cheerful tune as he packed his bag." },
    { title: "Sad and upset",
      words: ["Her shoulders drooped, and she stared at the floor.",
        "He sat alone at the end of the bench, poking at his food.",
        "Her eyes were red and puffy from crying.",
        "He sniffed and quickly wiped his nose on his sleeve.",
        "She gave me a small, wobbly smile that did not reach her eyes.",
        "He trudged home with his head hanging low.",
        "Her voice was barely a whisper.",
        "He turned away so that nobody would see his tears."],
      ex: "<b>Linked:</b> He sat alone at the end of the bench, poking at his food, and when I said hello, his voice was barely a whisper." },
    { title: "Angry and cross",
      words: ["His face turned bright red, and his fists clenched at his sides.",
        "She slammed her book shut and glared at me.",
        "He stomped out of the room without a word.",
        "Her lips pressed into a thin, tight line.",
        "A vein throbbed on the side of his forehead.",
        "She folded her arms and refused to look at anyone.",
        "He muttered angrily under his breath.",
        "Her nostrils flared as she took a sharp breath."],
      ex: "<b>Linked:</b> She slammed her book shut and folded her arms, her lips pressed into a thin, tight line." },
    { title: "Nervous and worried",
      words: ["He chewed the end of his pencil until it was covered in tooth marks.",
        "Her knee jiggled up and down under the desk.",
        "She kept tucking the same strand of hair behind her ear.",
        "He swallowed hard and wiped his sweaty palms on his shorts.",
        "Her eyes darted towards the door every few seconds.",
        "He cleared his throat three times before he spoke.",
        "She twisted the hem of her shirt round and round her finger.",
        "His voice cracked halfway through the sentence."],
      ex: "<b>Linked:</b> Her knee jiggled up and down under the desk while her eyes darted towards the door every few seconds." },
    { title: "Tired or bored",
      words: ["He slumped over his desk with his chin in his hands.",
        "Her eyelids drooped, and her head kept nodding forward.",
        "He let out a long, loud yawn without covering his mouth.",
        "She stared blankly out of the window, tapping her pen.",
        "He dragged his school bag along the floor behind him.",
        "Dark rings circled her eyes.",
        "He sighed and turned the page without reading a word.",
        "She rested her cheek on her arm and doodled in the margins."],
      ex: "<b>Linked:</b> He slumped over his desk with his chin in his hands, sighing as he turned the page without reading a word." },
    { title: "Surprised or shocked",
      words: ["Her mouth fell open, but no words came out.",
        "He blinked twice, as if he could not believe his eyes.",
        "She clapped a hand over her mouth.",
        "He stopped mid-bite, his spoon frozen halfway to his mouth.",
        "She gasped and took a step backwards.",
        "The colour drained from his face.",
        "He stared at the letter, reading it again and again.",
        "She let out a squeal and grabbed my arm."],
      ex: "<b>Linked:</b> She gasped and took a step backwards as the colour drained from her face." }
    ] },

  { type: "chips", title: "Places",
    groups: [
    { title: "The classroom",
      words: ["Thirty-five desks stood in neat rows facing the whiteboard.",
        "The ceiling fans whirred overhead, ruffling the stack of worksheets.",
        "Colourful charts and our best artwork covered the soft board at the back.",
        "The scratching of pencils filled the room during the spelling test.",
        "A forgotten water bottle sat on the windowsill, glinting in the sun.",
        "The moment the teacher stepped out, the classroom exploded into chatter.",
        "The smell of markers and pencil shavings hung in the air.",
        "Afternoon sunlight slanted across the desks, making everyone drowsy.",
        "Chairs screeched as we stood up to greet the teacher.",
        "Long after dismissal, the empty classroom was silent except for the hum of the fan."],
      ex: "<b>Linked:</b> Afternoon sunlight slanted across the desks while the ceiling fans whirred overhead, and soon everyone was drowsy." },
    { title: "The hawker centre",
      words: ["The hawker centre was packed with office workers on their lunch break.",
        "Packets of tissue lay on the empty tables, quietly “choping” seats.",
        "Steam billowed from the noodle stall as the hawker lifted the basket out of the boiling water.",
        "The smoky smell of char kway teow drifted from a sizzling wok.",
        "Uncles in singlets sipped their kopi and argued about football.",
        "Long queues snaked in front of the most popular chicken rice stall.",
        "A cleaner wheeled her trolley between the tables, collecting trays and bowls.",
        "Pigeons strutted under the tables, pecking at fallen grains of rice.",
        "The drinks auntie shouted orders to her helper above the din.",
        "By two o’clock, the crowds had thinned and the hawkers were wiping down their counters."],
      ex: "<b>Linked:</b> The hawker centre was packed with office workers, and long queues snaked in front of the most popular chicken rice stall." },
    { title: "On the MRT",
      words: ["The train glided into the station with a soft whoosh.",
        "Commuters stood shoulder to shoulder, swaying with the movement of the train.",
        "Almost everyone in the carriage was staring down at a phone.",
        "A recorded voice reminded us to mind the platform gap.",
        "The doors chimed and slid shut just as a boy dashed towards them.",
        "An office worker dozed against the pole, his head nodding at every stop.",
        "A young man stood up to give his seat to an elderly lady.",
        "The cool air in the carriage was a relief after the long walk in the sun.",
        "The tunnel lights flashed past the windows in long streaks.",
        "When the doors opened at City Hall, a wave of passengers poured out."],
      ex: "<b>Linked:</b> Commuters stood shoulder to shoulder, swaying with the train, and almost every one of them was staring down at a phone." },
    { title: "The void deck",
      words: ["The void deck was cool and shady, a welcome escape from the afternoon heat.",
        "Two old men hunched over a game of Chinese chess, surrounded by silent onlookers.",
        "Children chased one another round the pillars, their shrieks echoing off the ceiling.",
        "A row of letterboxes lined the wall near the lift lobby.",
        "An auntie sat on the stone bench, fanning herself with a folded newspaper.",
        "A tabby cat lay stretched out on the cool floor tiles.",
        "The smell of someone’s dinner floated down from the flats above.",
        "On Saturday, the void deck became a wedding hall filled with red chairs and balloons.",
        "A boy kicked his football against the wall, again and again.",
        "Under the dim lights at night, the void deck was quiet and a little eerie."],
      ex: "<b>Linked:</b> The void deck was cool and shady, and two old men hunched over a game of Chinese chess while a tabby cat dozed on the tiles nearby." },
    { title: "The beach",
      words: ["Gentle waves rolled onto the shore and slid back with a soft hiss.",
        "The sand was so hot that we hopped across it to reach the water.",
        "Families sat on picnic mats in the shade of the casuarina trees.",
        "Ships dotted the horizon like grey toy boats.",
        "A little boy patted the sides of his sandcastle with a plastic spade.",
        "Crows hopped along the sand, hunting for leftover food.",
        "The smell of barbecued chicken wings drifted over from the pits.",
        "A cool sea breeze tugged at our hats and towels.",
        "Cyclists and skaters whizzed along the path behind the beach.",
        "Shells and bits of driftwood were scattered along the waterline.",
        "By sunset, the sea had turned a deep shade of orange and gold."],
      ex: "<b>Linked:</b> The sand was so hot that we hopped across it to the water, where gentle waves rolled onto the shore and slid back with a soft hiss." },
    { title: "The playground",
      words: ["The playground was alive with the squeals of excited children.",
        "A little girl pumped her legs hard to make the swing go higher.",
        "Two boys raced each other to the top of the climbing net.",
        "The slide was so hot in the sun that it almost burnt my legs.",
        "Parents sat on the benches nearby, keeping one eye on their children.",
        "The rubber flooring was soft and springy under my feet.",
        "A toddler squealed with delight as he whooshed down the slide.",
        "The see-saw creaked up and down as two friends took turns.",
        "Sand crunched underfoot near the sandpit.",
        "When the rain came, the playground emptied in minutes."],
      ex: "<b>Linked:</b> The playground was alive with squeals as a little girl pumped her legs hard to make the swing go higher." },
    { title: "The hospital",
      words: ["The waiting area was lined with rows of blue plastic chairs.",
        "Patients sat quietly, glancing up whenever a new queue number appeared.",
        "The sharp smell of antiseptic stung my nose as soon as we stepped in.",
        "Nurses hurried along the corridor in their crisp white uniforms.",
        "A machine beside Grandpa’s bed beeped steadily.",
        "The ward was chilly, and the curtains around each bed were drawn.",
        "A porter wheeled an empty bed down the long, pale corridor.",
        "Visitors spoke in hushed voices, as if afraid of waking someone.",
        "Get-well cards and a basket of fruit crowded the small bedside table.",
        "Through the window, I could see the busy road far below."],
      ex: "<b>Linked:</b> The ward was chilly and quiet, and the only sound was the machine beside Grandpa’s bed, beeping steadily." },
    { title: "The library",
      words: ["Rows of tall shelves stretched towards the back of the library.",
        "The only sounds were the turning of pages and the soft hum of the air-conditioning.",
        "A boy lay sprawled on a beanbag, completely lost in his book.",
        "Bright posters about new books were stuck on the wall near the entrance.",
        "The self-checkout machine beeped as I scanned my books one by one.",
        "A librarian pushed a squeaky trolley of returned books between the aisles.",
        "Students sat at the long tables, bent over their worksheets.",
        "Sunlight fell across the reading corner in warm golden squares.",
        "Somebody’s phone rang, and a dozen heads turned to glare.",
        "The smell of old paper and new covers filled the air."],
      ex: "<b>Linked:</b> The only sounds were the turning of pages and the hum of the air-conditioning, until somebody’s phone rang and a dozen heads turned to glare." },
    { title: "The wet market",
      words: ["The wet market was bustling long before the sun came up.",
        "Fishmongers scooped ice over glistening rows of fish.",
        "The floor was wet and slippery, and I had to watch every step.",
        "Aunties haggled over the price of vegetables, their baskets hooked over their arms.",
        "Bright red chillies, green kailan and purple brinjals were piled high on the stalls.",
        "The butcher’s cleaver thudded down on the chopping board.",
        "A strong, fishy smell hit me the moment we walked in.",
        "Live crabs clawed at one another in a plastic tub.",
        "The flower stall was a burst of colour in the middle of the grey market.",
        "By ten o’clock, most of the stallholders were hosing down their counters."],
      ex: "<b>Linked:</b> A strong, fishy smell hit me the moment we walked in, and the floor was so wet and slippery that I had to watch every step." },
    { title: "Home at night",
      words: ["The flat was dark except for the blue glow of the television.",
        "The ceiling fan turned slowly above my bed.",
        "Through the half-open door, I could see the glow of Dad’s laptop as he finished his work.",
        "Outside my window, the lights in the next block went off one by one.",
        "The washing machine finished its last load with a cheerful little tune.",
        "Mum switched off the last light, and darkness settled over the flat.",
        "A motorcycle roared somewhere in the distance and faded away.",
        "My little sister mumbled something in her sleep and rolled over.",
        "The floor tiles felt cool under my bare feet as I crept to the kitchen.",
        "Only the soft tick of the kitchen clock broke the silence."],
      ex: "<b>Linked:</b> The ceiling fan turned slowly above my bed while, outside my window, the lights in the next block went off one by one." }
    ] },

  { type: "chips", title: "Crowds and busy scenes",
    groups: [
    { title: "Crowds",
      words: ["A sea of people filled the square, all pushing towards the stage.",
        "Everyone craned their necks to get a better view.",
        "I was swept along by the crowd and almost lost hold of Mum’s hand.",
        "Hundreds of voices blended into one loud, cheerful roar.",
        "People jostled and squeezed past one another with their shopping bags.",
        "Children rode on their fathers’ shoulders, waving little flags.",
        "Elbows bumped against me from every side.",
        "Phones were held high above heads to film the fireworks.",
        "The queue stretched all the way round the corner.",
        "When the gates opened, the crowd surged forward."],
      ex: "<b>Linked:</b> When the gates opened, the crowd surged forward, and I was swept along so fast that I almost lost hold of Mum’s hand." },
    { title: "Rush and chaos",
      words: ["Car horns blared as the traffic inched forward.",
        "Shopkeepers shouted over one another to attract customers.",
        "Trolleys rattled, babies cried and music blasted from every shop.",
        "Delivery riders weaved in and out between the cars.",
        "Everyone seemed to be in a hurry, and nobody looked up.",
        "The canteen was a whirl of trays, bowls and hungry pupils.",
        "Waiters rushed between the tables, balancing plates on their arms.",
        "A dozen conversations went on at once, and I could barely hear myself think.",
        "At the bus interchange, people dashed from one bus to the next.",
        "The kitchen was chaos: pots bubbled, the oven beeped and the doorbell rang."],
      ex: "<b>Linked:</b> Car horns blared as the traffic inched forward, while delivery riders weaved in and out between the cars." }
    ] },

  { type: "chips", title: "Quiet scenes",
    groups: [
    { title: "Peaceful and calm",
      words: ["The park was empty except for an old man walking his dog.",
        "Only the gentle rustle of leaves broke the silence.",
        "The surface of the pond was perfectly still.",
        "A single bird sang somewhere high in the trees.",
        "The early morning air was cool and fresh.",
        "Sunlight filtered softly through the curtains.",
        "The whole estate seemed to be asleep.",
        "It was so quiet that I could hear the faint tick of my watch.",
        "A light breeze stirred the curtains, and then all was still again.",
        "For a long moment, nobody moved or said a word."],
      ex: "<b>Linked:</b> The park was empty except for an old man walking his dog, and only the gentle rustle of leaves broke the silence." },
    { title: "Lonely or eerie quiet",
      words: ["The corridor was deserted, and my footsteps echoed behind me.",
        "The swings creaked gently, though nobody was on them.",
        "An empty can rolled across the car park, rattling in the wind.",
        "Every classroom door was shut, and every light was off.",
        "The silence was so thick that I could hear myself breathing.",
        "Not a single car passed along the road.",
        "A lone street lamp flickered at the end of the path.",
        "The house felt strangely empty without my brother’s noise.",
        "The only light came from the green exit sign above the door.",
        "Somewhere far away, a dog barked once and then fell silent."],
      ex: "<b>Linked:</b> The corridor was deserted, and as my footsteps echoed behind me, a lone light flickered at the far end." }
    ] },

  { type: "chips", title: "Food",
    groups: [
    { title: "Hawker and local favourites",
      words: ["The chicken rice was fragrant, and the chicken skin glistened with oil.",
        "Steam rose from the bowl of laksa, carrying the smell of coconut and spice.",
        "The roti prata was crispy on the outside and soft and fluffy inside.",
        "Thick, dark sauce coated every strand of the noodles.",
        "The chilli was so fiery that my eyes began to water.",
        "The satay sticks were charred at the edges and sticky with sweet sauce.",
        "A bowl of icy chendol was the perfect cure for the afternoon heat.",
        "Each ondeh-ondeh burst with sweet, melted gula melaka when I bit into it.",
        "The kaya toast was warm, crunchy and dripping with butter.",
        "Fishballs bobbed in the clear soup like little white moons."],
      ex: "<b>Linked:</b> Steam rose from the bowl of laksa, carrying the smell of coconut and spice, and the chilli was so fiery that my eyes began to water." },
    { title: "Cooking and eating at home",
      words: ["Mum lifted the lid, and a cloud of fragrant steam rose from the pot.",
        "The table groaned under dishes of curry, fried fish and stir-fried vegetables.",
        "My stomach rumbled loudly as the smell of fried garlic filled the flat.",
        "I blew on the spoonful of porridge before taking a careful sip.",
        "The cake was so soft that it almost melted on my tongue.",
        "Grandma piled more food into my bowl before I could say no.",
        "We slurped our noodles noisily and grinned at one another.",
        "Flakes of pastry tumbled onto my lap as I bit into the curry puff.",
        "The ice cream dribbled down the cone and onto my fingers.",
        "After the meal, everyone leaned back in their chairs, too full to move."],
      ex: "<b>Linked:</b> My stomach rumbled as the smell of fried garlic filled the flat, and when Mum lifted the lid, a cloud of fragrant steam rose from the pot." }
    ] },

  { type: "chips", title: "Animals and pets",
    groups: [
    { title: "Pets at home",
      words: ["My puppy’s tail wagged so hard that his whole body wiggled.",
        "The cat stretched lazily and blinked at me with sleepy green eyes.",
        "Our hamster stuffed seeds into its cheeks until they bulged.",
        "The goldfish darted to the top of the tank whenever I came near.",
        "He bounded towards me and nearly knocked me over.",
        "She curled up on my lap, purring softly.",
        "The puppy tilted his head to one side, his ears pricked up.",
        "My rabbit twitched his nose and nibbled on a carrot.",
        "The kitten pounced on the dangling string and missed completely.",
        "Our dog whimpered at the door until someone took him for a walk."],
      ex: "<b>Linked:</b> The puppy tilted his head to one side, and then he bounded towards me so fast that he nearly knocked me over." },
    { title: "Animals around the neighbourhood",
      words: ["A monitor lizard slid lazily into the canal.",
        "A flock of mynahs squabbled noisily over a piece of bread.",
        "A squirrel scampered up the tree trunk and vanished among the leaves.",
        "A family of otters glided through the water in a neat line.",
        "Ants marched in a long, determined line towards the fallen biscuit.",
        "A gecko clung to the ceiling, waiting patiently for a moth.",
        "A kingfisher flashed past, a streak of brilliant blue.",
        "Crows cawed harshly from the top of the lamp post.",
        "A stray cat slunk along the drain, its belly low to the ground.",
        "A huge spider sat perfectly still in the middle of its web."],
      ex: "<b>Linked:</b> A family of otters glided through the water in a neat line as a kingfisher flashed past, a streak of brilliant blue." }
    ] },

  { type: "chips", title: "Movement and action scenes",
    groups: [
    { title: "Running, playing and sport",
      words: ["I pumped my arms and legs as hard as I could.",
        "He leapt over the puddle but landed with a splash anyway.",
        "She swerved round the corner and almost crashed into the dustbin.",
        "We scrambled up the slope, grabbing at roots to pull ourselves up.",
        "He dived for the ball and skidded across the wet grass.",
        "The relay baton slipped from my fingers and clattered onto the track.",
        "She crouched low and then sprang forward like a coiled spring.",
        "I raced up the stairs two at a time.",
        "He wobbled on his bicycle, then found his balance and pedalled away.",
        "We tiptoed past the sleeping guard dog, hardly daring to breathe."],
      ex: "<b>Linked:</b> I raced up the stairs two at a time, pumping my arms as hard as I could." },
    { title: "Sudden moments and accidents",
      words: ["Without warning, the boy slipped and fell flat on his back.",
        "The glass slid off the table and shattered on the floor.",
        "I lunged forward and grabbed her arm just in time.",
        "The cyclist braked hard, and his tyres screeched on the road.",
        "He tripped over his shoelace and went sprawling.",
        "She spun round at the sound of her name.",
        "The ball flew past the goalkeeper’s outstretched hands.",
        "The box toppled off the shelf, and toys tumbled onto my head.",
        "I snatched my hand back from the hot pan.",
        "Everyone jumped to their feet and rushed to help."],
      ex: "<b>Linked:</b> Without warning, the boy tripped over his shoelace and went sprawling, and everyone jumped to their feet and rushed to help." }
    ] },

  { type: "chips", title: "Sounds of a scene",
    groups: [
    { title: "Everyday sounds",
      words: ["The school bell rang shrilly, and chairs scraped across the floor.",
        "Somewhere below, a rubbish truck groaned and clanked.",
        "Chopsticks clattered and trays thudded down on the tables.",
        "The washing machine rumbled and thudded in the kitchen.",
        "A neighbour’s radio crackled with the evening news.",
        "Car doors slammed and children called goodbye in the car park.",
        "The lift doors pinged open and slid shut along the corridor.",
        "Footsteps pattered up the staircase, then stopped.",
        "The cash register drawer slid open with a cheerful ding.",
        "Laughter floated up from the void deck."],
      ex: "<b>Linked:</b> Car doors slammed in the car park below while laughter floated up from the void deck." },
    { title: "Dramatic sounds",
      words: ["A deafening crash came from the kitchen.",
        "A piercing scream cut through the air.",
        "Sirens wailed louder and louder as the fire engine drew closer.",
        "The crowd let out a loud groan as the ball hit the post.",
        "There was a sharp crack, and the branch snapped.",
        "Broken glass tinkled onto the pavement.",
        "The whole hall erupted into thunderous applause.",
        "Something heavy thumped against the door.",
        "The fire alarm shrieked, and everyone clapped their hands over their ears.",
        "Then came a sound that made us all freeze: a long, low rumble of thunder."],
      ex: "<b>Linked:</b> A deafening crash came from the kitchen, followed by the tinkle of broken glass on the floor." }
    ] },

  { type: "chips", title: "Endings of a day",
    groups: [
    { title: "Happy and peaceful endings",
      words: ["As the sun dipped behind the blocks, we packed up our things and headed home.",
        "That night, I fell asleep with a smile on my face.",
        "Tired but happy, we trudged back to the car.",
        "I snuggled under my blanket and replayed the whole day in my mind.",
        "The street lamps flickered on one by one as we walked home.",
        "It had been the best day of the holidays, and I never wanted it to end.",
        "Mum tucked me in and switched off the light.",
        "My legs ached, but my heart was full.",
        "We waved goodbye until their car disappeared round the bend.",
        "I wrote everything down in my diary so that I would never forget it."],
      ex: "<b>Linked:</b> The street lamps flickered on one by one as we walked home, tired but happy." },
    { title: "Thoughtful endings",
      words: ["Lying in bed, I thought about everything I had learnt that day.",
        "I promised myself that I would never make the same mistake again.",
        "It was a day that taught me what true friendship means.",
        "As I closed my eyes, I felt lighter than I had in weeks.",
        "Although the day had started badly, it ended far better than I had hoped.",
        "I knew that tomorrow I would have to apologise, and I was ready.",
        "From that day on, I never took my grandparents for granted.",
        "The house fell quiet, and I finally let out the breath I had been holding.",
        "Looking back, I realised that telling the truth had been worth it.",
        "Sleep came quickly that night, and I dreamt of the sea."],
      ex: "<b>Linked:</b> Although the day had started badly, it ended far better than I had hoped, and as I closed my eyes, I felt lighter than I had in weeks.",
      note: "A thoughtful ending shows what the character learnt or felt. Make sure it matches what really happened in your story." }
    ] },

  { type: "tip",
    html: "<b>Make it yours:</b> take “The hawker centre was packed with office workers on their lunch break.” and change it: “The coffee shop was packed with sleepy families on Sunday morning.” Same pattern, new picture. That is the best way to use this bank." }
  ] }

], extends: [

{ id: "en-similes", blocks: [
  { type: "chips", title: "More similes and metaphors: people, feelings, school and everyday life",
    groups: [
    { title: "How people look",
      words: ["hair as black and glossy as a crow’s feather", "eyebrows as thick as two caterpillars", "a voice as deep as a well", "a laugh like a squeaky door", "as skinny as a beanpole", "as tall as a basketball hoop", "cheeks as round as steamed buns", "a nose as red as a cherry", "a face as creased and kind as a well-loved map", "freckles sprinkled like cinnamon on toast", "hands as rough as tree bark", "eyes as dark as black coffee"],
      ex: "Uncle Ravi had eyebrows as thick as two caterpillars, and they wriggled whenever he laughed." },
    { title: "What people are like",
      words: ["as patient as a fisherman", "as curious as a kitten", "as cool as a cucumber", "as chatty as a parrot", "as neat as a freshly made bed", "as quiet as a mouse", "as slippery as an eel", "my little sister is a tiny tornado", "Dad is our family’s human GPS", "our captain was the glue that held the team together", "Grandpa is a treasure chest of old stories", "he was a bulldozer on the football field", "my brother is a night owl", "she is a sponge for new facts"],
      ex: "Our captain was the glue that held the team together, and without her we fell apart.",
      note: "Calling someone a bulldozer or a tornado is a metaphor: you say they ARE the thing, without using like or as." },
    { title: "Happy, proud and relieved",
      words: ["pride swelled in my chest like rising bread dough", "joy popped inside me like popcorn in a pan", "relief washed over me like a cool shower", "relief spread through me like warmth from a hot drink", "my heart was as warm as freshly baked bread", "excitement crackled through me like electricity", "I glowed as if someone had switched on a lamp inside me", "my heart soared like a kite on a breezy day", "as content as a cat in a patch of sunlight", "gratitude filled me like water filling a cup", "her hug was a warm blanket", "I felt ten feet tall", "hope was a tiny seed sprouting inside me", "her praise was music to my ears"],
      ex: "When my name was called, pride swelled in my chest like rising bread dough." },
    { title: "Worried, guilty, embarrassed and jealous",
      words: ["guilt sat in my stomach like a cold lump of rice", "my cheeks burnt as hot as a toaster", "jealousy wriggled inside me like a worm", "disappointment sank in my chest like a stone dropped into a pond", "loneliness was an empty room with the lights off", "my worries buzzed like mosquitoes I could not swat", "I felt as small as an ant", "shame clung to me like wet clothes", "my heart pounded like a fist on a door", "dread crept over me like a long shadow", "my throat felt as tight as a knotted shoelace", "the silence between us was a wall", "regret gnawed at me like a dog with a bone", "my stomach churned like a washing machine", "frustration built up inside me like steam in a pressure cooker"],
      ex: "All through dinner, guilt sat in my stomach like a cold lump of rice, and I could hardly eat." },
    { title: "Movement",
      words: ["she glided across the stage like a swan", "he waddled like a penguin in his new shoes", "we scattered like marbles dropped on the floor", "the toddler tottered like a wind-up toy", "he shot off the starting block like a rocket", "the pupils filed out like ducklings behind their mother", "she twirled like a spinning top", "he slithered under the fence like a snake", "the runners bunched together like a school of fish", "he crept down the stairs as silently as a cat", "the crowd parted like a pair of curtains", "she sprang up like a jack-in-the-box"],
      ex: "When the teacher said “Line up!”, the Primary One pupils filed out like ducklings behind their mother." },
    { title: "School life",
      words: ["the exam hall was as silent as a library at night", "the bell was a starting pistol for recess", "my homework piled up like dirty dishes", "the spelling words swam on the page like tadpoles", "the canteen at recess was a beehive", "my pencil case was a treasure box of colourful pens", "the teacher’s stare was a searchlight", "the timetable was a puzzle with too many pieces", "my brain soaked up facts like a sponge", "the test paper was a mountain I had to climb", "the classroom after the holidays was as fresh as a new notebook", "ideas popped up like toast from a toaster", "my mind went as blank as an empty whiteboard", "the corridor was a river of uniforms"],
      ex: "I turned over the paper, and my mind went as blank as an empty whiteboard." },
    { title: "Food",
      words: ["the curry was as fiery as a dragon’s breath", "the rice was as fluffy as cotton wool", "the jelly trembled like a frightened mouse", "the prata was as thin as tissue paper", "the bread was as hard as a brick", "the mango was as sweet as honey", "the soup was a warm hug in a bowl", "the durian smelt like a pair of old socks", "the noodles slid down like slippery eels", "the cake was a fluffy cloud on a plate", "the sour plum made my face scrunch up like a crumpled tissue", "the buffet table was a treasure island of food", "my ice kachang was a melting rainbow mountain"],
      ex: "After a long, rainy day, Grandma’s soup was a warm hug in a bowl." },
    { title: "Sounds",
      words: ["her laugh tinkled like wind chimes", "his snores rumbled like a motorbike", "the old gate squealed like a pig", "the crowd buzzed like a swarm of bees", "her voice was as sweet as a songbird’s", "the drums pounded like galloping horses", "my stomach growled like a hungry tiger", "the empty hall echoed like a giant cave", "the recorder squeaked like a mouse with hiccups", "whispers spread like ripples on a pond", "the alarm clock beeped like an angry robot", "the cymbals crashed like a stack of dropped metal trays"],
      ex: "In the silent exam hall, my stomach growled like a hungry tiger, and the boy next to me giggled." },
    { title: "Time",
      words: ["the school holidays were a long golden road ahead", "the clock hands seemed glued in place", "the last day of school arrived like a long-awaited train", "the afternoon stretched out like chewing gum", "Monday morning crashed in like an unwelcome alarm", "the countdown felt as long as a year", "the weekend slipped through my fingers like sand", "time was a thief that stole our last hours together", "the hours raced by like cars on an expressway", "the waiting-room clock ticked as slowly as a dripping tap"],
      ex: "The weekend slipped through my fingers like sand, and suddenly it was Sunday night." },
    { title: "Objects and things around us",
      words: ["my school bag was as heavy as a sack of bricks", "the old sofa sagged like a tired dog", "the new bicycle gleamed like a jewel", "the umbrella opened like a flower blooming", "the crumpled letter lay there like a wounded bird", "the old car coughed like a man with a cold", "the pages of the old book were as thin as onion skin", "my room was a museum of half-finished projects", "the phone screen was a window into another world", "the toy cupboard was a volcano waiting to erupt", "his shoes were as worn as an old doormat", "the HDB blocks stood in a row like giant dominoes", "the kite’s tail fluttered like a gymnast’s ribbon", "the long MRT escalator was a staircase to the clouds"],
      ex: "I opened the toy cupboard carefully, because it was a volcano waiting to erupt." }
    ] }
] }

]});
