window.CONTENT_PARTS = window.CONTENT_PARTS || [];
window.CONTENT_PARTS.push({ lang: "en", units: [

{ id: "en-wordfamilies", group: "Word banks", order: 86, cat: "words", title: "Word families",
  intro: "Small word parts like <b>un-</b> and <b>-ful</b> can turn one word into a whole family of words. Learn the parts and you will understand, spell and use many more words in your compositions.",
  blocks: [
    { type: "text", title: "How words grow", html: "A <b>prefix</b> is added to the FRONT of a word and usually changes its meaning (<i>happy</i> becomes <i>unhappy</i>). A <b>suffix</b> is added to the END and often changes the job the word does (<i>happy</i> becomes <i>happiness</i>, a noun, or <i>happily</i>, an adverb). The word in the middle is the <b>root</b> or <b>base word</b>." },

    { type: "table", title: "Prefixes at a glance", head: ["Prefix", "Meaning", "Examples"], rows: [
      ["un-", "not; the opposite of", "unhappy, unlock, unfair"],
      ["dis-", "not; the opposite of", "disagree, disappear, dishonest"],
      ["re-", "again; back", "rewrite, replay, return"],
      ["mis-", "wrongly; badly", "misspell, misbehave, misunderstand"],
      ["pre-", "before", "preview, preheat, prehistoric"],
      ["over-", "too much; above", "overeat, oversleep, overflow"],
      ["under-", "too little; below", "undercooked, underground, underline"],
      ["im- / in-", "not", "impossible, impatient, incorrect, invisible"]
    ]},

    { type: "chips", title: "Prefix word banks", groups: [
      { title: "un- (not, the opposite of)", words: ["unhappy", "unkind", "unfair", "unlock", "untidy", "unusual", "unlucky", "unable", "unafraid", "unbelievable", "uncomfortable", "unexpected", "unfriendly", "unpack", "unwrap", "unsure"],
        ex: "The unexpected knock on the door made Mei Ling jump out of her seat.",
        note: "un- is the most common prefix in English. It can mean “not” (unkind) or “reverse the action” (unlock, unwrap)." },
      { title: "dis- (not, the opposite of)", words: ["disagree", "dislike", "disappear", "dishonest", "disobey", "disconnect", "discomfort", "disapprove", "disorder", "distrust", "disloyal", "discourage", "disqualify"],
        ex: "Wei Ming was disqualified from the race for pushing another runner." },
      { title: "re- (again, back)", words: ["redo", "rewrite", "replay", "return", "rebuild", "recycle", "reread", "refill", "repay", "reheat", "retell", "reunite", "reopen", "restart"],
        ex: "After the storm, the villagers worked together to rebuild their homes.",
        note: "Use re- words in your endings: “I reread my note and smiled.”" },
      { title: "mis- (wrongly, badly)", words: ["misbehave", "misspell", "misunderstand", "mislead", "misplace", "mistake", "misjudge", "misread", "misprint", "misfortune", "mishear", "misuse"],
        ex: "I had misjudged Aisha; she was not proud at all, just shy." },
      { title: "pre- (before)", words: ["preview", "prepay", "preheat", "prehistoric", "preschool", "predict", "precaution", "prearrange", "pre-order", "prefix", "preset", "pretest"],
        ex: "As a precaution, Dad checked the weather forecast before our cycling trip." },
      { title: "over- (too much, above)", words: ["overeat", "oversleep", "overflow", "overjoyed", "overcrowded", "overcooked", "overcome", "overhear", "overlook", "overtake", "overdo", "overconfident", "overreact", "overheat"],
        ex: "I overslept and had to sprint all the way to the bus stop.",
        note: "overjoyed is a lovely, strong word for “very happy”." },
      { title: "under- (too little, below)", words: ["underground", "underline", "underwater", "underestimate", "undercooked", "underpaid", "undersea", "underdog", "underneath", "undercover", "underfed", "underarm"],
        ex: "Everyone underestimated our team, but we, the underdogs, won the final." },
      { title: "im- / in- (not)", words: ["impossible", "impatient", "impolite", "imperfect", "immature", "immobile", "inactive", "incorrect", "incomplete", "invisible", "inaccurate", "independent", "indirect", "inexpensive", "insensitive", "incredible"],
        ex: "It seemed impossible, but Priya finished the puzzle before the bell rang.",
        note: "im- usually comes before b, m and p (impolite, immobile). Watch out: <i>invaluable</i> means “very valuable”, not “not valuable”!" },
      { title: "Bonus: il- and ir- (not)", words: ["illegal", "illegible", "illogical", "irregular", "irresponsible", "irrelevant", "irreplaceable"],
        ex: "Grandma’s old photo album is irreplaceable to our family.",
        note: "il- comes before l, and ir- comes before r." }
    ]},

    { type: "table", title: "Suffixes at a glance", head: ["Suffix", "Meaning", "Word type it makes", "Examples"], rows: [
      ["-ful", "full of", "adjective", "cheerful, hopeful, careful"],
      ["-less", "without", "adjective", "careless, fearless, speechless"],
      ["-ness", "the state of being", "noun", "kindness, darkness, happiness"],
      ["-ly", "in a … way", "adverb", "quickly, gently, nervously"],
      ["-ment", "the action or result of", "noun", "excitement, enjoyment, achievement"],
      ["-able / -ible", "can be; able to be", "adjective", "comfortable, reliable, visible"],
      ["-ous", "full of; having", "adjective", "famous, curious, courageous"],
      ["-er / -est", "more / most", "comparing adjectives", "taller, tallest; braver, bravest"]
    ]},

    { type: "chips", title: "Suffix word banks", groups: [
      { title: "-ful (full of)", words: ["cheerful", "careful", "hopeful", "graceful", "painful", "playful", "thoughtful", "fearful", "grateful", "peaceful", "powerful", "resourceful", "colourful", "beautiful", "truthful", "boastful"],
        ex: "It was thoughtful of Jun Hao to save me a seat at the crowded hawker centre.",
        note: "The suffix has only ONE l: careful, never carefull." },
      { title: "-less (without)", words: ["careless", "fearless", "hopeless", "helpless", "homeless", "breathless", "speechless", "restless", "harmless", "pointless", "endless", "thoughtless", "heartless", "motionless", "sleepless", "tireless"],
        ex: "Grandpa sat motionless by the pond, waiting for a fish to bite.",
        note: "Many -ful words have a -less partner: careful / careless, hopeful / hopeless." },
      { title: "-ness (the state of being)", words: ["kindness", "happiness", "sadness", "darkness", "loneliness", "weakness", "fairness", "laziness", "eagerness", "nervousness", "gentleness", "forgiveness", "stillness", "carelessness", "illness", "emptiness"],
        ex: "A wave of loneliness washed over me as I sat alone at recess." },
      { title: "-ly (in a … way)", words: ["quickly", "slowly", "gently", "angrily", "happily", "nervously", "proudly", "softly", "bravely", "eagerly", "patiently", "carefully", "timidly", "silently", "suddenly", "gracefully"],
        ex: "Aisha carefully lifted the injured bird and placed it in a shoebox." },
      { title: "-ment (the action or result of)", words: ["enjoyment", "excitement", "amazement", "disappointment", "agreement", "encouragement", "achievement", "punishment", "payment", "movement", "arrangement", "improvement", "embarrassment", "astonishment", "treatment"],
        ex: "To my astonishment, the shy new boy stood up and sang in front of the whole class." },
      { title: "-able / -ible (can be)", words: ["comfortable", "enjoyable", "reliable", "breakable", "washable", "readable", "adorable", "remarkable", "likeable", "dependable", "forgivable", "affordable", "predictable", "unforgettable", "visible", "flexible", "sensible", "responsible"],
        ex: "Our trip to the Night Safari was an unforgettable experience." },
      { title: "-ous (full of, having)", words: ["famous", "dangerous", "nervous", "curious", "generous", "courageous", "adventurous", "mysterious", "humorous", "jealous", "poisonous", "joyous", "glorious", "anxious", "cautious", "envious"],
        ex: "A mysterious parcel sat outside our door with no name on it." },
      { title: "-er / -est (more, most)", words: ["taller, tallest", "faster, fastest", "braver, bravest", "happier, happiest", "bigger, biggest", "kinder, kindest", "noisier, noisiest", "brighter, brightest", "darker, darkest", "hotter, hottest", "wiser, wisest", "gentler, gentlest"],
        ex: "It was the hottest day of the year, and the queue for ice cream was the longest I had ever seen.",
        note: "Long words use <i>more</i> and <i>most</i> instead: more beautiful, most dangerous." },
      { title: "-er / -or (a person who)", words: ["teacher", "baker", "swimmer", "driver", "cleaner", "leader", "helper", "visitor", "inventor", "sailor", "actor", "collector"],
        ex: "The cleaner at our void deck always greets us with a warm smile." }
    ]},

    { type: "table", title: "Spelling rules when adding suffixes", head: ["Rule", "Examples"], rows: [
      ["Change y to i (when a consonant comes before the y)", "happy → happiness, happily; lazy → laziness; angry → angrily; busy → business"],
      ["Keep the y when a vowel comes before it", "play → playful; enjoy → enjoyment; joy → joyous"],
      ["Double the last consonant for short words (one vowel + one consonant)", "big → bigger, biggest; hot → hotter; sad → sadder"],
      ["Drop the silent e before a suffix that starts with a vowel", "excite → excitable; adore → adorable; fame → famous"],
      ["Keep the silent e before a suffix that starts with a consonant", "hope → hopeful; excite → excitement; care → careless"],
      ["Watch the exceptions", "true → truly; argue → argument; whole → wholly; courage → courageous (keeps its e)"],
      ["Adding a prefix never changes the spelling of the root", "dis + appear → disappear; mis + spell → misspell; un + necessary → unnecessary"]
    ]},

    { type: "tip", html: "<b>Tip:</b> When you meet a long word you do not know, cover the prefix and suffix with your fingers. The root left in the middle often tells you the meaning: <i>un-forget-able</i> means “cannot be forgotten”." },

    { type: "table", title: "44 word families for compositions", head: ["Word", "Noun", "Adjective", "Adverb", "Opposites and relatives"], rows: [
      ["happy", "happiness", "happy", "happily", "unhappy, unhappiness, unhappily"],
      ["kind", "kindness", "kind, kind-hearted", "kindly", "unkind, unkindness"],
      ["brave", "bravery", "brave", "bravely", "braver, bravest"],
      ["care", "care, carer, carelessness", "careful, careless, caring", "carefully, carelessly", "uncaring, carefree"],
      ["hope", "hope, hopefulness", "hopeful, hopeless", "hopefully, hopelessly", "hopelessness"],
      ["fear", "fear, fearlessness", "fearful, fearless, fearsome", "fearfully, fearlessly", "fear (verb)"],
      ["anger", "anger", "angry", "angrily", "anger (verb), angered"],
      ["sad", "sadness", "sad", "sadly", "sadden, saddened"],
      ["nervous", "nervousness, nerves", "nervous", "nervously", "unnerved, nerve-racking"],
      ["proud", "pride", "proud", "proudly", "pride yourself on"],
      ["honest", "honesty", "honest", "honestly", "dishonest, dishonesty, dishonestly"],
      ["patient", "patience", "patient", "patiently", "impatient, impatience, impatiently"],
      ["polite", "politeness", "polite", "politely", "impolite, impoliteness"],
      ["excite", "excitement", "excited, exciting", "excitedly", "excitable, unexciting"],
      ["disappoint", "disappointment", "disappointed, disappointing", "disappointingly", "disappoint (verb)"],
      ["amaze", "amazement", "amazed, amazing", "amazingly", "amaze (verb)"],
      ["embarrass", "embarrassment", "embarrassed, embarrassing", "embarrassingly", "embarrass (verb)"],
      ["terror", "terror", "terrified, terrifying", "terrifyingly", "terrify (verb)"],
      ["joy", "joy, enjoyment", "joyful, joyous, enjoyable", "joyfully", "enjoy, joyless"],
      ["grateful", "gratitude", "grateful", "gratefully", "ungrateful"],
      ["friend", "friendship, friendliness", "friendly", "in a friendly way", "unfriendly, befriend, friendless"],
      ["lonely", "loneliness", "lonely, alone", "alone", "lonelier, loneliest"],
      ["curious", "curiosity", "curious", "curiously", "curiosities, more curious"],
      ["generous", "generosity", "generous", "generously", "ungenerous"],
      ["confident", "confidence", "confident", "confidently", "overconfident, self-confidence"],
      ["anxious", "anxiety", "anxious", "anxiously", "anxieties"],
      ["calm", "calm, calmness", "calm", "calmly", "calm down, calmer"],
      ["quiet", "quiet, quietness", "quiet", "quietly", "quieten"],
      ["silent", "silence", "silent", "silently", "silence (verb)"],
      ["dark", "darkness", "dark", "darkly", "darken"],
      ["bright", "brightness", "bright", "brightly", "brighten"],
      ["beauty", "beauty", "beautiful", "beautifully", "beautify"],
      ["danger", "danger", "dangerous", "dangerously", "endanger, endangered"],
      ["courage", "courage", "courageous", "courageously", "encourage, encouragement, discourage"],
      ["mystery", "mystery", "mysterious", "mysteriously", "mystify, mystified"],
      ["success", "success", "successful", "successfully", "succeed, unsuccessful"],
      ["help", "help, helper, helpfulness", "helpful, helpless", "helpfully, helplessly", "unhelpful, helplessness"],
      ["power", "power", "powerful, powerless", "powerfully", "empower, overpower"],
      ["peace", "peace", "peaceful", "peacefully", "peacemaker"],
      ["thought", "thought, thoughtfulness", "thoughtful, thoughtless", "thoughtfully, thoughtlessly", "think, rethink"],
      ["comfort", "comfort", "comfortable, comforting", "comfortably", "uncomfortable, discomfort"],
      ["surprise", "surprise", "surprised, surprising", "surprisingly", "surprise (verb)"],
      ["wonder", "wonder", "wonderful, wondrous", "wonderfully", "wonder (verb)"],
      ["sudden", "suddenness", "sudden", "suddenly", "all of a sudden"]
    ]},

    { type: "chips", title: "Word families in action", groups: [
      { title: "The happy family", words: ["happy", "happier", "happiest", "happily", "happiness", "unhappy", "unhappily", "unhappiness"],
        ex: "Her unhappiness melted away when she saw her grandmother waving happily at the gate." },
      { title: "The care family", words: ["care", "careful", "carefully", "careless", "carelessly", "carelessness", "caring", "carefree"],
        ex: "My carelessness cost us the game, so I promised to play more carefully next time." },
      { title: "The courage family", words: ["courage", "courageous", "courageously", "encourage", "encouraging", "encouragement", "discourage", "discouraged"],
        ex: "With Mum’s encouragement, I courageously raised my hand to answer." },
      { title: "The fear family", words: ["fear", "fearful", "fearfully", "fearless", "fearlessly", "fearlessness", "fearsome"],
        ex: "The dog looked fearsome, but my fearless little sister walked straight up and asked the owner if she could pat it." },
      { title: "The patience family", words: ["patient", "patiently", "patience", "impatient", "impatiently", "impatience"],
        ex: "Tapping his foot impatiently, Ravi glared at the slow-moving queue." },
      { title: "The honest family", words: ["honest", "honestly", "honesty", "dishonest", "dishonestly", "dishonesty"],
        ex: "Her honesty in returning the wallet earned her a letter of praise from the principal." },
      { title: "The success family", words: ["succeed", "success", "successful", "successfully", "unsuccessful", "unsuccessfully"],
        ex: "After three unsuccessful attempts, I finally succeeded in riding without stabilisers." },
      { title: "The comfort family", words: ["comfort", "comforting", "comfortable", "comfortably", "uncomfortable", "uncomfortably", "discomfort"],
        ex: "I shifted uncomfortably in my seat as the teacher read out my name." }
    ]},

    { type: "mcq", title: "Quick check", intro: "Choose the correct word.", items: [
      { q: "Jun Hao was so ____ that he forgot his water bottle three times this week.", o: ["careful", "careless", "caring"], a: 1, e: "<b>careless</b> means without care, which explains why he kept forgetting." },
      { q: "I had to ____ my composition because it was full of mistakes.", o: ["rewrite", "miswrite", "unwrite"], a: 0, e: "re- means again, so <b>rewrite</b> means write again." },
      { q: "The magician made the coin ____ into thin air.", o: ["misappear", "unappear", "disappear"], a: 2, e: "dis- + appear = <b>disappear</b>." },
      { q: "We watched the fireworks in ____.", o: ["amazement", "amazing", "amazedly"], a: 0, e: "After “in” we need a noun: <b>amazement</b>." },
      { q: "Which word is spelt correctly?", o: ["happyness", "happiness", "happines"], a: 1, e: "Change y to i before adding -ness: <b>happiness</b>." },
      { q: "It is ____ to finish ten pages of homework in five minutes!", o: ["unpossible", "impossible", "dispossible"], a: 1, e: "im- comes before p: <b>impossible</b>." },
      { q: "Mdm Lee thanked the volunteers for their ____.", o: ["generous", "generously", "generosity"], a: 2, e: "We need a noun after “their”: <b>generosity</b>." },
      { q: "The rice was ____, so it was still hard in the middle.", o: ["undercooked", "overcooked", "precooked"], a: 0, e: "under- means too little, so <b>undercooked</b> food is not cooked enough." }
    ]}
  ]},

{ id: "en-confused", group: "Word banks", order: 87, cat: "words", title: "Commonly confused words",
  intro: "Some words sound alike or look alike but mean very different things. Read these pairs often, learn the memory tricks, and you will stop losing marks for easy mistakes.",
  blocks: [
    { type: "tip", html: "<b>Tip:</b> When you proofread, slow down at these words and ask: “Which one do I mean here?” Say the sentence again with the meaning instead of the word. If it still makes sense, you chose correctly." },

    { type: "table", title: "Sound-alikes you use every day", head: ["Words", "Meaning", "Example"], rows: [
      ["their / there / they’re", "their = belonging to them; there = in that place; they’re = they are", "They’re putting their bags over there."],
      ["your / you’re", "your = belonging to you; you’re = you are", "You’re going to love your present."],
      ["its / it’s", "its = belonging to it; it’s = it is / it has", "It’s wagging its tail."],
      ["to / too / two", "to = towards; too = also / very; two = 2", "The two of us went to the park too."],
      ["where / were / wear / we’re", "where = which place; were = past of are; wear = put on clothes; we’re = we are", "We’re not sure where our jackets were, so we couldn’t wear them."],
      ["whose / who’s", "whose = belonging to whom; who’s = who is", "Who’s the boy whose kite is stuck in the tree?"],
      ["hear / here", "hear = with your ears; here = this place", "Come over here so you can hear the music."],
      ["then / than", "then = after that; than = comparing", "I finished my homework, then I read. Reading is more fun than TV."],
      ["weather / whether", "weather = rain, sun, wind; whether = if", "We do not know whether the weather will be fine on Sports Day."],
      ["passed / past", "passed = went by (verb); past = time before, or beyond", "We passed the old school. In the past, Dad studied there."],
      ["right / write", "right = correct or the opposite of left; write = put words on paper", "Write your name on the right side of the page."],
      ["knew / new", "knew = past of know; new = not old", "I knew at once that the bag was new."],
      ["know / no", "know = have the knowledge; no = not any / the opposite of yes", "I know there is no milk left."],
      ["threw / through", "threw = past of throw; through = in one side and out the other", "He threw the ball through the open window."],
      ["whole / hole", "whole = all of it; hole = an opening", "The whole class stared at the hole in the ceiling."],
      ["peace / piece", "peace = calm, no fighting; piece = a part", "May I have a piece of cake in peace?"],
      ["week / weak", "week = seven days; weak = not strong", "I felt weak for a whole week after the flu."],
      ["son / sun", "son = a male child; sun = the star that gives us light", "Mr Lim’s son loves playing in the sun."],
      ["hour / our", "hour = sixty minutes; our = belonging to us", "Our bus was an hour late."],
      ["meat / meet", "meat = food from animals; meet = come together", "Let’s meet at the satay stall. The grilled meat there is the best!"],
      ["sea / see", "sea = a large body of salt water; see = with your eyes", "From the top of the hill, you can see the sea."],
      ["one / won", "one = 1; won = past of win", "Our team won by one goal."],
      ["for / four", "for = meant for; four = 4", "I bought four buns for my family."],
      ["by / buy / bye", "by = next to / done by; buy = pay for; bye = goodbye", "I said bye and went to buy bread by the MRT station."],
      ["tail / tale", "tail = the end part of an animal; tale = a story", "Grandpa told a tale about a monkey with a very long tail."],
      ["plain / plane", "plain = simple / flat land; plane = an aeroplane", "From the plane, the green plain looked like a carpet."],
      ["flour / flower", "flour = powder for baking; flower = a bloom", "Mum dusted flour on the dough shaped like a flower."],
      ["bare / bear", "bare = uncovered; bear = an animal / to put up with", "The bear walked across the bare rocks."],
      ["brake / break", "brake = to stop a vehicle; break = to smash / a rest", "Dad had to brake hard, but luckily the eggs in the boot did not break."],
      ["sight / site", "sight = seeing / something seen; site = a place where something is built", "The construction site was not a pretty sight."],
      ["steal / steel", "steal = take without asking; steel = a strong metal", "The thief tried to steal the steel safe."],
      ["board / bored", "board = a flat piece of wood / to get on; bored = not interested", "I was so bored that I drew on the whiteboard."],
      ["poor / pour", "poor = having little money / unlucky; pour = make liquid flow", "Pour some water for the poor, thirsty dog."],
      ["role / roll", "role = a part in a play; roll = to turn over / bread", "Priya ate a bread roll before practising her role in the class play."],
      ["fair / fare", "fair = just / a fun event; fare = the price of a ride", "It is not fair that the bus fare went up again."],
      ["grate / great", "grate = shred food; great = very good / very big", "I helped Mum grate the cheese, and the pizza tasted great."],
      ["heal / heel", "heal = get better; heel = the back of your foot", "It took two weeks for the cut on my heel to heal."],
      ["waist / waste", "waist = the middle of your body; waste = to use carelessly / rubbish", "Don’t waste that long ribbon. Tie it round your waist as a belt."],
      ["sew / so / sow", "sew = stitch with a needle; so = therefore / very; sow = plant seeds", "Grandma likes to sew, so she made me an apron to wear when we sow seeds."],
      ["mail / male", "mail = letters and parcels; male = a boy or man", "The male cat sat on the pile of mail."],
      ["aisle / isle", "aisle = a walkway between rows; isle = a small island", "We walked down the supermarket aisle looking for snacks for our trip to the isle."],
      ["dyeing / dying", "dyeing = colouring with dye; dying = about to die", "She was dyeing the old T-shirt blue. The plant was dying from thirst."],
      ["morning / mourning", "morning = early part of the day; mourning = feeling sorrow after a death", "The family was in mourning; that morning the house was silent."],
      ["allowed / aloud", "allowed = permitted; aloud = so others can hear", "We are allowed to read aloud during the story session."],
      ["lead / led", "lead = to guide (now) / a grey metal; led = guided (past)", "Yesterday the teacher led us to the hall. Today Aisha will lead us."],
      ["cereal / serial", "cereal = breakfast grain; serial = in a series", "I ate my cereal while reading the serial number on the box."]
    ]},

    { type: "table", title: "Look-alikes and meaning mix-ups", head: ["Words", "Meaning", "Example"], rows: [
      ["affect / effect", "affect = to change something (verb); effect = the result (noun)", "The loud noise affected my sleep. The effect was a terrible headache."],
      ["lose / loose", "lose = not have any more / not win; loose = not tight", "My tooth is loose. I hope I don’t lose it at school!"],
      ["borrow / lend", "borrow = take for a while; lend = give for a while", "May I borrow your ruler? Yes, I will lend it to you."],
      ["quite / quiet", "quite = fairly / very; quiet = not noisy", "The library was quite quiet that afternoon."],
      ["advice / advise", "advice = a suggestion (noun); advise = to suggest (verb)", "The coach advised us to rest. It was good advice."],
      ["accept / except", "accept = agree to take; except = but not", "I accept all the invitations except the one on Sunday."],
      ["breath / breathe", "breath = the air (noun); breathe = to take in air (verb)", "Take a deep breath, and breathe out slowly."],
      ["desert / dessert", "desert = a dry, sandy place; dessert = a sweet dish after a meal", "We had chendol for dessert, not sand from the desert!"],
      ["practice / practise", "practice = the noun; practise = the verb (British spelling)", "I practise the piano daily. Practice makes perfect."],
      ["licence / license", "licence = the noun; license = the verb (British spelling)", "You need a licence to drive. The shop is licensed to sell medicine."],
      ["device / devise", "device = a gadget (noun); devise = to plan or invent (verb)", "We devised a clever device to water the plants."],
      ["stationary / stationery", "stationary = not moving; stationery = pens, paper and so on", "The bus was stationary outside the stationery shop."],
      ["principal / principle", "principal = head of a school / most important; principle = a rule or belief", "Our principal says honesty is an important principle."],
      ["compliment / complement", "compliment = praise; complement = go well with", "She paid me a compliment on how my scarf complemented my dress."],
      ["bought / brought", "bought = past of buy; brought = past of bring", "I bought a cake and brought it to Grandma’s flat."],
      ["choose / chose", "choose = pick (now); chose = picked (past)", "Today I choose red. Yesterday I chose blue."],
      ["lie / lay", "lie = rest flat (lie, lay, lain); lay = put something down (lay, laid, laid)", "I lie on the sofa. Please lay the plates on the table."],
      ["rise / raise", "rise = go up by itself; raise = lift something up", "The sun rises early. Raise your hand to answer."],
      ["cloth / clothes", "cloth = material; clothes = things you wear", "Mum used an old cloth to wipe the clothes rack."],
      ["dairy / diary", "dairy = milk products; diary = a daily journal", "In my diary, I wrote about our trip to the dairy farm."],
      ["later / latter", "later = after some time; latter = the second of two", "Between rice and noodles, I chose the latter. I will have rice later."],
      ["lightning / lightening", "lightning = flash in a storm; lightening = making lighter", "A flash of lightning lit up the room. Later, the sky was lightening as dawn came."],
      ["envelop / envelope", "envelop = to wrap or surround; envelope = a paper cover for a letter", "Fog enveloped the hill. I sealed the envelope."],
      ["metre / meter", "metre = a unit of length; meter = a machine that measures", "The water meter is one metre from the gate."],
      ["check / cheque", "check = to look over; cheque = a written order to pay money", "Dad checked the cheque before signing it."],
      ["medal / meddle", "medal = an award; meddle = interfere", "Don’t meddle with my medal collection!"],
      ["farther / further", "farther = more distance; further = more, extra", "We walked farther than planned. Let me explain further."],
      ["beside / besides", "beside = next to; besides = as well as / also", "Besides Wei Ming, who sat beside you?"],
      ["sore / saw", "sore = painful; saw = past of see / a cutting tool", "I saw that my knee was red and sore."]
    ]},

    { type: "table", title: "Grammar pairs that trip us up", head: ["Words", "Meaning", "Example"], rows: [
      ["fewer / less", "fewer = things you can count; less = things you cannot count", "Fewer pupils came, so we had less noise."],
      ["number / amount", "number = countable things; amount = uncountable things", "A large number of birds ate a large amount of bread."],
      ["between / among", "between = two people or things; among = three or more", "The secret stayed between Aisha and me, not among the whole class."],
      ["bring / take", "bring = carry towards here; take = carry away from here", "Bring your book to me, then take it home."],
      ["teach / learn", "teach = give knowledge; learn = get knowledge", "Mr Tan teaches us maths, and we learn a lot."],
      ["say / tell", "say something; tell someone something", "She said hello. She told me a secret."],
      ["see / look / watch", "see = notice with eyes; look = turn your eyes to; watch = look for a while at something moving", "Look! Can you see the bird? Let’s watch it build its nest."],
      ["hear / listen", "hear = sounds reach your ears; listen = pay attention to sounds", "I heard a noise, so I listened carefully."],
      ["since / for", "since = from a point in time; for = a length of time", "I have lived here since 2020. I have lived here for six years."],
      ["already / all ready", "already = before now; all ready = everyone or everything is ready", "We were all ready, but the bus had already left."],
      ["altogether / all together", "altogether = completely / in total; all together = all in one place", "We sang all together. Altogether, it was a lovely concert."],
      ["everyday / every day", "everyday = ordinary (adjective); every day = each day", "Brushing my teeth is an everyday task. I do it every day."],
      ["maybe / may be", "maybe = perhaps; may be = might be", "Maybe it will rain. It may be too wet to play."],
      ["a lot / alot", "a lot is always two words; alot is not a word", "I learnt a lot at camp."]
    ]},

    { type: "cards", title: "Memory tricks", items: [
      { tag: "Spelling", title: "desert or dessert?", text: "Dessert has two s’s because you always want seconds of something sweet.", ex: "Strawberry shortcake is my favourite dessert." },
      { tag: "Spelling", title: "quiet or quite?", text: "Quiet ends in “et”, like “pet”. A sleeping pet is quiet.", ex: "The cat was quiet; the test was quite easy." },
      { tag: "Meaning", title: "their or there?", text: "There has “here” inside it, so it is about a place. Their has “heir”, a person who owns things.", ex: "Their shoes are over there." },
      { tag: "Meaning", title: "its or it’s?", text: "Try saying “it is”. If it fits, use it’s. If not, use its. Like his and hers, its has no apostrophe.", ex: "It’s raining, and the dog is chewing its bone." },
      { tag: "Meaning", title: "affect or effect?", text: "Remember RAVEN: Remember, Affect is a Verb, Effect is a Noun.", ex: "The rain affected the game. The effect was a muddy field." },
      { tag: "Meaning", title: "lose or loose?", text: "Loose has two o’s, like a loose belt with extra room. Lose has lost one o.", ex: "If my shoelace is loose, I may lose my shoe." },
      { tag: "Meaning", title: "borrow or lend?", text: "Borrow means taking FROM; lend means giving TO. You borrow from someone; you lend to someone.", ex: "Can you lend me your pencil? Can I borrow your pencil?" },
      { tag: "Spelling", title: "advice or advise? practice or practise?", text: "C is for the noun (think “ice” is a thing), S is for the verb (doing). Same trick for licence / license.", ex: "I took her advice and practised harder." },
      { tag: "Spelling", title: "stationary or stationery?", text: "Stationery with an e is for envelopes. Stationary with an a is for “a car standing still”.", ex: "I bought stationery while the bus stood stationary." },
      { tag: "Meaning", title: "principal or principle?", text: "The principal is your pal. A principle is a rule.", ex: "The principal explained the school’s principles." },
      { tag: "Meaning", title: "breath or breathe?", text: "Breathe has an extra e, and you need to say the long “ee” sound when you breathe in.", ex: "I held my breath, then breathed out slowly." },
      { tag: "Meaning", title: "accept or except?", text: "Except starts with “ex”, like exit: something is left out.", ex: "Everyone except Ravi accepted the invitation." },
      { tag: "Meaning", title: "hear or here?", text: "You hear with your ear. Hear has “ear” inside it!", ex: "I can hear the ice-cream van from here." },
      { tag: "Grammar", title: "fewer or less?", text: "If you can count them one by one (sweets, people), use fewer. If you cannot (sugar, water), use less.", ex: "Fewer sweets means less sugar." }
    ]},

    { type: "mcq", title: "Which word fits?", intro: "Choose the correct word for each sentence.", items: [
      { q: "The children forgot ____ umbrellas at the void deck.", o: ["there", "their", "they’re"], a: 1, e: "<b>their</b> shows the umbrellas belong to the children." },
      { q: "The heavy rain did not ____ our plans for the picnic.", o: ["effect", "infect", "affect"], a: 2, e: "We need a verb (to change): <b>affect</b>." },
      { q: "Could you ____ me your eraser, please?", o: ["lend", "borrow", "loan off"], a: 0, e: "You <b>lend</b> something to someone. I borrow FROM you; you lend TO me." },
      { q: "Please be ____ in the library.", o: ["quiet", "quite", "quit"], a: 0, e: "<b>quiet</b> means not noisy." },
      { q: "My grandmother gave me some wise ____.", o: ["advices", "advise", "advice"], a: 2, e: "After “some wise” we need a noun: <b>advice</b>." },
      { q: "I need to ____ my spelling every day.", o: ["practise", "practice", "practising"], a: 0, e: "In British spelling, the verb is <b>practise</b> with an s." },
      { q: "After the race, I could hardly ____.", o: ["breath", "breathe", "breathing"], a: 1, e: "We need the verb: <b>breathe</b>." },
      { q: "If you are not careful, you will ____ your wallet.", o: ["loss", "loose", "lose"], a: 2, e: "<b>lose</b> means to no longer have something. Loose means not tight." },
      { q: "We had mango pudding for ____.", o: ["dessert", "desert", "deserts"], a: 0, e: "<b>dessert</b> is the sweet dish after a meal." },
      { q: "Everyone came to the party ____ Jun Hao, who was ill.", o: ["accept", "except", "expect"], a: 1, e: "<b>except</b> means “but not”." }
    ]}
  ]},

{ id: "en-formal", group: "Word banks", order: 88, cat: "phrases", title: "Formal phrases",
  intro: "When you write to a principal, a company or someone you do not know well, your words should sound polite and formal. Borrow these phrases for every part of a formal letter or email in situational writing.",
  blocks: [
    { type: "tip", html: "<b>Tip:</b> Formal writing is polite, clear and complete. Use full forms (I am, not I’m), avoid slang and exclamation marks, and get to the point: say WHY you are writing in your first or second sentence." },

    { type: "chips", title: "Starting your letter or email", groups: [
      { title: "Greetings", words: ["Dear Mr Tan,", "Dear Mrs Kumar,", "Dear Ms Wong,", "Dear Madam Lim,", "Dear Dr Rahman,", "Dear Principal,", "Dear Sir or Madam,", "Dear Members of the Residents’ Committee,", "Dear Parents,", "Dear Fellow Pupils,"],
        ex: "Dear Sir or Madam,",
        note: "Use the person’s title and surname (Mr Tan), never their first name. If you do not know the name, write “Dear Sir or Madam”." },
      { title: "Opening lines", words: ["I hope this letter finds you well.", "I hope you are keeping well.", "Thank you for your letter dated 3 March.", "Thank you for your prompt reply.", "I am a Primary 5 pupil from Class 5B.", "Please allow me to introduce myself.", "My name is Priya and I am the class monitor of 4E.", "I am writing on behalf of my class.", "I am writing on behalf of the Environmental Club.", "With reference to your notice about the upcoming Racial Harmony Day,", "Further to our conversation yesterday,", "I am a resident of Block 245, Bedok North."],
        ex: "My name is Priya and I am the class monitor of 4E. I am writing on behalf of my class." }
    ]},

    { type: "chips", title: "Stating your purpose", groups: [
      { title: "Say why you are writing", words: ["I am writing to inform you that…", "I am writing to ask whether…", "I am writing to request…", "I am writing to apologise for…", "I am writing to express my thanks for…", "I am writing to complain about…", "I am writing to invite you to…", "I am writing to suggest…", "The purpose of this letter is to…", "I would like to bring to your attention…", "I would like to enquire about…", "I wish to report that…", "I am writing in response to…", "I would like to share some concerns about…", "This email is to let you know that…", "I would like to propose…"],
        ex: "I am writing to request permission to use the school hall for our class farewell party.",
        note: "Your purpose should be clear by the end of your first paragraph. The reader should never have to guess." }
    ]},

    { type: "chips", title: "Giving details", groups: [
      { title: "When, where, what, how much", words: ["The event will be held on Saturday, 12 May, from 9 a.m. to 12 noon.", "The venue is the school hall.", "The incident took place at about 4 p.m. on Monday.", "It happened near the void deck of Block 123.", "Participants are required to wear their PE attire.", "The cost is $5 per person.", "Please note that…", "Further details are as follows:", "I have attached a copy of the receipt.", "According to your notice,", "To give you some background,", "The item in question is a blue water bottle with my name on it.", "The closing date for registration is 30 April.", "Light refreshments will be provided."],
        ex: "The event will be held on Saturday, 12 May, from 9 a.m. to 12 noon. The venue is the school hall.",
        note: "Answer the 5Ws and 1H: who, what, when, where, why and how. Copy dates, times and places exactly from the question." },
      { title: "Formal linking words", words: ["Firstly,", "Secondly,", "Lastly,", "In addition,", "Furthermore,", "Moreover,", "However,", "Therefore,", "As a result,", "Consequently,", "Nevertheless,", "Meanwhile,", "Regarding…", "With regard to…", "Prior to…", "In conclusion,"],
        ex: "The playground lights are not working. As a result, the area is very dark at night." }
    ]},

    { type: "chips", title: "Asking politely", groups: [
      { title: "Making requests", words: ["Could you please…?", "Would it be possible to…?", "I would be grateful if you could…", "I would appreciate it if you could…", "May I request…", "Kindly let me know…", "I would like to ask for permission to…", "Would you be able to…?", "Please let me know if…", "I would be most grateful for your help in…", "Could you kindly reply by Friday, 10 June?", "I hope you will consider my request.", "It would be very helpful if…", "Please advise me on…", "Do let me know whether this is convenient for you."],
        ex: "I would be grateful if you could let us know whether the hall is available on that day.",
        note: "“I would be grateful if…” is one of the most useful formal phrases. It is polite but still clear." },
      { title: "Inviting", words: ["We would be delighted if you could attend…", "It is my pleasure to invite you to…", "We would be privileged to have you as our guest of honour.", "We sincerely hope that you will be able to join us.", "Your presence would mean a great deal to us.", "Please let us know by 5 May if you are able to attend.", "We look forward to welcoming you.", "Kindly confirm your attendance with Ms Lee.", "The programme will include…", "Do join us for an evening of fun and games."],
        ex: "We would be delighted if you could attend our Teachers’ Day concert on Friday, 2 September." }
    ]},

    { type: "chips", title: "Saying sorry and making things right", groups: [
      { title: "Apologising", words: ["I sincerely apologise for…", "Please accept my apologies for…", "I am truly sorry for…", "I regret to inform you that…", "I apologise for any inconvenience caused.", "I deeply regret my careless behaviour.", "It was not my intention to…", "I take full responsibility for…", "I should have…", "I assure you that it will not happen again.", "I hope you will accept my apology.", "To make up for it, I will…", "I am sorry for the delay in replying.", "I understand how upsetting this must have been for you."],
        ex: "I sincerely apologise for breaking your window with my football. I take full responsibility and will pay for the repair.",
        note: "A good apology does three things: says sorry, admits what you did, and offers to put it right." }
    ]},

    { type: "chips", title: "Complaining politely", groups: [
      { title: "Raising a problem calmly", words: ["I am writing to express my concern about…", "I would like to draw your attention to…", "I was disappointed to find that…", "Unfortunately,…", "I regret to say that…", "I am afraid that…", "This has caused much inconvenience to…", "Many residents have noticed that…", "It is not the first time this has happened.", "Despite my earlier request,…", "I understand that you are busy, but…", "I believe this problem could be solved by…"],
        ex: "I would like to draw your attention to the overflowing rubbish bins at the void deck of Block 87.",
        note: "Stay calm and stick to facts. A polite complaint is far more likely to be acted on than an angry one." },
      { title: "Asking for action", words: ["I would be grateful if the matter could be looked into.", "I hope this matter can be resolved soon.", "I trust you will take the necessary action.", "I would appreciate a replacement or a full refund.", "I would like to request that the item be repaired.", "Could you please look into this matter as soon as possible?", "I hope to receive your reply within a week."],
        ex: "I would appreciate a replacement or a full refund, as the headphones stopped working after two days." }
    ]},

    { type: "chips", title: "Thanking and suggesting", groups: [
      { title: "Thanking", words: ["Thank you very much for…", "I am truly grateful for…", "I would like to express my heartfelt thanks to…", "I really appreciate…", "Your kindness is deeply appreciated.", "We are most grateful for your generous donation.", "It was very thoughtful of you to…", "Thank you for taking the time to…", "Your help made a great difference to…", "Without your help, we would not have…", "On behalf of my class, I would like to thank…", "Words cannot express how grateful I am.", "Please accept our sincere thanks."],
        ex: "On behalf of my class, I would like to thank you for taking the time to show us around the fire station." },
      { title: "Suggesting", words: ["I would like to suggest that…", "Perhaps we could…", "May I suggest…", "It might be a good idea to…", "One possible solution would be to…", "I believe it would be helpful if…", "Would you consider…?", "Another option is to…", "I propose that…", "It would be beneficial to…", "This would allow us to…", "If possible, we could…", "I strongly recommend…", "In my opinion, the best way forward is…"],
        ex: "One possible solution would be to place more recycling bins near the canteen.",
        note: "After a suggestion, add a reason: “This would allow pupils to recycle their drink cans easily.”" }
    ]},

    { type: "chips", title: "Ending your letter or email", groups: [
      { title: "Closing lines", words: ["I look forward to hearing from you.", "I look forward to your reply.", "Thank you for your time and attention.", "Thank you for your understanding.", "Thank you in advance for your help.", "Should you have any questions, please contact me at 9123 4567.", "Please do not hesitate to contact me.", "I hope to hear from you soon.", "Thank you once again.", "I hope my suggestions will be considered.", "We hope to see you there."],
        ex: "Thank you for your time and attention. I look forward to hearing from you." },
      { title: "Sign-offs", words: ["Yours sincerely,", "Yours faithfully,", "Kind regards,", "Best regards,", "Warm regards,"],
        ex: "Yours sincerely,<br>Tan Wei Ming<br>Class Monitor, 5C",
        note: "Use “Yours sincerely” when you began with the person’s name, and “Yours faithfully” when you began with “Dear Sir or Madam”. Below your sign-off, write your full name (and your role, if it helps)." }
    ]},

    { type: "table", title: "Informal or formal?", head: ["Informal (for friends)", "Formal (for situational writing)"], weakCol: 0, rows: [
      ["Hi!", "Dear Mr Tan,"],
      ["Hey guys", "Dear residents,"],
      ["I hope you’re fine.", "I hope this letter finds you well."],
      ["Just wanted to say…", "I am writing to…"],
      ["About…", "Regarding… / With regard to…"],
      ["I want to…", "I would like to…"],
      ["Can you…?", "Could you please…?"],
      ["Tell me…", "Please inform me…"],
      ["Let me know.", "Please let me know at your earliest convenience."],
      ["ask about", "enquire about"],
      ["get", "receive / obtain"],
      ["give", "provide"],
      ["need", "require"],
      ["help", "assist"],
      ["start", "begin / commence"],
      ["end", "conclude"],
      ["buy", "purchase"],
      ["fix", "repair / resolve"],
      ["look into it", "investigate the matter"],
      ["find", "locate"],
      ["before", "prior to"],
      ["lots of / loads of", "many / a large number of"],
      ["heaps of rubbish", "a large amount of litter"],
      ["a bit", "slightly"],
      ["kids", "children"],
      ["stuff", "items / belongings"],
      ["cool / awesome", "excellent / impressive"],
      ["yummy", "delicious"],
      ["really bad", "unacceptable / very poor"],
      ["OK", "acceptable / satisfactory"],
      ["mess up", "make a mistake"],
      ["sort it out", "resolve the matter"],
      ["hang out", "spend time together"],
      ["I think…", "In my opinion… / I believe…"],
      ["Also,", "In addition, / Furthermore,"],
      ["But", "However,"],
      ["So", "Therefore, / As a result,"],
      ["ASAP", "as soon as possible"],
      ["I’m / don’t / won’t", "I am / do not / will not"],
      ["gonna / wanna", "going to / would like to"],
      ["yeah", "yes"],
      ["Sorry!", "I sincerely apologise."],
      ["I’m really sorry I broke it.", "I sincerely apologise for breaking it."],
      ["Thanks a lot!", "Thank you very much."],
      ["Thanks so much for the stuff!", "We are most grateful for your kind donation."],
      ["It was super fun!", "It was a very enjoyable experience."],
      ["Come to our party!", "We would be delighted if you could attend our party."],
      ["You must come!", "We hope you will be able to join us."],
      ["Your shop is terrible.", "I am disappointed with the service I received."],
      ["That’s so unfair!", "I feel that this is unfair."],
      ["Give me my money back.", "I would appreciate a full refund."],
      ["Hurry up and fix it.", "I would be grateful if this could be repaired soon."],
      ["Tell me what you think.", "I would welcome your views."],
      ["Got it, thanks.", "Thank you. I have noted the details."],
      ["Get back to me.", "I look forward to your reply."],
      ["See you!", "I look forward to meeting you."],
      ["Bye! / Love,", "Yours sincerely,"]
    ]},

    { type: "tip", html: "<b>Tip:</b> Check your tone by imagining you are reading your letter aloud to the principal. If any line would make you giggle or blush, change it to a formal phrase from this page." }
  ]}

]});
