window.CONTENT_PARTS = window.CONTENT_PARTS || [];
window.CONTENT_PARTS.push({ lang: "en", units: [

{ id: "en-festivals", group: "Word banks", order: 96, cat: "topics", title: "Festivals and celebrations",
  intro: "Singapore celebrates all year round. This bank gives you lines for the sights, sounds, smells, tastes, actions and feelings of each festival, plus things people really say, so your celebration story feels like you were there.",
  blocks: [
    { type: "text", title: "How to use this bank", html: "Each festival is set out the way you would plan a story: <b>getting ready</b>, <b>the big day</b>, <b>the food</b>, <b>the people</b> and <b>how it felt</b>. The basic festival words (reunion dinner, ketupat, oil lamps, mooncakes) are already in the <i>Singapore life</i> and <i>Topic vocabulary</i> banks. Here you will find whole phrases and sentences that bring those words to life." },
    { type: "tip", html: "<b>Tip:</b> When you write about a festival that is not your own, write about what you <b>saw, tasted and learnt</b> as a guest, and show that you were curious and thankful. That is how a good friend writes, and it makes a lovely story." },

    { type: "chips", title: "Chinese New Year: getting ready", groups: [
      { title: "Spring cleaning and decorating", words: ["wiped down every window until it squeaked", "dusted the top of the cupboard for the first time all year", "threw out a whole bag of old newspapers", "pasted the red couplets on either side of the door", "hung a paper fu upside down so good fortune would “arrive”", "stuck red paper cut-outs on the windows", "set out a tray of sweets and dried fruit", "lined up pairs of mandarin oranges in a bowl", "filled the glass jars with love letters and kueh bangkit", "brought home a pot of pussy willow", "a new tablecloth in bright red", "Dad changed the curtains while Mum mopped"],
        ex: "The week before Chinese New Year, Mum and I wiped down every window until it squeaked, then pasted the red couplets on either side of the door.",
        note: "“Fu” means good fortune. Some families hang it upside down because the word for “upside down” sounds like “arrive” in Chinese." },
      { title: "Shopping in Chinatown", words: ["squeezed through the crowded stalls of Chinatown", "the rows of red lanterns overhead", "stall-owners calling out their best prices", "boxes of pineapple tarts stacked like bricks", "the sweet, smoky smell of bak kwa on the grill", "a queue that snaked round the corner", "Mum haggled politely for a better price", "free samples handed out on toothpicks", "bags so full the handles cut into my fingers", "the stall-owner wished us a prosperous year", "a giant lit-up zodiac animal above the street", "shoulder to shoulder with a thousand other shoppers"],
        ex: "We squeezed through the crowded stalls of Chinatown while the sweet, smoky smell of bak kwa on the grill made my stomach rumble." },
      { title: "New Year’s Eve", words: ["the whole family squeezed round one table", "Grandma had been cooking since morning", "the steamboat bubbled in the middle of the table", "chopsticks reached in from every side", "a whole steamed fish, saved for the end", "we left a little fish on the plate for a year of plenty", "Ah Ma spooned the best piece into my bowl", "cousins I had not seen since last year", "the adults talked over each other happily", "the television played New Year songs in the background", "we stayed up past midnight to welcome the New Year", "my eyelids grew heavy, but I refused to sleep"],
        ex: "At the reunion dinner, the whole family squeezed round one table while the steamboat bubbled in the middle.",
        note: "Leaving a little fish uneaten is a custom: the word for fish sounds like “plenty” or “surplus”." }
    ] },

    { type: "chips", title: "Chinese New Year: the big day", groups: [
      { title: "Visiting and red packets", words: ["put on my stiff new clothes", "the new shoes pinched my toes", "carried two mandarin oranges to every home", "offered the oranges with both hands", "bowed slightly and wished my grandparents good health", "received the red packet with both hands", "slipped the red packet into my pocket without opening it", "waited until we got home to open the red packets", "Uncle Ben’s flat was packed with relatives", "a blur of handshakes, hugs and “you’ve grown so tall!”", "the same question at every house: “How’s school?”", "drove from one flat to another all afternoon"],
        ex: "I offered the two mandarin oranges with both hands, bowed slightly and wished Ah Gong good health.",
        note: "It is polite to wait until you get home before opening red packets." },
      { title: "Tossing yusheng (lo hei)", words: ["a plate of raw fish and shredded vegetables in bright colours", "everyone stood up with chopsticks raised", "the shreds of carrot and radish flew into the air", "the higher we tossed, the louder we shouted", "called out wishes for good grades and good health", "a strand of jellyfish landed on Dad’s sleeve", "sweet plum sauce drizzled over the top", "crispy crackers crunched like tiny fireworks", "the plate was a happy mess by the end", "my little cousin tossed so hard that half of it landed on the table"],
        ex: "Everyone stood up with chopsticks raised, and the shreds of carrot and radish flew into the air as we shouted our wishes." },
      { title: "The lion dance", words: ["the drum began, slow and deep", "the cymbals crashed and my ears rang", "the gong boomed like thunder", "the lion blinked its huge furry eyes", "it shook its head and flapped its ears", "it crept forward as if it were sniffing for food", "two dancers moved as one animal", "it reared up onto a dancer’s shoulders", "it leapt from pole to pole", "it snapped up the lettuce hanging over the door", "tore the lettuce and scattered the leaves for good luck", "the crowd cheered and the little ones hid behind their parents", "a shower of mandarin orange peel rained down", "the beat got faster and faster until my heart kept time with it"],
        ex: "The lion blinked its huge furry eyes, crept forward and snapped up the lettuce hanging over the shop door." },
      { title: "Tastes of Chinese New Year", words: ["a pineapple tart that crumbled the moment I bit it", "sticky, sweet jam inside a buttery crust", "a slice of bak kwa, sweet and slightly charred", "crunchy love letters that shattered into flakes", "kueh bangkit that melted on my tongue", "a handful of salty melon seeds", "nian gao fried in egg until it was gooey", "sticky fingers from the sweet tray", "I lost count of how many tarts I ate"],
        ex: "The pineapple tart crumbled the moment I bit it, and the sticky, sweet jam stuck to my teeth." },
      { title: "Things people say at Chinese New Year", words: ["“Gong xi fa cai, Ah Ma!”", "“Xin nian kuai le!”", "“Wah, so tall already!”", "“Study hard, okay?”", "“Take more, take more, don’t be shy.”", "“Say thank you to Auntie.”", "“Wait until we get home to open it.”", "“Who wants to toss the yusheng?”", "“Higher! Higher!”", "“Huat ah!”", "“Can I have one more pineapple tart? Just one?”", "“Ah Gong, may you have good health and a long life.”"],
        ex: "“Wah, so tall already!” said Auntie Mei, pinching my cheek before pressing a red packet into my hands." }
    ] },

    { type: "chips", title: "Hari Raya Puasa", groups: [
      { title: "During Ramadan, the fasting month", words: ["Aisha woke before dawn for an early meal with her family", "she did not eat or drink from sunrise to sunset", "she still played at recess, just more gently", "the family waited at the table as the sun went down", "broke their fast with a sweet date and a glass of water", "the call to prayer drifted across the estate", "a quiet, thankful moment before the meal", "a spread of curries, kuih and rose syrup drink", "her family shared food with neighbours", "the Geylang Serai bazaar glowed with stalls and lights", "lanterns and lights strung along the streets", "her patience amazed me"],
        ex: "Aisha’s family waited at the table as the sun went down, then broke their fast with a sweet date and a glass of water.",
        note: "Fasting during Ramadan is an important act of worship for Muslims. Write about it with respect and admiration." },
      { title: "Hari Raya morning", words: ["the men and boys went to the mosque for morning prayers", "matching outfits in the same soft colour", "a baju Melayu with a songkok and a samping", "a flowing baju kurung in pale green", "the family lined up to ask forgiveness from the elders", "she kissed her grandmother’s hand and touched it to her forehead", "her grandmother hugged her and forgave her with a smile", "tears of joy in Nenek’s eyes", "everyone said “maaf zahir dan batin”", "little green packets of duit raya", "a family photo in front of the lit-up doorway", "the house smelt of coconut and spices before breakfast"],
        ex: "One by one, the family asked forgiveness from the elders, and Aisha kissed her grandmother’s hand.",
        note: "“Maaf zahir dan batin” means “forgive me, in body and in heart”." },
      { title: "Raya food and the open house", words: ["ketupat cut into neat white squares", "the woven coconut-leaf cases of ketupat", "rendang so tender it fell apart", "a rich, spicy smell that filled the whole corridor", "sayur lodeh in creamy coconut gravy", "lemang cooked in bamboo", "jars of kueh tart and kuih makmur", "pink rose syrup with tiny bubbles", "plate after plate kept coming out of the kitchen", "the door was open to friends of every race", "my classmates and I took off our shoes at the door", "Aisha’s mum would not let anyone leave hungry", "we ate with our right hands, the way Aisha showed us", "the flat was full of laughter and clinking plates"],
        ex: "At Aisha’s open house, plate after plate kept coming out of the kitchen, and her mum would not let anyone leave hungry." },
      { title: "Things people say at Hari Raya", words: ["“Selamat Hari Raya!”", "“Maaf zahir dan batin.”", "“Come in, come in! Have you eaten?”", "“Try the rendang, my mother made it.”", "“Take some kuih home for your family.”", "“Thank you for inviting us.”", "“You look so nice in your baju kurung!”", "“This is the best ketupat I’ve ever had.”", "“Is it all right if I sit here?”", "“Thank you, Makcik!”"],
        ex: "“Come in, come in! Have you eaten?” Aisha’s grandmother asked, already passing me a plate." }
    ] },

    { type: "chips", title: "Deepavali", groups: [
      { title: "Getting ready", words: ["Priya’s family cleaned the house from top to bottom", "new clothes folded on the bed, ready for the morning", "a bright silk saree with a golden border", "a crisp new kurta", "henna patterns swirling across her palms", "the henna smelt earthy and left orange-brown swirls", "strings of marigolds above the door", "rows of clay lamps lined up on the windowsill", "the house smelt of ghee and cardamom", "boxes of sweets ready to give away", "Priya could hardly sleep the night before"],
        ex: "Henna patterns swirled across Priya’s palms, and her new silk saree lay folded on the bed, ready for the morning." },
      { title: "The kolam at the doorstep", words: ["drew a kolam at the doorstep with rice flour", "let the white rice flour trickle between her fingers", "dots first, then loops joining them together", "a pattern of lotus petals and curling lines", "filled the shapes with bright coloured powder", "her grandmother’s hands moved quickly and surely", "I held my breath so I would not blow it away", "the kolam welcomed every visitor", "ants came to nibble the rice flour", "it was gone in a few days, which made it feel even more special"],
        ex: "Priya’s grandmother let the white rice flour trickle between her fingers, and a kolam of curling lotus petals appeared at the doorstep.",
        note: "A kolam is drawn with rice flour to welcome guests. In the past, the flour also fed ants and small birds." },
      { title: "Deepavali morning and the Festival of Lights", words: ["an oil bath before the sun came up", "prayers at the temple, with bells ringing", "the smell of camphor and incense", "the little flames trembled in the breeze", "a hundred tiny lamps glowing in the dark", "light pushed back the darkness", "the festival celebrates light winning over darkness", "the warm glow on everyone’s faces", "the whole corridor twinkled", "sparklers fizzing in the children’s hands"],
        ex: "When night fell, a hundred tiny lamps glowed along the corridor, and their flames trembled in the breeze." },
      { title: "Little India at Deepavali", words: ["arches of light stretched over Serangoon Road", "glowing peacocks and lotus flowers above the street", "the bazaar stalls spilled onto the pavement", "bangles stacked in every colour", "garlands of jasmine and marigold", "a sweet, heavy scent of flowers", "Tamil songs played from a shop", "the crowd moved slowly, like a warm river", "piles of bright fabric and shiny brass lamps", "a stall-owner smiled and handed me a free ladoo"],
        ex: "Arches of light stretched over Serangoon Road, and the sweet, heavy scent of jasmine garlands drifted through the crowd." },
      { title: "Deepavali food and greetings", words: ["murukku that crunched like a twig", "round, golden ladoo that crumbled in my hand", "a sweet so sugary it made my teeth tingle", "spicy mixture of fried lentils and peanuts", "biryani with fragrant yellow rice", "“Happy Deepavali!”", "“Please, have some more, there’s plenty.”", "“My grandmother made the murukku herself.”", "“Mind the kolam, don’t step on it!”", "“Light this one with me.”"],
        ex: "“My grandmother made the murukku herself,” Priya said proudly, and it crunched like a twig when I bit into it." }
    ] },

    { type: "chips", title: "Christmas", groups: [
      { title: "Orchard Road at Christmas", words: ["the trees along Orchard Road wrapped in fairy lights", "a giant tree outside the mall, taller than a bus", "snowflake lights twinkling overhead", "fake snow drifting down from a machine", "carollers in red scarves despite the heat", "a jazzy version of “Jingle Bells” from a shop", "families taking photos under the lights", "the shop windows looked like little winter worlds", "the smell of roasted chestnuts and caramel popcorn", "the street was so bright it felt like daytime", "warm, sticky air but a wintry feeling inside", "children perched on their dads’ shoulders"],
        ex: "Fake snow drifted down from a machine, and for a moment the warm, sticky air on Orchard Road felt like winter." },
      { title: "Christmas at home and church", words: ["hung the baubles on the lowest branches I could reach", "my little sister put the star on top, on Dad’s shoulders", "presents piling up under the tree", "the crackle of wrapping paper", "carols at church on Christmas Eve", "candlelight flickering on everyone’s faces", "the roast chicken came out golden and sizzling", "a log cake with a little plastic Santa on top", "Grandpa fell asleep on the sofa after lunch", "the house smelt of cinnamon and roast meat"],
        ex: "My little sister sat on Dad’s shoulders and put the star on top of the tree while we all clapped." },
      { title: "The class gift exchange", words: ["drew a name out of the tin and kept it a secret", "spent my savings on a set of gel pens", "wrapped it neatly, but the tape went everywhere", "a mountain of presents on the teacher’s table", "everyone shook their gifts to guess what was inside", "tore the paper open in one big rip", "a present I didn’t expect but loved", "we tried to guess who our Secret Santa was", "“How did you know I wanted this?”", "“Merry Christmas! I hope you like it.”", "“You were my Secret Santa? No way!”"],
        ex: "Everyone shook their gifts to guess what was inside, and Jun Hao gasped, “How did you know I wanted this?”" }
    ] },

    { type: "chips", title: "Mid-Autumn Festival", groups: [
      { title: "Lanterns", words: ["a rabbit lantern with a bobbing head", "a paper star-fruit lantern that folded flat", "a red carp lantern with paper scales", "a lantern that played a tinny tune", "the candle flickered inside the thin paper", "the lantern glowed orange against the dark", "a long line of lanterns weaving round the estate", "the moon followed us as we walked", "my candle tipped and the paper caught fire", "I blew it out quickly and only the corner was burnt", "glowsticks bent into bracelets", "the playground turned into a sea of little lights"],
        ex: "A long line of lanterns wove round the estate, and the moon seemed to follow us as we walked.",
        note: "If you write about a lantern catching fire, keep it small and show the child staying calm." },
      { title: "Mooncakes and the moon", words: ["cut the mooncake into thin slices, like a pie", "a golden salted egg yolk in the middle, like a tiny moon", "thick, sweet lotus paste", "the soft, cold skin of a snow-skin mooncake", "Grandma poured small cups of Chinese tea", "the tea washed away the sweetness", "the moon hung round and bright over the HDB blocks", "the fullest, brightest moon of the year", "Ah Ma told us the story of Chang’e flying to the moon", "I squinted, trying to see the rabbit on the moon", "we ate pomelo, sour and juicy", "families picnicked at the void deck under the moon"],
        ex: "Ah Ma cut the mooncake into thin slices, and a golden salted egg yolk sat in the middle like a tiny moon." },
      { title: "Things people say at Mid-Autumn", words: ["“Careful, don’t swing your lantern so hard.”", "“Look, the moon is so round tonight!”", "“Who wants the slice with the yolk?”", "“Can I light another candle?”", "“Ah Ma, tell us the story again.”", "“Your lantern is so cute!”", "“Let’s walk one more round.”", "“Do you think Chang’e is lonely up there?”"],
        ex: "“Ah Ma, tell us the story again,” my cousin begged, and Grandma smiled as she began the tale of Chang’e." }
    ] },

    { type: "chips", title: "Vesak Day and Thaipusam", groups: [
      { title: "Vesak Day", words: ["Vesak Day remembers the birth, enlightenment and passing of the Buddha", "Buddhist families went to the temple early in the morning", "rows of lotus lanterns hung at the temple", "people queued quietly to bathe a small statue of the baby Buddha", "poured water gently with a ladle", "the scent of incense and fresh flowers", "chanting rose and fell like waves", "many families ate vegetarian food that day", "volunteers gave out free meals", "people did good deeds and gave to those in need", "a candlelight procession in the evening", "a calm, peaceful feeling filled the hall"],
        ex: "At the temple, people queued quietly to bathe the small statue of the baby Buddha, pouring water gently with a ladle." },
      { title: "Thaipusam", words: ["Thaipusam is a Hindu festival of thanksgiving to Lord Murugan", "devotees prepare for weeks with prayer and fasting", "they walk barefoot from one temple to another", "many carried pots of milk on their heads", "some carried a kavadi, a tall, decorated frame", "peacock feathers swayed on the kavadi", "family and friends walked beside them to encourage them", "the beat of drums and the sound of singing", "people gave out water along the route", "a sense of deep faith and determination", "I watched quietly, full of respect"],
        ex: "Many devotees walked barefoot carrying pots of milk on their heads, while family and friends walked beside them to encourage them.",
        note: "Thaipusam is a solemn, religious day. Write about it calmly and with respect, as someone watching and learning." }
    ] },

    { type: "chips", title: "Birthdays", groups: [
      { title: "Getting the party ready", words: ["blew up balloons until I felt dizzy", "a balloon popped in my face and made everyone jump", "streamers taped across the void deck pillars", "a banner with my name in shiny letters", "party packs lined up on the table", "Mum ordered curry puffs, fried bee hoon and chicken wings", "my friends arrived in twos and threes", "a pile of presents grew on the chair", "Dad’s phone was ready to record everything", "musical chairs and pass-the-parcel", "the game got so noisy the neighbours peeped out"],
        ex: "A balloon popped in my face and made everyone jump, and then we all burst out laughing." },
      { title: "Cake and candles", words: ["the lights went off and the room went quiet", "Mum carried in the cake, candles flickering", "everyone sang “Happy Birthday”, a little out of tune", "the candles lit up my friends’ faces", "I closed my eyes and made a wish", "blew out all the candles in one breath", "one stubborn candle kept relighting", "smoke curled up from the wicks", "icing smeared on my nose", "chocolate cake so rich it stuck to the roof of my mouth", "Dad cut the cake into wobbly squares", "the first slice went to Grandma"],
        ex: "I closed my eyes, made a wish and blew out all the candles in one breath while everyone cheered." },
      { title: "Birthday feelings and dialogue", words: ["counted the days on the calendar", "woke up feeling a whole year older", "a surprise I never saw coming", "“Surprise!”", "“Make a wish, quick, before the candles melt!”", "“What did you wish for?”", "“I can’t tell you, or it won’t come true.”", "“Happy birthday to you…”", "“Open mine first!”", "“This is the best birthday ever.”"],
        ex: "“What did you wish for?” Mei Ling whispered. I grinned. “I can’t tell you, or it won’t come true.”" }
    ] },

    { type: "chips", title: "National Day", groups: [
      { title: "Before the parade", words: ["flags hung from almost every HDB window", "red and white everywhere I looked", "I wore my red T-shirt and white shorts", "practised the National Day songs in the school hall", "the fun pack was crammed with goodies", "a clapper, a flag, a torch and snacks", "the stands filled up hours before the start", "the air buzzed with excitement", "strangers smiled at one another", "the evening sky turned pink over Marina Bay"],
        ex: "Flags hung from almost every HDB window, and red and white was everywhere I looked." },
      { title: "The parade", words: ["fighter jets roared overhead in perfect formation", "the helicopter flew past carrying the huge flag", "the whole crowd looked up at the same time", "soldiers marched in step, boots striking together", "the tanks and trucks of the mobile column rumbled past", "the parachutists drifted down, trailing smoke", "the President arrived and everyone stood", "dancers in bright costumes filled the floor", "the screens showed the crowd waving", "we waved our flags until our arms ached", "a Mexican wave rolled round the stadium"],
        ex: "The helicopter flew past carrying the huge flag, and the whole crowd looked up at the same time." },
      { title: "The anthem and the pledge", words: ["the music began and everyone rose to their feet", "we sang “Majulah Singapura” together", "thousands of voices filled the bay", "stood still and tall for the national anthem", "placed my right fist over my heart for the pledge", "“…one united people, regardless of race, language or religion…”", "Grandpa’s voice wobbled as he sang", "a lump in my throat I did not expect", "I felt proud to be part of something so big", "goosebumps rose on my arms"],
        ex: "Thousands of voices sang “Majulah Singapura” together, and Grandpa’s voice wobbled as he sang.",
        note: "We stand still for the national anthem and place the right fist over the heart for the pledge." },
      { title: "Fireworks", words: ["the first firework whistled into the sky", "a golden flower burst open over the water", "sparks rained down like glitter", "the boom thudded in my chest", "red and white stars filled the sky", "every burst lit up the faces around me", "the smell of smoke drifted over the bay", "the reflections danced on the water", "everyone said “Wahhh!” at the same time", "the last firework was the biggest of all", "the sky went dark and the crowd roared"],
        ex: "A golden flower burst open over the water, and the boom thudded in my chest." },
      { title: "Things people say on National Day", words: ["“Happy Birthday, Singapore!”", "“Look, the flag! Up there!”", "“Here come the jets!”", "“Did you get the fun pack?”", "“I can feel the boom in my chest!”", "“Grandpa, were you at the first parade?”", "“Let’s sing louder!”", "“Best National Day ever.”"],
        ex: "“Here come the jets!” Wei Ming shouted, pointing as they roared overhead." }
    ] },

    { type: "chips", title: "Celebrations at school", groups: [
      { title: "Children’s Day", words: ["no lessons, just fun, for the whole morning", "our teachers put on a show just for us", "Mr Tan danced in a sparkly costume", "the hall shook with laughter", "teachers sang a song they had practised in secret", "a game of charades between teachers", "each of us got a small gift and a packet of sweets", "a class party with snacks from home", "pizza boxes stacked on the teacher’s table", "we went home early with big smiles", "it was the one day the teachers worked hard to make us laugh"],
        ex: "Our teachers put on a show just for us, and the hall shook with laughter when Mr Tan danced in a sparkly costume." },
      { title: "Teachers’ Day", words: ["made a card with glitter that got everywhere", "wrote a thank-you note in my neatest handwriting", "rehearsed the song every recess for a week", "the class sang to our form teacher", "Mrs Lim pressed a hand to her chest", "her eyes went shiny and she smiled", "we gave her a bunch of sunflowers", "the cards piled up on her desk", "the student leaders gave a speech on stage", "my hand shook as I handed over my card", "I wanted her to know she made a difference"],
        ex: "When we finished singing, Mrs Lim pressed a hand to her chest, and her eyes went shiny as she smiled." },
      { title: "Things people say at school celebrations", words: ["“Happy Teachers’ Day, Mrs Lim!”", "“Thank you for always being patient with us.”", "“We made this for you.”", "“Oh, you shouldn’t have! It’s beautiful.”", "“Happy Children’s Day, everyone!”", "“Is that really Mr Tan?”", "“Can we do this every day?”", "“I’ll keep this card forever.”"],
        ex: "“I’ll keep this card forever,” Mrs Lim said softly, holding it to her chest." }
    ] },

    { type: "chips", title: "Festivals all around you", groups: [
      { title: "Sounds and smells in the estate", words: ["the pop and crackle of sparklers at the void deck", "a kompang drum group beating outside a flat", "Tamil songs drifting from an open door", "carols playing softly from a neighbour’s radio", "laughter spilling out of a full flat", "the clink of cups as guests arrived", "slippers and shoes piled outside every door", "the sweet smell of kuih baking in a neighbour’s oven", "spices frying in hot oil down the corridor", "the smoky scent of joss sticks from a nearby temple", "the lift was crowded with visitors carrying gifts", "every corridor smelt like a different kitchen"],
        ex: "During the festive season, every corridor smelt like a different kitchen, and slippers and shoes piled up outside every door." },
      { title: "Lights and decorations", words: ["fairy lights blinking around the window grille", "lanterns swaying in the evening breeze", "a lit-up arch over the street", "the shop fronts glowed red and gold", "streets turned into rivers of light", "paper lanterns casting soft circles on the floor", "tiny lamps lined up like soldiers on the ledge", "the neighbourhood looked like a picture book", "the lights reflected in the puddles after the rain", "the night was never really dark", "colours I had never seen together, all at once", "a glow that made the whole block look friendly"],
        ex: "After the rain, the festive lights reflected in the puddles, and the night was never really dark." },
      { title: "Helping out", words: ["rolled the pastry for the tarts with Grandma", "pressed the dough flat with my thumb", "carried trays of drinks very slowly", "set out the plates and the cutlery", "folded serviettes into neat triangles", "washed a mountain of cups after the guests left", "handed out sweets to the younger cousins", "welcomed guests at the door with a smile", "helped Mum wrap the gifts", "felt grown-up because they trusted me", "my hands were sticky but my heart was proud", "Grandma said I was her best helper"],
        ex: "I carried the trays of drinks very slowly, and Grandma said I was her best helper." },
      { title: "Being a guest at a friend’s festival", words: ["took off my shoes and left them neatly by the door", "greeted my friend’s parents politely", "brought a small gift for the family", "asked my friend what each dish was called", "tried a little of everything", "listened carefully when they explained the custom", "copied my friend so I would do it the right way", "said thank you before I left", "felt welcomed like one of the family", "learnt something new about my friend’s culture", "realised we celebrate in different ways but feel the same joy", "invited my friend to my own festival in return"],
        ex: "I asked Aisha what each dish was called, and I realised we celebrate in different ways but feel the same joy." }
    ] },

    { type: "chips", title: "Any festival: feelings and endings", groups: [
      { title: "Festive feelings, quiet to bright", words: ["a warm, cosy glow", "content and full", "cheerful", "bubbling with excitement", "bursting with joy", "proud of my family’s traditions", "curious about my friend’s festival", "grateful to be invited", "a little shy at first", "sleepy but happy", "a pang of sadness when it ended", "already counting down to next year"],
        ex: "Sleepy but happy, I curled up in the car with a bag of kuih on my lap.",
        note: "Choose a feeling that fits the moment. A small, honest feeling is often better than a huge one." },
      { title: "Ending a festival story", words: ["the last lantern flickered out", "the plates were empty and our tummies were full", "the house was quiet again, but it still felt warm", "I fell asleep with my red packets under my pillow", "the fireworks were over, but the smiles stayed", "I learnt that a festival is really about the people", "I hope I can celebrate with them again next year", "it was not the food or the gifts I remembered most", "for the first time, I understood why it mattered to Grandma", "I went to bed with a happy, full heart"],
        ex: "It was not the food or the gifts I remembered most. It was the whole family laughing round one table." }
    ] },

    { type: "mcq", title: "Quick check", intro: "Choose the best answer.", items: [
      { q: "Which line shows good manners when receiving a red packet?", o: ["I grabbed it and ripped it open.", "I received it with both hands and said thank you.", "I asked how much was inside."], a: 1, e: "Receiving with both hands and thanking the giver is polite." },
      { q: "What do people say to each other on Hari Raya Puasa to ask forgiveness?", o: ["“Gong xi fa cai”", "“Happy Deepavali”", "“Maaf zahir dan batin”"], a: 2, e: "It means “forgive me, in body and in heart”." },
      { q: "A kolam is…", o: ["a pattern drawn at the doorstep with rice flour", "a kind of mooncake", "a lantern shaped like a fish"], a: 0, e: "A kolam welcomes guests at Deepavali and other special days." },
      { q: "Which sentence about the lion dance is the most vivid?", o: ["The lion dance was nice.", "There was a lion dance at the shop.", "The lion blinked its furry eyes and snapped up the lettuce."], a: 2, e: "It shows exactly what the lion did." },
      { q: "What do we do during the national anthem?", o: ["Stand still and tall", "Wave and cheer", "Sit down quietly"], a: 0, e: "We stand still as a sign of respect." },
      { q: "Which reaction suits a small birthday mishap, like a candle that keeps relighting?", o: ["My heart exploded.", "We all burst out laughing.", "I screamed in terror."], a: 1, e: "Keep reactions believable for small events." },
      { q: "Which line best describes a Mid-Autumn lantern walk?", o: ["A long line of lanterns wove round the estate.", "The lanterns were very lantern-like.", "We walked and walked and walked."], a: 0, e: "It paints a clear picture." },
      { q: "When you write about a friend’s festival, the best approach is to…", o: ["say it is strange", "show what you saw, tasted and learnt as a thankful guest", "only write about the food"], a: 1, e: "Curious, grateful writing is respectful and interesting." }
    ] }
  ] },

{ id: "en-travel", group: "Word banks", order: 97, cat: "topics", title: "Travel and trips",
  intro: "Going somewhere new is full of story moments: the night before, the airport, the flight, the first step into cold air, strange food, a moment of being lost and the joy of coming home. Borrow lines from each stage of your trip.",
  blocks: [
    { type: "text", title: "How to use this bank", html: "This bank follows a trip from start to finish: <b>packing</b>, <b>the airport</b>, <b>the flight</b>, <b>arriving</b>, <b>exploring</b>, <b>small problems</b> and <b>coming home</b>. Simple travel words (passport, boarding gate, suitcase) are in the <i>Topic vocabulary</i> bank. Here you will find phrases and whole sentences to make your trip feel real." },
    { type: "tip", html: "<b>Tip:</b> A trip story is not a list of places (<i>First we went to…, then we went to…</i>). Choose <b>one or two moments</b> and slow them down with your senses. The first breath of cold air or one bowl of noodles can be the heart of your story." },

    { type: "chips", title: "Before you go", groups: [
      { title: "Planning and counting down", words: ["circled the date on the calendar in red", "crossed off each day with a big X", "looked up photos of the place every night", "Dad printed out our plan for each day", "Mum checked the weather forecast for the tenth time", "learnt how to say “thank you” in Japanese", "borrowed a thick winter jacket from my cousin", "packed and unpacked my bag three times", "could not stop talking about it at school", "the days crawled by like a snail", "only one more sleep!"],
        ex: "I crossed off each day on the calendar with a big X until there was only one more sleep." },
      { title: "Packing", words: ["laid everything out on the bed first", "rolled my T-shirts so they would fit", "sat on the suitcase so Dad could zip it shut", "the zip groaned but held", "squeezed in one more storybook", "Mum made me take out three soft toys", "thick socks, gloves and a woolly hat", "a little bag for my toothbrush and toothpaste", "my passport safe in Dad’s travel pouch", "a name tag on every bag", "the suitcase was so heavy it would not stand up", "checked and double-checked the list"],
        ex: "The zip groaned as I sat on the suitcase, but it held, and Dad finally pulled it shut." },
      { title: "The night before", words: ["lay in bed with my eyes wide open", "my suitcase stood by the door like a guard", "too excited to sleep", "my stomach fizzed like a soft drink", "listened to the clock ticking", "pictured the snow I had only seen on TV", "Mum told me to sleep or I’d be grumpy", "fell asleep at last, still smiling", "the alarm rang in the dark", "stumbled out of bed half asleep", "a quick breakfast eaten standing up", "Dad counted the bags one last time: “One, two, three, four.”"],
        ex: "My suitcase stood by the door like a guard, and I lay in bed with my eyes wide open." }
    ] },

    { type: "chips", title: "Changi Airport", groups: [
      { title: "Arriving and checking in", words: ["the taxi pulled up at the departure hall", "glass doors slid open to cool, bright air", "the big board flicked through cities from all over the world", "found our flight on the board", "trolleys rattling across the shiny floor", "joined the queue at the check-in counter", "our bags were weighed and tagged", "my suitcase disappeared along the moving belt", "the lady at the counter handed us our boarding passes", "“Have a good trip!”", "Grandma came to see us off", "waved goodbye until we turned the corner"],
        ex: "The big board flicked through cities from all over the world, and my heart jumped when I found our flight." },
      { title: "Inside the airport", words: ["the waterfall at Jewel roared down from the glass roof", "a mist drifted up from the waterfall onto my face", "a forest of plants growing indoors", "the travelator carried us along like a conveyor belt", "the gentle chime before every announcement", "a voice announced a flight to London", "travellers from every country hurrying past", "people asleep on the benches with their bags as pillows", "a carpet so soft my footsteps vanished", "the smell of coffee and perfume from the shops", "planes lined up outside the huge windows", "one plane after another rose into the sky"],
        ex: "The waterfall at Jewel roared down from the glass roof, and a cool mist drifted onto my face." },
      { title: "Immigration and the gate", words: ["held my passport open at the photo page", "looked into the camera and the gate slid open", "placed my thumb on the scanner", "put my bag in a grey tray for the X-ray", "walked through the security arch", "the gate area filled with travellers", "pressed my nose against the window to see our plane", "the plane looked enormous up close", "“We are now boarding…”", "walked down the long tunnel to the plane", "the flight attendant smiled and said “Welcome aboard”"],
        ex: "I pressed my nose against the window, and our plane looked enormous up close." }
    ] },

    { type: "chips", title: "On the plane", groups: [
      { title: "Getting settled", words: ["found our row and slid into my seat", "Dad lifted the bags into the overhead locker", "clicked my seat belt shut", "the seat belt felt tight across my lap", "a tiny pillow and a thin blanket", "a screen on the back of every seat", "pressed every button on the armrest", "watched the safety video carefully", "the flight attendant showed us how to wear the life jacket", "found the nearest exit, just in case", "the engines began to hum"],
        ex: "I clicked my seat belt shut, and soon the engines began to hum beneath my feet." },
      { title: "Take-off", words: ["the plane rolled slowly towards the runway", "it paused, as if taking a deep breath", "the engines roared louder and louder", "I was pressed back into my seat", "the buildings blurred past the window", "the wheels left the ground with a bump", "my tummy dropped, like on a lift", "my ears popped, so I swallowed hard", "chewing a sweet helped my ears", "Singapore grew smaller and smaller below us", "the ships in the sea looked like toys", "we climbed through the clouds into bright sunshine"],
        ex: "The engines roared louder and louder, and I was pressed back into my seat as the buildings blurred past." },
      { title: "The view from the window", words: ["clouds like a field of cotton wool", "the sky above the clouds was a deep, clear blue", "the wing glinted in the sun", "tiny roads like grey threads", "fields stitched together like a quilt", "a river curling like a silver ribbon", "snow-capped mountains poking through the clouds", "the sea sparkled like broken glass", "the sunset turned the clouds pink and gold", "at night, cities below glowed like spilt jewels", "nothing but darkness and a blinking light on the wing"],
        ex: "Below us, I saw fields stitched together like a quilt, and a river curled through them like a silver ribbon." },
      { title: "Bumps in the air", words: ["the seat belt sign pinged on", "the plane gave a little shake", "my cup of water wobbled on the tray", "the plane dipped and my tummy dipped with it", "I gripped the armrest", "Mum squeezed my hand and smiled", "“It’s just a bit of bumpy air, like a car on a rough road.”", "the captain calmly asked everyone to stay seated", "the flight attendants buckled up too", "I breathed slowly and counted to ten", "after a few minutes, the air was smooth again", "the sign pinged off and I let out my breath"],
        ex: "The plane gave a little shake and I gripped the armrest, but Mum squeezed my hand. “It’s just a bit of bumpy air,” she said.",
        note: "Turbulence is normal. Show the character staying calm, being comforted or comforting someone else." },
      { title: "The long flight", words: ["the trolley rattled down the aisle", "“Chicken or fish?”", "peeled back the foil lid and steam rose out", "everything came in tiny boxes and packets", "watched two films back to back", "the cabin lights dimmed", "people slept with their mouths open", "a baby cried a few rows behind", "the hum of the engines made me drowsy", "my legs felt stiff, so I walked to the back", "the map on the screen showed our little plane creeping forward", "woke up with a crick in my neck"],
        ex: "The cabin lights dimmed, and the hum of the engines slowly made me drowsy." },
      { title: "Landing", words: ["the captain announced we would land soon", "put my seat upright and folded my table", "the ground rose up to meet us", "the wheels touched down with a thump", "the engines roared as the plane slowed down", "some passengers clapped", "everyone stood up at once to reach for their bags", "a cold draught at the door of the plane", "walked out into a country I had never seen before", "the signs were in a language I could not read"],
        ex: "The wheels touched down with a thump, and I grinned at Dad. We had arrived." }
    ] },

    { type: "chips", title: "Arriving somewhere new", groups: [
      { title: "Cold air", words: ["the cold slapped my cheeks the moment we stepped out", "my breath came out in little white clouds", "the air smelt clean and sharp", "my fingers went numb, even in my gloves", "my nose turned red and runny", "I zipped my jacket right up to my chin", "my teeth chattered", "stamped my feet to keep warm", "wrapped my hands round a hot drink", "the heater in the car felt like a hug", "I had never felt cold like this in Singapore"],
        ex: "The cold slapped my cheeks the moment we stepped out, and my breath came out in little white clouds." },
      { title: "Snow", words: ["tiny white flakes drifted down", "snowflakes landed on my sleeve, each one different", "caught a snowflake on my tongue", "everything was covered in a thick white blanket", "the snow squeaked and crunched under my boots", "my boots sank up to my ankles", "the trees wore white coats", "made my first snowman, a little lopsided", "a snowball burst on my back", "lay down and made a snow angel", "the cold soaked through my gloves", "the world was so quiet, as if the snow had swallowed every sound"],
        ex: "The snow crunched under my boots, and the world was so quiet it felt as if the snow had swallowed every sound." },
      { title: "Autumn leaves", words: ["trees blazing red, orange and gold", "leaves twirled down like little paper boats", "a carpet of leaves along the path", "kicked through piles of crunchy leaves", "a maple leaf shaped like an open hand", "the leaves crackled like crisps underfoot", "the air smelt of earth and wood smoke", "a cool breeze and a pale, gentle sun", "pressed a red leaf inside my diary"],
        ex: "Leaves twirled down like little paper boats, and they crackled like crisps under my feet." },
      { title: "A big train station", words: ["a station so big it had its own shopping streets", "a roof of glass and iron arches high above", "crowds flowing in every direction", "announcements in a language I did not understand", "the departure board clicked and changed", "a bullet train glided in without a sound", "its long, pointed nose looked like a bird’s beak", "the train left exactly on time, to the second", "the countryside rushed past the window", "a lady pushed a snack trolley down the carriage", "held Mum’s hand tightly in the crowd"],
        ex: "A bullet train glided into the station without a sound, its long, pointed nose like a bird’s beak." },
      { title: "A busy city", words: ["skyscrapers so tall I had to tip my head back", "giant screens flashing on every building", "a huge crossing where hundreds of people walked at once", "red double-decker buses rumbling past", "black taxis honking at the corner", "a busker played the violin in the square", "pigeons fluttered up from the cobblestones", "old stone buildings next to shiny glass towers", "the smell of hot pretzels and roasting nuts", "everyone walked so fast", "the city lights came on one by one"],
        ex: "At the huge crossing, hundreds of people walked at once, and somehow nobody bumped into anyone." },
      { title: "Mountains and countryside", words: ["mountains rose up like giant sleeping animals", "a snowy peak glittered in the sun", "the road wound up the mountain like a ribbon", "my ears popped as we drove higher", "mist curled around the pine trees", "a waterfall tumbled down the rocks", "a lake as still as a mirror", "the air was so fresh it felt cold in my chest", "rolling green hills dotted with sheep", "cows stared at us over the fence", "the only sound was the wind and a bird calling"],
        ex: "A lake lay as still as a mirror, and the snowy mountains were reflected in it upside down." },
      { title: "Onsen and hot springs", words: ["steam rose from the hot spring into the cold air", "the smell of the water was a little like eggs", "we washed carefully before getting in, like everyone else", "lowered myself in, one toe at a time", "the hot water made my skin tingle", "snowflakes melted as they touched the water", "my cheeks went pink and my body felt floppy", "a tiny towel folded on Dad’s head", "slipped into a soft cotton robe afterwards", "sipped cold milk from a glass bottle"],
        ex: "Steam rose from the hot spring into the cold air, and snowflakes melted the moment they touched the water.",
        note: "At a Japanese onsen, people wash before getting in and keep towels out of the water." },
      { title: "Farms and markets", words: ["picked strawberries straight from the plant", "the strawberries were warm from the sun", "fed a lamb from a bottle", "its tongue tickled my palm", "the smell of hay and animals", "a farmer waved from his tractor", "a market stall piled high with red apples", "the fish market smelt of salt and sea", "a stall-owner let me try a slice of fruit", "stalls selling hot chestnuts in paper cones", "a night market lit with strings of bulbs", "shouted prices and sizzling woks"],
        ex: "We picked strawberries straight from the plant, and they were still warm from the sun." }
    ] },

    { type: "chips", title: "Trying new food", groups: [
      { title: "Food around the world", words: ["a steaming bowl of ramen with a soft-boiled egg", "slurped the noodles, just like the man next to us", "sushi going round on a little conveyor belt", "fish and chips wrapped in paper on a windy pier", "a crispy croissant that flaked all over my jacket", "a hot meat pie at a footy match", "soup dumplings that burst with hot broth", "a bubbling hotpot so spicy my lips tingled", "roast duck with crackling skin", "hot chocolate thick enough to stand a spoon in", "satay smoking on a roadside grill in Malaysia", "a bowl of laksa that tasted a bit like home"],
        ex: "I slurped the ramen noodles, just like the man next to us, and the warm broth chased away the cold." },
      { title: "Trying something brave", words: ["stared at the plate for a long time", "took the tiniest bite", "it was slimy, but not in a bad way", "squeezed my eyes shut and swallowed", "it tasted much better than it looked", "my face went red from the spice", "gulped down a whole glass of water", "Dad laughed and finished it for me", "I was secretly proud I had tried it", "it became my favourite food of the trip"],
        ex: "I squeezed my eyes shut and took the tiniest bite. To my surprise, it tasted much better than it looked." }
    ] },

    { type: "chips", title: "Exploring", groups: [
      { title: "Where we stayed", words: ["the hotel key card did not work the first time", "a room on the twentieth floor with a view of the city", "bounced on the bed before Mum could stop me", "a little kettle and packets of green tea on the table", "slippers and a fluffy robe in the cupboard", "a big breakfast buffet with food from everywhere", "a cosy cabin with a wood fire", "the wooden floor creaked as we walked", "slept on a futon on a straw mat floor", "a farmhouse with chickens in the yard", "my brother and I shared a bunk bed", "fell asleep to the sound of rain on the roof"],
        ex: "We slept on futons on the straw mat floor, and I fell asleep to the sound of rain on the roof." },
      { title: "Getting around", words: ["rode a cable car high above the valley", "the cable car swayed gently in the wind", "a ferry ride with the spray on my face", "a tram that clanged its bell", "an open-top bus with the wind in my hair", "the subway map looked like a plate of spaghetti", "tapped a travel card at the gate, like at home", "the train curved along the coast", "walked so much that my feet ached", "a long road trip with snacks in the back seat", "Dad drove on narrow, winding roads", "we stopped at every lookout point for photos"],
        ex: "The cable car swayed gently in the wind as we floated high above the valley." },
      { title: "Sightseeing", words: ["a castle with thick stone walls and narrow windows", "climbed a spiral staircase to the top of a tower", "a quiet temple garden with raked gravel", "a museum full of dinosaur bones", "a cathedral so tall my voice echoed", "a bridge lit up with golden lights", "a palace with guards in tall, furry hats", "a garden of tulips in every colour", "a giant Ferris wheel by the river", "a famous tower that looked smaller than I expected", "a street of old wooden houses", "queued for an hour but it was worth it"],
        ex: "We climbed a spiral staircase to the top of the castle tower, and the whole town spread out below us." },
      { title: "Weather abroad", words: ["a fine, cold drizzle that never stopped", "the wind turned my umbrella inside out", "the sun set before five in the afternoon", "the sky stayed light until nine at night", "a clear, crisp morning with frost on the grass", "frost sparkled like sugar on the car windows", "a thick fog hid the top of the mountain", "a dry heat that made my lips crack", "the weather changed four times in one day", "I needed a jacket in the morning and a T-shirt by noon"],
        ex: "Frost sparkled like sugar on the car windows on a clear, crisp morning." }
    ] },

    { type: "chips", title: "Around the world", groups: [
      { title: "Japan", words: ["bowed and said “arigato” to everyone", "a vending machine on almost every corner", "the streets were so clean I could not find a single piece of litter", "cherry blossoms drifting like pink snow", "a red gate glowing at the entrance to a shrine", "a tiny restaurant with only eight seats", "trains so quiet you could hear a whisper", "a bento box with every food in its own neat space", "deer that bowed back when I bowed to them", "Mount Fuji appeared above the clouds like a painting"],
        ex: "Mount Fuji appeared above the clouds like a painting, and the whole train went quiet." },
      { title: "The United Kingdom", words: ["red postboxes and red phone boxes", "the clock tower struck the hour", "rain one minute, sunshine the next", "a cosy café with scones, jam and cream", "a castle on a hill above a grey stone town", "squirrels darting across the park", "a boat ride along the River Thames", "everyone said “Cheers!” instead of “Thank you!”", "the Tube rattled through dark tunnels", "a puffy jacket over my school jumper"],
        ex: "A boat carried us along the River Thames as the clock tower struck the hour." },
      { title: "China", words: ["climbed the Great Wall until my legs wobbled", "the wall snaked over the hills as far as I could see", "a giant panda munching bamboo", "red lanterns along an ancient street", "steamed buns as big as my fist", "a busy morning park full of people doing tai chi", "Grandpa read the signs and translated for us", "a high-speed train zooming past fields", "relatives we had only met on video calls", "Grandma’s hometown, where she grew up"],
        ex: "The Great Wall snaked over the hills as far as I could see, and my legs wobbled by the time we reached the top." },
      { title: "Malaysia", words: ["drove across the Causeway early in the morning", "the queue of cars at the checkpoint", "cool, misty air in the Cameron Highlands", "tea plantations like green stripes on the hills", "a durian stall by the roadside", "a beach with water as clear as glass", "a night market with fresh coconut juice", "the food tasted familiar but a little different", "fireflies blinking along the river at night", "felt close to home but still on holiday"],
        ex: "In the Cameron Highlands, the tea plantations ran like green stripes over the hills." },
      { title: "Australia", words: ["a kangaroo bounded across the field", "held a koala that smelt of eucalyptus", "a wide, empty beach with roaring waves", "seagulls trying to steal our chips", "the sky looked bigger than anywhere else", "slathered on sunscreen even when it was cool", "a farm stay where I collected eggs", "the Opera House roof looked like white sails", "a long drive past red earth and tall gum trees", "“G’day!” said the friendly ranger"],
        ex: "A kangaroo bounded across the field, and I held my breath so I would not scare it away." },
      { title: "Europe", words: ["cobbled streets that made my suitcase bounce", "a square with a fountain and fluttering pigeons", "colourful houses lined up along a canal", "people cycling everywhere, even in the cold", "a Christmas market with wooden huts and twinkling lights", "the smell of warm waffles and cinnamon", "church bells ringing across the rooftops", "a snowy mountain village with wooden chalets", "every country we crossed had a different language", "an old town that looked like a fairy tale"],
        ex: "The cobbled streets made my suitcase bounce, and church bells rang across the rooftops of the old town." }
    ] },

    { type: "chips", title: "When things go a little wrong", groups: [
      { title: "A language barrier", words: ["the waiter spoke quickly and I did not understand a word", "Mum pointed at a picture on the menu", "Dad typed into a translation app and held up his phone", "we both laughed when the app got it wrong", "used our hands to explain", "a kind shopkeeper drew us a map on a napkin", "nodded and smiled, hoping that was right", "said “arigato” and bowed, the one word I knew", "the lady’s face lit up when I said thank you in her language", "a smile works in every language"],
        ex: "Dad typed into a translation app and held up his phone, and the shopkeeper nodded and drew us a map on a napkin." },
      { title: "Separated, then found", words: ["I turned round and Mum was gone", "a sea of strangers’ coats around me", "my heart thudded and my mouth went dry", "I wanted to run, but I made myself stand still", "remembered what Dad said: “Stay where you are.”", "went up to a staff member in a uniform", "showed the card with Mum’s phone number", "the staff member spoke kindly and made an announcement", "a few minutes felt like an hour", "then I heard my name", "Mum pushed through the crowd and hugged me tight", "she was shaking, and so was I", "after that, I never let go of her hand in a crowd"],
        ex: "I wanted to run, but I made myself stand still, just like Dad had said. Then I heard my name, and Mum pushed through the crowd towards me.",
        note: "Show the sensible things the character does: stay still, find a staff member, show a phone number. That makes the ending believable." },
      { title: "Small mishaps", words: ["we got on the train going the wrong way", "my glove fell onto the train tracks", "the rain caught us without an umbrella", "our bag was the last one off the luggage belt", "Dad got the map upside down", "we walked in circles for half an hour", "the shop was closed for the holiday", "it turned into a funny story later"],
        ex: "Dad held the map upside down and we walked in circles for half an hour, but it turned into a funny story later." }
    ] },

    { type: "chips", title: "Souvenirs and memories", groups: [
      { title: "Choosing souvenirs", words: ["a snow globe that swirled when I shook it", "a keychain for every classmate", "a box of biscuits for my teacher", "a postcard I wrote and mailed to myself", "a little wooden doll painted by hand", "a fridge magnet for Grandma’s collection", "a pebble from the beach in my pocket", "a ticket stub stuck in my scrapbook", "took a hundred photos and kept twenty", "spent my pocket money carefully", "chose a gift for my brother who stayed home"],
        ex: "I chose a snow globe for Grandma, and every time she shakes it, she will think of the trip." }
    ] },

    { type: "chips", title: "Feelings on a trip", groups: [
      { title: "Excitement and wonder", words: ["my eyes went wide", "I forgot to blink", "I could hardly believe I was really there", "it looked exactly like the photos, only better", "I wanted to remember it forever", "my face hurt from smiling", "I gasped out loud", "I felt very small and the world felt very big"],
        ex: "I stood at the top of the mountain and felt very small, and the world felt very big." },
      { title: "Homesickness", words: ["I suddenly missed my own bed", "I wished I could hug my dog", "the hotel pillow did not smell like home", "I thought about my friends at recess without me", "I missed Grandma’s cooking", "a video call home made me feel better", "seeing a familiar logo on a shop made me smile", "I would not swap the trip, but I missed home a little"],
        ex: "That night, the hotel pillow did not smell like home, and I suddenly wished I could hug my dog." },
      { title: "Jet lag", words: ["wide awake at three in the morning", "the sky was still dark but my body said it was lunchtime", "yawned through breakfast", "fell asleep in the middle of dinner", "my head kept nodding on the bus", "my tummy rumbled at strange times", "it took my body a few days to catch up", "Mum said the sunshine would help us adjust"],
        ex: "I was wide awake at three in the morning because my body still thought it was lunchtime." },
      { title: "Things people say on a trip", words: ["“Have you got the passports?”", "“Stay close to me, okay?”", "“Look out of the window, quick!”", "“Is this snow? Real snow?”", "“How do you say ‘thank you’ here?”", "“I’m so cold I can’t feel my nose!”", "“Just try one bite.”", "“If we get separated, wait right here.”", "“Can we come back next year?”", "“I miss home a little bit.”", "“What time is it in Singapore now?”", "“Smile! One more photo!”"],
        ex: "“Is this snow? Real snow?” my little sister squealed, holding out her mittens." }
    ] },

    { type: "chips", title: "Coming home", groups: [
      { title: "The journey back", words: ["the last morning came too quickly", "packed slowly, as if that would make the trip longer", "the suitcase was heavier with souvenirs", "took one last look out of the hotel window", "slept for most of the flight home", "the warm, damp air hugged me as soon as I stepped out", "the familiar smell of rain and orchids at Changi", "the taxi uncle asked, “Holiday ah? Where you go?”", "the HDB blocks never looked so welcoming", "our flat was exactly as we had left it", "flopped onto my own bed with a happy sigh", "ate a plate of chicken rice and felt truly home"],
        ex: "The warm, damp air hugged me as soon as I stepped out, and I knew we were home." },
      { title: "Ending a trip story", words: ["the photos are on my phone, but the memories are in my heart", "I learnt that the world is much bigger than my neighbourhood", "I came home with a full suitcase and a fuller heart", "travelling taught me to be brave and to try new things", "the best part was not the place but being together", "I still keep that red leaf in my diary", "I am already dreaming about our next trip", "it was good to go away, and it was even better to come home"],
        ex: "It was good to go away, and it was even better to come home." }
    ] },

    { type: "mcq", title: "Quick check", intro: "Choose the best answer.", items: [
      { q: "Which line best describes snow with the senses?", o: ["There was a lot of snow.", "The snow crunched under my boots.", "Snow is white and cold, which is nice."], a: 1, e: "It uses sound to make the snow feel real." },
      { q: "During turbulence, which reaction is calm and believable?", o: ["I gripped the armrest until the air was smooth again.", "I screamed that we were all doomed.", "I jumped out of my seat."], a: 0, e: "A small, calm reaction fits normal bumpy air." },
      { q: "If you get separated from your family in a crowd, the sensible thing to do is…", o: ["run around looking everywhere", "leave with a stranger", "stay where you are and find a staff member"], a: 2, e: "Staying put and asking a staff member helps your family find you." },
      { q: "Which is the best way to start a trip story?", o: ["First we went to the airport. Then we went to the hotel.", "The cold slapped my cheeks the moment we stepped out of the airport.", "This is a story about my trip."], a: 1, e: "It drops the reader straight into a vivid moment." },
      { q: "What does “jet lag” mean?", o: ["being sick on a plane", "a delayed flight", "feeling tired at the wrong times after flying to a new time zone"], a: 2, e: "Your body clock needs time to catch up." },
      { q: "Which simile best describes fields seen from a plane?", o: ["like a quilt stitched together", "like a hawker centre at lunchtime", "like a ticking clock"], a: 0, e: "Fields from above look like patches of a quilt." },
      { q: "Which ending sounds the most thoughtful?", o: ["Then we went home. The end.", "I came home with a full suitcase and a fuller heart.", "It was very very fun."], a: 1, e: "It reflects on what the trip meant." },
      { q: "At a Japanese onsen, people usually…", o: ["jump in straight away", "wash before getting into the water", "swim laps"], a: 1, e: "Washing first keeps the shared water clean." }
    ] }
  ] }

] });
