window.CONTENT_PARTS = window.CONTENT_PARTS || [];
window.CONTENT_PARTS.push({ lang: "en", units: [], extends: [

{ id: "en-adjectives", blocks: [
  { type: "chips", title: "More describing words: places, things and people", groups: [
    { title: "Weather and air", words: ["muggy","humid","balmy","sweltering","overcast","drizzly","blustery","breezy","stormy","hazy","misty","crisp","stuffy"],
      ex: "It was a muggy afternoon, and the overcast sky pressed down on the estate like a heavy lid.",
      note: "Muggy and humid mean warm and damp. Crisp means cool and fresh, like an early morning." },
    { title: "Old, worn or brand-new", words: ["battered","rusty","faded","tattered","threadbare","chipped","dented","worn-out","dusty","cracked","moth-eaten","mouldy","brand-new","pristine"],
      ex: "Grandpa still carried his battered old briefcase, its leather faded and its corners scuffed.",
      note: "These words tell the reader the history of an object without a long explanation." },
    { title: "The mood of a place", words: ["cosy","cramped","spacious","deserted","bustling","chaotic","tranquil","eerie","dreary","cluttered","airy","welcoming"],
      ex: "The library was tranquil and airy, a welcome change from our cramped, chaotic classroom." },
    { title: "Strong or easily broken", words: ["flimsy","sturdy","fragile","delicate","rigid","wobbly","feather-light","weighty","solid","brittle","durable"],
      ex: "The flimsy umbrella turned inside out, but Dad’s sturdy one did not even bend." },
    { title: "Patterns and markings", words: ["striped","spotted","checked","speckled","dotted","streaked","mottled","floral","patterned","plain","polka-dot","tie-dyed"],
      ex: "A speckled brown egg lay in the nest, next to a mottled feather." },
    { title: "Wet and dry", words: ["soggy","sodden","drenched","waterlogged","moist","dewy","parched","bone-dry","dripping","muddy","slippery","soaking"],
      ex: "By the time we reached the shelter, our shoes were soggy and our socks were soaking.",
      note: "Drenched and sodden are stronger than wet. Parched and bone-dry are stronger than dry." },
    { title: "Food you can see and bite", words: ["crunchy","chewy","gooey","flaky","tender","mushy","charred","glistening","steaming","sizzling","doughy","syrupy"],
      ex: "The curry puff was flaky on the outside and steaming hot inside." },
    { title: "How people and animals look and move", words: ["nimble","clumsy","graceful","agile","lanky","plump","scrawny","muscular","wiry","hunched","sprightly","frail","stooped"],
      ex: "Great-grandpa looks frail, but he is still sprightly enough to walk to the market every morning.",
      note: "Choose kind words for people: plump or stocky sounds friendlier than fat." },
    { title: "Warm and cool on the skin", words: ["lukewarm","tepid","frosty","clammy","feverish","toasty","chilly","nippy","sweaty","sun-baked","refreshing"],
      ex: "My hands were clammy, and the lukewarm water in my bottle did nothing to cool me down." }
  ]}
]},

{ id: "en-wordswap", blocks: [
  { type: "table", title: "Forty more overused words and stronger choices", head: ["Instead of","Try"], weakCol: 0, rows: [
    ["thing","object, item, gadget, belonging, creature (choose the exact name if you can)"],
    ["stuff","belongings, things, items, equipment, clutter"],
    ["like","enjoy, be fond of, be keen on, be into, have a soft spot for"],
    ["love","adore, cherish, treasure, be crazy about"],
    ["hate","dislike, detest, loathe, cannot stand, dread"],
    ["think","believe, suppose, wonder, reckon, imagine, consider"],
    ["know","realise, understand, be sure, recognise, be aware"],
    ["saw","spotted, noticed, caught sight of, glimpsed, witnessed"],
    ["heard","overheard, caught the sound of, made out, detected"],
    ["came","arrived, appeared, turned up, approached, showed up"],
    ["gave","handed, passed, offered, presented, donated"],
    ["made","built, created, prepared, baked, crafted, designed"],
    ["asked","questioned, enquired, begged, requested, wondered aloud"],
    ["told","explained, informed, warned, reminded, assured"],
    ["smiled","grinned, beamed, smirked, flashed a smile, smiled shyly"],
    ["sat","perched, slumped, sank, settled, squatted, plopped down"],
    ["stood","waited, lingered, loomed, towered, stood rooted to the spot"],
    ["held","gripped, clutched, clasped, cradled, clung to"],
    ["opened","flung open, prised open, unlocked, unzipped, tore open"],
    ["closed","shut, slammed, sealed, zipped up, pulled shut"],
    ["pushed","shoved, nudged, jostled, pressed, thrust"],
    ["pulled","tugged, yanked, dragged, hauled, heaved"],
    ["threw","tossed, hurled, slung, lobbed, chucked"],
    ["hit","struck, tapped, thumped, bumped, banged, knocked"],
    ["jumped","leapt, sprang, hopped, bounded, vaulted"],
    ["climbed","scrambled, clambered, scaled, crawled up, hauled myself up"],
    ["angry","cross, annoyed, seething, livid, fuming, irritated"],
    ["scared","afraid, frightened, spooked, petrified, alarmed"],
    ["tired","weary, sleepy, drained, worn out, fatigued"],
    ["pretty","beautiful, attractive, charming, elegant, graceful"],
    ["old","elderly (people), vintage, antique, worn, battered"],
    ["new","brand-new, fresh, modern, latest, unused"],
    ["fast","quick, swift, speedy, brisk, nimble"],
    ["hard","difficult, tricky, challenging, tough, demanding"],
    ["easy","simple, straightforward, painless, a breeze"],
    ["interesting","gripping, exciting, intriguing, eye-opening, absorbing"],
    ["boring","dull, tiresome, monotonous, uneventful, dreary"],
    ["funny","amusing, side-splitting, comical, witty, laugh-out-loud"],
    ["strange","odd, weird, unusual, peculiar, mysterious"],
    ["really","truly, extremely, incredibly, completely, utterly (or cut it out)"]
  ]},
  { type: "table", title: "Thirty-five more “very ___” words to swap", head: ["Instead of","Try"], weakCol: 0, rows: [
    ["very thirsty","parched"],
    ["very boring","tedious"],
    ["very interesting","fascinating"],
    ["very difficult","gruelling"],
    ["very important","crucial"],
    ["very worried","anxious"],
    ["very nervous","jittery"],
    ["very ugly","hideous"],
    ["very strong","mighty"],
    ["very weak","feeble"],
    ["very rich","wealthy"],
    ["very busy","swamped"],
    ["very full (after eating)","stuffed"],
    ["very crowded","packed"],
    ["very dark","pitch-black"],
    ["very shiny","gleaming"],
    ["very thin","scrawny"],
    ["very tall","lofty"],
    ["very sure","convinced"],
    ["very excited","ecstatic"],
    ["very careful","meticulous"],
    ["very brave","fearless"],
    ["very sleepy","drowsy"],
    ["very noisy","rowdy"],
    ["very calm","serene"],
    ["very shy","timid"],
    ["very silly","ridiculous"],
    ["very beautiful","stunning"],
    ["very upset","distraught"],
    ["very embarrassed","mortified"],
    ["very weird","bizarre"],
    ["very heavy","hefty"],
    ["very tasty","delicious"],
    ["very spicy","fiery"],
    ["very windy","blustery"]
  ]}
]},

{ id: "en-wordpairs", blocks: [
  { type: "chips", title: "More strong word pairs", groups: [
    { title: "Faces and eyes", words: ["a piercing stare","a blank expression","a puzzled frown","a sly smile","a cheeky grin","a wry smile","furrowed brows","narrowed eyes","wide-eyed wonder","a steely gaze","a sidelong glance","a knowing look","a stony face","flushed cheeks"],
      ex: "Mr Tan gave me a knowing look, and my flushed cheeks told him everything." },
    { title: "Voices and sounds people make", words: ["a hoarse whisper","a shaky voice","a booming voice","a shrill cry","a high-pitched squeal","a low growl","a nervous laugh","a hollow laugh","a deep sigh","a sharp intake of breath","a muffled sob","a resounding cheer"],
      ex: "There was a sharp intake of breath from the audience as the acrobat wobbled." },
    { title: "Movements", words: ["a sudden jolt","a gentle nudge","a firm grip","a tight hug","a sharp turn","a mad dash","a slow shuffle","a quick glance","a hasty retreat","a graceful leap","a heavy footstep","a steady pace"],
      ex: "The bus came to a stop with a sudden jolt, and I tightened my grip on the pole." },
    { title: "Places", words: ["a narrow alley","a bustling market","a deserted street","a winding staircase","a dimly lit corridor","a crowded platform","a quiet corner","a cluttered desk","a sprawling estate","a cosy nook","a packed hall","an empty stadium"],
      ex: "I found Grandpa in a quiet corner of the bustling market, bargaining over a bag of limes." },
    { title: "More feeling pairs", words: ["a surge of excitement","a twinge of jealousy","a stab of fear","a rush of adrenaline","a hint of sadness","a burst of energy","deeply grateful","utterly exhausted","painfully shy","secretly pleased","quietly confident","hopelessly lost"],
      ex: "I felt a twinge of jealousy when Aisha won, but I was secretly pleased for her too.",
      note: "Try the pattern a + amount word + of + feeling: a twinge of, a stab of, a surge of." },
    { title: "Doing words that go together", words: ["make an excuse","make a fuss","make a wish","take turns","take a risk","take the blame","take part","pay a visit","pay a compliment","give a speech","give way","catch a cold","catch sight of","break the news","break a record","hold a grudge","keep in touch","lose hope","win a prize","meet a deadline"],
      ex: "Instead of making an excuse, Jun Hao took the blame for the broken window.",
      note: "We make a mistake but do our homework. Learn these pairs as one chunk." }
  ]}
]},

{ id: "en-topicvocab", blocks: [
  { type: "chips", title: "More topic vocabulary: hobbies, gadgets and health", groups: [
    { title: "Hobbies", words: ["sketchbook","watercolours","origami","jigsaw puzzle","Lego set","baking tray","recipe","knitting needles","stamp collection","scrapbook","chessboard","checkmate","skateboard","guitar strings","magic tricks","gardening gloves"],
      ex: "I spent the whole Sunday hunched over a thousand-piece jigsaw puzzle, hunting for the last corner piece." },
    { title: "Technology", words: ["coding club","robotics kit","touchscreen","keyboard","headphones","Wi-Fi signal","buffering","low battery","screenshot","upload","group chat","search engine","QR code","smartwatch","frozen screen","restart"],
      ex: "Just as the video call started, the screen froze and a little wheel kept spinning: buffering.",
      note: "Useful for stories about online safety, screen time or a gadget that goes wrong." },
    { title: "Health and the clinic", words: ["waiting room","queue number","thermometer","high fever","sore throat","runny nose","cough mixture","prescription","dispensary","capsules","medical certificate","injection","vaccination","stethoscope","bandage","recover"],
      ex: "I sat in the waiting room clutching my queue number, my throat burning with every swallow." }
  ]},
  { type: "chips", title: "More topic vocabulary: trips, weather and the outdoors", groups: [
    { title: "Travel", words: ["passport","immigration counter","boarding gate","window seat","aisle seat","seat belt sign","turbulence","in-flight meal","flight attendant","take-off","landing","hotel lobby","key card","suitcase","road trip","travel adaptor"],
      ex: "As the plane hit some turbulence, the seat belt sign pinged on and my little sister grabbed my arm." },
    { title: "Weather events", words: ["thunderstorm","thunderclap","lightning strike","heatwave","drought","typhoon","hailstorm","gale-force winds","fallen tree","power cut","flooded roads","overcast sky","drizzle","humidity","weather forecast","heat stroke"],
      ex: "A deafening thunderclap shook the windows, and a moment later there was a power cut." },
    { title: "Nature trips", words: ["hiking boots","insect repellent","binoculars","compass","trail map","summit","lookout point","treetop walk","suspension bridge","MacRitchie Reservoir","Bukit Timah Hill","Pulau Ubin","wild boar","hornbill","park ranger","mosquito bites"],
      ex: "Halfway across the suspension bridge, I peered through my binoculars and spotted a hornbill." }
  ]},
  { type: "chips", title: "More topic vocabulary: money and the planet", groups: [
    { title: "Money and shopping", words: ["pocket money","piggy bank","savings","budget","price tag","discount","special offer","receipt","cashier","checkout counter","shopping list","shopping basket","afford","overspend","refund","window shopping"],
      ex: "I checked the price tag twice. Even with the discount, I could not afford it with my pocket money." },
    { title: "Environment and recycling", words: ["recycling bin","reusable bag","recyclable","plastic waste","food waste","compost","litter","litterbug","reduce, reuse, recycle","single-use plastic","carbon footprint","climate change","global warming","save electricity","turn off the tap","clean-up campaign"],
      ex: "During the beach clean-up campaign, we filled six bags with single-use plastic in just one hour.",
      note: "Great for stories about a class project, a beach clean-up or learning to care for the environment." }
  ]}
]},

{ id: "en-sglife", blocks: [
  { type: "chips", title: "More Singapore life: food, neighbourhood and getting around", groups: [
    { title: "Coffee shop favourites", words: ["kopi O","teh peng","Milo dinosaur","soft-boiled eggs","wanton mee","bak chor mee","yong tau foo","economic rice","nasi padang","thosai","mee siam","curry puff","ondeh-ondeh","kueh lapis","bandung","ice cream sandwich"],
      ex: "Grandpa dipped his toast into his soft-boiled eggs while I slurped my Milo dinosaur." },
    { title: "Coffee shop phrases", words: ["the uncle ladled curry generously over my rice","we reserved a table with a packet of tissues","I carried the takeaway home in a bulging plastic bag","the drinks auntie pulled the teh in a long, frothy stream","an old radio crackled with songs from Grandpa’s youth","the ice cream uncle sliced a block of ice cream and wrapped it in bread"],
      ex: "The drinks auntie pulled the teh in a long, frothy stream, and not a single drop spilled." },
    { title: "Neighbourhood happenings", words: ["pasar malam","night market stalls","getai","Hungry Ghost Festival","void deck wedding","kompang drums","Residents’ Committee","neighbourhood police post","park connector","dengue fogging","town council cleaner","tai chi","line dancing","karung guni man","dragon playground","BTO flat"],
      ex: "On Saturday night, the car park turned into a pasar malam glowing with fairy lights and the smell of grilled corn." },
    { title: "Everyday neighbourhood scenes", words: ["the kompang drums welcomed the bride and groom","fogging smoke drifted across the void deck","joss paper burned in a metal bin by the road","aunties did line dancing at the plaza","uncles played Chinese chess at the stone tables","the karung guni man called out from the corridor","Grandma went for her morning tai chi in the park","the newspaper landed outside the door with a thud","the ice cream cart bell tinkled at the bus stop","a cat dozed under a car in the multi-storey car park"],
      ex: "Every morning, uncles played Chinese chess at the stone tables, slapping down their pieces with a loud clack." },
    { title: "Getting around", words: ["LRT","taxi stand","overhead bridge","zebra crossing","covered linkway","bus interchange","ERP gantry","expressway","school bus","school bus uncle","traffic light","pedestrian crossing"],
      ex: "We hurried along the covered linkway as the rain began to pelt down." }
  ]},
  { type: "chips", title: "More Singapore places and school days", groups: [
    { title: "Places to visit", words: ["Botanic Gardens","Chinatown","Kampong Glam","Haji Lane","Singapore River","the Merlion","Esplanade","National Museum","Science Centre","Bird Paradise","Night Safari","Changi Beach","Coney Island","Sultan Mosque"],
      ex: "At the Science Centre, my hair stood on end when I touched the glowing ball." },
    { title: "Phrases for famous places", words: ["the Merlion spouted water into the bay","bumboats chugged along the Singapore River","the spiky domes of the Esplanade glinted in the sun","the golden dome of Sultan Mosque shone against the blue sky","swans glided across the lake at the Botanic Gardens","colourful murals brightened the walls of Haji Lane"],
      ex: "As we strolled by the river, bumboats chugged past, packed with tourists snapping photos." },
    { title: "More school days", words: ["Mother Tongue lesson","PE lesson","learning journey","school camp","Total Defence Day","International Friendship Day","remedial lesson","class party"],
      ex: "On our learning journey to the National Museum, we sketched old rickshaws and wrote down three questions each." }
  ]}
]},

{ id: "en-golden", blocks: [
  { type: "chips", title: "Golden phrases: lost items", groups: [
    { title: "Realising it is gone", words: ["My hand slid into my pocket and met nothing but air.","I patted every pocket twice, then a third time.","The spot on my desk where my watch had been was bare.","A horrible thought crept into my mind: had I left it on the bus?","My mind raced back over every step I had taken that morning.","Where had I last seen it?"],
      ex: "My hand slid into my pocket and met nothing but air. My EZ-Link card was gone." },
    { title: "Searching high and low", words: ["I retraced my steps all the way back to the canteen.","We combed every corner of the classroom.","I crawled under the desks, ignoring the dust on my knees.","I emptied my bag onto the floor and sifted through the mess.","I asked everyone I passed if they had seen a blue water bottle.","Hope fading, I checked the lost-and-found box one last time."],
      ex: "We combed every corner of the classroom. Hope fading, I checked the lost-and-found box one last time." },
    { title: "Found at last", words: ["There, wedged between two sofa cushions, was my missing card.","My eyes landed on a familiar flash of red.","I let out a whoop of joy that made the librarian frown.","I clutched it to my chest as if it might vanish again.","A kind cleaner had handed it in to the general office."],
      ex: "My eyes landed on a familiar flash of red, and I let out a whoop of joy." }
  ]},
  { type: "chips", title: "Golden phrases: accidents", groups: [
    { title: "The moment it happens", words: ["There was a sickening crunch.","My foot caught on the edge of the step, and the ground rushed up to meet me.","The ladder swayed, then tipped.","With a screech of brakes, the cyclist swerved.","A sharp pain shot up my ankle.","Hot soup splashed across the table and onto his lap."],
      ex: "My foot caught on the edge of the step, and the ground rushed up to meet me. A sharp pain shot up my ankle." },
    { title: "Right after", words: ["For a moment, nobody moved.","A small crowd quickly gathered around us.","Blood trickled from a cut on his knee.","She clutched her wrist, her face white with pain.","I tried to stand, but my leg buckled beneath me.","Someone shouted for a teacher."],
      ex: "For a moment, nobody moved. Then someone shouted for a teacher." },
    { title: "Getting help", words: ["I pressed a clean handkerchief firmly against the wound.","The school nurse hurried over with a first-aid kit.","Mr Lim knelt down and spoke in a calm, steady voice.","“Don’t move. Help is on the way,” I said, squeezing her hand.","Within minutes, the wail of an ambulance siren grew louder.","Gently, the paramedics lifted him onto a stretcher."],
      ex: "“Don’t move. Help is on the way,” I said, squeezing her hand. Moments later, the school nurse hurried over with a first-aid kit." }
  ]},
  { type: "chips", title: "Golden phrases: competitions", groups: [
    { title: "Before it starts", words: ["The hall was packed to the rafters with supporters.","My stomach churned as the judges took their seats.","I ran through my lines one last time in my head.","Our rivals looked confident, almost bored.","Ms Chua gave us a thumbs-up from the front row.","“Next up, Team Phoenix!” the emcee announced."],
      ex: "The hall was packed to the rafters, and my stomach churned as the judges took their seats." },
    { title: "In the thick of it", words: ["The starting whistle shrilled.","I dug my toes into the track and pushed off.","The cheers faded into a dull roar as I focused.","Our opponents were catching up, inch by inch.","With one final stroke, I touched the wall.","My mind went completely blank.","The scoreboard flashed 2–2 with one minute left."],
      ex: "The scoreboard flashed 2–2 with one minute left, and our opponents were catching up, inch by inch." },
    { title: "The results", words: ["The emcee paused, dragging out the suspense.","“And the winner is…”","Our names echoed through the hall.","We leapt to our feet, screaming and hugging.","We had lost, but we had given it everything.","I shook hands with the winner and meant every word of my congratulations.","The trophy was heavier than I had imagined."],
      ex: "We had lost, but we had given it everything, and that felt like its own kind of win." }
  ]},
  { type: "chips", title: "Golden phrases: misunderstandings", groups: [
    { title: "How it starts", words: ["I overheard only half of the conversation, and it was the worst half.","It looked bad, I had to admit.","She was sure I had told everyone her secret.","Jun Hao glared at me as if I were a thief.","The words came out wrong, and I could not take them back.","Before I could explain, she stormed off."],
      ex: "Before I could explain, she stormed off, leaving me standing alone by the lockers." },
    { title: "The silent treatment", words: ["For three whole days, Mei Ling refused to look at me.","Our usual seat at recess felt strangely empty.","Whispers followed me down the corridor.","I lay awake that night, replaying the scene again and again."],
      ex: "For three whole days, Mei Ling refused to look at me, and our usual seat at recess felt strangely empty." },
    { title: "Clearing it up", words: ["“Can we talk?” I asked quietly.","I explained everything, from the very beginning.","Slowly, the frown on her face melted away.","“Why didn’t you just tell me?” she asked.","We laughed at how silly it had all been.","It had all been one big mix-up.","I realised I should have asked instead of assuming.","Only then did the truth come out.","I felt foolish for jumping to conclusions."],
      ex: "Slowly, the frown on her face melted away. It had all been one big mix-up." }
  ]},
  { type: "chips", title: "Golden phrases: surprises", groups: [
    { title: "Something is going on", words: ["Something felt odd the moment I stepped through the door.","The house was dark and strangely silent.","Mum had been acting mysteriously all week.","My friends kept whispering and stopped whenever I came near.","Dad told me to close my eyes and hold out my hands.","Everyone had been in on the secret except me."],
      ex: "My friends kept whispering and stopped whenever I came near. What were they hiding?" },
    { title: "The big reveal", words: ["“Surprise!” The lights flicked on and a crowd of faces beamed at me.","Balloons, streamers and a huge cake filled the living room.","I could hardly believe my eyes.","My jaw dropped.","Standing at the door was Uncle Ravi, who was supposed to be in London.","Inside the box, curled up on a blanket, was a tiny puppy."],
      ex: "Standing at the door was Uncle Ravi, who was supposed to be in London. My jaw dropped." },
    { title: "Reacting", words: ["I was speechless.","Tears of joy filled my eyes.","I squealed and threw my arms around her.","For a moment, I thought I was dreaming.","I pinched myself to make sure it was real.","I had been completely fooled.","It was the best surprise of my life."],
      ex: "I was speechless. For a moment, I thought I was dreaming." }
  ]},
  { type: "chips", title: "Golden endings for these stories", groups: [
    { title: "Closing lines to borrow", words: ["From then on, I always zipped my bag properly.","I will never again take my belongings for granted.","Whenever I see the scar on my knee, I remember to slow down.","The medal now hangs above my desk, a reminder of every early morning practice.","Winning was wonderful, but the friendships we built meant even more.","That day taught me never to jump to conclusions.","Our friendship was stronger than ever after that.","I still smile whenever I think of that surprise.","Sometimes the best things happen when we least expect them.","I learnt that a little care can save a lot of tears."],
      ex: "That day taught me never to jump to conclusions. Our friendship was stronger than ever after that.",
      note: "Match the ending to the problem: a lost item ends with being careful, a misunderstanding ends with asking before assuming." }
  ]}
]},

{ id: "en-transitions", blocks: [
  { type: "chips", title: "More linking phrases", groups: [
    { title: "More times and days to open with", words: ["As dusk fell,","Just after midnight,","At the stroke of midnight,","As the first rays of sunlight crept in,","During recess,","On the last day of term,","At the end of the school day,","One drizzly afternoon,","The week before Christmas,","Early the next morning,"],
      ex: "One drizzly afternoon, as I waited for the school bus, I noticed a small box under the bench." },
    { title: "Putting steps in order", words: ["To begin with,","First of all,","Secondly,","Afterwards,","Subsequently,","Lastly,","The final step was","Once that was done,","Having done that,","The next step was"],
      ex: "To begin with, we sorted the rubbish into piles. Once that was done, we washed every bottle.",
      note: "Perfect for recounts, reports and situational writing where the order matters." },
    { title: "Time passing", words: ["Minutes ticked by.","The minutes crawled past.","Time seemed to fly.","An hour later,","Days turned into weeks.","As the days went by,","Over the next few weeks,","By the end of the month,","Months later,","Years from now,"],
      ex: "Days turned into weeks, and still there was no sign of the missing cat." },
    { title: "Giving examples and explaining", words: ["For example,","For instance,","such as","In other words,","That is to say,","In fact,","Indeed,","Clearly,","Of course,","Surprisingly,"],
      ex: "Grandma loves gardening. In fact, she grows chillies, pandan and lime on her tiny corridor ledge." },
    { title: "Conditions and comparisons", words: ["If","Unless","As long as","Provided that","Otherwise,","In the same way,","Similarly,","Likewise,","Just like","Compared to"],
      ex: "As long as we stayed on the trail, we would be safe. Otherwise, we could easily get lost." },
    { title: "Twists of luck", words: ["Just as I was about to give up,","As luck would have it,","Fortunately,","Unfortunately,","Sadly,","Luckily for us,","To make matters worse,","As if that were not enough,","Strangely,","Then came the twist:"],
      ex: "To make matters worse, it started to pour. As luck would have it, a kind stallholder let us shelter under her awning." }
  ]}
]},

{ id: "en-patterns", blocks: [
  { type: "table", title: "Twenty-four more sentence patterns", head: ["Pattern","Example","Use it to..."], rows: [
    ["31. Whenever ..., ...","Whenever thunder rumbled, my dog squeezed under the bed.","show something that happens every single time"],
    ["32. ... until ...","I kept searching until my legs ached and the sky grew dark.","show how long an action went on"],
    ["33. ... as if ...","Mei Ling stared at me as if I had grown two heads.","compare an action to something imaginary"],
    ["34. Once ..., ...","Once the rain stopped, we hurried out to the playground.","show that one thing had to finish before the next began"],
    ["35. Unless ..., ...","Unless we found the key, we would be locked out all night.","build worry by showing what will happen if nothing changes"],
    ["36. It was such a ... that ...","It was such a long queue that we almost gave up.","show how big or strong something was by its result"],
    ["37. -ly word opener","Slowly, carefully, I lifted the lid of the box.","show how an action was done and slow the moment down"],
    ["38. “...,” + speaker + -ing action","“Don’t move,” Dad whispered, pointing at the snake.","mix speech and action in one sentence"],
    ["39. Question to the reader","Have you ever felt your heart stop for a second?","pull the reader into your story, often in an opening"],
    ["40. A very short sentence","Then the lights went out.","create shock or suspense after a longer sentence"],
    ["41. Place opener","Beneath the old staircase, something glinted in the dark.","start with where something is, to build mystery"],
    ["42. Not once did ...","Not once did Grandpa complain about the pain.","stress that something never happened"],
    ["43. What a ...!","What a mess we had made!","show a strong reaction as an exclamation"],
    ["44. All I could do was ...","All I could do was watch helplessly as the bus pulled away.","show that the character felt powerless"],
    ["45. The last thing I wanted was ...","The last thing I wanted was to let my team down.","show what the character feared most"],
    ["46. Of all the ..., ...","Of all the days to forget my umbrella, it had to be today.","show bad luck with a touch of humour"],
    ["47. Either ... or ...","Either we owned up now, or we would be found out later.","show a difficult choice between two options"],
    ["48. Adjective + as + I was, ...","Tired as I was, I helped Grandma carry her shopping up the stairs.","show a struggle in a more grown-up way than although"],
    ["49. ... — + surprise","I opened the box, and there it was — my lost watch.","save a surprise for the end of the sentence"],
    ["50. It was not ... but ...","It was not the medal that mattered, but the friends I made.","show what really matters, often in an ending"],
    ["51. Had I ..., I would have ...","Had I checked my bag, I would have found the key.","show regret about something that cannot be changed"],
    ["52. Past participle opener","Covered in mud, the puppy wagged its tail proudly.","describe someone’s state before the main action"],
    ["53. Nothing could have prepared me for ...","Nothing could have prepared me for what I saw next.","build suspense just before a big reveal"],
    ["54. By the time ..., ...","By the time the ambulance arrived, a crowd had gathered.","show that something had already happened before another event"]
  ]}
]},

{ id: "en-idioms2", blocks: [
  { type: "idioms", title: "Even more idioms and proverbs", items: [
    { w: "a bundle of nerves", py: "", m: "very nervous", ex: "Before the choir competition, I was a bundle of nerves.", cat: "Feelings" },
    { w: "hit the roof", py: "", m: "become suddenly very angry", ex: "Dad hit the roof when he saw the scratch on his new car.", cat: "Feelings" },
    { w: "lost for words", py: "", m: "so surprised or moved that you cannot speak", ex: "When my class gave me a farewell card, I was lost for words.", cat: "Feelings" },
    { w: "my blood ran cold", py: "", m: "I felt sudden, terrible fear", ex: "My blood ran cold when I heard footsteps in the empty flat.", cat: "Feelings" },
    { w: "fly off the handle", py: "", m: "lose your temper suddenly", ex: "Jun Hao tends to fly off the handle when he loses a game.", cat: "Feelings" },
    { w: "in seventh heaven", py: "", m: "extremely happy", ex: "With a new puppy in her arms, Aisha was in seventh heaven.", cat: "Feelings" },
    { w: "keep my cool", py: "", m: "stay calm in a difficult situation", ex: "Even when the others shouted, I tried to keep my cool.", cat: "Feelings" },
    { w: "on top of the world", py: "", m: "very happy and proud", ex: "After scoring the winning goal, I felt on top of the world.", cat: "Feelings" },
    { w: "for the time being", py: "", m: "for now, but not for ever", ex: "For the time being, the kitten will sleep in a box in the kitchen.", cat: "Time" },
    { w: "the time of my life", py: "", m: "a very enjoyable time", ex: "I had the time of my life at the school camp.", cat: "Time" },
    { w: "in the heat of the moment", py: "", m: "while feeling angry or excited, without thinking", ex: "In the heat of the moment, I said things I did not mean.", cat: "Time" },
    { w: "on the spur of the moment", py: "", m: "suddenly, without planning", ex: "On the spur of the moment, we decided to cycle to the beach.", cat: "Time" },
    { w: "every now and then", py: "", m: "sometimes, not often", ex: "Every now and then, Grandma tells us stories about her kampong days.", cat: "Time" },
    { w: "now or never", py: "", m: "you must act right now or lose your chance", ex: "The bus doors were closing. It was now or never.", cat: "Time" },
    { w: "a scaredy-cat", py: "", m: "someone who is easily frightened", ex: "My brother is such a scaredy-cat that he hides behind the sofa during cartoons.", cat: "People" },
    { w: "a copycat", py: "", m: "someone who copies what others do", ex: "Stop being a copycat and think of your own idea!", cat: "People" },
    { w: "a show-off", py: "", m: "someone who keeps trying to impress others", ex: "Nobody likes a show-off who boasts about every test score.", cat: "People" },
    { w: "an early bird", py: "", m: "someone who gets up or arrives early", ex: "Dad is an early bird who jogs before the sun rises.", cat: "People" },
    { w: "a good egg", py: "", m: "a kind, decent person", ex: "Mr Kumar is a good egg who always helps the neighbours.", cat: "People" },
    { w: "a busy bee", py: "", m: "someone who is always busy and working", ex: "Mum is a busy bee from morning till night.", cat: "People" },
    { w: "keep the ball rolling", py: "", m: "keep something going", ex: "To keep the ball rolling, Priya suggested another fundraising idea.", cat: "Effort" },
    { w: "pull my weight", py: "", m: "do my fair share of the work", ex: "In our group project, I made sure I pulled my weight.", cat: "Effort" },
    { w: "learn the hard way", py: "", m: "learn something through a bad experience", ex: "I learnt the hard way that I should always save my work.", cat: "Effort" },
    { w: "give it a go", py: "", m: "try something", ex: "I had never played the drums, but I decided to give it a go.", cat: "Effort" },
    { w: "stick to my guns", py: "", m: "refuse to change my mind", ex: "Even when my friends laughed, I stuck to my guns and told the truth.", cat: "Effort" },
    { w: "hit the books", py: "", m: "study hard", ex: "With the exams a week away, it was time to hit the books.", cat: "Effort" },
    { w: "caught red-handed", py: "", m: "caught while doing something wrong", ex: "My brother was caught red-handed with his hand in the biscuit tin.", cat: "Trouble" },
    { w: "open a can of worms", py: "", m: "start something that causes many new problems", ex: "Asking who broke the vase opened a can of worms.", cat: "Trouble" },
    { w: "between a rock and a hard place", py: "", m: "facing two choices that are both difficult", ex: "I was between a rock and a hard place: tell on my friend or keep quiet.", cat: "Trouble" },
    { w: "in a jam", py: "", m: "in a difficult situation", ex: "I was in a jam when I realised I had left my wallet at home.", cat: "Trouble" },
    { w: "cross the line", py: "", m: "go too far and do something unacceptable", ex: "Teasing is one thing, but posting that photo crossed the line.", cat: "Trouble" },
    { w: "a recipe for disaster", py: "", m: "something likely to end badly", ex: "Running on a wet floor is a recipe for disaster.", cat: "Trouble" },
    { w: "not my cup of tea", py: "", m: "not something I enjoy", ex: "Horror films are not my cup of tea.", cat: "Food" },
    { w: "butter someone up", py: "", m: "be extra nice to someone to get something", ex: "My sister buttered Dad up before asking for a later bedtime.", cat: "Food" },
    { w: "egg someone on", py: "", m: "encourage someone to do something unwise", ex: "The older boys egged him on to climb the fence.", cat: "Food" },
    { w: "have a sweet tooth", py: "", m: "love sweet food", ex: "Grandpa has a sweet tooth and can never say no to kueh.", cat: "Food" },
    { w: "walk on eggshells", py: "", m: "be very careful not to upset someone", ex: "After their quarrel, we all walked on eggshells around Wei Ming.", cat: "Food" },
    { w: "like a bull in a china shop", py: "", m: "very clumsy in a place where things break easily", ex: "My little brother charged around the gift shop like a bull in a china shop.", cat: "Animals" },
    { w: "smell a rat", py: "", m: "suspect that something is wrong", ex: "When the class went silent as I walked in, I smelt a rat.", cat: "Animals" },
    { w: "until the cows come home", py: "", m: "for a very long time", ex: "You can argue until the cows come home, but the answer is still no.", cat: "Animals" },
    { w: "in the doghouse", py: "", m: "in trouble with someone", ex: "After forgetting Mum’s birthday, Dad was in the doghouse.", cat: "Animals" },
    { w: "the black sheep of the family", py: "", m: "the family member who is different or causes trouble", ex: "Uncle Sam called himself the black sheep of the family because he became a clown.", cat: "Animals" },
    { w: "a wolf in sheep’s clothing", py: "", m: "someone who seems kind but is not", ex: "The boy who offered to “help” with my homework only wanted to copy it. He was a wolf in sheep’s clothing.", cat: "Animals" },
    { w: "all fingers and thumbs", py: "", m: "clumsy with your hands", ex: "I was all fingers and thumbs as I tried to tie the ribbon.", cat: "Body" },
    { w: "get something off my chest", py: "", m: "tell someone what has been worrying me", ex: "I finally got it off my chest and told Mum about the broken phone.", cat: "Body" },
    { w: "my lips are sealed", py: "", m: "I will keep the secret", ex: "“Don’t worry, my lips are sealed,” Priya promised.", cat: "Body" },
    { w: "play it by ear", py: "", m: "decide what to do as things happen", ex: "We didn’t have a plan for the afternoon, so we played it by ear.", cat: "Body" },
    { w: "find my feet", py: "", m: "become comfortable in a new place", ex: "It took me a month to find my feet in my new school.", cat: "Body" },
    { w: "have a change of heart", py: "", m: "change your mind, often to be kinder", ex: "The bully had a change of heart and apologised.", cat: "Body" },
    { w: "a fair-weather friend", py: "", m: "a friend who disappears when you need help", ex: "When I lost the match, I learnt who was only a fair-weather friend.", cat: "Weather" },
    { w: "have my head in the clouds", py: "", m: "be daydreaming and not paying attention", ex: "I had my head in the clouds and missed my MRT stop.", cat: "Weather" },
    { w: "a breeze", py: "", m: "very easy", ex: "After all that practice, the spelling test was a breeze.", cat: "Weather" },
    { w: "pay through the nose", py: "", m: "pay far too much", ex: "We paid through the nose for drinks at the theme park.", cat: "Money" },
    { w: "a penny-pincher", py: "", m: "someone who hates spending money", ex: "My uncle is such a penny-pincher that he reuses wrapping paper.", cat: "Money" },
    { w: "on the house", py: "", m: "free, paid for by the shop", ex: "The stallholder smiled and said the extra fishballs were on the house.", cat: "Money" },
    { w: "Beauty is only skin deep.", py: "", m: "what a person is like inside matters more than looks", ex: "The prince in the story was handsome but unkind. Beauty is only skin deep.", cat: "Proverbs" },
    { w: "It never rains but it pours.", py: "", m: "bad things often happen all at once", ex: "First I missed the bus, then I forgot my file. It never rains but it pours.", cat: "Proverbs" },
    { w: "A penny saved is a penny earned.", py: "", m: "saving money is as good as earning it", ex: "I put half my pocket money in my piggy bank. A penny saved is a penny earned.", cat: "Proverbs" },
    { w: "Time is money.", py: "", m: "wasting time is like wasting money", ex: "“Hurry up and pack,” said the tour guide. “Time is money!”", cat: "Proverbs" },
    { w: "Better safe than sorry.", py: "", m: "it is wiser to be careful than to take a risk", ex: "I brought an umbrella even though it was sunny. Better safe than sorry.", cat: "Proverbs" },
    { w: "Silence is golden.", py: "", m: "sometimes it is best to say nothing", ex: "After a noisy day, the quiet library felt wonderful. Silence is golden.", cat: "Proverbs" },
    { w: "Great oaks from little acorns grow.", py: "", m: "big things start from small beginnings", ex: "Our tiny recycling corner became a school-wide project. Great oaks from little acorns grow.", cat: "Proverbs" },
    { w: "The apple doesn’t fall far from the tree.", py: "", m: "children are often like their parents", ex: "Mei Ling sings just as beautifully as her mother. The apple doesn’t fall far from the tree.", cat: "Proverbs" },
    { w: "Hope for the best, prepare for the worst.", py: "", m: "stay positive but be ready for problems", ex: "We packed raincoats for the picnic. Hope for the best, prepare for the worst.", cat: "Proverbs" },
    { w: "Every dog has its day.", py: "", m: "everyone gets a chance to succeed one day", ex: "After years on the bench, Ravi scored the winning goal. Every dog has its day.", cat: "Proverbs" },
    { w: "Practise what you preach.", py: "", m: "do what you tell others to do", ex: "If you tell us to be on time, you should be on time too. Practise what you preach!", cat: "Proverbs" },
    { w: "One good turn deserves another.", py: "", m: "if someone helps you, help them back", ex: "Aisha helped me with maths, so I helped her with art. One good turn deserves another.", cat: "Proverbs" },
    { w: "Don’t put off until tomorrow what you can do today.", py: "", m: "do your tasks now instead of delaying", ex: "I finished my project on Friday instead of Sunday night. Don’t put off until tomorrow what you can do today.", cat: "Proverbs" },
    { w: "There’s no smoke without fire.", py: "", m: "rumours usually have some truth in them", ex: "Everyone said the shop was closing. There’s no smoke without fire, and sure enough, it shut a month later.", cat: "Proverbs" },
    { w: "Fortune favours the brave.", py: "", m: "people who take brave chances are often rewarded", ex: "I put up my hand to sing the solo. Fortune favours the brave.", cat: "Proverbs" },
    { w: "Home is where the heart is.", py: "", m: "home is wherever the people you love are", ex: "Our flat is small, but home is where the heart is.", cat: "Proverbs" }
  ]}
]},

{ id: "en-themes", blocks: [
  { type: "chips", title: "More words for every theme pack", groups: [
    { title: "More kindness words", words: ["kind-hearted","caring","selfless","empathy","a random act of kindness","brightened her day","lightened his load","reached out to","offered my seat","without a second thought","paid it forward","gentle, reassuring words"],
      ex: "Without a second thought, I offered my seat to the tired mother and her baby." },
    { title: "More honesty words", words: ["truthful","sincere","deceive","cheat","a white lie","fibbed","my conscience nagged me","could not look her in the eye","admitted my mistake","earned back their trust","broke his trust","a clear conscience"],
      ex: "My conscience nagged me all through dinner, and I could not look Mum in the eye." },
    { title: "More courage words", words: ["fearless","daring","heroic","valiant","quaking with fear","took a leap of faith","spoke up","did not flinch","conquered my fear","braved the storm","held my nerve","put on a brave face"],
      ex: "Although I was quaking with fear, I held my nerve and spoke up." },
    { title: "More responsibility words", words: ["accountable","conscientious","mature","punctual","organised","a role model","looked after","set an example","counted on me","kept my promise","did my part","let everyone down"],
      ex: "My teacher had counted on me, and I did not want to let everyone down." },
    { title: "More perseverance words", words: ["resilient","tenacious","unwavering","hard-earned","bounced back","dusted myself off","kept at it","one step at a time","never lost hope","went the distance","grit","the finish line was in sight"],
      ex: "I dusted myself off and kept at it, one step at a time." },
    { title: "More friendship words", words: ["companion","trusting","a falling-out","made up","kept in touch","lifelong friends","a heart-to-heart talk","inside jokes","cheered me up","stood up for me","had each other’s backs","laughed till our sides ached"],
      ex: "After a long heart-to-heart talk, we made up and laughed till our sides ached." },
    { title: "More family words", words: ["siblings","doting grandparents","family ties","bonding time","family tradition","quality time","hand-me-downs","Sunday lunch at Grandma’s","sibling rivalry","protective","nurturing","a warm embrace"],
      ex: "Sunday lunch at Grandma’s is a family tradition that none of us would ever miss." },
    { title: "More words for making a mistake", words: ["absent-minded","thoughtless","blunder","hasty","consequences","a slip-up","learnt the hard way","owned up to","wished I could undo","faced the music","a second chance","I should have known better"],
      ex: "It was a thoughtless blunder, and I knew I would have to face the consequences." },
    { title: "More gratitude words", words: ["thank-you card","repay their kindness","give back","forever thankful","deeply touched","thankful from the bottom of my heart","return the favour","grateful beyond words","showed my appreciation","a simple thank you","went out of her way","never take it for granted again"],
      ex: "Mrs Lee had gone out of her way to help me, and I wanted to repay her kindness somehow." },
    { title: "More teamwork words", words: ["teammates","coordinate","delegate","role","strategy","huddle","morale","trust one another","play to our strengths","lifted each other up","no one left behind","stronger together"],
      ex: "We huddled together, agreed on a strategy and decided to play to our strengths." }
  ]}
]}

]});
