window.VG = window.VG || [];

/* ---------- 1. Plural nouns ---------- */
window.VG.push({
  id: "en-g-plurals",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Plural nouns",
  lv: "A",
  intro: "A plural noun means more than one thing. Most words just add s, but some words change in special ways, and good writers know them.",
  rules: [
    { h: "Most nouns: add s", html: "one <b>book</b> → two <b>books</b><br>one <b>bus stop</b> → three <b>bus stops</b><br>one <b>pencil</b> → many <b>pencils</b>" },
    { h: "Ends in s, ss, sh, ch, x or z: add es", html: "<b>bus</b> → <b>buses</b>, <b>glass</b> → <b>glasses</b>, <b>brush</b> → <b>brushes</b>, <b>bench</b> → <b>benches</b>, <b>box</b> → <b>boxes</b><br>Say it aloud: you can hear the extra sound <b>-iz</b>." },
    { h: "Consonant + y: change y to ies", html: "<b>baby</b> → <b>babies</b>, <b>story</b> → <b>stories</b>, <b>library</b> → <b>libraries</b><br>But vowel + y just adds s: <b>boy</b> → <b>boys</b>, <b>key</b> → <b>keys</b>, <b>day</b> → <b>days</b>." },
    { h: "Many words ending in f or fe: change to ves", html: "<b>leaf</b> → <b>leaves</b>, <b>knife</b> → <b>knives</b>, <b>wolf</b> → <b>wolves</b>, <b>shelf</b> → <b>shelves</b>, <b>half</b> → <b>halves</b><br>Some just add s: <b>roof</b> → <b>roofs</b>, <b>chief</b> → <b>chiefs</b>." },
    { h: "Some words ending in o add es", html: "<b>tomato</b> → <b>tomatoes</b>, <b>potato</b> → <b>potatoes</b>, <b>hero</b> → <b>heroes</b><br>Others just add s: <b>piano</b> → <b>pianos</b>, <b>photo</b> → <b>photos</b>, <b>radio</b> → <b>radios</b>." },
    { h: "Irregular plurals: learn by heart", html: "<b>child</b> → <b>children</b>, <b>man</b> → <b>men</b>, <b>woman</b> → <b>women</b>, <b>mouse</b> → <b>mice</b>, <b>tooth</b> → <b>teeth</b>, <b>foot</b> → <b>feet</b>, <b>goose</b> → <b>geese</b>, <b>person</b> → <b>people</b><br>✗ childs, mouses, tooths, foots" },
    { h: "Same in singular and plural", html: "one <b>sheep</b> → ten <b>sheep</b>, one <b>deer</b> → two <b>deer</b>, one <b>fish</b> → many <b>fish</b><br>✓ I saw five sheep. ✗ I saw five sheeps." }
  ],
  words: [],
  mistakes: [
    { wrong: "The childrens are playing at the playground.", right: "The children are playing at the playground.", why: "Children is already plural. Do not add s." },
    { wrong: "Mum bought three boxs of tissue.", right: "Mum bought three boxes of tissue.", why: "Box ends in x, so add es: boxes." },
    { wrong: "I read two storys before bed.", right: "I read two stories before bed.", why: "Story ends in consonant + y, so change y to ies." },
    { wrong: "The gardener swept up the dry leafs.", right: "The gardener swept up the dry leaves.", why: "Leaf changes f to ves: leaves." },
    { wrong: "The farmer has twenty sheeps.", right: "The farmer has twenty sheep.", why: "Sheep stays the same when there is more than one." },
    { wrong: "I brush my tooths every night.", right: "I brush my teeth every night.", why: "Tooth is irregular. The plural is teeth." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "There are three ___ on the table.", o: ["cup", "cups", "cupes"], a: 1, why: "Most nouns just add s: cup → cups." },
    { t: "mcq", lv: "A", q: "Grandma packed two ___ for our picnic at East Coast Park.", o: ["boxs", "boxes", "boxies"], a: 1, why: "Box ends in x, so we add es: boxes." },
    { t: "mcq", lv: "A", q: "The ___ are playing hide-and-seek at the void deck.", o: ["childs", "childrens", "children"], a: 2, why: "Child is irregular: one child, two children. No s is needed." },
    { t: "mcq", lv: "A", q: "My little brother has lost two front ___.", o: ["tooths", "teeth", "teeths"], a: 1, why: "Tooth is irregular: one tooth, many teeth." },
    { t: "mcq", lv: "A", q: "We saw many ___ swimming in the pond at the Botanic Gardens.", o: ["fish", "fishs", "fishies"], a: 0, why: "When we talk about many fish, the word usually stays fish." },
    { t: "mcq", lv: "A", q: "The cat chased two ___ in the storeroom.", o: ["mouses", "mice", "mices"], a: 1, why: "Mouse is irregular: one mouse, two mice." },
    { t: "mcq", lv: "A", q: "Mr Tan read us three funny ___ today.", o: ["storys", "stories", "storyes"], a: 1, why: "Story ends in consonant + y (r + y), so change y to ies: stories." },
    { t: "mcq", lv: "A", q: "Aisha has two ___ on her key chain.", o: ["keys", "keies", "kies"], a: 0, why: "Key ends in vowel + y (e + y), so just add s: keys." },
    { t: "mcq", lv: "A", q: "The farmer in the picture book has ten ___.", o: ["sheeps", "sheep", "sheepes"], a: 1, why: "Sheep is the same for one or many: ten sheep." },
    { t: "mcq", lv: "B", q: "Mum cut the papaya into two ___.", o: ["halfs", "halves", "halfes", "halvs"], a: 1, why: "Half changes f to ves: halves." },
    { t: "mcq", lv: "B", q: "The chef at the hawker stall sharpened his ___.", o: ["knifes", "knives", "knivs", "knife's"], a: 1, why: "Knife changes fe to ves: knives." },
    { t: "mcq", lv: "B", q: "Dad bought a bag of ___ for the curry.", o: ["potatos", "potatoes", "potatoe", "potatose"], a: 1, why: "Potato adds es: potatoes. (Tomato → tomatoes works the same way.)" },
    { t: "mcq", lv: "B", q: "Our school hall has two ___ for the choir to use.", o: ["pianoes", "pianos", "pianies", "piano"], a: 1, why: "Piano just adds s: pianos. Not every word ending in o adds es." },
    { t: "mcq", lv: "B", q: "Ten ___ were waiting at the bus stop.", o: ["persones", "people", "peoples", "peoplies"], a: 1, why: "In everyday English, the plural of person is people." },
    { t: "mcq", lv: "B", q: "Which plural is spelt correctly?", o: ["wolfs", "babys", "benches", "foots"], a: 2, why: "Bench ends in ch, so add es: benches. The others should be wolves, babies and feet." },
    { t: "mcq", lv: "B", q: "Which plural is spelt WRONGLY?", o: ["libraries", "monkeys", "shelves", "womans"], a: 3, why: "Woman is irregular: the plural is women, not womans." },
    { t: "mcq", lv: "B", q: "The ___ waddled across the farm in Kranji.", o: ["gooses", "geese", "geeses", "goose's"], a: 1, why: "Goose is irregular: one goose, many geese." },
    { t: "mcq", lv: "C", q: "The firemen were called ___ for saving the cat.", o: ["heros", "heroes", "heroies", "heroe"], a: 1, why: "Hero adds es: heroes." },
    { t: "mcq", lv: "C", q: "Which group has ALL plurals correct?", o: ["roofs, leaves, photos", "rooves, leafs, photoes", "roofs, leafs, photos", "rooves, leaves, photoes"], a: 0, why: "Roof just adds s, leaf becomes leaves, and photo just adds s." },
    { t: "fix", lv: "A", q: "The childrens sang a song for Teachers' Day.", err: "childrens", a: "children", why: "Children is already plural. Do not add s." },
    { t: "fix", lv: "A", q: "Mei Ling put the dirty dishs in the sink.", err: "dishs", a: "dishes", why: "Dish ends in sh, so add es: dishes." },
    { t: "fix", lv: "B", q: "Our class has two new pet mouses.", err: "mouses", a: "mice", why: "Mouse is irregular: the plural is mice." },
    { t: "fix", lv: "B", q: "The dry leafs fell onto the playground.", err: "leafs", a: "leaves", why: "Leaf changes f to ves: leaves." },
    { t: "fix", lv: "B", q: "There are three new librarys in the west of Singapore.", err: "librarys", a: "libraries", why: "Library ends in consonant + y, so change y to ies." },
    { t: "fix", lv: "C", q: "My feets hurt after the long walk up Bukit Timah Hill.", err: "feets", a: "feet", why: "Foot is irregular: one foot, two feet. Do not add s." },
    { t: "fill", lv: "A", q: "There are four ___ (bus) at the interchange.", a: ["buses"], why: "Bus ends in s, so add es: buses." },
    { t: "fill", lv: "A", q: "Jun Hao's mum has two ___ (baby).", a: ["babies"], why: "Baby ends in consonant + y, so change y to ies." },
    { t: "fill", lv: "A", q: "Five ___ (man) helped to carry the heavy cupboard.", a: ["men"], why: "Man is irregular: one man, many men." },
    { t: "fill", lv: "B", q: "Please put the books back on the ___ (shelf).", a: ["shelves"], why: "Shelf changes f to ves: shelves." },
    { t: "fill", lv: "B", q: "We saw three ___ (deer) at the zoo.", a: ["deer"], why: "Deer stays the same in the plural." },
    { t: "fill", lv: "C", q: "Grandpa grows chillies and ___ (tomato) along the HDB corridor.", a: ["tomatoes"], why: "Tomato adds es: tomatoes." },
    { t: "trans", lv: "B", q: "Change to plural: The child has a toy mouse.", a: ["The children have toy mice."], why: "Child → children, has → have, mouse → mice. When the noun becomes plural, the verb changes too." }
  ]
});

/* ---------- 2. Countable and uncountable nouns ---------- */
window.VG.push({
  id: "en-g-countable",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Countable and uncountable nouns",
  lv: "B",
  intro: "Some things we can count (one apple, two apples). Some things we cannot count one by one (water, rice, advice). Knowing which is which helps you choose many or much, few or little.",
  rules: [
    { h: "Countable nouns", html: "We can count them and they have a plural: <b>an apple, two apples</b>; <b>a chair, five chairs</b>.<br>Use <b>many</b>, <b>a few</b>, <b>few</b>, <b>a number of</b> with them." },
    { h: "Uncountable nouns", html: "We cannot count them one by one and they have <b>no plural</b>: <b>water, rice, sugar, money, furniture, luggage, advice, homework, information, equipment</b>.<br>✓ some furniture ✗ some furnitures<br>Use <b>much</b>, <b>a little</b>, <b>little</b>, <b>an amount of</b> with them." },
    { h: "Tricky uncountables", html: "These are uncountable in English, even though they seem countable: <b>furniture, luggage, baggage, advice, homework, information, news, equipment, stationery</b>.<br>✓ The news <b>is</b> good. ✓ I have a lot of homework. ✗ I have many homeworks." },
    { h: "Counting uncountables", html: "Use a measure word: <b>a piece of</b> advice, <b>a piece of</b> furniture, <b>a glass of</b> water, <b>a bowl of</b> rice, <b>a bottle of</b> milk, <b>a loaf of</b> bread." },
    { h: "Words that work with both", html: "<b>a lot of / lots of</b>: a lot of books ✓ a lot of water ✓<br><b>some</b>: usually in positive sentences — I have some sweets. I need some help.<br><b>any</b>: usually in questions and negatives — Do you have any glue? I don't have any money." },
    { h: "Few vs a few, little vs a little", html: "<b>a few</b> / <b>a little</b> = some, enough (positive): I have a few friends here, so I am happy.<br><b>few</b> / <b>little</b> = not many / not much, almost none (negative): Few pupils came, so the hall was empty." },
    { h: "Uncountable nouns take a singular verb", html: "✓ The furniture <b>is</b> new. ✓ My homework <b>was</b> easy. ✓ The information <b>is</b> on the notice board.<br>✗ The furniture are new." }
  ],
  words: [],
  mistakes: [
    { wrong: "Our teacher gave us many homeworks.", right: "Our teacher gave us a lot of homework.", why: "Homework is uncountable: no s, and use a lot of or much, not many." },
    { wrong: "My grandma gave me an advice.", right: "My grandma gave me a piece of advice.", why: "Advice is uncountable, so we cannot say an advice. Use a piece of advice." },
    { wrong: "How many sugar do you want in your teh?", right: "How much sugar do you want in your teh?", why: "Sugar is uncountable, so use much." },
    { wrong: "We bought some new furnitures for the flat.", right: "We bought some new furniture for the flat.", why: "Furniture is uncountable. It never takes s." },
    { wrong: "The informations are on the website.", right: "The information is on the website.", why: "Information is uncountable: no s, and it takes a singular verb (is)." },
    { wrong: "There are less people at the pool today.", right: "There are fewer people at the pool today.", why: "People can be counted, so use fewer. Less goes with uncountable nouns, like less water." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "How ___ apples are in the basket?", o: ["many", "much", "little"], a: 0, why: "Apples can be counted, so use many." },
    { t: "mcq", lv: "A", q: "How ___ water should I pour into the pot?", o: ["many", "much", "few"], a: 1, why: "Water cannot be counted one by one, so use much." },
    { t: "mcq", lv: "A", q: "Can I have ___ glass of milk, please?", o: ["a", "much", "many"], a: 0, why: "We count milk using a measure: a glass of milk." },
    { t: "mcq", lv: "A", q: "I ate a bowl of ___ at the hawker centre.", o: ["rices", "rice", "a rice"], a: 1, why: "Rice is uncountable, so it has no s. We say a bowl of rice." },
    { t: "mcq", lv: "B", q: "Our teacher gave us a lot of ___ today.", o: ["homeworks", "homework", "a homework", "homeworkes"], a: 1, why: "Homework is uncountable, so it never takes s or a." },
    { t: "mcq", lv: "B", q: "Grandpa gave me a useful ___ about saving money.", o: ["advice", "advices", "piece of advice", "pieces of advices"], a: 2, why: "Advice is uncountable, so we say a piece of advice." },
    { t: "mcq", lv: "B", q: "The new ___ in our living room looks nice.", o: ["furniture", "furnitures", "a furniture", "furnitures pieces"], a: 0, why: "Furniture is uncountable: no s and no a." },
    { t: "mcq", lv: "B", q: "We had so much ___ that Dad needed a trolley at Changi Airport.", o: ["luggages", "luggage", "a luggage", "luggage's"], a: 1, why: "Luggage is uncountable. It never takes s." },
    { t: "mcq", lv: "B", q: "The ___ about the school camp is on the notice board.", o: ["information", "informations", "an information", "informationes"], a: 0, why: "Information is uncountable: no s and no an." },
    { t: "mcq", lv: "B", q: "The news ___ very exciting!", o: ["are", "is", "were", "have been"], a: 1, why: "News is uncountable, even though it ends in s. It takes a singular verb: is." },
    { t: "mcq", lv: "B", q: "Do you have ___ glue? Mine has run out.", o: ["any", "many", "a few", "few"], a: 0, why: "Glue is uncountable, and this is a question, so use any." },
    { t: "mcq", lv: "B", q: "There isn't ___ milk left in the fridge.", o: ["many", "much", "few", "a few"], a: 1, why: "Milk is uncountable, and this is a negative sentence, so use much." },
    { t: "mcq", lv: "B", q: "I still have ___ sweets left. Do you want one?", o: ["a few", "a little", "much", "little"], a: 0, why: "Sweets can be counted, and we mean some (enough to share), so use a few." },
    { t: "mcq", lv: "B", q: "Add ___ salt to the soup, not too much.", o: ["a few", "a little", "many", "few"], a: 1, why: "Salt is uncountable, and we mean a small amount, so use a little." },
    { t: "mcq", lv: "C", q: "Very ___ pupils came for the extra class because of the heavy rain, so the classroom was almost empty.", o: ["little", "few", "much", "a little"], a: 1, why: "Pupils can be counted, and the meaning is almost none, so use few (not a few)." },
    { t: "mcq", lv: "C", q: "Ravi had ___ time to finish the test, so he left two questions blank.", o: ["few", "a few", "little", "many"], a: 2, why: "Time here is uncountable, and the meaning is not enough, so use little." },
    { t: "mcq", lv: "C", q: "There are ___ cars on the road on Sunday mornings than on weekdays.", o: ["less", "fewer", "little", "much"], a: 1, why: "Cars can be counted, so use fewer. Less is for uncountable nouns." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["The equipments are in the store.", "The equipment are in the store.", "The equipment is in the store.", "An equipment is in the store."], a: 2, why: "Equipment is uncountable: no s, no an, and a singular verb (is)." },
    { t: "mcq", lv: "C", q: "Which noun is uncountable?", o: ["chair", "suitcase", "luggage", "bag"], a: 2, why: "Luggage is uncountable. Chair, suitcase and bag can all be counted." },
    { t: "fix", lv: "B", q: "Mum bought some new furnitures for my room.", err: "furnitures", a: "furniture", why: "Furniture is uncountable, so it never takes s." },
    { t: "fix", lv: "B", q: "How many sugar do you take in your kopi?", err: "many", a: "much", why: "Sugar is uncountable, so use much." },
    { t: "fix", lv: "B", q: "I have finished all my homeworks.", err: "homeworks", a: "homework", why: "Homework is uncountable. It never takes s." },
    { t: "fix", lv: "C", q: "Please read the informations on this poster.", err: "informations", a: "information", why: "Information is uncountable, so it never takes s." },
    { t: "fix", lv: "C", q: "There were less children at the playground today.", err: "less", a: "fewer", why: "Children can be counted, so use fewer." },
    { t: "fix", lv: "C", q: "My uncle gave me a lot of advices about studying.", err: "advices", a: "advice", why: "Advice is uncountable, so it never takes s: a lot of advice." },
    { t: "fill", lv: "A", q: "Please buy a ___ of bread from the bakery. (loaf / glass)", a: ["loaf"], why: "We count bread using a loaf: a loaf of bread." },
    { t: "fill", lv: "B", q: "How ___ money do you need for the excursion? (much / many)", a: ["much"], why: "Money is uncountable, so use much." },
    { t: "fill", lv: "B", q: "How ___ pencils are in your pencil case? (much / many)", a: ["many"], why: "Pencils can be counted, so use many." },
    { t: "fill", lv: "B", q: "Would you like ___ more rice? (some / many)", a: ["some"], why: "Rice is uncountable. In offers, we use some." },
    { t: "fill", lv: "C", q: "Let me give you a ___ of advice: always check your work. (piece / bowl)", a: ["piece"], why: "We count advice using a piece: a piece of advice." },
    { t: "fill", lv: "C", q: "I can lend you ___ money because I have some left. (a little / little)", a: ["a little"], why: "A little means some, enough to share. Little would mean almost none." },
    { t: "trans", lv: "C", q: "Correct the sentence: She gave me many good advices.", a: ["She gave me a lot of good advice.", "She gave me some good advice.", "She gave me lots of good advice."], why: "Advice is uncountable: no s, and we use a lot of or some instead of many." }
  ]
});

/* ---------- 3. Collective nouns ---------- */
window.VG.push({
  id: "en-g-collective",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Collective nouns",
  lv: "B",
  intro: "A collective noun is one word for a whole group, like a team, a class or a flock of birds. Using the right group word makes your writing sound precise.",
  rules: [
    { h: "Groups of animals", html: "a <b>flock</b> of birds / sheep<br>a <b>herd</b> of cows / elephants<br>a <b>school</b> of fish (also a <b>shoal</b> of fish)<br>a <b>swarm</b> of bees / ants<br>a <b>pack</b> of wolves<br>a <b>pride</b> of lions<br>a <b>litter</b> of puppies / kittens" },
    { h: "Groups of people", html: "a <b>class</b> of pupils<br>a <b>team</b> of players<br>a <b>crowd</b> of people / spectators<br>a <b>band</b> of musicians<br>a <b>choir</b> of singers<br>a <b>crew</b> of sailors<br>an <b>audience</b> (people watching a show)" },
    { h: "Groups of things", html: "a <b>bunch</b> of flowers / keys / grapes / bananas<br>a <b>pair</b> of shoes / socks<br>a <b>stack</b> or <b>pile</b> of books<br>a <b>fleet</b> of ships / buses<br>a <b>set</b> of tools / stamps<br>a <b>bouquet</b> of flowers" },
    { h: "The group acting as one: singular verb", html: "When the group does something together as one unit, use a <b>singular</b> verb. This is what your school exercises usually expect.<br>✓ The class <b>is</b> going on a learning journey.<br>✓ Our team <b>has</b> won the match.<br>✓ The choir <b>sings</b> every Friday." },
    { h: "'A ___ of ___': look at the group word", html: "In <b>a flock of birds</b>, the main noun is <b>flock</b> (one group), so the verb is singular.<br>✓ A flock of birds <b>is</b> flying over the field.<br>✓ A bunch of keys <b>was</b> found in the canteen.<br>✓ A swarm of bees <b>has</b> built a hive in the tree." },
    { h: "More than one group: plural verb", html: "If there are two or more groups, the collective noun becomes plural and the verb is plural.<br>✓ Two <b>teams are</b> playing in the final.<br>✓ All the <b>classes have</b> gone to the hall." },
    { h: "Pronouns for a group acting as one", html: "Use <b>it</b> and <b>its</b> for a group acting as one unit.<br>✓ The team celebrated <b>its</b> win.<br>✓ The committee gave <b>its</b> answer." }
  ],
  words: [],
  mistakes: [
    { wrong: "A flock of birds are flying over the field.", right: "A flock of birds is flying over the field.", why: "The main noun is flock (one group), so use is." },
    { wrong: "Our class are going to the Science Centre.", right: "Our class is going to the Science Centre.", why: "The class is going together as one group, so use a singular verb." },
    { wrong: "A herd of fish swam past the boat.", right: "A school of fish swam past the boat.", why: "Fish move in a school (or shoal). A herd is for animals like cows and elephants." },
    { wrong: "Kumar found a bunch of key on the floor.", right: "Kumar found a bunch of keys on the floor.", why: "After a bunch of, the noun is plural: keys." },
  ],
  items: [
    { t: "mcq", lv: "A", q: "A ___ of birds flew over the playground.", o: ["flock", "herd", "litter"], a: 0, why: "Birds fly together in a flock." },
    { t: "mcq", lv: "A", q: "Mum bought a ___ of bananas at the market.", o: ["pack", "bunch", "crowd"], a: 1, why: "Bananas grow and are sold in a bunch." },
    { t: "mcq", lv: "A", q: "I need a new ___ of socks for school.", o: ["pair", "fleet", "swarm"], a: 0, why: "Socks come in twos, so we say a pair of socks." },
    { t: "mcq", lv: "A", q: "Our cat gave birth to a ___ of kittens.", o: ["litter", "herd", "choir"], a: 0, why: "Baby animals born together are called a litter." },
    { t: "mcq", lv: "A", q: "A ___ of bees buzzed around the flowers.", o: ["bunch", "swarm", "pair"], a: 1, why: "Bees fly together in a swarm." },
    { t: "mcq", lv: "B", q: "We saw a ___ of elephants at the Night Safari.", o: ["herd", "flock", "school", "bunch"], a: 0, why: "Large animals like elephants and cows move in a herd." },
    { t: "mcq", lv: "B", q: "A ___ of fish swam past us at the aquarium.", o: ["herd", "pack", "school", "crew"], a: 2, why: "Fish swim together in a school (or shoal)." },
    { t: "mcq", lv: "B", q: "A ___ of lions rested under the tree.", o: ["pride", "flock", "litter", "swarm"], a: 0, why: "A group of lions is called a pride." },
    { t: "mcq", lv: "B", q: "A ___ of wolves howled at the moon.", o: ["pack", "school", "herd", "bunch"], a: 0, why: "Wolves hunt and live in a pack." },
    { t: "mcq", lv: "B", q: "A large ___ cheered when Singapore scored a goal.", o: ["crowd", "fleet", "litter", "flock"], a: 0, why: "Many people gathered together are a crowd." },
    { t: "mcq", lv: "B", q: "A ___ of buses waits at the depot every night.", o: ["fleet", "herd", "choir", "pride"], a: 0, why: "A group of vehicles like buses or ships is a fleet." },
    { t: "mcq", lv: "B", q: "The ___ of the ship worked hard during the storm.", o: ["crew", "crowd", "flock", "team"], a: 0, why: "The people who work on a ship are its crew." },
    { t: "mcq", lv: "B", q: "Our class ___ going to the Science Centre tomorrow.", o: ["is", "are", "were", "have"], a: 0, why: "The class is going together as one group, so use the singular verb is." },
    { t: "mcq", lv: "B", q: "A flock of birds ___ resting on the rooftop.", o: ["are", "is", "were", "have been"], a: 1, why: "The main noun is flock, which is one group, so use is." },
    { t: "mcq", lv: "B", q: "Our school team ___ won the netball match!", o: ["have", "has", "are", "were"], a: 1, why: "The team won as one group, so use the singular has." },
    { t: "mcq", lv: "B", q: "A bunch of keys ___ found in the school canteen.", o: ["were", "was", "are", "have"], a: 1, why: "The main noun is bunch (one bunch), so use was." },
    { t: "mcq", lv: "C", q: "Two teams ___ playing in the final this afternoon.", o: ["is", "are", "was", "has"], a: 1, why: "There are two teams (more than one group), so use the plural are." },
    { t: "mcq", lv: "C", q: "The choir ___ every Friday after school.", o: ["practise", "practises", "practising", "are practise"], a: 1, why: "The choir practises as one group, so the verb takes s: practises." },
    { t: "mcq", lv: "C", q: "The team was proud of ___ trophy.", o: ["its", "it's", "their's", "it"], a: 0, why: "The team acts as one unit, so we use its (no apostrophe for owning)." },
    { t: "fix", lv: "A", q: "A herd of fish swam under the bridge.", err: "herd", a: ["school", "shoal"], why: "Fish swim in a school (or shoal). A herd is for cows or elephants." },
    { t: "fix", lv: "B", q: "Dad bought Mum a bunch of flower for her birthday.", err: "flower", a: "flowers", why: "After a bunch of, the noun is plural: flowers." },
    { t: "fix", lv: "B", q: "A swarm of ants are marching towards the sugar.", err: "are", a: "is", why: "The main noun is swarm (one group), so use is." },
    { t: "fix", lv: "B", q: "A crowd of fans are waiting outside the stadium.", err: "are", a: "is", why: "The main noun is crowd (one group), so use is." },
    { t: "fix", lv: "C", q: "All the class in the school have gone to the hall for assembly.", err: "class", a: "classes", why: "All means more than one class, so the noun must be plural: classes." },
    { t: "fix", lv: "C", q: "A pack of wolf chased the deer in the documentary.", err: "wolf", a: "wolves", why: "After a pack of, the noun is plural. Wolf → wolves." },
    { t: "fill", lv: "A", q: "The farmer has a ___ of sheep on the hill. (flock / school)", a: ["flock"], why: "Sheep move together in a flock." },
    { t: "fill", lv: "A", q: "Siti carried a ___ of books to the library. (pile / pride)", a: ["pile"], why: "Books placed on top of one another make a pile." },
    { t: "fill", lv: "B", q: "The ___ of cows walked slowly to the river. (herd / swarm)", a: ["herd"], why: "Cows move together in a herd." },
    { t: "fill", lv: "B", q: "The ___ sang beautifully at the National Day concert. (choir / crew)", a: ["choir"], why: "A group of singers is a choir." },
    { t: "fill", lv: "C", q: "The class ___ (have / has) finished its project on recycling.", a: ["has"], why: "The class worked as one unit (notice its), so use has." },
    { t: "fill", lv: "C", q: "A pride of lions ___ (was / were) sleeping in the shade.", a: ["was"], why: "The main noun is pride, which is one group, so use was." },
    { t: "trans", lv: "C", q: "Rewrite using a collective noun: Many bees were flying around the hive.", a: ["A swarm of bees was flying around the hive."], why: "A swarm of bees is one group, so the verb becomes singular: was." }
  ]
});

/* ---------- 4. Articles ---------- */
window.VG.push({
  id: "en-g-articles",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Articles: a, an, the",
  lv: "A",
  intro: "A, an and the are small words that come before nouns. Choosing the right one makes your sentences sound correct and clear.",
  rules: [
    { h: "a: before a consonant sound", html: "<b>a</b> cat, <b>a</b> bus, <b>a</b> durian, <b>a</b> red apple<br>Use a or an for <b>one</b> thing that is not special or not yet known." },
    { h: "an: before a vowel sound", html: "<b>an</b> apple, <b>an</b> egg, <b>an</b> ice cream, <b>an</b> owl, <b>an</b> umbrella<br>Vowel letters: a, e, i, o, u." },
    { h: "Listen to the sound, not the letter", html: "<b>an hour</b> (h is silent, sounds like 'our')<br><b>an honest</b> boy<br><b>a uniform</b>, <b>a university</b> (sounds like 'you')<br><b>a one-dollar</b> coin (sounds like 'won')<br><b>an MRT station</b> (M sounds like 'em')" },
    { h: "Look at the next word", html: "The article matches the word right after it.<br><b>an</b> apple → <b>a</b> big apple<br><b>a</b> egg ✗ → <b>an</b> egg ✓ → <b>a</b> boiled egg ✓" },
    { h: "the: a particular or known thing", html: "Use <b>the</b> when we know which one.<br>I saw <b>a</b> dog. <b>The</b> dog was barking. (second time: now we know which dog)<br>Please close <b>the</b> door. (the door of this room)" },
    { h: "the: only one in the world", html: "<b>the</b> sun, <b>the</b> moon, <b>the</b> sky, <b>the</b> sea<br>Also: <b>the</b> best, <b>the</b> tallest, <b>the</b> first." },
    { h: "No article", html: "No article before most names, plural nouns and uncountable nouns in general.<br>✓ I like <b>cats</b>. ✓ <b>Water</b> is important. ✓ We go to <b>school</b> by MRT.<br>✗ I like the cats. (when you mean all cats in general)" }
  ],
  words: [],
  mistakes: [
    { wrong: "I ate a apple during recess.", right: "I ate an apple during recess.", why: "Apple starts with a vowel sound, so use an." },
    { wrong: "We waited for a hour.", right: "We waited for an hour.", why: "The h in hour is silent, so it starts with a vowel sound: an hour." },
    { wrong: "Every pupil must wear an uniform.", right: "Every pupil must wear a uniform.", why: "Uniform starts with a 'you' sound, which is a consonant sound: a uniform." },
    { wrong: "Look at a moon tonight!", right: "Look at the moon tonight!", why: "There is only one moon, so use the." },
    { wrong: "I saw a cat. A cat was sleeping.", right: "I saw a cat. The cat was sleeping.", why: "The second time, we already know which cat, so use the." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "I ate ___ banana for breakfast.", o: ["a", "an", "many"], a: 0, why: "Banana starts with a consonant sound (b), so use a." },
    { t: "mcq", lv: "A", q: "Wei Ling has ___ orange in her lunch box.", o: ["a", "an", "many"], a: 1, why: "Orange starts with a vowel sound (o), so use an." },
    { t: "mcq", lv: "A", q: "There is ___ elephant at the zoo.", o: ["a", "an", "many"], a: 1, why: "Elephant starts with a vowel sound (e), so use an." },
    { t: "mcq", lv: "A", q: "Please bring ___ umbrella. It may rain.", o: ["a", "an", "many"], a: 1, why: "Umbrella starts with a vowel sound (u as in 'up'), so use an." },
    { t: "mcq", lv: "A", q: "___ sun is very hot today.", o: ["A", "An", "The"], a: 2, why: "There is only one sun, so use the." },
    { t: "mcq", lv: "A", q: "Hassan has ___ pet hamster.", o: ["a", "an", "many"], a: 0, why: "Pet starts with a consonant sound (p), so use a." },
    { t: "mcq", lv: "A", q: "I saw ___ owl in the storybook.", o: ["a", "an", "many"], a: 1, why: "Owl starts with a vowel sound, so use an." },
    { t: "mcq", lv: "A", q: "Dad bought ___ ice cream for me at the mall.", o: ["a", "an", "many"], a: 1, why: "Ice cream starts with a vowel sound (i), so use an." },
    { t: "mcq", lv: "B", q: "The movie lasted for ___ hour.", o: ["a", "an", "many", "few"], a: 1, why: "The h in hour is silent, so it begins with a vowel sound: an hour." },
    { t: "mcq", lv: "B", q: "My sister studies at ___ university.", o: ["a", "an", "some", "many"], a: 0, why: "University begins with a 'you' sound, which is a consonant sound, so use a." },
    { t: "mcq", lv: "B", q: "Every pupil must wear ___ uniform to school.", o: ["a", "an", "many", "some"], a: 0, why: "Uniform begins with a 'you' sound, so use a, not an." },
    { t: "mcq", lv: "B", q: "Priya is ___ honest girl who always tells the truth.", o: ["a", "an", "many", "few"], a: 1, why: "The h in honest is silent, so it starts with a vowel sound: an honest girl." },
    { t: "mcq", lv: "B", q: "Grandma gave me ___ old photo of her wedding.", o: ["a", "an", "many", "few"], a: 1, why: "The next word is old, which starts with a vowel sound, so use an." },
    { t: "mcq", lv: "B", q: "Ahmad ate ___ big apple.", o: ["a", "an", "some", "many"], a: 0, why: "Look at the next word: big starts with a consonant sound, so use a." },
    { t: "mcq", lv: "B", q: "I saw a dog at the void deck. ___ dog was wagging its tail.", o: ["A", "An", "The", "Some"], a: 2, why: "The second time we mention the dog, we know which dog, so use the." },
    { t: "mcq", lv: "B", q: "Mount Everest is ___ highest mountain in the world.", o: ["a", "an", "the", "some"], a: 2, why: "With words like highest, best and tallest, we use the." },
    { t: "mcq", lv: "C", q: "We alighted at ___ MRT station near the museum.", o: ["a", "an", "few", "many"], a: 1, why: "MRT is said letter by letter, and M sounds like 'em', a vowel sound. So use an." },
    { t: "mcq", lv: "C", q: "I paid for the sweet with ___ one-dollar coin.", o: ["a", "an", "many", "few"], a: 0, why: "One sounds like 'won', which starts with a consonant sound, so use a." },
    { t: "mcq", lv: "C", q: "Which sentence correctly says that you like ALL cats in general?", o: ["I like the cats.", "I like cats.", "I like a cats.", "I like an cats."], a: 1, why: "When we talk about cats in general, we use no article: I like cats. (I like the cats means some particular cats.)" },
    { t: "fix", lv: "A", q: "Mum gave me a egg for breakfast.", err: "a egg", a: "an egg", why: "Egg starts with a vowel sound, so use an." },
    { t: "fix", lv: "A", q: "Look at a moon! It is so round tonight.", err: "a moon", a: "the moon", why: "There is only one moon, so use the." },
    { t: "fix", lv: "B", q: "We had to wait for a hour at the clinic.", err: "a hour", a: "an hour", why: "Hour has a silent h, so it starts with a vowel sound: an hour." },
    { t: "fix", lv: "B", q: "Jia Hui bought an new pencil case.", err: "an new", a: "a new", why: "The next word is new, which starts with a consonant sound, so use a." },
    { t: "fix", lv: "C", q: "My cousin wants to go to an university overseas.", err: "an university", a: "a university", why: "University starts with a 'you' sound, which is a consonant sound, so use a." },
    { t: "fix", lv: "C", q: "Daniel found a wallet. He gave a wallet to the teacher.", err: "gave a wallet", a: ["gave the wallet", "gave it"], why: "The second time, we know which wallet, so use the." },
    { t: "fill", lv: "A", q: "I want to be ___ astronaut when I grow up. (a / an)", a: ["an"], why: "Astronaut starts with a vowel sound, so use an." },
    { t: "fill", lv: "A", q: "There is ___ cat on the wall. (a / an)", a: ["a"], why: "Cat starts with a consonant sound, so use a." },
    { t: "fill", lv: "B", q: "Please switch off ___ fan before you leave the classroom. (a / the)", a: ["the"], why: "We know which fan: the one in this classroom. So use the." },
    { t: "fill", lv: "B", q: "Nurul drew ___ octopus in her art book. (a / an)", a: ["an"], why: "Octopus starts with a vowel sound, so use an." },
    { t: "fill", lv: "C", q: "It was ___ honour to meet the President. (a / an)", a: ["an"], why: "The h in honour is silent, so it starts with a vowel sound: an honour." },
    { t: "fill", lv: "C", q: "Siew Mei is ___ tallest girl in our class. (a / the)", a: ["the"], why: "With tallest, best or first, we use the." },
    { t: "trans", lv: "B", q: "Join with an article: I saw a bird. The bird was blue. (Use one sentence starting 'The bird I saw')", a: ["The bird I saw was blue.", "The bird that I saw was blue.", "The bird which I saw was blue."], why: "Once we know which bird (the one I saw), we use the." }
  ]
});

/* ---------- 5. Apostrophes for owning ---------- */
window.VG.push({
  id: "en-g-possessive",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Apostrophes for owning",
  lv: "B",
  intro: "An apostrophe (') with s shows that something belongs to someone: Ali's bag. Putting it in the right place tells the reader whether one person or many people own it.",
  rules: [
    { h: "One owner: add 's", html: "the girl<b>'s</b> bag (one girl)<br>my sister<b>'s</b> bicycle<br>the teacher<b>'s</b> desk<br>Wei Jie<b>'s</b> water bottle" },
    { h: "Plural owners ending in s: add ' only", html: "the girl<b>s'</b> toilet (many girls)<br>the pupil<b>s'</b> books (many pupils)<br>my parent<b>s'</b> room (both parents)" },
    { h: "Irregular plurals not ending in s: add 's", html: "the <b>children's</b> playground<br>the <b>men's</b> changing room<br>the <b>women's</b> team<br>the <b>people's</b> choice<br>✗ childrens' ✗ childrens" },
    { h: "Step by step", html: "1. Write the owner word first (girl, girls, children).<br>2. Does it end in s and is it plural? Add <b>'</b> only.<br>3. Otherwise, add <b>'s</b>." },
    { h: "its and it's", html: "<b>its</b> = belonging to it (no apostrophe): The cat licked <b>its</b> paw.<br><b>it's</b> = it is or it has: <b>It's</b> raining. <b>It's</b> been a long day.<br>Test: can you say 'it is'? If yes, write it's." },
    { h: "No apostrophe in ordinary plurals", html: "✓ I bought three apples. ✗ I bought three apple's.<br>✓ The boys are playing. ✗ The boy's are playing.<br>Also no apostrophe in <b>his, hers, ours, yours, theirs</b>." }
  ],
  words: [],
  mistakes: [
    { wrong: "The dog wagged it's tail.", right: "The dog wagged its tail.", why: "Its (belonging to it) has no apostrophe. It's means it is." },
    { wrong: "Its raining outside.", right: "It's raining outside.", why: "This means it is raining, so it needs an apostrophe: it's." },
    { wrong: "The childrens' toys are in the box.", right: "The children's toys are in the box.", why: "Children does not end in s, so add 's: children's." },
    { wrong: "Mum sells cake's at the school fair.", right: "Mum sells cakes at the school fair.", why: "Cakes is just a plural. Nothing is owned, so no apostrophe." },
    { wrong: "This is my brothers room. He keeps it tidy.", right: "This is my brother's room. He keeps it tidy.", why: "The room belongs to one brother (he), so add 's." },
    { wrong: "The pencil case is your's.", right: "The pencil case is yours.", why: "Yours never takes an apostrophe. Neither do his, hers, ours or theirs." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "This is ___ pencil case.", o: ["Ali's", "Alis", "Alis'"], a: 0, why: "The pencil case belongs to Ali, one person, so add 's." },
    { t: "mcq", lv: "A", q: "The ___ tail is very fluffy.", o: ["cats", "cat's", "cats's"], a: 1, why: "The tail belongs to one cat, so write cat's." },
    { t: "mcq", lv: "A", q: "I borrowed my ___ storybook.", o: ["sister's", "sisters", "sister"], a: 0, why: "The storybook belongs to my sister, so add 's." },
    { t: "mcq", lv: "B", q: "The dog chased ___ own tail.", o: ["its", "it's", "its'", "it is"], a: 0, why: "Its (no apostrophe) means belonging to it." },
    { t: "mcq", lv: "B", q: "___ very hot today. Drink more water!", o: ["Its", "It's", "Its'", "It"], a: 1, why: "We mean it is very hot, so write it's." },
    { t: "mcq", lv: "B", q: "The ___ playground at the park has a new slide.", o: ["childrens", "childrens'", "children's", "childs'"], a: 2, why: "Children does not end in s, so add 's: children's." },
    { t: "mcq", lv: "B", q: "All the ___ bags are in the classroom. (many pupils)", o: ["pupil's", "pupils'", "pupils's", "pupils"], a: 1, why: "Many pupils own the bags. Pupils ends in s, so add ' only: pupils'." },
    { t: "mcq", lv: "B", q: "The ___ bag is on the chair. (one pupil)", o: ["pupil's", "pupils'", "pupils", "pupil"], a: 0, why: "One pupil owns the bag, so add 's: pupil's." },
    { t: "mcq", lv: "B", q: "My ___ room is next to mine. (Mum and Dad)", o: ["parent's", "parents'", "parents", "parents's"], a: 1, why: "Two parents share the room. Parents ends in s, so add ' only: parents'." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["I bought three apple's.", "I bought three apples.", "I bought three apples'.", "I bought three apple'."], a: 1, why: "Apples is just a plural. Nothing is owned, so no apostrophe." },
    { t: "mcq", lv: "B", q: "Is this water bottle ___?", o: ["your's", "yours", "yours'", "you's"], a: 1, why: "Yours never takes an apostrophe." },
    { t: "mcq", lv: "C", q: "The ___ toilet is on the second floor. (for all the boys)", o: ["boy's", "boys'", "boys", "boys's"], a: 1, why: "The toilet is for many boys. Boys ends in s, so add ' only." },
    { t: "mcq", lv: "C", q: "The ___ team won the relay at Sports Day.", o: ["womens", "women's", "womens'", "woman's'"], a: 1, why: "Women does not end in s, so add 's: women's." },
    { t: "mcq", lv: "C", q: "___ been a long day at school.", o: ["Its", "It's", "Its'", "It"], a: 1, why: "It has been → it's. It's can mean it is or it has." },
    { t: "mcq", lv: "C", q: "The school changed ___ timetable this term.", o: ["it's", "its", "its'", "it is"], a: 1, why: "The timetable belongs to the school, so use its (no apostrophe)." },
    { t: "mcq", lv: "C", q: "Which sentence is punctuated correctly?", o: ["The teachers' room is upstairs.", "The teacher's' room is upstairs.", "The teachers room's upstairs.", "The teachers's room is upstairs."], a: 0, why: "The room belongs to many teachers. Teachers ends in s, so add ' only: teachers'." },
    { t: "mcq", lv: "C", q: "The ___ tails were all wagging. (three dogs)", o: ["dog's", "dogs'", "dogs", "dogs's"], a: 1, why: "Three dogs own the tails. Dogs ends in s, so add ' only: dogs'." },
    { t: "mcq", lv: "C", q: "The ___ changing room is next to the pool.", o: ["mens'", "men's", "mens", "man's'"], a: 1, why: "Men does not end in s, so add 's: men's." },
    { t: "fix", lv: "A", q: "This is my brothers room and he keeps it tidy.", err: "brothers", a: "brother's", why: "The room belongs to one brother (he), so add 's: brother's." },
    { t: "fix", lv: "B", q: "The bird flapped it's wings.", err: "it's", a: "its", why: "Its (belonging to it) has no apostrophe. It's means it is." },
    { t: "fix", lv: "B", q: "Its time to go home now.", err: "Its", a: ["It's", "It is"], why: "We mean it is time, so write it's." },
    { t: "fix", lv: "B", q: "Auntie sells curry puff's at the pasar malam.", err: "puff's", a: "puffs", why: "Puffs is just a plural. Nothing is owned, so no apostrophe." },
    { t: "fix", lv: "C", q: "The childrens' artwork is on the wall.", err: "childrens'", a: "children's", why: "Children does not end in s, so add 's: children's." },
    { t: "fix", lv: "C", q: "The answer sheet is their's, not ours.", err: "their's", a: "theirs", why: "Theirs never takes an apostrophe." },
    { t: "fill", lv: "A", q: "That is ___ (Mei) red umbrella.", a: ["Mei's"], why: "The umbrella belongs to Mei, so add 's: Mei's." },
    { t: "fill", lv: "A", q: "The ___ (baby) milk bottle is on the table.", a: ["baby's"], why: "One baby owns the bottle, so add 's: baby's." },
    { t: "fill", lv: "B", q: "The ___ (teacher) desk is very tidy. (one teacher)", a: ["teacher's"], why: "One teacher owns the desk, so add 's: teacher's." },
    { t: "fill", lv: "B", q: "The cat is licking ___ paw. (its / it's)", a: ["its"], why: "The paw belongs to the cat, so use its (no apostrophe)." },
    { t: "fill", lv: "C", q: "The ___ (girls) hockey team trains on Tuesdays. (the team for many girls)", a: ["girls'"], why: "Many girls share the team. Girls ends in s, so add ' only: girls'." },
    { t: "fill", lv: "C", q: "We read the ___ (people) letters to the newspaper.", a: ["people's"], why: "People does not end in s, so add 's: people's." },
    { t: "trans", lv: "B", q: "Rewrite using an apostrophe: the bicycle that belongs to Arjun", a: ["Arjun's bicycle"], why: "One owner (Arjun), so add 's." },
    { t: "trans", lv: "C", q: "Rewrite using an apostrophe: the shoes that belong to the children", a: ["the children's shoes", "The children's shoes"], why: "Children does not end in s, so add 's: the children's shoes." }
  ]
});
