window.VG = window.VG || [];

window.VG.push({
  id: "en-v-phrasal2",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Phrasal verbs 2: come across, carry on, turn down, break down, get along with…",
  lv: "C",
  intro: "A phrasal verb is a verb plus a small word like up, down, off or on. Together they make a NEW meaning, so you must learn them as a team.",
  rules: [
    {"h":"Two words, one meaning","html":"<b>turn down</b> an offer = say no to it. <br>It is not about turning anything downwards! Learn the whole phrase as one word."},
    {"h":"The small word changes everything","html":"<b>put on</b> a jacket (wear it) <br><b>put off</b> a trip (do it later) <br><b>put up with</b> noise (accept something annoying)"},
    {"h":"Some can be split","html":"✓ She <b>turned down</b> the offer. <br>✓ She <b>turned</b> the offer <b>down</b>. <br>✓ She <b>turned it down</b>. <br>✗ She turned down it. (With it, them, him, put the small word after.)"},
    {"h":"Some cannot be split","html":"✓ I <b>came across</b> an old photo. <br>✗ I came an old photo across. <br><b>look after</b>, <b>come across</b>, <b>get along with</b> and <b>run out of</b> always stay together."},
    {"h":"Change the verb, not the small word","html":"Tenses change the verb only: <b>break down</b> → <b>broke down</b> → <b>has broken down</b>. The small word stays the same."}
  ],
  words: [
    {"w":"come across","m":"find or meet by chance","ex":"While tidying the cupboard, Mei Ling came across her old kindergarten photo."},
    {"w":"carry on","m":"continue doing something","ex":"Carry on reading while I fetch the worksheets."},
    {"w":"turn down","m":"say no to an offer or request; also make quieter","ex":"Arjun turned down the second plate of chicken rice because he was full."},
    {"w":"break down","m":"stop working (a machine); or start crying","ex":"Our bus broke down on the PIE, so we were late for school."},
    {"w":"get along with","m":"have a friendly relationship with","ex":"Siti gets along with everyone in her CCA."},
    {"w":"look after","m":"take care of","ex":"Grandma looks after my baby brother while my parents are at work."},
    {"w":"look forward to","m":"feel excited about something that will happen","ex":"We are looking forward to the school holidays."},
    {"w":"put off","m":"delay; do later","ex":"The sports day was put off because of the thunderstorm."},
    {"w":"give up","m":"stop trying; or stop a habit","ex":"Wei Jie never gives up, even when a maths problem is hard."},
    {"w":"run out of","m":"have no more left","ex":"The printer ran out of paper in the middle of my project."},
    {"w":"set off","m":"start a journey","ex":"We set off for the zoo at eight o'clock."},
    {"w":"take after","m":"look or behave like an older family member","ex":"Priya takes after her mother. They both love to sing."},
    {"w":"call off","m":"cancel","ex":"The match was called off because of lightning."},
    {"w":"bring up","m":"raise a child; or mention a topic","ex":"Ahmad was brought up by his grandparents in Tampines."},
    {"w":"find out","m":"discover a fact","ex":"Ben found out that the canteen sells mango ice cream."},
    {"w":"look up","m":"search for information in a dictionary or online","ex":"Look up the meaning of the word in your dictionary."},
    {"w":"put up with","m":"accept something unpleasant without complaining","ex":"We had to put up with the drilling noise from the flat upstairs."},
    {"w":"turn up","m":"arrive or appear; or make louder","ex":"Only five pupils turned up for the early practice."},
    {"w":"pass away","m":"die (a gentle, polite way to say it)","ex":"Our neighbour's old cat passed away last week."},
    {"w":"make up","m":"become friends again after a quarrel; or invent a story","ex":"Jun Hao and Kumar argued, but they made up after recess."}
  ],
  mistakes: [
    {"wrong":"She turned down it.","right":"She turned it down.","why":"With it, them or him, the small word goes after: turned it down."},
    {"wrong":"I am looking forward to go to the zoo.","right":"I am looking forward to going to the zoo.","why":"In look forward to, the word to is followed by an -ing verb."},
    {"wrong":"We run out of milk yesterday.","right":"We ran out of milk yesterday.","why":"Yesterday means past, so change the verb: run → ran. The small words stay."},
    {"wrong":"I came the old diary across.","right":"I came across the old diary.","why":"Come across cannot be split. Keep the two words together."},
    {"wrong":"Lina gets along her cousin.","right":"Lina gets along with her cousin.","why":"Get along needs with before the person."}
  ],
  items: [
    {"t":"mcq","lv":"B","q":"While cleaning my room, I ___ a ten-dollar note under the bed.","o":["carried on","turned down","broke down","came across"],"a":3,"why":"Come across means to find something by chance. You were not looking for the note, you just found it."},
    {"t":"mcq","lv":"B","q":"Our car ___ on the way to Sentosa, so we called for help.","o":["set off","turned up","broke down","gave up"],"a":2,"why":"When a machine or car stops working, we say it broke down."},
    {"t":"mcq","lv":"B","q":"Mr Tan told us to ___ with our work while he answered the phone.","o":["call off","carry on","put off","look up"],"a":1,"why":"Carry on means continue. The class should keep working."},
    {"t":"mcq","lv":"C","q":"Hui Min ___ the invitation to the party because she had a piano exam.","o":["turned down","turned up","came across","took after"],"a":0,"why":"Turn down an invitation means say no to it. She could not go because of her exam."},
    {"t":"mcq","lv":"B","q":"Do you ___ your new classmates?","o":["get up","get off","get over","get along with"],"a":3,"why":"Get along with someone means you are friendly with them and do not quarrel."},
    {"t":"mcq","lv":"A","q":"Can you ___ my goldfish while I am away?","o":["look up","look out","look after"],"a":2,"why":"Look after means take care of. The goldfish needs someone to feed it."},
    {"t":"mcq","lv":"B","q":"The football match was ___ because of heavy rain. It will not happen at all.","o":["carried on","called off","set off","found out"],"a":1,"why":"Call off means cancel. The match will not take place."},
    {"t":"mcq","lv":"C","q":"The meeting was ___ until next Friday.","o":["put off","put up with","given up","broken down"],"a":0,"why":"Put off means delay. The meeting will still happen, just later."},
    {"t":"mcq","lv":"B","q":"We ___ early in the morning to catch the first ferry to Pulau Ubin.","o":["turned down","took after","made up","set off"],"a":3,"why":"Set off means start a journey."},
    {"t":"mcq","lv":"B","q":"Dad has the same curly hair as Grandpa. He really ___ him.","o":["looks after","gets along with","takes after","comes across"],"a":2,"why":"Take after means look or act like an older family member, such as a parent or grandparent."},
    {"t":"mcq","lv":"C","q":"My sister and I quarrelled, but we ___ before dinner.","o":["made out","made up","broke down","called off"],"a":1,"why":"Make up means become friends again after a quarrel."},
    {"t":"mcq","lv":"B","q":"Hurry! We have almost ___ time.","o":["run out of","run into","run after","run over"],"a":0,"why":"Run out of means have none left. There is hardly any time left."},
    {"t":"mcq","lv":"C","q":"How can you ___ such a noisy neighbour? I would complain!","o":["put off","turn up","carry on","put up with"],"a":3,"why":"Put up with means accept something annoying without complaining."},
    {"t":"mcq","lv":"C","q":"Which sentence is correct?","o":["She turned down it.","She down turned it.","She turned it down.","She turned it downs."],"a":2,"why":"When the object is it, put it between the verb and the small word: turned it down."},
    {"t":"mcq","lv":"B","q":"Rahim wanted to ___ how many legs a spider has, so he searched online.","o":["carry on","find out","give up","set off"],"a":1,"why":"Find out means discover a fact you did not know."},
    {"t":"mcq","lv":"C","q":"When she heard that her hamster was gone, Amy ___ and cried for a long time.","o":["broke down","broke up","turned up","set off"],"a":0,"why":"Break down can also mean start crying because you are very upset."},
    {"t":"mcq","lv":"B","q":"Only three people ___ for the beach clean-up because it was raining.","o":["turned down","looked after","took after","turned up"],"a":3,"why":"Turn up means arrive or come. Only three people came."},
    {"t":"mcq","lv":"C","q":"The music is too loud. Please ___ the volume.","o":["turn up","come across","turn down","carry on"],"a":2,"why":"Turn down the volume means make it quieter. Turn up would make it louder."},
    {"t":"mcq","lv":"B","q":"Don't ___! You can solve this puzzle if you keep trying.","o":["look up","give up","set off","turn up"],"a":1,"why":"Give up means stop trying. The speaker wants you to keep going."},
    {"t":"fix","lv":"C","q":"I am looking forward to meet my pen pal.","err":"meet","a":"meeting","why":"After look forward to, use the -ing form: looking forward to meeting."},
    {"t":"fix","lv":"B","q":"Yesterday the lift break down and we had to take the stairs.","err":"break","a":"broke","why":"Yesterday is in the past, so break becomes broke. The word down stays the same."},
    {"t":"fix","lv":"B","q":"Nadia gets along her new neighbours very well.","err":"along","a":"along with","why":"The phrasal verb is get along with. You need with before the people."},
    {"t":"fix","lv":"C","q":"We have run out milk, so I will buy some.","err":"run out","a":"run out of","why":"The phrasal verb is run out of. You need of before the thing that is finished."},
    {"t":"fix","lv":"C","q":"The concert was called up because the singer was sick.","err":"called up","a":["called off", "cancelled"],"why":"Call off means cancel. Call up means telephone someone."},
    {"t":"fix","lv":"B","q":"Please look up your little brother while I cook.","err":"look up","a":["look after", "take care of", "watch", "mind"],"why":"Look after means take care of. Look up means search for information."},
    {"t":"fill","lv":"B","q":"If you do not know a word, ___ it up in the dictionary.","a":["look"],"why":"Look up means search for information in a dictionary or online."},
    {"t":"fill","lv":"B","q":"Grandma looks ___ my baby cousin every afternoon.","a":["after"],"why":"Look after means take care of someone."},
    {"t":"fill","lv":"C","q":"The trip was put ___ until next month because of the haze.","a":["off","back"],"why":"Put off (or put back) means delay. The trip will happen later."},
    {"t":"fill","lv":"C","q":"We set ___ for Malaysia at six in the morning.","a":["off","out"],"why":"Set off (or set out) means start a journey."},
    {"t":"fill","lv":"B","q":"Please carry ___ with your reading until the bell rings.","a":["on"],"why":"Carry on means continue doing something."},
    {"t":"fill","lv":"C","q":"I came ___ an interesting book about dinosaurs at the library.","a":["across","upon"],"why":"Come across (or come upon) means find something by chance."},
    {"t":"trans","lv":"C","q":"Rewrite using a phrasal verb with 'off': The principal cancelled the camp.","a":["The principal called off the camp.","The principal called the camp off."],"why":"Cancel = call off. Both word orders are correct because the object is a noun."},
    {"t":"trans","lv":"C","q":"Rewrite, replacing 'it' correctly: She turned down the offer. (Use 'it' instead of 'the offer'.)","a":["She turned it down."],"why":"With it, the small word goes after it: turned it down, not turned down it."}
  ]
});

window.VG.push({
  id: "en-v-idioms",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Idioms in context",
  lv: "B",
  intro: "An idiom is a group of words with a meaning that is different from the words themselves. If it is raining cats and dogs, no animals are falling from the sky! Idioms make your writing lively.",
  rules: [
    {"h":"Do not read idioms word by word","html":"<b>a piece of cake</b> = something very easy. <br>The test was a piece of cake. (No cake at all!)"},
    {"h":"Use the clues around the idiom","html":"Read the whole sentence. <br>She was <b>on cloud nine</b> after winning first prize. <br>Winning first prize → she was very happy."},
    {"h":"Keep the words exactly the same","html":"✓ <b>let the cat out of the bag</b> <br>✗ let the dog out of the bag <br>Idioms are fixed. Do not swap words."},
    {"h":"Change the verb for the tense","html":"Today I <b>break the ice</b>. Yesterday I <b>broke the ice</b>. Only the verb changes."},
    {"h":"Use idioms in stories, not too many","html":"One or two idioms make a composition lively. Too many make it sound strange. Formal letters usually do not use idioms."}
  ],
  words: [
    {"w":"a piece of cake","m":"very easy","ex":"The spelling test was a piece of cake for Hannah."},
    {"w":"under the weather","m":"feeling a little sick","ex":"Ravi stayed home because he was feeling under the weather."},
    {"w":"raining cats and dogs","m":"raining very heavily","ex":"It was raining cats and dogs, so recess was in the hall."},
    {"w":"break the ice","m":"say or do something to make people feel relaxed when they first meet","ex":"Our teacher played a game to break the ice on the first day."},
    {"w":"once in a blue moon","m":"very rarely","ex":"We eat at a fancy restaurant once in a blue moon."},
    {"w":"let the cat out of the bag","m":"tell a secret by mistake","ex":"Ming let the cat out of the bag about Mum's surprise party."},
    {"w":"spill the beans","m":"tell a secret","ex":"Come on, spill the beans! Who is the new class monitor?"},
    {"w":"cost an arm and a leg","m":"be very expensive","ex":"That new game console costs an arm and a leg."},
    {"w":"on cloud nine","m":"extremely happy","ex":"Aisha was on cloud nine when she got into the school choir."},
    {"w":"over the moon","m":"very happy and pleased","ex":"Dad was over the moon when his team won."},
    {"w":"in hot water","m":"in trouble","ex":"Kenji was in hot water for drawing on the classroom wall."},
    {"w":"keep an eye on","m":"watch carefully","ex":"Please keep an eye on my bag while I buy a drink."},
    {"w":"pull someone's leg","m":"tease or joke with someone","ex":"Don't worry, I'm just pulling your leg. There is no test today."},
    {"w":"see eye to eye","m":"agree with someone","ex":"My brother and I do not always see eye to eye about which show to watch."},
    {"w":"bite off more than you can chew","m":"try to do more than you are able to","ex":"Joining four CCAs was biting off more than he could chew."},
    {"w":"the last straw","m":"the final problem that makes someone lose patience","ex":"When the dog chewed her homework, it was the last straw."},
    {"w":"in the same boat","m":"in the same difficult situation as others","ex":"Don't worry, we are all in the same boat. Nobody finished the worksheet."},
    {"w":"get cold feet","m":"become nervous and want to back out","ex":"Lily got cold feet just before her solo performance."},
    {"w":"a blessing in disguise","m":"something that seems bad at first but turns out good","ex":"Missing the bus was a blessing in disguise, because I met my old friend at the stop."},
    {"w":"hit the books","m":"study hard","ex":"With exams next week, it is time to hit the books."},
    {"w":"lend a hand","m":"help","ex":"Could you lend a hand with these heavy boxes?"},
    {"w":"all ears","m":"listening eagerly","ex":"Tell me the story! I'm all ears."}
  ],
  mistakes: [
    {"wrong":"It is raining cats and puppies.","right":"It is raining cats and dogs.","why":"Idioms are fixed. Do not change any of the words."},
    {"wrong":"He let the dog out of the bag.","right":"He let the cat out of the bag.","why":"The idiom is always let the cat out of the bag."},
    {"wrong":"The test was a piece of cake, so I failed.","right":"The test was a piece of cake, so I did well.","why":"A piece of cake means very easy, so the result should be good."},
    {"wrong":"She was under the weather, so she ran a marathon.","right":"She was under the weather, so she stayed in bed.","why":"Under the weather means feeling sick. The rest of the sentence must match."}
  ],
  items: [
    {"t":"mcq","lv":"A","q":"The maths quiz was a piece of cake. The quiz was ___.","o":["very tasty","very easy","very long"],"a":1,"why":"A piece of cake means very easy. There is no real cake!"},
    {"t":"mcq","lv":"B","q":"Jia Hui is feeling under the weather today. She is ___.","o":["standing in the rain","very excited","feeling hot from the sun","a little sick"],"a":3,"why":"Under the weather means feeling a little unwell."},
    {"t":"mcq","lv":"A","q":"It is raining cats and dogs! This means it is raining ___.","o":["very heavily","a little","animals"],"a":0,"why":"Raining cats and dogs means raining very heavily."},
    {"t":"mcq","lv":"B","q":"Kai let the cat out of the bag about the surprise. What did Kai do?","o":["He set a cat free.","He told the secret by mistake.","He bought a present.","He kept the secret well."],"a":1,"why":"Let the cat out of the bag means to tell a secret by accident."},
    {"t":"mcq","lv":"B","q":"We go to the cinema once in a blue moon. How often do we go?","o":["very rarely","every week","every night","only when the moon is full"],"a":0,"why":"Once in a blue moon means very rarely."},
    {"t":"mcq","lv":"B","q":"Nurul was ___ when she won the art competition.","o":["under the weather","in hot water","in the same boat","on cloud nine"],"a":3,"why":"On cloud nine means extremely happy, which fits winning a prize."},
    {"t":"mcq","lv":"B","q":"Darren is ___ because he broke the window with his ball.","o":["on cloud nine","all ears","in hot water","a piece of cake"],"a":2,"why":"In hot water means in trouble. Breaking a window would get him into trouble."},
    {"t":"mcq","lv":"B","q":"That branded bag costs an arm and a leg. It is ___.","o":["very cheap","very expensive","very heavy","very small"],"a":1,"why":"Cost an arm and a leg means cost a lot of money."},
    {"t":"mcq","lv":"B","q":"Please ___ your little sister at the playground.","o":["keep an eye on","spill the beans on","pull the leg of","hit the books on"],"a":0,"why":"Keep an eye on means watch carefully."},
    {"t":"mcq","lv":"C","q":"\"There's no school tomorrow!\" said Sam. Then he laughed, \"I'm only ___.\"","o":["breaking the ice","under the weather","over the moon","pulling your leg"],"a":3,"why":"Pulling your leg means joking or teasing. Sam was not serious."},
    {"t":"mcq","lv":"C","q":"On the first day of camp, the leader told a funny story to ___.","o":["spill the beans","hit the books","break the ice","get cold feet"],"a":2,"why":"Break the ice means help strangers feel relaxed when they first meet."},
    {"t":"mcq","lv":"C","q":"Mei and her brother never ___ about which TV show to watch. They always argue.","o":["lend a hand","see eye to eye","keep an eye","hit the books"],"a":1,"why":"See eye to eye means agree. They always argue, so they do not agree."},
    {"t":"mcq","lv":"C","q":"Daniel signed up for five competitions in one week. He has ___.","o":["bitten off more than he can chew","let the cat out of the bag","broken the ice","been on cloud nine"],"a":0,"why":"Bite off more than you can chew means try to do too much."},
    {"t":"mcq","lv":"C","q":"My brother broke my pencil, took my eraser and then tore my book. That was ___!","o":["a piece of cake","a blessing in disguise","once in a blue moon","the last straw"],"a":3,"why":"The last straw is the final annoying thing that makes you lose patience."},
    {"t":"mcq","lv":"C","q":"Losing the race was a blessing in disguise. It means ___.","o":["it was a secret","it was very easy","it looked bad but turned out to be good","it made everyone angry"],"a":2,"why":"A blessing in disguise seems bad at first but brings something good later."},
    {"t":"mcq","lv":"B","q":"Nobody understood the new topic. We were all ___.","o":["on cloud nine","in the same boat","over the moon","all ears"],"a":1,"why":"In the same boat means in the same difficult situation as others."},
    {"t":"mcq","lv":"C","q":"Zara practised for weeks, but just before going on stage she ___ and wanted to go home.","o":["got cold feet","hit the books","saw eye to eye","kept an eye on it"],"a":0,"why":"Get cold feet means become nervous and want to back out."},
    {"t":"mcq","lv":"B","q":"\"Tell me what happened!\" said Grandma. \"I'm ___.\"","o":["in hot water","under the weather","in the same boat","all ears"],"a":3,"why":"All ears means listening eagerly."},
    {"t":"mcq","lv":"B","q":"The exams are next week. It is time to ___.","o":["spill the beans","break the ice","hit the books","pull someone's leg"],"a":2,"why":"Hit the books means study hard. It has nothing to do with hitting."},
    {"t":"fix","lv":"B","q":"It was raining cats and fish, so we stayed indoors.","err":"fish","a":"dogs","why":"The idiom is raining cats and dogs. Idioms never change their words."},
    {"t":"fix","lv":"B","q":"Oops! Wei let the dog out of the bag about the gift.","err":"dog","a":"cat","why":"The idiom is let the cat out of the bag, meaning tell a secret by mistake."},
    {"t":"fix","lv":"C","q":"The test was a piece of cake, so most of us found it very hard.","err":"hard","a":"easy","why":"A piece of cake means very easy, so the pupils should find it easy."},
    {"t":"fix","lv":"C","q":"Rina was over the moon when she lost her purse.","err":"lost","a":"found","why":"Over the moon means very happy. Finding your purse makes you happy, losing it does not."},
    {"t":"fix","lv":"C","q":"Can you lend a foot with these chairs?","err":"foot","a":"hand","why":"The idiom is lend a hand, which means help."},
    {"t":"fix","lv":"C","q":"Please keep an ear on the soup so it does not boil over.","err":"ear","a":"eye","why":"The idiom is keep an eye on, which means watch carefully."},
    {"t":"fill","lv":"B","q":"Come on, spill the ___! Who sent you the card?","a":["beans"],"why":"Spill the beans means tell a secret."},
    {"t":"fill","lv":"B","q":"When he scored the winning goal, Faris was over the ___.","a":["moon"],"why":"Over the moon means very happy."},
    {"t":"fill","lv":"B","q":"I'm feeling under the ___, so I will rest today.","a":["weather"],"why":"Under the weather means a little sick."},
    {"t":"fill","lv":"C","q":"We visit our cousins in Australia once in a blue ___.","a":["moon"],"why":"Once in a blue moon means very rarely."},
    {"t":"fill","lv":"C","q":"Don't worry about the mess. We are all in the same ___.","a":["boat"],"why":"In the same boat means in the same situation together."},
    {"t":"trans","lv":"C","q":"Rewrite using an idiom for 'very happy': Grace was very happy with her results.","a":["Grace was over the moon with her results.","Grace was on cloud nine with her results."],"why":"Over the moon and on cloud nine both mean very happy."}
  ]
});

window.VG.push({
  id: "en-v-proverbs",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Proverbs and sayings",
  lv: "C",
  intro: "A proverb is a short, well-known saying that gives wise advice. Using one at the end of a story is a neat way to show its lesson.",
  rules: [
    {"h":"A proverb gives a lesson","html":"<b>Practice makes perfect.</b> = If you keep practising, you get better."},
    {"h":"Look for the hidden meaning","html":"<b>Don't count your chickens before they hatch.</b> <br>It is not about chickens. It means: do not be sure of something good until it really happens."},
    {"h":"Match the proverb to the story","html":"A boy rushes his work and makes many mistakes → <b>Haste makes waste.</b> <br>Friends help a girl in trouble → <b>A friend in need is a friend indeed.</b>"},
    {"h":"Do not change the words","html":"✓ <b>The early bird catches the worm.</b> <br>✗ The early bird catches the insect."},
    {"h":"Use it well in a composition","html":"End your story with: <i>I learnt that honesty is the best policy.</i> Do not stuff in many proverbs."}
  ],
  words: [
    {"w":"Practice makes perfect.","m":"If you keep practising, you will get better.","ex":"Liam played the piece every day. Practice makes perfect."},
    {"w":"Don't count your chickens before they hatch.","m":"Do not be sure of a good result before it happens.","ex":"We are winning at half-time, but don't count your chickens before they hatch."},
    {"w":"Look before you leap.","m":"Think carefully before you act.","ex":"Read the whole question first. Look before you leap."},
    {"w":"The early bird catches the worm.","m":"People who start early get the best chances.","ex":"Mum queued at 7 a.m. for the sale. The early bird catches the worm."},
    {"w":"Actions speak louder than words.","m":"What you do matters more than what you say.","ex":"He promised to help, but never did. Actions speak louder than words."},
    {"w":"Many hands make light work.","m":"A job is easier when many people help.","ex":"Everyone helped to stack the chairs. Many hands make light work."},
    {"w":"Too many cooks spoil the broth.","m":"When too many people try to lead, the work goes wrong.","ex":"All six of us wanted to draw the poster. Too many cooks spoil the broth."},
    {"w":"Honesty is the best policy.","m":"Telling the truth is always the best choice.","ex":"Sara owned up to breaking the vase. Honesty is the best policy."},
    {"w":"Better late than never.","m":"It is better to do something late than not at all.","ex":"He finally said sorry a week later. Better late than never."},
    {"w":"Don't judge a book by its cover.","m":"Do not decide what someone is like from how they look.","ex":"The quiet new boy was the funniest of all. Don't judge a book by its cover."},
    {"w":"Where there's a will, there's a way.","m":"If you really want to do something, you will find a way.","ex":"She had no ball, so she made one from paper. Where there's a will, there's a way."},
    {"w":"A friend in need is a friend indeed.","m":"A true friend helps you when you are in trouble.","ex":"Ali shared his lunch when I forgot mine. A friend in need is a friend indeed."},
    {"w":"Slow and steady wins the race.","m":"Working carefully and steadily brings success.","ex":"He revised a little every day. Slow and steady wins the race."},
    {"w":"Every cloud has a silver lining.","m":"Something good can come from a bad situation.","ex":"I broke my leg, but I read twenty books. Every cloud has a silver lining."},
    {"w":"Birds of a feather flock together.","m":"People who are alike spend time together.","ex":"The three chess lovers always sit together. Birds of a feather flock together."},
    {"w":"Better safe than sorry.","m":"It is wiser to be careful than to risk trouble.","ex":"Bring an umbrella. Better safe than sorry."},
    {"w":"Rome wasn't built in a day.","m":"Big things take time and patience.","ex":"Learning the violin takes years. Rome wasn't built in a day."},
    {"w":"Two heads are better than one.","m":"Two people thinking together solve problems better.","ex":"Let's solve the riddle together. Two heads are better than one."},
    {"w":"Don't put all your eggs in one basket.","m":"Do not depend on just one plan or thing.","ex":"Apply to more than one CCA. Don't put all your eggs in one basket."},
    {"w":"Haste makes waste.","m":"Doing things too quickly leads to mistakes.","ex":"He rushed his test and made careless errors. Haste makes waste."},
    {"w":"Strike while the iron is hot.","m":"Act quickly while you have a good chance.","ex":"The teacher is in a good mood. Strike while the iron is hot and ask now."},
    {"w":"When in Rome, do as the Romans do.","m":"Follow the customs of the place you are visiting.","ex":"In Japan we took off our shoes indoors. When in Rome, do as the Romans do."}
  ],
  mistakes: [
    {"wrong":"The early bird catches the insect.","right":"The early bird catches the worm.","why":"Proverbs are fixed. Keep every word the same."},
    {"wrong":"Practise make perfect.","right":"Practice makes perfect.","why":"Here practice is a noun (spelt with c), and it needs makes."},
    {"wrong":"Many hands make heavy work.","right":"Many hands make light work.","why":"Light work means easy work. Many helpers make a job easier."},
    {"wrong":"Don't judge a cover by its book.","right":"Don't judge a book by its cover.","why":"The cover is the outside. Do not judge what is inside by the outside."}
  ],
  items: [
    {"t":"mcq","lv":"B","q":"Kumar practised his speech every night and gave a great talk. Which proverb fits?","o":["Too many cooks spoil the broth.","Practice makes perfect.","Better safe than sorry.","Birds of a feather flock together."],"a":1,"why":"He practised a lot and became very good. That is Practice makes perfect."},
    {"t":"mcq","lv":"C","q":"Hana spent her prize money before she even knew if she had won. What advice fits?","o":["Don't count your chickens before they hatch.","The early bird catches the worm.","Many hands make light work.","Two heads are better than one."],"a":0,"why":"She was sure of a good result before it happened. Don't count your chickens before they hatch."},
    {"t":"mcq","lv":"B","q":"The whole class helped to clean the classroom and finished in five minutes. Which proverb fits?","o":["Too many cooks spoil the broth.","Haste makes waste.","Look before you leap.","Many hands make light work."],"a":3,"why":"With many helpers, the job was quick and easy. Many hands make light work."},
    {"t":"mcq","lv":"C","q":"Five pupils all gave different orders while baking, and the cake was a disaster. Which proverb fits?","o":["Many hands make light work.","Practice makes perfect.","Too many cooks spoil the broth.","Better late than never."],"a":2,"why":"Too many people trying to lead spoilt the cake. Too many cooks spoil the broth."},
    {"t":"mcq","lv":"B","q":"Mrs Lim reached the bakery first and got the last pandan cake. Which proverb fits?","o":["Slow and steady wins the race.","The early bird catches the worm.","Rome wasn't built in a day.","Actions speak louder than words."],"a":1,"why":"She came early and got the best chance. The early bird catches the worm."},
    {"t":"mcq","lv":"B","q":"Ethan admitted that he broke the vase, and Mum was proud of him. Which proverb fits?","o":["Honesty is the best policy.","Haste makes waste.","Better safe than sorry.","Strike while the iron is hot."],"a":0,"why":"Telling the truth was the right choice. Honesty is the best policy."},
    {"t":"mcq","lv":"C","q":"Jun said he would help his grandmother, but he never did. Which proverb fits?","o":["Look before you leap.","Every cloud has a silver lining.","Two heads are better than one.","Actions speak louder than words."],"a":3,"why":"His words did not match his actions. What you do matters more. Actions speak louder than words."},
    {"t":"mcq","lv":"C","q":"The new girl looked unfriendly, but she turned out to be very kind. Which proverb fits?","o":["Birds of a feather flock together.","The early bird catches the worm.","Don't judge a book by its cover.","Too many cooks spoil the broth."],"a":2,"why":"You cannot tell what someone is like from how they look. Don't judge a book by its cover."},
    {"t":"mcq","lv":"C","q":"When Mei Lin hurt her ankle, Farah carried her bag every day. Which proverb fits?","o":["Better late than never.","A friend in need is a friend indeed.","Haste makes waste.","Look before you leap."],"a":1,"why":"Farah helped when Mei Lin was in trouble. That is a true friend."},
    {"t":"mcq","lv":"C","q":"Owen jumped into the pool without checking how deep it was. What should he have remembered?","o":["Look before you leap.","Practice makes perfect.","The early bird catches the worm.","Many hands make light work."],"a":0,"why":"Look before you leap means think carefully before acting."},
    {"t":"mcq","lv":"C","q":"Rushing through his test, Ryan made many careless mistakes. Which proverb fits?","o":["Slow and steady loses the race.","Better late than never.","Two heads are better than one.","Haste makes waste."],"a":3,"why":"Haste means hurry. Hurrying led to mistakes."},
    {"t":"mcq","lv":"B","q":"Bring a raincoat, just in case. ___","o":["Haste makes waste.","Too many cooks spoil the broth.","Better safe than sorry.","Birds of a feather flock together."],"a":2,"why":"Better safe than sorry means being careful is wiser than taking a risk."},
    {"t":"mcq","lv":"C","q":"Grandpa finally learnt to use a smartphone at 75. Which proverb fits?","o":["The early bird catches the worm.","Better late than never.","Look before you leap.","Don't put all your eggs in one basket."],"a":1,"why":"He learnt it late, but that is better than never learning it."},
    {"t":"mcq","lv":"C","q":"Rain cancelled our picnic, but we discovered a great board game café. Which proverb fits?","o":["Every cloud has a silver lining.","Haste makes waste.","Actions speak louder than words.","Too many cooks spoil the broth."],"a":0,"why":"Something good came out of a disappointing day. Every cloud has a silver lining."},
    {"t":"mcq","lv":"C","q":"\"Building a big Lego city takes weeks,\" said Dad. \"___\"","o":["Better safe than sorry.","Honesty is the best policy.","The early bird catches the worm.","Rome wasn't built in a day."],"a":3,"why":"Big things take time and patience. Rome wasn't built in a day."},
    {"t":"mcq","lv":"B","q":"Ali and Wen could not solve the riddle alone, but together they got it. Which proverb fits?","o":["Too many cooks spoil the broth.","Haste makes waste.","Two heads are better than one.","Look before you leap."],"a":2,"why":"Two people thinking together solved it. Two heads are better than one."},
    {"t":"mcq","lv":"C","q":"What does 'Slow and steady wins the race' mean?","o":["Slow runners always win races.","Working carefully and steadily brings success.","You should never hurry to school.","Races are not important."],"a":1,"why":"It comes from the tortoise and the hare. Steady effort beats rushing."},
    {"t":"mcq","lv":"C","q":"Lucas had no paint, so he used coloured pencils and still finished his poster. Which proverb fits?","o":["Where there's a will, there's a way.","Better late than never.","Birds of a feather flock together.","Don't count your chickens before they hatch."],"a":0,"why":"He really wanted to finish and found a way. Where there's a will, there's a way."},
    {"t":"fix","lv":"B","q":"The early bird catches the fish.","err":"fish","a":"worm","why":"The proverb is The early bird catches the worm. Do not change the words."},
    {"t":"fix","lv":"C","q":"Many hands make heavy work.","err":"heavy","a":"light","why":"Light work means easy work. Many helpers make a job easier."},
    {"t":"fix","lv":"C","q":"Honesty is the worst policy.","err":"worst","a":"best","why":"The proverb says telling the truth is the best choice."},
    {"t":"fix","lv":"C","q":"Don't count your ducks before they hatch.","err":"ducks","a":"chickens","why":"The proverb is Don't count your chickens before they hatch."},
    {"t":"fix","lv":"C","q":"Words speak louder than actions.","err":"Words speak louder than actions","a":"Actions speak louder than words","why":"What you do matters more than what you say, so actions come first."},
    {"t":"fix","lv":"C","q":"Better sorry than safe, so I packed a first-aid kit.","err":"Better sorry than safe","a":"Better safe than sorry","why":"Being safe is better than being sorry later."},
    {"t":"fill","lv":"B","q":"Practice makes ___.","a":["perfect"],"why":"If you keep practising, you will become very good."},
    {"t":"fill","lv":"C","q":"Too many cooks spoil the ___.","a":["broth"],"why":"Broth is soup. When too many people lead, the work is spoilt."},
    {"t":"fill","lv":"C","q":"A friend in need is a friend ___.","a":["indeed"],"why":"Indeed means truly. A friend who helps when you need it is a true friend."},
    {"t":"fill","lv":"C","q":"Don't put all your eggs in one ___.","a":["basket"],"why":"If the basket falls, all the eggs break. Do not depend on just one plan."},
    {"t":"fill","lv":"C","q":"Birds of a ___ flock together.","a":["feather"],"why":"People who are alike like to spend time together."},
    {"t":"fill","lv":"B","q":"Don't judge a book by its ___.","a":["cover"],"why":"The cover is the outside. Do not judge people by how they look."},
    {"t":"trans","lv":"C","q":"End this story with a proverb: Tim forgot his water bottle, and his friend Raj shared his water on the long hike.","a":["A friend in need is a friend indeed."],"why":"Raj helped Tim when he was in trouble. That shows a true friend."}
  ]
});

window.VG.push({
  id: "en-v-similes",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Similes: as … as …",
  lv: "A",
  intro: "A simile compares two things using 'as … as'. 'As busy as a bee' paints a picture in the reader's mind and makes your writing more fun to read.",
  rules: [
    {"h":"The pattern","html":"<b>as</b> + describing word + <b>as</b> + a thing <br>as <b>busy</b> as <b>a bee</b>"},
    {"h":"Pick a thing that is famous for it","html":"Bees are always working → <b>as busy as a bee</b>. <br>Feathers weigh almost nothing → <b>as light as a feather</b>."},
    {"h":"Use both 'as' words","html":"✓ The pillow was <b>as soft as</b> a cloud. <br>✗ The pillow was soft as as a cloud. <br>✗ The pillow was so soft as a cloud."},
    {"h":"Keep the usual pair","html":"Most similes have a usual partner: <b>as cold as ice</b>, <b>as quiet as a mouse</b>, <b>as brave as a lion</b>."}
  ],
  words: [
    {"w":"as busy as a bee","m":"very busy","ex":"Mum was as busy as a bee before Chinese New Year."},
    {"w":"as cold as ice","m":"very cold","ex":"After the swim, Ben's hands were as cold as ice."},
    {"w":"as light as a feather","m":"very light","ex":"The baby kitten was as light as a feather."},
    {"w":"as quiet as a mouse","m":"very quiet","ex":"Nora was as quiet as a mouse during the exam."},
    {"w":"as brave as a lion","m":"very brave","ex":"The firefighter was as brave as a lion."},
    {"w":"as slow as a snail","m":"very slow","ex":"The traffic on the expressway was as slow as a snail."},
    {"w":"as white as snow","m":"very white","ex":"The new school shirt was as white as snow."},
    {"w":"as proud as a peacock","m":"very proud","ex":"Amir was as proud as a peacock after winning the medal."},
    {"w":"as gentle as a lamb","m":"very gentle","ex":"Our big dog is as gentle as a lamb with babies."},
    {"w":"as strong as an ox","m":"very strong","ex":"Uncle Raju is as strong as an ox and can lift the sofa."},
    {"w":"as sly as a fox","m":"very clever in a tricky way","ex":"The cat in the story was as sly as a fox."},
    {"w":"as wise as an owl","m":"very wise","ex":"Grandma is as wise as an owl."},
    {"w":"as fresh as a daisy","m":"full of energy, not tired","ex":"After a good sleep, I felt as fresh as a daisy."},
    {"w":"as flat as a pancake","m":"very flat","ex":"The ball was as flat as a pancake after the lorry ran over it."},
    {"w":"as good as gold","m":"very well-behaved","ex":"My little sister was as good as gold at the dentist."},
    {"w":"as hard as rock","m":"very hard","ex":"The old bread was as hard as rock."},
    {"w":"as sweet as honey","m":"very sweet","ex":"The ripe mango was as sweet as honey."},
    {"w":"as fast as lightning","m":"very fast","ex":"Aiden ran as fast as lightning in the relay."},
    {"w":"as blind as a bat","m":"unable to see well","ex":"Without his glasses, Grandpa is as blind as a bat."},
    {"w":"as heavy as lead","m":"very heavy","ex":"My school bag felt as heavy as lead on Monday."},
    {"w":"as red as a tomato","m":"very red (often from shyness)","ex":"When everyone sang to her, Clara's face turned as red as a tomato."},
    {"w":"as happy as a lark","m":"very happy","ex":"Tina was as happy as a lark on her birthday."},
    {"w":"as clear as crystal","m":"very clear","ex":"The water at the beach was as clear as crystal."},
    {"w":"as hungry as a wolf","m":"very hungry","ex":"After football, Josh was as hungry as a wolf."}
  ],
  mistakes: [
    {"wrong":"He is so brave as a lion.","right":"He is as brave as a lion.","why":"A simile with as needs as at both ends: as brave as."},
    {"wrong":"The bag was as heavy as a feather.","right":"The bag was as light as a feather.","why":"Feathers are famous for being light, not heavy."},
    {"wrong":"She was as quiet as a lion.","right":"She was as quiet as a mouse.","why":"Lions roar! Mice are famous for being quiet."},
    {"wrong":"The snail was as fast as lightning.","right":"The cheetah was as fast as lightning.","why":"Snails are slow. Pick something that really is fast."}
  ],
  items: [
    {"t":"mcq","lv":"A","q":"as busy as a ___","o":["snail","rock","bee"],"a":2,"why":"Bees are always flying around working, so we say as busy as a bee."},
    {"t":"mcq","lv":"A","q":"as cold as ___","o":["ice","fire","the sun"],"a":0,"why":"Ice is frozen water, so it is very cold."},
    {"t":"mcq","lv":"A","q":"as light as a ___","o":["brick","feather","elephant"],"a":1,"why":"A feather weighs almost nothing."},
    {"t":"mcq","lv":"A","q":"as quiet as a ___","o":["drum","lion","mouse"],"a":2,"why":"Mice move quietly. Drums and lions are loud."},
    {"t":"mcq","lv":"A","q":"as brave as a ___","o":["lion","mouse","lamb"],"a":0,"why":"Lions are known as brave, fearless animals."},
    {"t":"mcq","lv":"A","q":"as slow as a ___","o":["cheetah","snail","rocket"],"a":1,"why":"Snails move very slowly."},
    {"t":"mcq","lv":"A","q":"as white as ___","o":["coal","grass","snow"],"a":2,"why":"Snow is pure white. Coal is black and grass is green."},
    {"t":"mcq","lv":"A","q":"as strong as an ___","o":["ox","ant","egg"],"a":0,"why":"An ox is a big, strong animal that pulls heavy carts."},
    {"t":"mcq","lv":"A","q":"as sweet as ___","o":["lemon","honey","salt"],"a":1,"why":"Honey is very sweet. Lemon is sour and salt is salty."},
    {"t":"mcq","lv":"A","q":"as fast as ___","o":["a tortoise","a stone","lightning"],"a":2,"why":"Lightning flashes in an instant, so it is very fast."},
    {"t":"mcq","lv":"B","q":"The naughty puppy stole the sausage without anyone noticing. It was as sly as a ___.","o":["lamb","fox","cow","bee"],"a":1,"why":"Foxes in stories are tricky and clever, so we say as sly as a fox."},
    {"t":"mcq","lv":"B","q":"Owls are thought to be clever. We say as ___ as an owl.","o":["wise","busy","flat","cold"],"a":0,"why":"In stories owls are wise, so the simile is as wise as an owl."},
    {"t":"mcq","lv":"B","q":"Yan Ting showed off her new dress to everyone. She was as proud as a ___.","o":["mouse","snail","bat","peacock"],"a":3,"why":"Peacocks spread their beautiful tails as if showing off, so we say as proud as a peacock."},
    {"t":"mcq","lv":"B","q":"After a long nap, Ivan felt as fresh as a ___.","o":["rock","pancake","daisy","wolf"],"a":2,"why":"As fresh as a daisy means full of energy, like a fresh flower in the morning."},
    {"t":"mcq","lv":"B","q":"The tyre was as ___ as a pancake.","o":["sweet","flat","brave","busy"],"a":1,"why":"Pancakes are flat, so a burst tyre is as flat as a pancake."},
    {"t":"mcq","lv":"B","q":"Little Ken sat still all through the wedding. He was as good as ___.","o":["gold","silver","honey","ice"],"a":0,"why":"As good as gold means very well-behaved."},
    {"t":"mcq","lv":"B","q":"Our gentle cat never scratches. She is as gentle as a ___.","o":["lion","wolf","fox","lamb"],"a":3,"why":"Lambs are soft and gentle animals."},
    {"t":"mcq","lv":"B","q":"Which sentence is a correct simile?","o":["The bread was so hard as rock.","The bread was hard as as rock.","The bread was as hard as rock.","The bread was as hard like rock."],"a":2,"why":"The pattern is as + describing word + as: as hard as rock."},
    {"t":"mcq","lv":"B","q":"Without his glasses, Grandpa is as blind as a ___.","o":["eagle","bat","owl","cat"],"a":1,"why":"People used to think bats could not see, so we say as blind as a bat."},
    {"t":"fix","lv":"A","q":"The baby was as quiet as a lion.","err":"lion","a":"mouse","why":"Lions roar loudly. Mice are quiet, so we say as quiet as a mouse."},
    {"t":"fix","lv":"A","q":"My bag is as light as a brick.","err":"brick","a":"feather","why":"Bricks are heavy. Feathers are light."},
    {"t":"fix","lv":"B","q":"The cheetah was as slow as lightning.","err":"slow","a":["fast", "quick"],"why":"Lightning is famous for being fast, not slow. Cheetahs are fast too: as fast as lightning."},
    {"t":"fix","lv":"B","q":"Dad is so strong as an ox.","err":"so","a":"as","why":"A simile with as needs as at both ends: as strong as an ox."},
    {"t":"fix","lv":"B","q":"The water was as clear as mud.","err":"mud","a":"crystal","why":"Mud is dirty and brown. Crystal is clear."},
    {"t":"fill","lv":"A","q":"The ice cream was as cold as ___.","a":["ice"],"why":"The usual simile is as cold as ice."},
    {"t":"fill","lv":"A","q":"Mum was as busy as a ___ in the kitchen.","a":["bee"],"why":"Bees are always busy."},
    {"t":"fill","lv":"B","q":"After football, Josh was as hungry as a ___.","a":["wolf","horse","bear"],"why":"Wolves are known as hungry hunters, so we say as hungry as a wolf."},
    {"t":"fill","lv":"B","q":"My schoolbag felt as heavy as ___.","a":["lead","a rock","an elephant"],"why":"Lead is a very heavy metal, so the usual simile is as heavy as lead."},
    {"t":"fill","lv":"B","q":"When she forgot her lines, Clara's face turned as red as a ___.","a":["tomato","beetroot","rose"],"why":"A ripe tomato is bright red, like a face when you feel shy or embarrassed."},
    {"t":"fill","lv":"A","q":"Ravi was as brave as a ___ when he got his injection.","a":["lion"],"why":"Lions are famous for being brave."},
    {"t":"trans","lv":"B","q":"Rewrite using a simile: The kitten was very light.","a":["The kitten was as light as a feather."],"why":"Use as … as with something famous for being light, like a feather."},
    {"t":"trans","lv":"B","q":"Rewrite using a simile: Grandma is very wise.","a":["Grandma is as wise as an owl."],"why":"Owls are known in stories as wise, so we say as wise as an owl."}
  ]
});

window.VG.push({
  id: "en-v-confusing",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Confusing pairs: borrow/lend, bring/take, say/tell, rise/raise, lose/loose, advice/advise, practice/practise…",
  lv: "B",
  intro: "Some words look or sound alike but mean different things. Learn a trick for each pair so you always pick the right one.",
  rules: [
    {"h":"borrow / lend","html":"You <b>borrow</b> FROM someone (you take it for a while). <br>You <b>lend</b> TO someone (you give it for a while). <br>✓ Can I <b>borrow</b> your ruler? ✓ Can you <b>lend</b> me your ruler? <br>✗ Can you borrow me your ruler?"},
    {"h":"bring / take","html":"<b>bring</b> = carry towards here, where the speaker is. <br><b>take</b> = carry away to another place. <br>Bring your book to me. Take this note to the office."},
    {"h":"say / tell","html":"<b>tell</b> needs a person: tell <b>me</b>, tell <b>Ali</b>. <br><b>say</b> does not: say hello, say something. <br>✗ She said me a story. ✓ She told me a story."},
    {"h":"rise / raise","html":"<b>rise</b> = go up by itself: The sun rises. <br><b>raise</b> = lift something up: Raise your hand. <br>rise, rose, risen · raise, raised, raised"},
    {"h":"lose / loose","html":"<b>lose</b> (one o) = not have any more: Don't lose your EZ-Link card. <br><b>loose</b> (two o's) = not tight: My tooth is loose."},
    {"h":"advice / advise, practice / practise","html":"In British English the <b>c</b> word is the noun (a thing): <b>advice</b>, <b>practice</b>. <br>The <b>s</b> word is the verb (an action): <b>advise</b>, <b>practise</b>. <br>Trick: ICE is a thing (noun). Piano <b>practice</b> is fun, so I <b>practise</b> daily."}
  ],
  words: [
    {"w":"borrow","m":"take something for a short time and give it back","ex":"May I borrow your eraser?"},
    {"w":"lend","m":"give something for a short time to be returned","ex":"Can you lend me your eraser?"},
    {"w":"bring","m":"carry something to the place where the speaker is","ex":"Please bring your homework to my table."},
    {"w":"take","m":"carry something away to another place","ex":"Take your umbrella when you go out."},
    {"w":"say","m":"speak words (no person needed after it)","ex":"Say thank you to Auntie."},
    {"w":"tell","m":"give information to a person","ex":"Tell me what happened."},
    {"w":"rise","m":"go up by itself","ex":"The water level rises when it rains heavily."},
    {"w":"raise","m":"lift something up; increase","ex":"Raise your hand if you know the answer."},
    {"w":"lose","m":"not be able to find; not win","ex":"Don't lose your library card."},
    {"w":"loose","m":"not tight","ex":"Kevin's shoelaces were loose, so he tripped."},
    {"w":"advice","m":"(noun) helpful ideas about what to do","ex":"My teacher gave me good advice."},
    {"w":"advise","m":"(verb) give someone ideas about what to do","ex":"The doctor advised me to drink more water."},
    {"w":"practice","m":"(noun) the activity of practising","ex":"Choir practice is on Wednesday."},
    {"w":"practise","m":"(verb) do something again and again to improve","ex":"I practise the piano every day."},
    {"w":"quiet","m":"making little or no noise","ex":"The library is very quiet."},
    {"w":"quite","m":"fairly; rather","ex":"The test was quite easy."},
    {"w":"stationary","m":"not moving","ex":"The bus was stationary at the traffic light."},
    {"w":"stationery","m":"paper, pens and other writing things","ex":"I bought new stationery at the bookshop."},
    {"w":"desert","m":"a hot, dry, sandy place","ex":"Camels can live in the desert."},
    {"w":"dessert","m":"sweet food after a meal (two s's, because you want seconds!)","ex":"We had chendol for dessert."},
    {"w":"fewer","m":"a smaller number of things you can count","ex":"There are fewer pupils today."},
    {"w":"less","m":"a smaller amount of something you cannot count","ex":"Please add less sugar to my drink."},
    {"w":"accept","m":"agree to take something","ex":"Please accept this small gift."},
    {"w":"except","m":"not including","ex":"Everyone came except Wei Ming."}
  ],
  mistakes: [
    {"wrong":"Can you borrow me your pencil?","right":"Can you lend me your pencil?","why":"You lend TO someone and borrow FROM someone."},
    {"wrong":"She said me the answer.","right":"She told me the answer.","why":"Tell is followed by a person. Say is not."},
    {"wrong":"Please rise your hand.","right":"Please raise your hand.","why":"Raise means lift something. Rise means go up by itself."},
    {"wrong":"I don't want to loose my wallet.","right":"I don't want to lose my wallet.","why":"Lose (one o) means not have any more. Loose (two o's) means not tight."},
    {"wrong":"Thank you for your advise.","right":"Thank you for your advice.","why":"Advice (with c) is the noun, the thing you get."},
    {"wrong":"I need to practice my spelling.","right":"I need to practise my spelling.","why":"In British English, practise (with s) is the verb, the action."}
  ],
  items: [
    {"t":"mcq","lv":"A","q":"May I ___ your blue pen?","o":["borrow","lend","lent"],"a":0,"why":"You are taking the pen for a while, so you borrow it."},
    {"t":"mcq","lv":"A","q":"Can you ___ me your blue pen?","o":["borrow","lend","borrowed"],"a":1,"why":"The other person gives it to you for a while, so they lend it to you."},
    {"t":"mcq","lv":"B","q":"Mum, can you ___ me some money for the canteen?","o":["borrow","loan me with","lend","borrowed"],"a":2,"why":"Mum is giving the money to you, so she lends it. You would borrow from Mum."},
    {"t":"mcq","lv":"B","q":"Ms Wong said, \"___ your storybook to class tomorrow.\"","o":["Take","Bring","Taking","Brought"],"a":1,"why":"The book is coming to where Ms Wong is (the class), so we use bring."},
    {"t":"mcq","lv":"B","q":"Please ___ this letter to the general office.","o":["take","bring","brings","brought"],"a":0,"why":"The letter goes away from the speaker to another place, so we use take."},
    {"t":"mcq","lv":"A","q":"Did you ___ thank you to Grandma?","o":["tell","told","say"],"a":2,"why":"There is no person straight after the verb, so we use say."},
    {"t":"mcq","lv":"B","q":"Please ___ me a story before bed.","o":["say","speak","tell","talk"],"a":2,"why":"Tell is followed by a person (me). We tell stories."},
    {"t":"mcq","lv":"B","q":"The sun ___ in the east every morning.","o":["raises","rises","raise","rising"],"a":1,"why":"The sun goes up by itself, so we use rise. One sun → rises."},
    {"t":"mcq","lv":"B","q":"___ your hand if you want to answer.","o":["Raise","Rise","Rose","Risen"],"a":0,"why":"You lift your hand up, so we use raise."},
    {"t":"mcq","lv":"B","q":"My front tooth is ___. It will fall out soon.","o":["lose","lost","losing","loose"],"a":3,"why":"Loose (two o's) means not tight."},
    {"t":"mcq","lv":"B","q":"Hold your EZ-Link card tightly or you will ___ it.","o":["loose","loss","lose","lost"],"a":2,"why":"Lose (one o) means not have it any more."},
    {"t":"mcq","lv":"B","q":"My coach gave me some good ___ about running.","o":["advise","advice","advices","advised"],"a":1,"why":"Some good ___ needs a noun (a thing). Advice with c is the noun. It has no plural with s."},
    {"t":"mcq","lv":"C","q":"The doctor ___ Grandpa to walk every day.","o":["advised","adviced","advice","advices"],"a":0,"why":"This is an action (verb), so use advise with s. Past tense: advised."},
    {"t":"mcq","lv":"C","q":"Badminton ___ is every Thursday after school.","o":["practise","practising","practised","practice"],"a":3,"why":"Badminton practice is a thing (noun), so it has c in British English."},
    {"t":"mcq","lv":"C","q":"You must ___ your scales every day.","o":["practice","practices","practise","practicing"],"a":2,"why":"After must we need an action (verb). In British English the verb is practise with s."},
    {"t":"mcq","lv":"B","q":"Please be ___ in the library.","o":["quite","quiet","quit","quiets"],"a":1,"why":"Quiet means making no noise. Quite means fairly."},
    {"t":"mcq","lv":"B","q":"The movie was ___ funny, but a little long.","o":["quite","quiet","quit","quietly"],"a":0,"why":"Quite means fairly or rather."},
    {"t":"mcq","lv":"C","q":"We had durian pengat for ___ after dinner.","o":["desert","deserted","deserts","dessert"],"a":3,"why":"Dessert (two s's) is sweet food after a meal. A desert is a dry, sandy place."},
    {"t":"mcq","lv":"C","q":"Pens, rulers and paper are all ___.","o":["stationary","stations","stationery","stationed"],"a":2,"why":"Stationery with e is writing things. Trick: e for envelope."},
    {"t":"mcq","lv":"C","q":"There are ___ apples in this box than in that one.","o":["less","fewer","little","least"],"a":1,"why":"You can count apples, so use fewer. Use less for things you cannot count, like water."},
    {"t":"mcq","lv":"C","q":"Everyone came to the party ___ Daniel, who was sick.","o":["except","accept","expect","excepted"],"a":0,"why":"Except means not including. Accept means agree to take."},
    {"t":"fix","lv":"B","q":"Can you borrow me your eraser, please?","err":"borrow","a":"lend","why":"The friend gives it to you, so they lend it. You borrow FROM someone."},
    {"t":"fix","lv":"B","q":"Mira said me a funny joke.","err":"said","a":"told","why":"When a person comes right after, use tell: told me."},
    {"t":"fix","lv":"B","q":"Rice cost more, so the hawker had to rise his prices.","err":"rise","a":["raise", "increase"],"why":"The hawker lifts the prices, so he raises them. Prices rise by themselves."},
    {"t":"fix","lv":"B","q":"Be careful not to loose your house key.","err":"loose","a":"lose","why":"Lose (one o) means not have any more. Loose means not tight."},
    {"t":"fix","lv":"C","q":"My mother gave me some wise advise.","err":"advise","a":"advice","why":"Advice with c is the noun, the thing you are given."},
    {"t":"fix","lv":"C","q":"I need to practice my spelling words tonight.","err":"practice","a":"practise","why":"Here it is an action (verb), so in British English it is practise with s."},
    {"t":"fill","lv":"B","q":"Remember to ___ your PE shirt home to wash. (bring / take)","a":["take"],"why":"The shirt goes away from school to home, so use take."},
    {"t":"fill","lv":"B","q":"My trousers are too ___. I need a belt. (lose / loose)","a":["loose"],"why":"Loose means not tight."},
    {"t":"fill","lv":"C","q":"The smoke began to ___ into the sky. (rise / raise)","a":["rise"],"why":"Smoke goes up by itself, so use rise."},
    {"t":"fill","lv":"C","q":"I ___ my friends to wear a cap in the hot sun. (advice / advise)","a":["advise"],"why":"It is an action, so use the verb advise with s."},
    {"t":"fill","lv":"B","q":"Could you ___ me your umbrella? It's raining. (borrow / lend)","a":["lend"],"why":"You want the other person to give it to you for a while, so they lend it."},
    {"t":"trans","lv":"C","q":"Rewrite using 'borrow': Can you lend me your calculator?","a":["Can I borrow your calculator?","May I borrow your calculator?"],"why":"Now you are the one taking it, so you borrow it. The meaning stays the same."}
  ]
});

window.VG.push({
  id: "en-v-formal",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Formal and informal words (for letters and emails)",
  lv: "C",
  intro: "We talk to friends in a relaxed way, but we write to a principal or a company more politely. Choosing the right words is called using the right register.",
  rules: [
    {"h":"Who are you writing to?","html":"Friend, cousin → <b>informal</b>: Hi Aiden! Thanks a lot! <br>Principal, manager, stranger → <b>formal</b>: Dear Mrs Tan, Thank you very much."},
    {"h":"Formal swaps","html":"ask → <b>request</b> · buy → <b>purchase</b> · help → <b>assist</b> · get → <b>receive / obtain</b> · tell → <b>inform</b> · need → <b>require</b> · about → <b>regarding</b> · start → <b>commence</b>"},
    {"h":"No short forms in formal writing","html":"✗ I can't come. ✓ I <b>cannot</b> come. <br>✗ It's broken. ✓ It <b>is</b> broken. <br>No slang (gonna, cool, kids) and no exclamation marks!!!"},
    {"h":"Formal openings and endings","html":"Dear Sir/Madam … <b>Yours faithfully</b> (you do not know the name) <br>Dear Mr Lee … <b>Yours sincerely</b> (you know the name) <br>Useful: <b>I am writing to</b> … <b>I look forward to hearing from you.</b>"},
    {"h":"Informal openings and endings","html":"Hi Mei! / Dear Grandma, … <b>Love</b>, <b>Cheers</b>, <b>See you soon</b>, <b>Take care</b>"}
  ],
  words: [
    {"w":"request","m":"formal for ask for","ex":"I would like to request a replacement for the broken toy."},
    {"w":"purchase","m":"formal for buy","ex":"I purchased the shoes at your Jurong Point outlet."},
    {"w":"assist","m":"formal for help","ex":"Could you please assist me with this matter?"},
    {"w":"receive","m":"formal for get","ex":"I have not received the parcel."},
    {"w":"obtain","m":"formal for get","ex":"Pupils must obtain a consent form from the office."},
    {"w":"inform","m":"formal for tell","ex":"I am writing to inform you of a problem at the playground."},
    {"w":"require","m":"formal for need","ex":"We require two more volunteers."},
    {"w":"regarding","m":"formal for about","ex":"I am writing regarding the school excursion."},
    {"w":"commence","m":"formal for start","ex":"The concert will commence at 7 p.m."},
    {"w":"conclude","m":"formal for end","ex":"The event concluded with a prize-giving."},
    {"w":"sufficient","m":"formal for enough","ex":"There was not sufficient seating for the parents."},
    {"w":"approximately","m":"formal for about (a number)","ex":"Approximately fifty pupils attended."},
    {"w":"numerous","m":"formal for lots of","ex":"There have been numerous complaints about the noise."},
    {"w":"reside","m":"formal for live","ex":"I reside in Block 123, Bedok North."},
    {"w":"additional","m":"formal for extra","ex":"Do you need additional information?"},
    {"w":"apologise","m":"formal for say sorry","ex":"I apologise for the late reply."},
    {"w":"enquire","m":"formal for ask about","ex":"I am writing to enquire about swimming lessons."},
    {"w":"children","m":"formal for kids","ex":"The playground is popular with young children."},
    {"w":"however","m":"formal for but (at the start of a sentence)","ex":"The food was tasty. However, the service was slow."},
    {"w":"Yours sincerely","m":"formal ending when you know the person's name","ex":"Dear Mr Tan, ... Yours sincerely, Aisha Rahman"},
    {"w":"Yours faithfully","m":"formal ending when you start with Dear Sir/Madam","ex":"Dear Sir/Madam, ... Yours faithfully, Ryan Lim"},
    {"w":"I look forward to hearing from you.","m":"a polite closing line in a formal letter","ex":"Please reply by Friday. I look forward to hearing from you."}
  ],
  mistakes: [
    {"wrong":"Hey Principal Tan, the toilets are super gross!!!","right":"Dear Mrs Tan, I would like to inform you that the toilets are dirty.","why":"A letter to a principal must be formal: polite greeting, no slang, no extra exclamation marks."},
    {"wrong":"I can't attend the meeting.","right":"I cannot attend the meeting.","why":"Formal writing uses full forms, not short forms like can't."},
    {"wrong":"Dear Sir/Madam, ... Yours sincerely,","right":"Dear Sir/Madam, ... Yours faithfully,","why":"If you do not know the name, end with Yours faithfully."},
    {"wrong":"Dear Grandma, I am writing to inform you that I purchased a gift.","right":"Dear Grandma, guess what? I bought you a present!","why":"To family and friends, write in a friendly, relaxed way."}
  ],
  items: [
    {"t":"mcq","lv":"B","q":"Which is the most formal way to start a letter to the manager of a shop?","o":["Hi there!","Yo manager,","Hey,","Dear Sir/Madam,"],"a":3,"why":"Dear Sir/Madam is polite and formal. The others are for friends."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'buy': I ___ a toaster from your store last week.","o":["got","grabbed","purchased","picked up"],"a":2,"why":"Purchase is the formal word for buy."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'help': Could you please ___ me?","o":["give me a hand with","assist","sort out","fix up"],"a":1,"why":"Assist is the formal word for help."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'tell': I am writing to ___ you that the lift is broken.","o":["inform","tell","let you know","shout"],"a":0,"why":"Inform is the formal word for tell. Tell and let you know are fine with friends, but inform sounds more formal. Shout is rude."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'about': I am writing ___ the lost and found items.","o":["about all","on","around","regarding"],"a":3,"why":"Regarding is a formal way to say about."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'start': The ceremony will ___ at 9 a.m.","o":["kick off","get going","commence","begin lah"],"a":2,"why":"Commence is the formal word for start."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'got': I have not ___ my order yet.","o":["got hold of","received","grabbed","caught"],"a":1,"why":"Receive is the formal word for get when something is sent to you."},
    {"t":"mcq","lv":"C","q":"You start a letter with 'Dear Mr Wong'. How should you end it?","o":["Yours sincerely,","Yours faithfully,","Love,","Bye!"],"a":0,"why":"When you know the person's name, end with Yours sincerely."},
    {"t":"mcq","lv":"C","q":"You start a letter with 'Dear Sir/Madam'. How should you end it?","o":["Yours sincerely,","Cheers,","See ya,","Yours faithfully,"],"a":3,"why":"When you do not know the name, end with Yours faithfully. Trick: S and S don't go together (Sir... Sincerely)."},
    {"t":"mcq","lv":"B","q":"Which ending suits an email to your best friend?","o":["Yours faithfully,","I look forward to hearing from you.","See you soon!","Yours sincerely,"],"a":2,"why":"Friends get a relaxed, friendly ending like See you soon!"},
    {"t":"mcq","lv":"C","q":"Which sentence is the most formal?","o":["Gimme my money back.","I would like to request a refund.","I want my money back now!","Can I get a refund or what?"],"a":1,"why":"I would like to request is polite and formal. The others are rude or too casual."},
    {"t":"mcq","lv":"C","q":"Which sentence suits a formal complaint letter?","o":["The noise from the construction site is very disturbing.","The noise is super duper annoying!!!","That noise is so gross, man.","OMG the noise!"],"a":0,"why":"Formal writing is calm, uses full sentences and has no slang or extra exclamation marks."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'enough': There was not ___ food for everyone.","o":["plenty","loads of","a lot","sufficient"],"a":3,"why":"Sufficient is the formal word for enough."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'about' with a number: ___ 200 people attended the carnival.","o":["Like","Around-ish","Approximately","More or less like"],"a":2,"why":"Approximately is the formal way to say about for numbers."},
    {"t":"mcq","lv":"C","q":"Choose the formal word for 'need': Pupils ___ a permission slip.","o":["gotta have","require","wanna","need badly"],"a":1,"why":"Require is the formal word for need."},
    {"t":"mcq","lv":"B","q":"Which is an informal greeting?","o":["Hi Jasmine!","Dear Sir/Madam,","To whom it may concern,","Dear Principal,"],"a":0,"why":"Hi plus a first name is friendly and informal."},
    {"t":"mcq","lv":"C","q":"Which is a good closing line for a formal letter?","o":["Write back soon, OK?","Catch you later!","Bye bye!","I look forward to hearing from you."],"a":3,"why":"I look forward to hearing from you is the standard polite closing for formal letters."},
    {"t":"mcq","lv":"C","q":"Choose the formal phrase for 'say sorry': I ___ for any trouble caused.","o":["say sorry lah","feel bad","apologise","am like sorry"],"a":2,"why":"Apologise is the formal way to say sorry."},
    {"t":"fix","lv":"C","q":"Dear Mrs Lim, I am writing to tell you that the kids at the playground are being rude.","err":"kids","a":["children", "pupils"],"why":"Kids is informal. In a formal letter, use children."},
    {"t":"fix","lv":"C","q":"I can't attend the meeting on Friday.","err":"can't","a":["cannot", "am unable to"],"why":"Formal writing avoids short forms. Write cannot in full."},
    {"t":"fix","lv":"C","q":"Dear Sir/Madam, I would like to complain about the broken lift. Yours sincerely, Ahmad","err":"Yours sincerely","a":"Yours faithfully","why":"The letter starts with Dear Sir/Madam, so it ends with Yours faithfully."},
    {"t":"fix","lv":"C","q":"I would like to ask for a refund because the toy I got was broken.","err":"got","a":["purchased", "bought", "received"],"why":"In a formal letter, purchased is better than the informal got."},
    {"t":"fix","lv":"C","q":"I am writing to enquire about your swimming classes. I'd like to sign up my brother.","err":"I'd","a":"I would","why":"Avoid short forms like I'd in formal writing. Write I would in full."},
    {"t":"fix","lv":"C","q":"The food at the event was good. But the queue was too long.","err":"But","a":"However,","why":"In formal writing, start a new sentence with However, not But."},
    {"t":"fill","lv":"C","q":"I am writing to ___ about your piano lessons. (formal for 'ask')","a":["enquire","inquire"],"why":"Enquire means ask for information. It is the formal word."},
    {"t":"fill","lv":"C","q":"We ___ two more volunteers for the beach clean-up. (formal for 'need')","a":["require"],"why":"Require is the formal word for need."},
    {"t":"fill","lv":"C","q":"Do you need any ___ information? (formal for 'extra')","a":["additional"],"why":"Additional is the formal word for extra."},
    {"t":"fill","lv":"C","q":"I ___ in Block 45, Ang Mo Kio Avenue 3. (formal for 'live')","a":["reside"],"why":"Reside is the formal word for live."},
    {"t":"fill","lv":"C","q":"There have been ___ complaints about the smell. (formal for 'lots of')","a":["numerous","many"],"why":"Numerous is a formal word meaning many."},
    {"t":"trans","lv":"C","q":"Make this formal: Hey, can you help me with my problem?","a":["Could you please assist me with my problem?","I would be grateful if you could assist me with my problem."],"why":"Use a polite question and the formal word assist instead of help. Drop Hey."},
    {"t":"trans","lv":"C","q":"Make this informal for a friend: I would like to inform you that I have purchased a new bicycle.","a":["Guess what? I bought a new bike!","I just bought a new bike!","Guess what? I bought a new bicycle!"],"why":"With friends, use relaxed words: bought instead of purchased, and no need for I would like to inform you."}
  ]
});

window.VG.push({
  id: "en-v-describe",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Better words for said, nice, good, bad, big, small, went",
  lv: "A",
  intro: "Some words are tired because we use them all the time. Swapping them for sharper words shows the reader exactly what happened and makes your story come alive.",
  rules: [
    {"h":"Instead of said","html":"Loud: <b>shouted</b>, <b>yelled</b>, <b>exclaimed</b> <br>Soft: <b>whispered</b>, <b>mumbled</b> <br>Sad: <b>sobbed</b>, <b>sighed</b> <br>Answering or asking: <b>replied</b>, <b>asked</b>, <b>explained</b>"},
    {"h":"Instead of went","html":"Fast: <b>rushed</b>, <b>dashed</b>, <b>raced</b> <br>Slow: <b>strolled</b>, <b>wandered</b> <br>Quiet: <b>tiptoed</b>, <b>crept</b>"},
    {"h":"Instead of nice and good","html":"food → <b>delicious</b>, <b>tasty</b> <br>person → <b>kind</b>, <b>friendly</b>, <b>helpful</b> <br>day or trip → <b>wonderful</b>, <b>enjoyable</b> <br>work → <b>excellent</b>, <b>neat</b>"},
    {"h":"Instead of bad, big, small","html":"bad → <b>terrible</b>, <b>awful</b>, <b>naughty</b> (child), <b>rotten</b> (food) <br>big → <b>huge</b>, <b>enormous</b>, <b>gigantic</b> <br>small → <b>tiny</b>, <b>little</b>"},
    {"h":"Choose the word that fits the clue","html":"\"Shh, the baby is sleeping,\" Mum <b>whispered</b>. <br>Whispered fits because the baby is asleep. Always look for the clue."}
  ],
  words: [
    {"w":"whispered","m":"said very softly","ex":"\"The baby is asleep,\" Mum whispered."},
    {"w":"shouted","m":"said very loudly","ex":"\"Watch out!\" Jun shouted."},
    {"w":"exclaimed","m":"said suddenly with surprise or excitement","ex":"\"I won!\" Aisha exclaimed."},
    {"w":"replied","m":"said as an answer","ex":"\"Yes, I'm ready,\" Ben replied."},
    {"w":"sobbed","m":"said while crying","ex":"\"I lost my puppy,\" the little girl sobbed."},
    {"w":"mumbled","m":"said unclearly in a low voice","ex":"Kai mumbled an answer because he was shy."},
    {"w":"explained","m":"said to make something clear","ex":"Dad explained how to fix the bicycle chain."},
    {"w":"delicious","m":"very tasty","ex":"The laksa at the hawker centre was delicious."},
    {"w":"kind","m":"caring and helpful","ex":"The kind uncle helped me find my way."},
    {"w":"pleasant","m":"nice and enjoyable","ex":"We had a pleasant walk at East Coast Park."},
    {"w":"excellent","m":"very good","ex":"Ms Ng said my composition was excellent."},
    {"w":"wonderful","m":"very good, giving joy","ex":"We had a wonderful time at the Night Safari."},
    {"w":"terrible","m":"very bad","ex":"There was a terrible storm last night."},
    {"w":"awful","m":"very bad or unpleasant","ex":"The rubbish chute had an awful smell."},
    {"w":"naughty","m":"behaving badly (for a child or pet)","ex":"The naughty puppy chewed my slipper."},
    {"w":"huge","m":"very big","ex":"A huge python was found near the canal."},
    {"w":"enormous","m":"extremely big","ex":"The whale shark at the aquarium was enormous."},
    {"w":"gigantic","m":"extremely big, like a giant","ex":"We built a gigantic sandcastle."},
    {"w":"tiny","m":"very small","ex":"A tiny ant crawled across my desk."},
    {"w":"rushed","m":"went very quickly","ex":"Ali rushed to the MRT station."},
    {"w":"dashed","m":"ran quickly for a short distance","ex":"She dashed across the field to catch the ball."},
    {"w":"strolled","m":"walked slowly and calmly","ex":"Grandpa strolled along the park connector."},
    {"w":"tiptoed","m":"walked quietly on your toes","ex":"I tiptoed past my sleeping sister."},
    {"w":"crept","m":"moved slowly and quietly so as not to be noticed","ex":"The cat crept towards the pigeon."}
  ],
  mistakes: [
    {"wrong":"\"Help!\" whispered Ravi as he fell into the pool.","right":"\"Help!\" shouted Ravi as he fell into the pool.","why":"Someone in danger yells loudly. Whispered is too soft."},
    {"wrong":"The food was nice and the day was nice and my friend was nice.","right":"The food was delicious, the day was wonderful and my friend was kind.","why":"Use a different, sharper word for each thing."},
    {"wrong":"The tiny elephant was too heavy to lift.","right":"The enormous elephant was too heavy to lift.","why":"The clue too heavy tells you it is big, not tiny."},
    {"wrong":"The thief dashed slowly into the house.","right":"The thief crept slowly into the house.","why":"Dashed means fast. For slow and quiet, use crept."}
  ],
  items: [
    {"t":"mcq","lv":"A","q":"\"Shh, the baby is sleeping,\" Mum ___.","o":["whispered","shouted","yelled"],"a":0,"why":"The baby is asleep, so Mum speaks very softly. That is whispered."},
    {"t":"mcq","lv":"A","q":"\"Watch out for the car!\" Dad ___.","o":["whispered","shouted","mumbled"],"a":1,"why":"It is an emergency, so Dad says it very loudly. That is shouted."},
    {"t":"mcq","lv":"A","q":"\"I lost my teddy,\" the little boy ___, with tears on his face.","o":["laughed","cheered","sobbed"],"a":2,"why":"He has tears on his face, so he is crying. Sobbed means said while crying."},
    {"t":"mcq","lv":"A","q":"\"What is your name?\" asked the teacher. \"Mei Ling,\" she ___.","o":["replied","asked","screamed"],"a":0,"why":"She is answering a question, so replied fits."},
    {"t":"mcq","lv":"B","q":"\"I got full marks!\" Haziq ___ happily.","o":["sobbed","exclaimed","mumbled","whispered"],"a":1,"why":"He is excited, so he says it with excitement. That is exclaimed."},
    {"t":"mcq","lv":"B","q":"The teacher ___ how to solve the sum step by step.","o":["explained","sobbed","whispered","yelled"],"a":0,"why":"Explained means said something to make it clear."},
    {"t":"mcq","lv":"A","q":"The chicken rice was very tasty. It was ___.","o":["delicious","naughty","tiny"],"a":0,"why":"Delicious is the best word for very tasty food."},
    {"t":"mcq","lv":"A","q":"The auntie helped me carry my heavy bag. She was very ___.","o":["rotten","kind","enormous"],"a":1,"why":"A person who helps others is kind."},
    {"t":"mcq","lv":"B","q":"Ms Lee gave me a gold star. She said my work was ___.","o":["awful","excellent","terrible","rotten"],"a":1,"why":"Excellent means very good. A gold star is for very good work."},
    {"t":"mcq","lv":"B","q":"We had a ___ time at the Bird Paradise. Everyone smiled all day.","o":["wonderful","terrible","naughty","tiny"],"a":0,"why":"Everyone smiled, so the time was very good. Wonderful fits."},
    {"t":"mcq","lv":"A","q":"The puppy tore up all the newspapers. It was very ___.","o":["delicious","naughty","tiny"],"a":1,"why":"A pet or child that behaves badly is naughty."},
    {"t":"mcq","lv":"B","q":"The milk smelt ___ because it had gone bad.","o":["pleasant","excellent","awful","delicious"],"a":2,"why":"Milk that has gone bad smells very unpleasant. Awful fits."},
    {"t":"mcq","lv":"B","q":"There was a ___ storm and many trees fell.","o":["pleasant","terrible","tiny","kind"],"a":1,"why":"A storm that knocks down trees is very bad. Terrible fits."},
    {"t":"mcq","lv":"A","q":"The elephant at the zoo was ___!","o":["tiny","enormous","little"],"a":1,"why":"Elephants are very big. Enormous means extremely big."},
    {"t":"mcq","lv":"A","q":"A ___ ant crawled on my pencil case.","o":["huge","gigantic","tiny"],"a":2,"why":"Ants are very small. Tiny means very small."},
    {"t":"mcq","lv":"B","q":"Late for school, Kumar ___ to the bus stop.","o":["strolled","tiptoed","rushed","crept"],"a":2,"why":"He is late, so he goes fast. Rushed means went very quickly."},
    {"t":"mcq","lv":"B","q":"On Sunday evening, my grandparents ___ slowly around the park.","o":["dashed","strolled","raced","rushed"],"a":1,"why":"Slowly and calmly → strolled."},
    {"t":"mcq","lv":"B","q":"Not wanting to wake his sister, Jun ___ out of the room.","o":["tiptoed","stomped","raced","marched"],"a":0,"why":"He wants to be quiet, so he walks on his toes. That is tiptoed."},
    {"t":"mcq","lv":"B","q":"The cat ___ towards the bird without making a sound.","o":["stomped","dashed noisily","marched","crept"],"a":3,"why":"Without a sound and carefully → crept."},
    {"t":"fix","lv":"A","q":"\"Fire! Fire!\" whispered the man.","err":"whispered","a":["shouted", "yelled", "screamed", "cried"],"why":"In an emergency people yell loudly, so shouted fits."},
    {"t":"fix","lv":"A","q":"The tiny whale was as long as a bus.","err":"tiny","a":["enormous", "huge", "gigantic", "giant", "massive"],"why":"Something as long as a bus is very big, not tiny."},
    {"t":"fix","lv":"B","q":"Grandma strolled to the bus stop because she was late.","err":"strolled","a":["rushed", "hurried", "ran", "dashed"],"why":"When you are late you go fast. Strolled means walking slowly."},
    {"t":"fix","lv":"B","q":"The ice cream was terrible, so I asked for another one.","err":"terrible","a":["delicious", "tasty", "yummy"],"why":"You only want another one if it tastes very good, so delicious fits."},
    {"t":"fix","lv":"B","q":"\"Thank you for helping me,\" she sobbed with a big smile.","err":"sobbed","a":["said", "beamed"],"why":"Sobbed means said while crying, but she is smiling. Use said (or exclaimed)."},
    {"t":"fill","lv":"A","q":"The baby is asleep, so please ___ when you talk. (shout / whisper)","a":["whisper"],"why":"Whisper means speak very softly."},
    {"t":"fill","lv":"A","q":"The mouse was so ___ that it fitted in my palm. (tiny / huge)","a":["tiny"],"why":"Something that fits in your palm is very small."},
    {"t":"fill","lv":"B","q":"The ___ dinosaur was taller than a three-storey HDB block. (tiny / gigantic)","a":["gigantic"],"why":"Taller than a building means extremely big. Gigantic fits."},
    {"t":"fill","lv":"B","q":"Siti ___ across the field to catch the ball. (dashed / strolled)","a":["dashed"],"why":"To catch a ball you run fast. Dashed means ran quickly."},
    {"t":"fill","lv":"B","q":"\"Where is my bag?\" Ali asked. \"It's under your desk,\" Mei ___. (replied / asked)","a":["replied"],"why":"Mei is answering Ali's question, so replied fits."},
    {"t":"trans","lv":"B","q":"Rewrite with better words for 'nice' and 'big': We ate a nice cake at a big party.","a":["We ate a delicious cake at a huge party.","We ate a delicious cake at an enormous party.","We ate a tasty cake at a huge party."],"why":"For food, use delicious or tasty. For a big party, use huge or enormous."},
    {"t":"trans","lv":"B","q":"Rewrite with a better word for 'went': The thief went quietly into the room.","a":["The thief crept into the room.","The thief tiptoed into the room.","The thief crept quietly into the room."],"why":"Crept or tiptoed shows moving quietly so as not to be noticed."}
  ]
});

window.VG.push({
  id: "en-v-groups",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Word groups: odd one out and categories",
  lv: "A",
  intro: "Words belong to families called categories, like fruits, animals or furniture. Knowing the family name helps you spot the odd one out and write more exactly.",
  rules: [
    {"h":"What is a category?","html":"A category is a group of things that are the same kind. <br><b>fruits</b>: apple, mango, banana <br><b>furniture</b>: table, chair, bed"},
    {"h":"Finding the odd one out","html":"Ask: what do MOST of these have in common? <br>apple, mango, <b>carrot</b>, banana → carrot is a <b>vegetable</b>, the rest are fruits."},
    {"h":"Use the group name","html":"Instead of 'pens, pencils, rulers and erasers', write <b>stationery</b>. <br>Instead of 'cars, buses and lorries', write <b>vehicles</b>."},
    {"h":"Watch for tricky members","html":"A whale lives in the sea, but it is a <b>mammal</b>, not a fish. <br>A spider has eight legs, so it is <b>not an insect</b> (insects have six)."}
  ],
  words: [
    {"w":"fruits","m":"the sweet parts of plants that hold seeds","ex":"Durians, rambutans and papayas are fruits."},
    {"w":"vegetables","m":"plants or plant parts we cook or eat","ex":"Kang kong, carrots and spinach are vegetables."},
    {"w":"furniture","m":"large things in a room, like tables and beds","ex":"We bought new furniture for our HDB flat."},
    {"w":"stationery","m":"things for writing, like pens and paper","ex":"Pencils, rulers and erasers are stationery."},
    {"w":"vehicles","m":"machines that carry people or goods","ex":"Buses, taxis and lorries are vehicles."},
    {"w":"mammals","m":"warm-blooded animals that feed their babies milk","ex":"Dogs, cats and whales are mammals."},
    {"w":"insects","m":"small animals with six legs and three body parts","ex":"Ants, bees and butterflies are insects."},
    {"w":"birds","m":"animals with feathers, wings and beaks","ex":"Sparrows, mynahs and eagles are birds."},
    {"w":"reptiles","m":"cold-blooded animals with scaly skin","ex":"Snakes, lizards and crocodiles are reptiles."},
    {"w":"occupations","m":"jobs people do","ex":"Doctor, teacher and pilot are occupations."},
    {"w":"musical instruments","m":"things used to make music","ex":"The piano, flute and violin are musical instruments."},
    {"w":"utensils","m":"tools used for cooking or eating","ex":"A ladle, a spatula and a pair of tongs are kitchen utensils."},
    {"w":"cutlery","m":"knives, forks and spoons","ex":"Please put the cutlery on the table."},
    {"w":"appliances","m":"machines in the home that use electricity","ex":"A fridge, a fan and a washing machine are appliances."},
    {"w":"beverages","m":"drinks","ex":"Milo, teh and fruit juice are beverages."},
    {"w":"shapes","m":"outlines like circles and squares","ex":"A triangle, a square and a circle are shapes."},
    {"w":"body parts","m":"parts of the body","ex":"Elbows, knees and shoulders are body parts."},
    {"w":"weather","m":"what the sky and air are like","ex":"Rain, thunder and haze are kinds of weather."},
    {"w":"clothing","m":"things we wear","ex":"Shirts, skirts and jackets are clothing."},
    {"w":"feelings","m":"emotions, like happy or scared","ex":"Joy, anger and fear are feelings."},
    {"w":"odd one out","m":"the one that does not belong to the group","ex":"In cat, dog, rose and rabbit, the rose is the odd one out."}
  ],
  mistakes: [
    {"wrong":"A whale is a big fish.","right":"A whale is a big mammal.","why":"Whales breathe air and feed their babies milk, so they are mammals."},
    {"wrong":"A spider is an insect.","right":"A spider is not an insect. It has eight legs.","why":"Insects have six legs. Spiders have eight."},
    {"wrong":"I bought new stationary for school.","right":"I bought new stationery for school.","why":"Writing things are stationery with e. Stationary means not moving."},
    {"wrong":"The odd one out in 'red, blue, green, yellow' is green.","right":"There is no odd one out. They are all colours.","why":"Check the whole group first. All four are colours."}
  ],
  items: [
    {"t":"mcq","lv":"A","q":"Which is the odd one out?","o":["apple","carrot","mango"],"a":1,"why":"Apple and mango are fruits. A carrot is a vegetable."},
    {"t":"mcq","lv":"A","q":"Which is the odd one out?","o":["bus","sofa","taxi"],"a":1,"why":"Bus and taxi are vehicles. A sofa is furniture."},
    {"t":"mcq","lv":"A","q":"Which is the odd one out?","o":["cat","dog","rose"],"a":2,"why":"Cat and dog are animals. A rose is a flower."},
    {"t":"mcq","lv":"A","q":"Which is the odd one out?","o":["pencil","ruler","banana"],"a":2,"why":"Pencil and ruler are stationery. A banana is a fruit."},
    {"t":"mcq","lv":"A","q":"Which is the odd one out?","o":["circle","square","Tuesday"],"a":2,"why":"Circle and square are shapes. Tuesday is a day of the week."},
    {"t":"mcq","lv":"A","q":"Table, chair and bed are all ___.","o":["vehicles","fruits","furniture"],"a":2,"why":"Tables, chairs and beds are large things in a room. They are furniture."},
    {"t":"mcq","lv":"A","q":"Ants, bees and butterflies are all ___.","o":["insects","birds","fish"],"a":0,"why":"They have six legs and three body parts, so they are insects."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["piano","violin","hammer","flute"],"a":2,"why":"Piano, violin and flute are musical instruments. A hammer is a tool."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["doctor","teacher","hospital","pilot"],"a":2,"why":"Doctor, teacher and pilot are jobs (occupations). A hospital is a place."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["sparrow","eagle","bat","mynah"],"a":2,"why":"Sparrow, eagle and mynah are birds. A bat can fly, but it is a mammal with fur."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["snake","lizard","crocodile","frog"],"a":3,"why":"Snakes, lizards and crocodiles are reptiles with scaly skin. A frog is an amphibian with smooth, wet skin."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["happy","angry","scared","purple"],"a":3,"why":"Happy, angry and scared are feelings. Purple is a colour."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["fridge","fan","kettle","spoon"],"a":3,"why":"Fridge, fan and kettle use electricity (appliances). A spoon does not."},
    {"t":"mcq","lv":"B","q":"Which is the odd one out?","o":["elbow","knee","shoulder","sleeve"],"a":3,"why":"Elbow, knee and shoulder are body parts. A sleeve is part of clothing."},
    {"t":"mcq","lv":"B","q":"Milo, teh and orange juice are all ___.","o":["utensils","vehicles","appliances","beverages"],"a":3,"why":"Beverages means drinks."},
    {"t":"mcq","lv":"B","q":"Knives, forks and spoons are called ___.","o":["furniture","stationery","cutlery","clothing"],"a":2,"why":"Cutlery is the group name for knives, forks and spoons."},
    {"t":"mcq","lv":"B","q":"Rain, thunder and haze are all kinds of ___.","o":["feelings","weather","shapes","occupations"],"a":1,"why":"They describe what the sky and air are like, so they are weather."},
    {"t":"mcq","lv":"C","q":"Which is the odd one out?","o":["whale","dolphin","shark","seal"],"a":2,"why":"Whales, dolphins and seals are mammals that breathe air. A shark is a fish."},
    {"t":"mcq","lv":"C","q":"Which is the odd one out?","o":["ant","beetle","spider","grasshopper"],"a":2,"why":"Ants, beetles and grasshoppers are insects with six legs. A spider has eight legs."},
    {"t":"mcq","lv":"C","q":"Which is the odd one out?","o":["Mercury","Mars","Jupiter","the Moon"],"a":3,"why":"Mercury, Mars and Jupiter are planets. The Moon goes around the Earth, so it is not a planet."},
    {"t":"fix","lv":"B","q":"Pens, rulers and erasers are all furniture.","err":"furniture","a":"stationery","why":"Writing things are stationery. Furniture is tables, chairs and beds."},
    {"t":"fix","lv":"B","q":"Buses, trains and taxis are all appliances.","err":"appliances","a":"vehicles","why":"Things that carry people from place to place are vehicles."},
    {"t":"fix","lv":"C","q":"The blue whale is the biggest fish in the world.","err":"fish","a":"mammal","why":"A whale breathes air and feeds its babies milk, so it is a mammal."},
    {"t":"fix","lv":"B","q":"Shirts, skirts and socks are vegetables.","err":"vegetables","a":["clothing", "clothes"],"why":"Things we wear are clothing."},
    {"t":"fix","lv":"C","q":"A spider is an insect because it has eight legs.","err":"an insect","a":"not an insect","why":"Insects have six legs. With eight legs, a spider is not an insect."},
    {"t":"fill","lv":"A","q":"Apples, mangoes and bananas are all ___.","a":["fruits","fruit"],"why":"They are the sweet parts of plants that hold seeds. They are fruits."},
    {"t":"fill","lv":"A","q":"A table, a chair and a bed are pieces of ___.","a":["furniture"],"why":"Furniture is the group name for large things in a room."},
    {"t":"fill","lv":"B","q":"Kang kong, spinach and cabbage are all ___.","a":["vegetables"],"why":"They are plants we cook and eat. They are vegetables."},
    {"t":"fill","lv":"B","q":"Doctor, nurse and firefighter are all ___.","a":["occupations","jobs"],"why":"These are jobs people do. Another word is occupations."},
    {"t":"fill","lv":"B","q":"Sparrows, crows and parrots are all ___.","a":["birds"],"why":"They have feathers, wings and beaks, so they are birds."},
    {"t":"fill","lv":"C","q":"Dogs, cats and humans feed their babies milk. They are all ___.","a":["mammals"],"why":"Animals that feed their babies milk are mammals."},
    {"t":"trans","lv":"B","q":"Rewrite using one group word: I packed my pencils, pens, ruler and eraser.","a":["I packed my stationery."],"why":"Stationery is the group word for pencils, pens, rulers and erasers."}
  ]
});
