window.VG = window.VG || [];

window.VG.push({
  id: "en-g-sva",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Subject–verb agreement",
  lv: "A",
  intro: "The subject (who or what the sentence is about) and the verb must match, like a pair of socks. One person or thing takes one form of the verb; many take another.",
  rules: [
    { h: "One person or thing: add s", html: "In the present tense, after <b>he, she, it</b> or one name, add <b>-s</b> or <b>-es</b> to the verb.<br>✓ Ravi <b>plays</b> chess. ✓ She <b>watches</b> TV.<br>✗ Ravi play chess." },
    { h: "Many, or I / you / we / they: no s", html: "After <b>I, you, we, they</b> or more than one person, use the verb without s.<br>✓ The boys <b>play</b> football. ✓ I <b>like</b> mangoes.<br>✗ The boys plays football." },
    { h: "am / is / are", html: "<b>I am</b>. <b>He, she, it is</b> (one). <b>You, we, they are</b> (many).<br>✓ The cat <b>is</b> asleep. ✓ The cats <b>are</b> asleep." },
    { h: "was / were", html: "In the past: <b>I, he, she, it was</b>. <b>You, we, they were</b>.<br>✓ Grandpa <b>was</b> at home. ✓ The children <b>were</b> tired." },
    { h: "has / have", html: "<b>He, she, it has</b>. <b>I, you, we, they have</b>.<br>✓ Mei <b>has</b> a dog. ✓ My parents <b>have</b> a car." },
    { h: "doesn't / don't", html: "<b>He, she, it doesn't</b>. <b>I, you, we, they don't</b>. After does or doesn't, the verb has <b>no s</b>.<br>✓ Ahmad <b>doesn't like</b> durian. ✗ Ahmad doesn't likes durian." },
    { h: "Find the real subject", html: "Ignore the words in between. <b>The box</b> of crayons <b>is</b> on the desk (one box).<br>✓ The flowers in the garden <b>are</b> pretty." }
  ],
  words: [],
  mistakes: [
    { wrong: "My brother play the violin.", right: "My brother plays the violin.", why: "One person (he) → add s: plays." },
    { wrong: "The children was noisy.", right: "The children were noisy.", why: "Children = many → were." },
    { wrong: "She don't like spicy food.", right: "She doesn't like spicy food.", why: "She → doesn't." },
    { wrong: "Does he wants a drink?", right: "Does he want a drink?", why: "Does already has the s, so the verb after it has no s." },
    { wrong: "The box of pencils are on the table.", right: "The box of pencils is on the table.", why: "The subject is the box (one), not the pencils → is." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "My sister ___ the piano every Sunday.", o: ["play","plays","playing"], a: 1, why: "My sister = one person (she) → add s: plays." },
    { t: "mcq", lv: "A", q: "The boys ___ football at the void deck after school.", o: ["plays","play","playing"], a: 1, why: "The boys = many (they) → no s: play." },
    { t: "mcq", lv: "A", q: "Mei Ling ___ to school by bus.", o: ["go","goes","going"], a: 1, why: "Mei Ling = one person (she). Go ends in o, so add -es: goes." },
    { t: "mcq", lv: "A", q: "We ___ in the same class.", o: ["is","are","am"], a: 1, why: "We always goes with are." },
    { t: "mcq", lv: "A", q: "I ___ hungry after PE.", o: ["am","is","are"], a: 0, why: "I always goes with am." },
    { t: "mcq", lv: "A", q: "The cat ___ sleeping on the sofa.", o: ["is","are","am"], a: 0, why: "The cat = one animal (it) → is." },
    { t: "mcq", lv: "A", q: "Yesterday, the children ___ at the playground.", o: ["was","were","is"], a: 1, why: "Yesterday = past. The children = many → were." },
    { t: "mcq", lv: "A", q: "Grandpa ___ at the hawker centre this morning.", o: ["was","were","are"], a: 0, why: "This morning is over, so use the past. Grandpa = one person → was." },
    { t: "mcq", lv: "A", q: "She ___ a new pencil case.", o: ["have","has","having"], a: 1, why: "She → has." },
    { t: "mcq", lv: "A", q: "My parents ___ a red car.", o: ["has","have","having"], a: 1, why: "My parents = two people (they) → have." },
    { t: "mcq", lv: "B", q: "Ahmad ___ like durian.", o: ["don't","doesn't","isn't","not"], a: 1, why: "Ahmad = he → doesn't. We say 'doesn't like', not 'isn't like'." },
    { t: "mcq", lv: "B", q: "They ___ want to miss the MRT.", o: ["doesn't","don't","isn't","aren't"], a: 1, why: "They → don't. We say 'don't want', never 'aren't want': is/are are not used to make a normal verb negative." },
    { t: "mcq", lv: "B", q: "My friends and I ___ going to the library after school.", o: ["is","am","are","was"], a: 2, why: "My friends and I = more than one person (we) → are." },
    { t: "mcq", lv: "B", q: "___ your brother in Primary 5?", o: ["Is","Are","Am","Do"], a: 0, why: "Your brother = one person (he) → Is." },
    { t: "mcq", lv: "B", q: "___ the twins like ice kachang?", o: ["Does","Do","Is","Are"], a: 1, why: "The twins = two people (they) → Do. To ask a question with a doing/feeling verb like 'like', we use do/does, not is/are." },
    { t: "mcq", lv: "B", q: "Our teacher ___ the class every morning.", o: ["greet","greets","greeting","are greet"], a: 1, why: "Our teacher = one person → add s: greets." },
    { t: "mcq", lv: "B", q: "The baby ___ when she is hungry.", o: ["cry","cries","crys","crying"], a: 1, why: "One baby → add s. Cry ends in consonant + y, so change y to i and add -es: cries." },
    { t: "mcq", lv: "B", q: "Rani and her sister ___ at Block 25.", o: ["lives","live","living","is live"], a: 1, why: "Rani and her sister = two people (they) → live, with no s." },
    { t: "mcq", lv: "B", q: "The school bus ___ at our block at 6.30 a.m. every day.", o: ["arrive","arrives","arriving","are arrive"], a: 1, why: "The school bus = one thing (it) → arrives." },
    { t: "mcq", lv: "C", q: "The box of crayons ___ on my desk.", o: ["are","is","were","have"], a: 1, why: "The real subject is the box (one). 'Of crayons' just describes it → is." },
    { t: "mcq", lv: "C", q: "The flowers in the garden ___ beautiful.", o: ["is","are","was","has"], a: 1, why: "The real subject is the flowers (many), not the garden → are." },
    { t: "fix", lv: "A", q: "He play chess with his grandfather.", err: "play", a: "plays", why: "He = one person → add s: plays." },
    { t: "fix", lv: "A", q: "The students was very quiet during the test.", err: "was", a: "were", why: "The students = many → were." },
    { t: "fix", lv: "A", q: "You is my best friend.", err: "is", a: "are", why: "You always goes with are." },
    { t: "fix", lv: "B", q: "My mother don't drink coffee.", err: "don't", a: "doesn't", why: "My mother = she → doesn't." },
    { t: "fix", lv: "B", q: "Wei Jie have two goldfish.", err: "have", a: "has", why: "Wei Jie = one person (he) → has." },
    { t: "fix", lv: "B", q: "The shoes in the cupboard is dirty.", err: "is", a: "are", why: "The real subject is the shoes (many), not the cupboard → are." },
    { t: "fill", lv: "A", q: "Siti ___ (watch) cartoons on Saturday mornings.", a: ["watches"], why: "Siti = she → add s. Watch ends in ch, so add -es: watches." },
    { t: "fill", lv: "A", q: "The dogs ___ (bark) at the postman every morning.", a: ["bark","barked"], why: "The dogs = many → no s: bark. (Barked is also fine if you mean the past.)" },
    { t: "fill", lv: "A", q: "Jun Hao ___ (have) a cough today.", a: ["has"], why: "Jun Hao = he → has." },
    { t: "fill", lv: "B", q: "My uncle ___ (fly) planes for a living.", a: ["flies","flew"], why: "My uncle = he → add s. Fly ends in consonant + y, so change y to i: flies." },
    { t: "fill", lv: "B", q: "The children ___ (be) tired after the long walk yesterday.", a: ["were"], why: "Yesterday = past. The children = many → were." },
    { t: "fill", lv: "B", q: "Does she ___ (know) the way to the MRT station?", a: ["know"], why: "After does, use the verb with no s: know." }
  ]
});

window.VG.push({
  id: "en-g-sva2",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Tricky subject–verb agreement",
  lv: "C",
  intro: "Some subjects try to trick you: is it one or many? Learn these special patterns and you will catch the traps that often appear in school exams.",
  rules: [
    { h: "either…or, neither…nor: look at the nearer one", html: "The verb agrees with the subject <b>closer to it</b>.<br>✓ Neither the teacher nor <b>the pupils know</b>.<br>✓ Neither the pupils nor <b>the teacher knows</b>." },
    { h: "as well as, along with, together with", html: "These words add extra information but do <b>not</b> change the subject. The verb agrees with the <b>first</b> subject.<br>✓ <b>The captain</b>, as well as his players, <b>is</b> excited.<br>✗ The captain, as well as his players, are excited." },
    { h: "one of the…", html: "<b>One</b> is the subject, so the verb is singular.<br>✓ <b>One</b> of the boys <b>has</b> lost his bottle.<br>✗ One of the boys have lost his bottle." },
    { h: "each, every, everyone, nobody, neither of", html: "These mean one at a time → singular verb.<br>✓ <b>Each</b> of the girls <b>gets</b> a ribbon. ✓ <b>Everyone wants</b> to go. ✓ <b>Nobody knows</b>. ✓ <b>Neither</b> of the twins <b>likes</b> durian." },
    { h: "a pair of / scissors, trousers", html: "<b>A pair of</b> scissors <b>is</b> (one pair). Without 'a pair of', words like <b>scissors, trousers, spectacles, shorts</b> are plural.<br>✓ My trousers <b>are</b> too long." },
    { h: "the number of / a number of", html: "<b>The number of</b> pupils <b>is</b> growing (one number).<br><b>A number of</b> pupils <b>are</b> absent (= many pupils)." },
    { h: "there is / there are", html: "Look at the noun that comes <b>after</b> the verb.<br>✓ There <b>is</b> some milk. ✓ There <b>are</b> many stalls." },
    { h: "Group words (collective nouns)", html: "When a group such as <b>class, family, team</b> acts as one unit, use a singular verb.<br>✓ The class <b>is</b> going on a trip. ✓ My family <b>is</b> moving house." }
  ],
  words: [],
  mistakes: [
    { wrong: "Neither Raju nor his friends wants to go home.", right: "Neither Raju nor his friends want to go home.", why: "Neither…nor: look at the nearer subject. His friends = many → want." },
    { wrong: "The principal, as well as the teachers, were at the gate.", right: "The principal, as well as the teachers, was at the gate.", why: "As well as does not change the subject. The principal = one → was." },
    { wrong: "One of the girls are my neighbour.", right: "One of the girls is my neighbour.", why: "The subject is one → is." },
    { wrong: "Everybody have finished.", right: "Everybody has finished.", why: "Everybody is singular → has." },
    { wrong: "A number of stalls is closed.", right: "A number of stalls are closed.", why: "A number of = many → are." },
    { wrong: "My spectacles is broken.", right: "My spectacles are broken.", why: "Spectacles is a plural word → are." }
  ],
  items: [
    { t: "mcq", lv: "B", q: "Either Ali or Ben ___ going to carry the flag.", o: ["is","are","were","have"], a: 0, why: "Either…or: look at the nearer subject. Ben = one → is." },
    { t: "mcq", lv: "C", q: "Neither the teacher nor the pupils ___ the answer.", o: ["know","knows","knowing","has known"], a: 0, why: "Neither…nor: the nearer subject is the pupils (many) → know." },
    { t: "mcq", lv: "C", q: "Neither the pupils nor the teacher ___ the answer.", o: ["know","knows","are knowing","have known"], a: 1, why: "Neither…nor: the nearer subject is the teacher (one) → knows." },
    { t: "mcq", lv: "C", q: "Either my parents or my aunt ___ coming to the concert.", o: ["is","are","were","have"], a: 0, why: "Either…or: the nearer subject is my aunt (one) → is." },
    { t: "mcq", lv: "C", q: "The captain, as well as his players, ___ excited about the match.", o: ["is","are","were","have been"], a: 0, why: "As well as does not change the subject. The captain = one → is." },
    { t: "mcq", lv: "C", q: "My brothers, along with my cousin, ___ at the beach now.", o: ["is","are","was","has"], a: 1, why: "Along with does not change the subject. My brothers = many → are." },
    { t: "mcq", lv: "B", q: "One of the boys ___ lost his water bottle.", o: ["have","has","are","were"], a: 1, why: "The subject is one (one of the boys) → has." },
    { t: "mcq", lv: "B", q: "Each of the girls ___ a ribbon.", o: ["get","gets","are getting","have got"], a: 1, why: "Each = one at a time → singular: gets." },
    { t: "mcq", lv: "B", q: "Every pupil ___ to wear a name tag.", o: ["have","has","are","were"], a: 1, why: "Every pupil = each single pupil → has." },
    { t: "mcq", lv: "C", q: "A pair of scissors ___ on the teacher's desk.", o: ["is","are","were","have"], a: 0, why: "A pair = one pair → is." },
    { t: "mcq", lv: "C", q: "My new trousers ___ too long.", o: ["is","are","was","has"], a: 1, why: "Trousers is a plural word (two legs) → are." },
    { t: "mcq", lv: "C", q: "The number of pupils in the hall ___ growing.", o: ["is","are","were","have"], a: 0, why: "The number of = one number → is." },
    { t: "mcq", lv: "C", q: "A number of pupils ___ absent today.", o: ["is","are","was","has"], a: 1, why: "A number of = many → are." },
    { t: "mcq", lv: "B", q: "There ___ some milk in the fridge.", o: ["is","are","were","have"], a: 0, why: "Look at the noun after the verb: milk cannot be counted, so it takes is." },
    { t: "mcq", lv: "B", q: "There ___ many stalls at the hawker centre.", o: ["is","are","was","has"], a: 1, why: "Look at the noun after the verb: many stalls → are." },
    { t: "mcq", lv: "C", q: "The class ___ going on a trip to the Science Centre.", o: ["is","are","were","have"], a: 0, why: "The class acts as one group here → is." },
    { t: "mcq", lv: "C", q: "My family ___ moving to a new HDB flat next month.", o: ["is","are","were","have"], a: 0, why: "The family moves together as one unit → is." },
    { t: "mcq", lv: "C", q: "Neither of the twins ___ to swim.", o: ["like","likes","are liking","have liked"], a: 1, why: "Neither of = not this one and not that one, one at a time → likes." },
    { t: "mcq", lv: "C", q: "Each boy and each girl ___ a turn on the swing.", o: ["get","gets","are getting","have got"], a: 1, why: "With each, we think of one child at a time → gets." },
    { t: "fix", lv: "C", q: "Neither Raju nor his friends wants to go home.", err: "wants", a: "want", why: "Neither…nor: the nearer subject is his friends (many) → want." },
    { t: "fix", lv: "C", q: "The principal, as well as the teachers, were at the gate.", err: "were", a: "was", why: "As well as does not change the subject. The principal = one → was." },
    { t: "fix", lv: "B", q: "One of the girls are my neighbour.", err: "are", a: "is", why: "The subject is one → is." },
    { t: "fix", lv: "B", q: "Everybody have finished the worksheet.", err: "have", a: "has", why: "Everybody is singular → has." },
    { t: "fix", lv: "C", q: "A number of stalls is closed today.", err: "is", a: "are", why: "A number of = many stalls → are." },
    { t: "fix", lv: "C", q: "The number of cars on the road are increasing.", err: "are", a: "is", why: "The number of = one number → is." },
    { t: "fix", lv: "C", q: "My spectacles is broken.", err: "is", a: "are", why: "Spectacles is a plural word → are." },
    { t: "fill", lv: "C", q: "Either the cups or the plate ___ (need) washing.", a: ["needs"], why: "Either…or: the nearer subject is the plate (one) → needs." },
    { t: "fill", lv: "B", q: "Every child in the playground ___ (be) having fun.", a: ["is","was"], why: "Every child = each single child → is (or was for the past)." },
    { t: "fill", lv: "B", q: "There ___ (be) two new pupils in our class.", a: ["are","were"], why: "Look after the verb: two new pupils = many → are (or were for the past)." },
    { t: "fill", lv: "C", q: "These days, a pair of shoes ___ (cost) a lot of money.", a: ["costs"], why: "A pair = one pair → costs." },
    { t: "fill", lv: "B", q: "Somebody ___ (be) knocking on the door.", a: ["is","was"], why: "Somebody is singular → is (or was for the past)." },
    { t: "fill", lv: "C", q: "The girl, together with her parents, ___ (visit) her grandmother every Sunday.", a: ["visits"], why: "Together with does not change the subject. The girl = one → visits." },
    { t: "trans", lv: "C", q: "Combine using 'Neither…nor': Mei does not like broccoli. Her brothers do not like broccoli either.", a: ["Neither Mei nor her brothers like broccoli.","Neither her brothers nor Mei likes broccoli."], why: "Neither…nor already means 'not', so drop 'does not'. The nearer subject is her brothers (many) → like." }
  ]
});

window.VG.push({
  id: "en-g-modals",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Can, could, may, might, must, should, would",
  lv: "B",
  intro: "These little helping verbs (modals) change the meaning of a sentence: they show if something is possible, allowed, needed or a good idea. Picking the right one makes your writing clear and polite.",
  rules: [
    { h: "can / could: ability", html: "<b>Can</b> = able to now. <b>Could</b> = able to in the past.<br>✓ I <b>can</b> swim. ✓ When I was four, I <b>could not</b> read." },
    { h: "may / can / could: asking and giving permission", html: "<b>May I…?</b> is the most polite. <b>Can</b> is also used for permission.<br>✓ <b>May</b> I go to the toilet, please?" },
    { h: "might / may: maybe", html: "Use <b>might</b> or <b>may</b> when you are not sure.<br>✓ Take an umbrella. It <b>might</b> rain." },
    { h: "must / mustn't: rules", html: "<b>Must</b> = you have to. <b>Mustn't</b> = you are not allowed to.<br>✓ You <b>must</b> stop at a red light. ✓ You <b>mustn't</b> run near the pool." },
    { h: "should: advice", html: "<b>Should</b> = it is a good idea.<br>✓ You look tired. You <b>should</b> rest." },
    { h: "would / could: polite offers and requests", html: "✓ <b>Would</b> you like some tea? ✓ <b>Could</b> you help me, please?<br><b>Would</b> also talks about imagined things: If I had wings, I <b>would</b> fly." },
    { h: "Must / can't: being sure", html: "<b>Must</b> = I am sure it is true. <b>Can't</b> = I am sure it is not true.<br>✓ He ran for an hour. He <b>must</b> be tired. ✓ The lights are off. They <b>can't</b> be home." },
    { h: "After a modal: plain verb", html: "No <b>s</b>, no <b>to</b>, no <b>-ed</b> after a modal.<br>✓ She can <b>sing</b>. ✗ She can sings. ✗ You must to go." }
  ],
  words: [],
  mistakes: [
    { wrong: "She can sings very well.", right: "She can sing very well.", why: "After can, use the plain verb with no s." },
    { wrong: "You must to wear a helmet.", right: "You must wear a helmet.", why: "Never put to after must." },
    { wrong: "Yesterday I can't find my bottle.", right: "Yesterday I couldn't find my bottle.", why: "Yesterday = past → couldn't." },
    { wrong: "We should went home.", right: "We should go home.", why: "After should, use the plain verb: go." },
    { wrong: "He mights come later.", right: "He might come later.", why: "Modals never take an s." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Wen Hui ___ swim very fast. She won a gold medal.", o: ["can","mustn't","should"], a: 0, why: "This is about her ability → can." },
    { t: "mcq", lv: "A", q: "When I was four, I ___ not read.", o: ["can","could","may"], a: 1, why: "Ability in the past → could not." },
    { t: "mcq", lv: "B", q: "___ I go to the toilet, please, Mrs Lim?", o: ["May","Must","Should","Would"], a: 0, why: "Asking for permission politely → May I…?" },
    { t: "mcq", lv: "B", q: "You look tired. You ___ go to bed early tonight.", o: ["should","mustn't","would","may not"], a: 0, why: "This is a piece of advice → should." },
    { t: "mcq", lv: "B", q: "Pupils ___ wear their school uniform on school days. It is a rule.", o: ["must","might","could","would"], a: 0, why: "A rule that you have to follow → must." },
    { t: "mcq", lv: "B", q: "You ___ run near the swimming pool. It is dangerous.", o: ["mustn't","must","should","can"], a: 0, why: "It is not allowed because it is dangerous → mustn't." },
    { t: "mcq", lv: "B", q: "Take an umbrella. It ___ rain later.", o: ["might","must","mustn't","would"], a: 0, why: "We are not sure it will rain → might." },
    { t: "mcq", lv: "B", q: "___ you like some more rice?", o: ["Would","Should","Must","May"], a: 0, why: "A polite offer → Would you like…?" },
    { t: "mcq", lv: "B", q: "___ you help me carry this box, please?", o: ["Could","Must","Should","May"], a: 0, why: "A polite request → Could you…? (We do not say 'May you'.)" },
    { t: "mcq", lv: "B", q: "My brother can ___ the guitar.", o: ["play","plays","to play","playing"], a: 0, why: "After can, use the plain verb: play." },
    { t: "mcq", lv: "B", q: "She should ___ her homework now.", o: ["do","does","did","to do"], a: 0, why: "After should, use the plain verb: do." },
    { t: "mcq", lv: "C", q: "The lights are off and nobody answers the door. The Lims ___ be at home.", o: ["can't","mustn't","shouldn't","needn't"], a: 0, why: "We are sure they are not at home → can't be." },
    { t: "mcq", lv: "C", q: "Darren has been running for an hour. He ___ be very tired.", o: ["must","can","may not","shouldn't"], a: 0, why: "We are sure it is true → must be." },
    { t: "mcq", lv: "B", q: "If I had wings, I ___ fly to school.", o: ["would","will","must","should"], a: 0, why: "This is imagined, not real (If I had…) → would." },
    { t: "mcq", lv: "B", q: "Last year, my grandmother ___ walk without a stick, but now she needs one.", o: ["could","can","must","should"], a: 0, why: "Ability in the past (last year) → could." },
    { t: "mcq", lv: "B", q: "I'm not sure yet, but I ___ go to Jia Le's party. I haven't decided.", o: ["might","must","should","can't"], a: 0, why: "Not sure, not decided → might." },
    { t: "mcq", lv: "C", q: "Ravi was very sick yesterday, so he ___ go to school.", o: ["couldn't","can't","mustn't","shouldn't"], a: 0, why: "He was not able to, and it was in the past → couldn't." },
    { t: "mcq", lv: "B", q: "It is very hot today. You ___ drink plenty of water.", o: ["should","might","would","can't"], a: 0, why: "This is good advice → should." },
    { t: "mcq", lv: "B", q: "Dad says I ___ watch TV after I finish my homework.", o: ["can","must","should","would"], a: 0, why: "Dad is giving permission → can." },
    { t: "fix", lv: "A", q: "She can sings very well.", err: "sings", a: "sing", why: "After can, use the plain verb with no s: sing." },
    { t: "fix", lv: "B", q: "You must to wear a helmet when you cycle.", err: "must to wear", a: "must wear", why: "Never put to after must." },
    { t: "fix", lv: "B", q: "Yesterday I can't find my water bottle.", err: "can't", a: "couldn't", why: "Yesterday = past → couldn't." },
    { t: "fix", lv: "B", q: "We should went home before it gets dark.", err: "went", a: "go", why: "After should, use the plain verb: go." },
    { t: "fix", lv: "B", q: "He mights come to the party.", err: "mights", a: "might", why: "Modals never take an s: might." },
    { t: "fix", lv: "B", q: "You shouldn't to eat so many sweets.", err: "shouldn't to eat", a: "shouldn't eat", why: "Never put to after should or shouldn't." },
    { t: "fill", lv: "A", q: "I ___ (can/could) not open the jar yesterday, so Mum helped me.", a: ["could"], why: "Yesterday = past ability → could." },
    { t: "fill", lv: "B", q: "You ___ (must/might) stop when the traffic light is red.", a: ["must"], why: "It is a rule → must." },
    { t: "fill", lv: "B", q: "Bring a jacket. It ___ (might/must) be cold in the cinema.", a: ["might"], why: "We are not sure → might." },
    { t: "fill", lv: "B", q: "___ (Would/Must) you like to join our CCA?", a: ["Would","would"], why: "A polite invitation → Would you like…?" },
    { t: "fill", lv: "B", q: "You ___ (should/would) say sorry to your sister.", a: ["should"], why: "This is advice → should." },
    { t: "fill", lv: "B", q: "Children ___ (mustn't/needn't) play with fire.", a: ["mustn't"], why: "It is not allowed because it is dangerous → mustn't. (Needn't means it is not necessary.)" },
    { t: "trans", lv: "B", q: "Rewrite politely, starting with 'Could you': Pass me the salt.", a: ["Could you pass me the salt, please?","Could you please pass me the salt?","Could you pass me the salt?"], why: "Could you + plain verb makes an order into a polite request. End with a question mark." }
  ]
});

window.VG.push({
  id: "en-g-gerund",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "-ing or to + verb",
  lv: "C",
  intro: "When one verb follows another, the second one is either an -ing word (enjoy swimming) or to + verb (want to swim). The first verb decides which one to use, so these pairs are worth learning by heart.",
  rules: [
    { h: "Verbs followed by -ing", html: "<b>enjoy, finish, mind, keep, avoid, practise, miss, imagine</b><br>✓ I enjoy <b>swimming</b>. ✓ Would you mind <b>closing</b> the door?<br>✗ I enjoy to swim." },
    { h: "Verbs followed by to + verb", html: "<b>want, hope, decide, plan, agree, promise, learn, refuse, need</b><br>✓ I want <b>to swim</b>. ✓ We decided <b>to go</b>.<br>✗ I want swimming." },
    { h: "After a preposition: -ing", html: "After <b>at, in, of, for, about, before, after, without</b>, use -ing.<br>✓ good at <b>drawing</b> ✓ before <b>eating</b> ✓ thank you for <b>helping</b><br>Watch out: <b>looking forward to seeing</b> you (to is a preposition here)." },
    { h: "stop -ing / stop to", html: "<b>stop + -ing</b> = no longer do it. Dad stopped <b>eating</b> fried food.<br><b>stop + to</b> = stop in order to do something. We stopped <b>to buy</b> bubble tea." },
    { h: "remember / forget", html: "<b>remember / forget + to</b> = something you need to do. Remember <b>to switch</b> off the fan.<br><b>remember + -ing</b> = a memory of the past. I remember <b>visiting</b> the kampong." },
    { h: "-ing as the subject", html: "An -ing word can be the subject of a sentence.<br>✓ <b>Swimming</b> is my favourite sport." }
  ],
  words: [],
  mistakes: [
    { wrong: "I enjoy to read comics.", right: "I enjoy reading comics.", why: "Enjoy is followed by -ing." },
    { wrong: "My brother wants going out.", right: "My brother wants to go out.", why: "Want is followed by to + verb." },
    { wrong: "She is interested in learn Chinese.", right: "She is interested in learning Chinese.", why: "After a preposition (in), use -ing." },
    { wrong: "I am looking forward to see you.", right: "I am looking forward to seeing you.", why: "In 'look forward to', to is a preposition, so use -ing." },
    { wrong: "Remember locking the door when you go out.", right: "Remember to lock the door when you go out.", why: "Something you need to do later → remember to." }
  ],
  items: [
    { t: "mcq", lv: "B", q: "Ali enjoys ___ in the pool.", o: ["swim","swimming","to swim","swims"], a: 1, why: "Enjoy is followed by -ing: enjoys swimming." },
    { t: "mcq", lv: "B", q: "I want ___ a scientist when I grow up.", o: ["be","being","to be","been"], a: 2, why: "Want is followed by to + verb: want to be." },
    { t: "mcq", lv: "B", q: "Have you finished ___ your homework?", o: ["do","doing","to do","did"], a: 1, why: "Finish is followed by -ing: finished doing." },
    { t: "mcq", lv: "B", q: "Mum decided ___ chicken rice for dinner.", o: ["buy","buying","to buy","bought"], a: 2, why: "Decide is followed by to + verb: decided to buy." },
    { t: "mcq", lv: "C", q: "Would you mind ___ the window?", o: ["close","closing","to close","closed"], a: 1, why: "Mind is followed by -ing: mind closing." },
    { t: "mcq", lv: "B", q: "We hope ___ the zoo during the holidays.", o: ["visit","visiting","to visit","visited"], a: 2, why: "Hope is followed by to + verb: hope to visit." },
    { t: "mcq", lv: "C", q: "Please avoid ___ too much sugar.", o: ["eat","eating","to eat","ate"], a: 1, why: "Avoid is followed by -ing: avoid eating." },
    { t: "mcq", lv: "B", q: "Priya keeps ___ her pencil.", o: ["lose","losing","to lose","lost"], a: 1, why: "Keep (meaning 'do again and again') is followed by -ing: keeps losing." },
    { t: "mcq", lv: "C", q: "Jia Hui is good at ___ pictures.", o: ["draw","drawing","to draw","drew"], a: 1, why: "At is a preposition, and after a preposition we use -ing: good at drawing." },
    { t: "mcq", lv: "C", q: "Wash your hands before ___ your food.", o: ["eat","eating","to eat","ate"], a: 1, why: "Before is a preposition here, so use -ing: before eating." },
    { t: "mcq", lv: "C", q: "Dad stopped ___ fried food because it was bad for his health.", o: ["eat","eating","to eat","ate"], a: 1, why: "He no longer eats it → stop + -ing: stopped eating." },
    { t: "mcq", lv: "C", q: "On the way home, we stopped ___ some bubble tea.", o: ["buy","buying","to buy","bought"], a: 2, why: "We stopped walking in order to buy something → stop + to: stopped to buy." },
    { t: "mcq", lv: "C", q: "Remember ___ off the fan before you leave the classroom.", o: ["switch","switching","to switch","switched"], a: 2, why: "This is something you need to do → remember to switch." },
    { t: "mcq", lv: "C", q: "I remember ___ my grandmother's kampong house when I was small.", o: ["visit","visiting","to visit","visited"], a: 1, why: "This is a memory of the past → remember + -ing: remember visiting." },
    { t: "mcq", lv: "C", q: "Don't forget ___ your library books tomorrow.", o: ["return","returning","to return","returned"], a: 2, why: "Something you need to do later → forget to: forget to return." },
    { t: "mcq", lv: "B", q: "___ is my favourite sport.", o: ["Swim","Swimming","To swimming","Swims"], a: 1, why: "An -ing word can be the subject: Swimming is…" },
    { t: "mcq", lv: "C", q: "The boy refused ___ his toys with his brother.", o: ["share","sharing","to share","shared"], a: 2, why: "Refuse is followed by to + verb: refused to share." },
    { t: "mcq", lv: "C", q: "Mei Ling practises ___ the piano every day.", o: ["play","playing","to play","played"], a: 1, why: "Practise is followed by -ing: practises playing." },
    { t: "mcq", lv: "B", q: "Thank you for ___ me with my bags.", o: ["help","helping","to help","helped"], a: 1, why: "For is a preposition, so use -ing: for helping." },
    { t: "fix", lv: "B", q: "I enjoy to read comics before bedtime.", err: "to read", a: "reading", why: "Enjoy is followed by -ing: enjoy reading." },
    { t: "fix", lv: "B", q: "My brother wants going to the playground.", err: "going", a: "to go", why: "Want is followed by to + verb: wants to go." },
    { t: "fix", lv: "C", q: "She is interested in learn Chinese.", err: "learn", a: "learning", why: "After a preposition (in), use -ing: learning." },
    { t: "fix", lv: "C", q: "We agreed meeting at the MRT station at nine.", err: "meeting", a: "to meet", why: "Agree is followed by to + verb: agreed to meet." },
    { t: "fix", lv: "C", q: "Wei Ming finished to clean his room before lunch.", err: "to clean", a: "cleaning", why: "Finish is followed by -ing: finished cleaning." },
    { t: "fix", lv: "C", q: "I am looking forward to see you on Saturday.", err: "see", a: "seeing", why: "In 'look forward to', to is a preposition, so use -ing: seeing." },
    { t: "fill", lv: "B", q: "Nurul promised ___ (tidy) her room.", a: ["to tidy"], why: "Promise is followed by to + verb: promised to tidy." },
    { t: "fill", lv: "C", q: "Can you imagine ___ (live) on the moon?", a: ["living"], why: "Imagine is followed by -ing: imagine living." },
    { t: "fill", lv: "C", q: "He left without ___ (say) goodbye.", a: ["saying"], why: "Without is a preposition, so use -ing: without saying." },
    { t: "fill", lv: "B", q: "We plan ___ (go) to Sentosa on Saturday.", a: ["to go"], why: "Plan is followed by to + verb: plan to go." },
    { t: "fill", lv: "C", q: "I miss ___ (play) with my cousins in Malaysia.", a: ["playing"], why: "Miss is followed by -ing: miss playing." },
    { t: "fill", lv: "B", q: "Siew Lan learnt ___ (ride) a bicycle when she was six.", a: ["to ride"], why: "Learn is followed by to + verb: learnt to ride." },
    { t: "trans", lv: "C", q: "Combine using 'before': Zara brushed her teeth. Then she went to bed.", a: ["Zara brushed her teeth before going to bed.","Before going to bed, Zara brushed her teeth.","Zara brushed her teeth before she went to bed."], why: "Before + -ing (before going) is neat. You can also say 'before she went'. Do not keep 'then'." }
  ]
});

window.VG.push({
  id: "en-g-verbprep",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Words that go together",
  lv: "B",
  intro: "Some words always hold hands with the same little word: good at, afraid of, depend on. There is no rule that tells you which one, so learn them as a pair, like a phone number.",
  rules: [
    { h: "Feelings + of", html: "<b>afraid of, scared of, proud of, fond of, tired of, full of</b><br>✓ She is afraid <b>of</b> the dark. ✗ afraid from" },
    { h: "Good at, interested in", html: "<b>good at, bad at</b> a skill. <b>interested in</b> a topic.<br>✓ good <b>at</b> maths ✓ interested <b>in</b> dinosaurs ✗ good in maths" },
    { h: "About, with, to", html: "<b>worried about, excited about, angry with</b> a person, <b>kind to, similar to, different from</b>.<br>✓ Mum was angry <b>with</b> me. ✓ My bag is different <b>from</b> yours." },
    { h: "Words + on, for", html: "<b>depend on, insist on, congratulate someone on</b>; <b>wait for, apologise for, thank someone for</b>, <b>famous for</b>.<br>✓ It depends <b>on</b> the weather. ✓ He apologised <b>for</b> being late." },
    { h: "Verbs + to, at, after, with", html: "<b>listen to, belong to, laugh at, shout at, look after, agree with</b> someone.<br>✓ Listen <b>to</b> me. ✓ Who will look <b>after</b> the dog?" },
    { h: "After these little words: -ing", html: "If a verb comes after the little word, add -ing.<br>✓ good at <b>singing</b> ✓ insisted on <b>paying</b> ✗ insisted to pay" }
  ],
  words: [],
  mistakes: [
    { wrong: "Daniel is afraid from spiders.", right: "Daniel is afraid of spiders.", why: "The pair is afraid of." },
    { wrong: "My sister is good in badminton.", right: "My sister is good at badminton.", why: "The pair is good at." },
    { wrong: "Don't laugh on your friends.", right: "Don't laugh at your friends.", why: "The pair is laugh at." },
    { wrong: "He insisted to pay for the meal.", right: "He insisted on paying for the meal.", why: "The pair is insist on, and after on we use -ing." },
    { wrong: "I am worried for my test.", right: "I am worried about my test.", why: "We are worried about something." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Meera is good ___ maths.", o: ["at","in","on"], a: 0, why: "The pair is good at." },
    { t: "mcq", lv: "A", q: "My little sister is afraid ___ the dark.", o: ["of","from","with"], a: 0, why: "The pair is afraid of." },
    { t: "mcq", lv: "B", q: "Joshua is interested ___ dinosaurs.", o: ["in","on","at","about"], a: 0, why: "The pair is interested in." },
    { t: "mcq", lv: "B", q: "Grandma is very proud ___ my good results.", o: ["of","with","for","about"], a: 0, why: "The pair is proud of." },
    { t: "mcq", lv: "B", q: "Whether we go to the beach depends ___ the weather.", o: ["on","of","at","with"], a: 0, why: "The pair is depend on." },
    { t: "mcq", lv: "B", q: "Kai Xin apologised ___ being late.", o: ["for","of","about","on"], a: 0, why: "We apologise for something we did wrong." },
    { t: "mcq", lv: "A", q: "Please listen ___ your teacher.", o: ["to","at","on"], a: 0, why: "The pair is listen to." },
    { t: "mcq", lv: "A", q: "This water bottle belongs ___ Farah.", o: ["to","with","at"], a: 0, why: "The pair is belong to." },
    { t: "mcq", lv: "B", q: "We waited ___ the bus for twenty minutes.", o: ["for","to","on","at"], a: 0, why: "The pair is wait for." },
    { t: "mcq", lv: "B", q: "Who will look ___ your dog when you go on holiday?", o: ["after","for","at","on"], a: 0, why: "Look after = take care of. (Look for means search for something you lost.)" },
    { t: "mcq", lv: "B", q: "My cat is very different ___ your cat.", o: ["from","with","of","on"], a: 0, why: "The pair is different from." },
    { t: "mcq", lv: "B", q: "The bakery is famous ___ its egg tarts.", o: ["for","of","about","with"], a: 0, why: "The pair is famous for." },
    { t: "mcq", lv: "B", q: "The box was full ___ old toys.", o: ["of","with","in","from"], a: 0, why: "The pair is full of." },
    { t: "mcq", lv: "C", q: "Mr Lee congratulated Hana ___ winning the race.", o: ["on","at","about","with"], a: 0, why: "We congratulate someone on something." },
    { t: "mcq", lv: "B", q: "I agree ___ you. Your idea is a good one.", o: ["with","to","on","at"], a: 0, why: "We agree with a person." },
    { t: "mcq", lv: "C", q: "Mum was angry ___ me for breaking the vase.", o: ["with","of","on","to"], a: 0, why: "We are angry with a person." },
    { t: "mcq", lv: "B", q: "The pupils were excited ___ Sports Day.", o: ["about","of","on","to"], a: 0, why: "The pair is excited about." },
    { t: "mcq", lv: "B", q: "Aunty Lucy is always kind ___ animals.", o: ["to","with","for","at"], a: 0, why: "The pair is kind to." },
    { t: "mcq", lv: "C", q: "After many tries, he succeeded ___ fixing his bicycle.", o: ["in","on","at","to"], a: 0, why: "The pair is succeed in, followed by -ing." },
    { t: "fix", lv: "A", q: "Daniel is afraid from spiders.", err: "from", a: "of", why: "The pair is afraid of." },
    { t: "fix", lv: "B", q: "We are proud for our school choir.", err: "for", a: "of", why: "The pair is proud of." },
    { t: "fix", lv: "B", q: "My sister is good in badminton.", err: "good in", a: "good at", why: "The pair is good at." },
    { t: "fix", lv: "B", q: "Don't laugh on your friends when they make mistakes.", err: "laugh on", a: "laugh at", why: "The pair is laugh at." },
    { t: "fix", lv: "C", q: "He insisted to pay for the meal.", err: "to pay", a: "on paying", why: "The pair is insist on, and after on we use -ing: on paying." },
    { t: "fix", lv: "B", q: "I am worried for my spelling test tomorrow.", err: "worried for", a: "worried about", why: "We are worried about something." },
    { t: "fill", lv: "A", q: "Thank you ___ the lovely present.", a: ["for"], why: "We thank someone for something." },
    { t: "fill", lv: "B", q: "Samy is fond ___ his grandfather's stories.", a: ["of"], why: "The pair is fond of." },
    { t: "fill", lv: "B", q: "Your drawing is very similar ___ mine.", a: ["to"], why: "The pair is similar to." },
    { t: "fill", lv: "B", q: "Please don't shout ___ your little brother.", a: ["at"], why: "We shout at someone when we are angry." },
    { t: "fill", lv: "B", q: "Mrs Goh complained ___ the noise from the flat upstairs.", a: ["about"], why: "We complain about something." },
    { t: "fill", lv: "A", q: "Are you scared ___ thunder?", a: ["of"], why: "The pair is scared of." },
    { t: "trans", lv: "B", q: "Rewrite using 'good at': Lina can sing very well.", a: ["Lina is good at singing.","Lina is very good at singing."], why: "Good at + -ing: is good at singing. 'Very well' is not needed any more." }
  ]
});
