window.VG = window.VG || [];

window.VG.push({
  id: "en-g-present",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Simple present and present continuous",
  lv: "A",
  intro: "We use the simple present for things that happen again and again, and the present continuous for things happening right now. Choosing the right one makes your sentences clear.",
  rules: [
    { h: "Simple present: habits and facts", html: "Use it for things we do <b>regularly</b> and things that are <b>always true</b>.<br>✓ I <b>walk</b> to school every day.<br>✓ The sun <b>rises</b> in the east.<br>Signal words: <b>every day, always, usually, often, sometimes, never</b>." },
    { h: "He, she, it: add s", html: "With one person or thing (he, she, it, Mum, the dog), add <b>s</b> to the verb.<br>play → <b>plays</b>, go → <b>goes</b>, watch → <b>watches</b>, fly → <b>flies</b>.<br>✓ My sister <b>plays</b> the piano.<br>✗ My sister play the piano." },
    { h: "Present continuous: happening now", html: "Use <b>am / is / are + -ing</b> for an action happening <b>at this moment</b>.<br>✓ I <b>am reading</b>. She <b>is sleeping</b>. They <b>are swimming</b>.<br>Signal words: <b>now, right now, at the moment, Look!, Listen!</b>" },
    { h: "Spelling the -ing form", html: "Most verbs: just add -ing (read → reading).<br>Silent e: drop the e (make → <b>making</b>, ride → <b>riding</b>).<br>Short verb ending in one vowel + one consonant: double it (swim → <b>swimming</b>, run → <b>running</b>, sit → <b>sitting</b>).<br>ie → y (lie → <b>lying</b>)." },
    { h: "Questions and 'not'", html: "Simple present uses <b>do / does</b> + the plain verb.<br>✓ <b>Does</b> he <b>like</b> durians? ✗ Does he likes durians?<br>✓ She <b>does not play</b> chess. ✗ She does not plays chess." },
    { h: "Verbs that are not usually -ing", html: "Some verbs are about thinking or feeling, not doing: <b>like, love, want, need, know, believe, understand</b>. Use the simple present.<br>✓ I <b>want</b> a drink. ✗ I am wanting a drink.<br>✓ I <b>know</b> the answer. ✗ I am knowing the answer." }
  ],
  words: [],
  mistakes: [
    { wrong: "My brother play football every Saturday.", right: "My brother plays football every Saturday.", why: "One person (he) and a habit → add s: plays." },
    { wrong: "Look! The bus come.", right: "Look! The bus is coming.", why: "'Look!' means it is happening now → is coming." },
    { wrong: "Does she likes ice cream?", right: "Does she like ice cream?", why: "After does, use the plain verb with no s." },
    { wrong: "I am knowing the way.", right: "I know the way.", why: "Know is a thinking word, so we do not usually add -ing." },
    { wrong: "The children are swiming.", right: "The children are swimming.", why: "Swim has one vowel and one consonant at the end → double the m." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Mei Ling ___ to school by bus every day.", o: ["go","goes","going"], a: 1, why: "'Every day' is a habit, and Mei Ling is one person → goes." },
    { t: "mcq", lv: "A", q: "Look! The cat ___ on the wall.", o: ["sleeps","is sleeping","sleep"], a: 1, why: "'Look!' tells us it is happening right now → is sleeping." },
    { t: "mcq", lv: "A", q: "We ___ our grandparents every Sunday.", o: ["visit","visits","are visit"], a: 0, why: "A habit (every Sunday) with 'we' → visit, no s." },
    { t: "mcq", lv: "A", q: "Listen! Arjun ___ the piano.", o: ["plays","is playing","play"], a: 1, why: "'Listen!' means we can hear it now → is playing." },
    { t: "mcq", lv: "A", q: "The sun always ___ in the east.", o: ["rises","is rising","rise"], a: 0, why: "A fact that is always true → simple present. The sun is one thing → rises." },
    { t: "mcq", lv: "A", q: "My father ___ coffee every morning at the hawker centre.", o: ["drink","drinks","is drinking"], a: 1, why: "'Every morning' is a habit. My father = he → drinks." },
    { t: "mcq", lv: "A", q: "___ your brother play football?", o: ["Do","Does","Is"], a: 1, why: "Your brother = he, so the question starts with Does." },
    { t: "mcq", lv: "A", q: "They ___ not like spicy food.", o: ["do","does","is"], a: 0, why: "With they, we use do not (don't)." },
    { t: "mcq", lv: "A", q: "The birds ___ in the tree now.", o: ["sing","are singing","is singing"], a: 1, why: "'Now' → present continuous. Birds = more than one → are singing." },
    { t: "mcq", lv: "B", q: "Please be quiet. The baby ___.", o: ["sleeps","is sleeping","slept","sleep"], a: 1, why: "We must be quiet because the baby is sleeping at this moment." },
    { t: "mcq", lv: "B", q: "Siti ___ chicken rice. She has it almost every day.", o: ["likes","is liking","like","are liking"], a: 0, why: "Like is a feeling word, so we do not add -ing. Siti = she → likes." },
    { t: "mcq", lv: "B", q: "I ___ the answer to this sum now.", o: ["know","am knowing","knows","knowing"], a: 0, why: "Know is a thinking word. Even with 'now', we say I know." },
    { t: "mcq", lv: "B", q: "At the moment, Ravi and Ben ___ for the MRT train.", o: ["wait","waits","are waiting","is waiting"], a: 2, why: "'At the moment' → happening now. Ravi and Ben = two people → are waiting." },
    { t: "mcq", lv: "B", q: "Water ___ at 100 degrees Celsius.", o: ["boils","is boiling","boil","are boiling"], a: 0, why: "This is a science fact that is always true → simple present: boils." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["Mum is cooking dinner right now.","Mum cooks dinner right now.","Mum cook dinner right now.","Mum are cooking dinner right now."], a: 0, why: "'Right now' needs is/am/are + -ing. Mum = she → is cooking." },
    { t: "mcq", lv: "B", q: "Hurry up! The bus ___.", o: ["comes","is coming","come","coming"], a: 1, why: "The bus is on its way at this moment → is coming." },
    { t: "mcq", lv: "B", q: "Our school ___ at 7.30 a.m. every day.", o: ["start","starts","is starting","are starting"], a: 1, why: "A timetable that happens every day → simple present. Our school = it → starts." },
    { t: "mcq", lv: "C", q: "This week, Dad ___ from home because his office is being painted.", o: ["works","is working","work","are working"], a: 1, why: "This is only for a short time (this week), not his usual habit → is working." },
    { t: "mcq", lv: "C", q: "Hana usually walks to school, but this week she ___ the bus because her leg is hurt.", o: ["takes","is taking","take","are taking"], a: 1, why: "'Usually' is her habit, but 'this week' is a short, special time → is taking." },
    { t: "mcq", lv: "C", q: "How often ___ you brush your teeth?", o: ["do","are","does","is"], a: 0, why: "'How often' asks about a habit → simple present question with do (for you)." },
    { t: "fix", lv: "A", q: "My sister play badminton every Saturday.", err: "play", a: "plays", why: "My sister = she, and it is a habit → add s: plays." },
    { t: "fix", lv: "A", q: "Look! The boys is running to the canteen.", err: "is", a: "are", why: "The boys = more than one → are running." },
    { t: "fix", lv: "B", q: "Listen! Somebody knock on the door.", err: "knock", a: "is knocking", why: "'Listen!' means it is happening now → is knocking." },
    { t: "fix", lv: "B", q: "I am wanting a glass of water.", err: "am wanting", a: "want", why: "Want is a feeling word, so we do not use -ing: I want." },
    { t: "fix", lv: "B", q: "Does Priya likes durians?", err: "likes", a: "like", why: "After does, the verb has no s: Does Priya like...?" },
    { t: "fix", lv: "C", q: "Every morning, Grandma is doing taiji at the void deck.", err: "is doing", a: "does", why: "'Every morning' is a habit → simple present: Grandma does taiji." },
    { t: "fill", lv: "A", q: "Ahmad ___ (watch) cartoons every evening.", a: ["watches"], why: "Ahmad = he. Verbs ending in ch add -es: watches." },
    { t: "fill", lv: "A", q: "Shh! Mum ___ (talk) on the phone now.", a: ["is talking"], why: "'Now' → is + -ing: is talking." },
    { t: "fill", lv: "A", q: "Bees ___ (make) honey.", a: ["make"], why: "A fact about bees. Bees = more than one, so no s: make." },
    { t: "fill", lv: "B", q: "The children ___ (swim) in the pool right now.", a: ["are swimming"], why: "'Right now' → are + -ing. Remember to double the m: swimming." },
    { t: "fill", lv: "B", q: "Our cat ___ (not like) baths.", a: ["does not like","doesn't like"], why: "Our cat = it → does not + the plain verb like." },
    { t: "fill", lv: "C", q: "Look at those dark clouds! It ___ (begin) to rain.", a: ["is beginning"], why: "It is starting now → is beginning. Double the n before -ing." },
    { t: "trans", lv: "B", q: "Change to the present continuous and add 'now': Wei Jie reads a comic.", a: ["Wei Jie is reading a comic now.","Now Wei Jie is reading a comic.","Wei Jie is now reading a comic."], why: "Wei Jie = he → is + reading. 'Now' shows it is happening at this moment." }
  ]
});

window.VG.push({
  id: "en-g-past",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Simple past and irregular verbs",
  lv: "A",
  intro: "We use the simple past for things that already happened and are finished. Many verbs just add -ed, but some common ones change in their own special way, so it helps to learn them by heart.",
  rules: [
    { h: "Regular verbs: add -ed", html: "Most verbs add <b>-ed</b>: walk → <b>walked</b>, play → <b>played</b>.<br>Ends in e: add d (bake → <b>baked</b>).<br>Consonant + y: change y to i (cry → <b>cried</b>, carry → <b>carried</b>).<br>Short verb, one vowel + one consonant: double it (stop → <b>stopped</b>, hop → <b>hopped</b>)." },
    { h: "Signal words", html: "Words that tell us it is finished: <b>yesterday, last night, last week, ago, in 2020, just now, this morning</b> (when the morning is over).<br>✓ <b>Yesterday</b> we <b>visited</b> the zoo." },
    { h: "Irregular verbs (part 1)", html: "Present – Past – Past participle<br>go – <b>went</b> – gone<br>come – <b>came</b> – come<br>bring – <b>brought</b> – brought<br>buy – <b>bought</b> – bought<br>catch – <b>caught</b> – caught<br>teach – <b>taught</b> – taught<br>think – <b>thought</b> – thought<br>fight – <b>fought</b> – fought<br>see – <b>saw</b> – seen<br>eat – <b>ate</b> – eaten<br>drink – <b>drank</b> – drunk<br>give – <b>gave</b> – given<br>take – <b>took</b> – taken<br>write – <b>wrote</b> – written<br>speak – <b>spoke</b> – spoken<br>break – <b>broke</b> – broken" },
    { h: "Irregular verbs (part 2)", html: "fall – <b>fell</b> – fallen<br>feel – <b>felt</b> – felt<br>keep – <b>kept</b> – kept<br>sleep – <b>slept</b> – slept<br>leave – <b>left</b> – left<br>lose – <b>lost</b> – lost<br>sing – <b>sang</b> – sung<br>swim – <b>swam</b> – swum<br>ring – <b>rang</b> – rung<br>begin – <b>began</b> – begun<br>run – <b>ran</b> – run<br>sit – <b>sat</b> – sat<br>blow – <b>blew</b> – blown<br>fly – <b>flew</b> – flown<br>know – <b>knew</b> – known<br>tell – <b>told</b> – told<br>say – <b>said</b> – said<br>make – <b>made</b> – made<br>read – <b>read</b> – read (sounds like 'red')<br>put – <b>put</b> – put<br>cut – <b>cut</b> – cut" },
    { h: "Tricky pairs: bought/brought, lie/lay", html: "<b>buy → bought</b> (pay money). <b>bring → brought</b> (carry something with you).<br>lie (rest your body) – <b>lay</b> – lain: The dog <b>lay</b> on the mat.<br>lay (put something down) – <b>laid</b> – laid: The hen <b>laid</b> an egg.<br>lie (say something untrue) – <b>lied</b> – lied: He <b>lied</b> to me." },
    { h: "Sang or sung? Swam or swum?", html: "The simple past uses the <b>a</b> form on its own: We <b>sang</b>. She <b>swam</b>.<br>The <b>u</b> form needs a helper (has / have / had): We <b>have sung</b>. She <b>has swum</b>.<br>✗ We sung the song. ✓ We sang the song." },
    { h: "Questions and 'not' use did", html: "After <b>did</b> or <b>did not</b>, use the plain verb.<br>✓ <b>Did</b> you <b>see</b> it? ✗ Did you saw it?<br>✓ I <b>did not go</b>. ✗ I did not went." }
  ],
  words: [],
  mistakes: [
    { wrong: "Yesterday I goed to the park.", right: "Yesterday I went to the park.", why: "Go is irregular: go → went." },
    { wrong: "Mrs Lee teached us a song.", right: "Mrs Lee taught us a song.", why: "Teach is irregular: teach → taught." },
    { wrong: "Did you brought your book?", right: "Did you bring your book?", why: "After did, use the plain verb: bring." },
    { wrong: "We sung the national anthem.", right: "We sang the national anthem.", why: "Without has/have/had, use sang, not sung." },
    { wrong: "I laid on the bed because I was tired.", right: "I lay on the bed because I was tired.", why: "Resting your body: lie → lay. Laid is for putting something down." },
    { wrong: "Mum brought a dress at the shop for $30.", right: "Mum bought a dress at the shop for $30.", why: "Paying money → buy → bought. Brought comes from bring." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Yesterday, we ___ to the zoo.", o: ["go","went","gone"], a: 1, why: "'Yesterday' means it is finished → past tense of go is went." },
    { t: "mcq", lv: "A", q: "Last night, Dad ___ home some satay.", o: ["bring","brought","bringed"], a: 1, why: "Bring is irregular: bring → brought." },
    { t: "mcq", lv: "A", q: "Kai ___ a big fish at the reservoir last Sunday.", o: ["catched","caught","catch"], a: 1, why: "Catch is irregular: catch → caught. There is no word 'catched'." },
    { t: "mcq", lv: "A", q: "Mrs Tan ___ us a new song yesterday.", o: ["taught","teached","teach"], a: 0, why: "Teach is irregular: teach → taught." },
    { t: "mcq", lv: "A", q: "I ___ about the question for a long time before I wrote my answer.", o: ["thinked","thought","think"], a: 1, why: "Think is irregular: think → thought." },
    { t: "mcq", lv: "A", q: "Mum ___ a new school bag for me last week.", o: ["buyed","bought","buy"], a: 1, why: "Buy is irregular: buy → bought." },
    { t: "mcq", lv: "A", q: "Lina ___ off her bicycle and hurt her knee.", o: ["falled","fell","fall"], a: 1, why: "Fall is irregular: fall → fell." },
    { t: "mcq", lv: "A", q: "The baby ___ loudly last night.", o: ["cried","cryed","cry"], a: 0, why: "Consonant + y: change y to i and add -ed → cried." },
    { t: "mcq", lv: "B", q: "After the race, Jun ___ tired but happy.", o: ["feeled","felt","fell","filled"], a: 1, why: "Feel → felt. Fell comes from fall, and filled comes from fill." },
    { t: "mcq", lv: "B", q: "The tired dog ___ down on the mat and fell asleep.", o: ["laid","lay","lied","lain"], a: 1, why: "The dog rested its body: lie → lay. Laid means put something down." },
    { t: "mcq", lv: "B", q: "The choir ___ beautifully at the National Day concert.", o: ["sang","sung","singed","sing"], a: 0, why: "No has/have/had, so use the simple past: sang." },
    { t: "mcq", lv: "B", q: "Nurul ___ two lengths of the pool yesterday.", o: ["swam","swum","swimmed","swim"], a: 0, why: "Simple past of swim is swam. Swum needs has/have/had." },
    { t: "mcq", lv: "B", q: "Which one is NOT a correct past tense?", o: ["ran","ate","drinked","wrote"], a: 2, why: "Drink is irregular: drink → drank. 'Drinked' is not a word." },
    { t: "mcq", lv: "B", q: "Grandpa ___ the newspaper this morning before breakfast.", o: ["readed","read","reads","reading"], a: 1, why: "Read → read (same spelling, but it sounds like 'red')." },
    { t: "mcq", lv: "B", q: "Ben ___ his water bottle on the MRT train yesterday.", o: ["leaved","left","leave","leaves"], a: 1, why: "Leave is irregular: leave → left." },
    { t: "mcq", lv: "B", q: "Did you ___ the fireworks last night?", o: ["saw","see","seen","seeing"], a: 1, why: "After did, use the plain verb: see." },
    { t: "mcq", lv: "B", q: "We ___ not finish our homework last night.", o: ["did","do","does","done"], a: 0, why: "'Last night' is past → did not finish." },
    { t: "mcq", lv: "B", q: "Mum ___ a bag of oranges at the market for $5.", o: ["bought","brought","buyed","buys"], a: 0, why: "She paid $5, so she bought it (buy → bought). Brought comes from bring." },
    { t: "mcq", lv: "C", q: "The hen ___ three eggs yesterday.", o: ["lay","laid","lied","lain"], a: 1, why: "The hen put eggs down: lay → laid." },
    { t: "mcq", lv: "C", q: "Ken ___ to his teacher about the broken window, but later he told the truth.", o: ["lay","laid","lied","lain"], a: 2, why: "He said something untrue: lie → lied." },
    { t: "mcq", lv: "C", q: "The wind ___ so hard that my umbrella turned inside out.", o: ["blowed","blew","blown","blows"], a: 1, why: "Blow is irregular: blow → blew. Blown needs has/have/had." },
    { t: "fix", lv: "A", q: "Yesterday I goed to the library.", err: "goed", a: "went", why: "Go is irregular: go → went." },
    { t: "fix", lv: "A", q: "Wen Hui buyed a bowl of laksa.", err: "buyed", a: "bought", why: "Buy is irregular: buy → bought." },
    { t: "fix", lv: "B", q: "Last week, Mr Lim teached us how to make a kite.", err: "teached", a: "taught", why: "Teach is irregular: teach → taught." },
    { t: "fix", lv: "B", q: "Did you brought your PE shirt today?", err: "brought", a: "bring", why: "After did, use the plain verb: bring." },
    { t: "fix", lv: "B", q: "We swum in the sea at Sentosa during the June holidays.", err: "swum", a: "swam", why: "Without has/have/had, the past of swim is swam." },
    { t: "fix", lv: "C", q: "The children sung the school song loudly.", err: "sung", a: "sang", why: "Without has/have/had, the past of sing is sang." },
    { t: "fix", lv: "C", q: "Feeling sleepy, Ali laid on the sofa.", err: "laid", a: "lay", why: "Ali rested his body: lie → lay. Laid is for putting something down." },
    { t: "fill", lv: "A", q: "Yesterday, Ravi ___ (catch) the bus to school.", a: ["caught"], why: "Catch → caught." },
    { t: "fill", lv: "A", q: "Just now, Mum ___ (stop) the car at the red light.", a: ["stopped"], why: "Stop is short with one vowel + one consonant → double the p: stopped." },
    { t: "fill", lv: "B", q: "I ___ (think) the spelling test was easy.", a: ["thought"], why: "Think → thought." },
    { t: "fill", lv: "B", q: "Sarah ___ (feel) sick, so she stayed at home.", a: ["felt"], why: "Feel → felt." },
    { t: "fill", lv: "C", q: "The bell ___ (ring) and everyone ran to the hall.", a: ["rang"], why: "Ring → rang (rung needs has/have/had)." },
    { t: "trans", lv: "B", q: "Change to the simple past: Wei Ming brings his lunch box to school.", a: ["Wei Ming brought his lunch box to school."], why: "Bring → brought. The s goes away in the past tense." }
  ]
});

window.VG.push({
  id: "en-g-pastcont",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Past continuous (was/were + -ing)",
  lv: "B",
  intro: "The past continuous shows that something was in the middle of happening at a time in the past. It is very useful in stories, for example when something suddenly interrupts.",
  rules: [
    { h: "How to make it", html: "<b>was / were + -ing</b><br><b>was</b> with I, he, she, it, one person or thing.<br><b>were</b> with you, we, they, more than one.<br>✓ I <b>was reading</b>. ✓ They <b>were playing</b>." },
    { h: "In the middle of an action", html: "Use it for something that was going on at a certain time.<br>✓ At 8 p.m. last night, I <b>was doing</b> my homework." },
    { h: "Interrupted by a short action", html: "The long action uses <b>was/were + -ing</b>. The short action that cuts in uses the <b>simple past</b>.<br>✓ I <b>was walking</b> home when it <b>started</b> to rain.<br>✗ I was walking home when it was starting to rain." },
    { h: "While: two long actions together", html: "Use <b>while</b> when two things were going on at the same time.<br>✓ <b>While</b> Mum <b>was cooking</b>, Dad <b>was setting</b> the table.<br><b>when</b> usually goes with the short action; <b>while</b> goes with the long action." },
    { h: "Do not forget the -ing", html: "✗ We were eat dinner. ✓ We were <b>eating</b> dinner.<br>Spelling: swim → swim<b>m</b>ing, run → run<b>n</b>ing, write → wri<b>t</b>ing (drop the e)." },
    { h: "Thinking verbs stay simple", html: "Know, like, want and need do not usually take -ing.<br>✓ I <b>knew</b> the answer. ✗ I was knowing the answer." }
  ],
  words: [],
  mistakes: [
    { wrong: "We was playing chess.", right: "We were playing chess.", why: "We → were." },
    { wrong: "She were sleeping when I called.", right: "She was sleeping when I called.", why: "She → was." },
    { wrong: "I was watch TV when Dad came home.", right: "I was watching TV when Dad came home.", why: "After was/were, add -ing to the verb." },
    { wrong: "I was reading when the phone was ringing.", right: "I was reading when the phone rang.", why: "The short action that interrupts uses the simple past." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "At 8 p.m. last night, I ___ my homework.", o: ["was doing","were doing","am doing"], a: 0, why: "In the middle of an action at a past time. I → was doing." },
    { t: "mcq", lv: "A", q: "The children ___ in the playground when it started to rain.", o: ["was playing","were playing","are playing"], a: 1, why: "The children = more than one → were playing." },
    { t: "mcq", lv: "A", q: "Mum ___ when the phone rang.", o: ["was cooking","were cooking","is cooking"], a: 0, why: "Mum = she → was cooking. The ringing cut in while she was cooking." },
    { t: "mcq", lv: "A", q: "We ___ not sleeping when the fire alarm rang.", o: ["were","was","are"], a: 0, why: "We → were. It happened in the past, so not 'are'." },
    { t: "mcq", lv: "A", q: "It ___ raining heavily this morning.", o: ["was","were","is being"], a: 0, why: "It → was raining. This morning is over." },
    { t: "mcq", lv: "B", q: "While Dad was driving, we ___ songs in the car.", o: ["were singing","was singing","are singing","sing"], a: 0, why: "Two long actions at the same time. We → were singing." },
    { t: "mcq", lv: "B", q: "I was walking home when I ___ a lost puppy.", o: ["saw","was seeing","see","seen"], a: 0, why: "Seeing the puppy is the short action that happened suddenly → simple past: saw." },
    { t: "mcq", lv: "B", q: "What ___ you doing at 3 p.m. yesterday?", o: ["were","was","are","did"], a: 0, why: "You → were. 'Yesterday' is past, so not 'are'." },
    { t: "mcq", lv: "B", q: "Kumar was ___ a shower when the lights went out.", o: ["take","taking","took","takes"], a: 1, why: "After was, we need the -ing form: taking." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["They was waiting for the bus.","They were waiting for the bus.","They were wait for the bus.","They waiting for the bus."], a: 1, why: "They → were, and the verb needs -ing: were waiting." },
    { t: "mcq", lv: "B", q: "The sun ___ brightly when we reached East Coast Park.", o: ["was shining","were shining","shines","is shining"], a: 0, why: "The sun = one thing → was shining. 'Reached' tells us it is the past." },
    { t: "mcq", lv: "B", q: "While Amy ___ the plants, her brother was sweeping the floor.", o: ["was watering","were watering","waters","is watering"], a: 0, why: "Two long actions together. Amy = she → was watering." },
    { t: "mcq", lv: "B", q: "Ah Ma fell asleep while she ___ television.", o: ["was watching","were watching","is watching","watches"], a: 0, why: "Watching TV was the long action. She → was watching." },
    { t: "mcq", lv: "B", q: "When the teacher came in, the pupils ___ loudly.", o: ["were talking","was talking","are talking","talk"], a: 0, why: "The pupils were in the middle of talking. Pupils = many → were." },
    { t: "mcq", lv: "B", q: "Jason hurt his ankle while he ___ football.", o: ["was playing","were playing","is playing","plays"], a: 0, why: "Playing was the long action. He → was playing." },
    { t: "mcq", lv: "C", q: "I ___ my bag on the MRT while I was looking at my phone.", o: ["left","was leaving","leave","leaves"], a: 0, why: "Leaving the bag happened in a moment → simple past: left. Looking was the long action." },
    { t: "mcq", lv: "C", q: "At this time last year, we ___ in Japan.", o: ["were travelling","was travelling","are travelling","travel"], a: 0, why: "In the middle of an action at a past time. We → were travelling (British spelling has double l)." },
    { t: "mcq", lv: "C", q: "Choose the best ending: The dog barked loudly while ___", o: ["the thief was climbing over the gate.","the thief were climbing over the gate.","the thief climbs over the gate.","the thief is climbing over the gate."], a: 0, why: "The story is in the past. The thief = one person → was climbing." },
    { t: "mcq", lv: "C", q: "Siew Ling ___ her homework when her friend called, so she did not pick up the phone.", o: ["was finishing","finishes","were finishing","is finishing"], a: 0, why: "She was busy in the middle of her homework. She → was finishing." },
    { t: "fix", lv: "A", q: "We was eating dinner when Dad came home.", err: "was", a: "were", why: "We → were." },
    { t: "fix", lv: "A", q: "My sister were reading in her room.", err: "were", a: "was", why: "My sister = she → was." },
    { t: "fix", lv: "B", q: "While I was brush my teeth, I heard a loud bang.", err: "brush", a: "brushing", why: "After was, use the -ing form: was brushing." },
    { t: "fix", lv: "B", q: "When the bell rang, the pupils were eat their lunch.", err: "eat", a: "eating", why: "After were, use the -ing form: were eating." },
    { t: "fix", lv: "B", q: "The baby was crying when the doctor was arriving.", err: "was arriving", a: "arrived", why: "The doctor arriving is the short action that happened → simple past: arrived." },
    { t: "fix", lv: "C", q: "I was knowing the answer, but I was too shy to say it.", err: "was knowing", a: "knew", why: "Know is a thinking verb, so we do not add -ing: I knew." },
    { t: "fix", lv: "C", q: "They were swiming in the pool when the lightning started.", err: "swiming", a: "swimming", why: "Swim → double the m before -ing: swimming." },
    { t: "fill", lv: "A", q: "At 7 a.m. yesterday, Priya ___ (eat – past continuous) her breakfast.", a: ["was eating"], why: "Priya = she → was + eating." },
    { t: "fill", lv: "A", q: "The boys ___ (run – past continuous) to the canteen when one of them fell.", a: ["were running"], why: "The boys = many → were. Run → double the n: running." },
    { t: "fill", lv: "B", q: "While Grandpa ___ (read – past continuous) the newspaper, Grandma was knitting.", a: ["was reading"], why: "Two long actions together. Grandpa = he → was reading." },
    { t: "fill", lv: "B", q: "It ___ (rain – past continuous) when we left the cinema.", a: ["was raining"], why: "The rain was going on when we left → was raining." },
    { t: "fill", lv: "C", q: "Nobody noticed the cat because everyone ___ (look – past continuous) at the magician.", a: ["was looking"], why: "Everyone is treated as one group → was looking." },
    { t: "trans", lv: "B", q: "Join using 'while': Mum was cooking. Dad was setting the table.", a: ["While Mum was cooking, Dad was setting the table.","Mum was cooking while Dad was setting the table."], why: "While joins two long actions that happened at the same time." },
    { t: "trans", lv: "C", q: "Join using 'when': I was crossing the road. I saw my teacher.", a: ["I was crossing the road when I saw my teacher.","When I was crossing the road, I saw my teacher."], why: "The long action (was crossing) and the short action (saw) are joined by when." }
  ]
});

window.VG.push({
  id: "en-g-perfect",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Present perfect: has/have + past participle (since, for, already, yet, just)",
  lv: "B",
  intro: "The present perfect links the past to now. We use it for something that has happened and still matters now, or something that started in the past and is still going on.",
  rules: [
    { h: "How to make it", html: "<b>has / have + past participle</b><br><b>has</b> with he, she, it, one person. <b>have</b> with I, you, we, they.<br>✓ She <b>has finished</b>. ✓ We <b>have eaten</b>.<br>Past participles to learn: gone, been, seen, eaten, done, written, taken, broken, known, won, lost, bought." },
    { h: "Since and for", html: "<b>since</b> + a starting point: since 2019, since Monday, since 8 a.m., since Primary 1.<br><b>for</b> + a length of time: for two years, for three days, for an hour.<br>✓ I have lived here <b>since</b> 2020. ✓ I have lived here <b>for</b> five years." },
    { h: "Already, just, yet", html: "<b>already</b> = sooner than expected: I have <b>already</b> eaten.<br><b>just</b> = a very short time ago: The train has <b>just</b> left.<br><b>yet</b> = up to now, used in questions and 'not' sentences, at the end: Have you finished <b>yet</b>? I have not finished <b>yet</b>." },
    { h: "Ever and never", html: "Use <b>ever</b> in questions about your whole life, and <b>never</b> for 'not at any time'.<br>✓ Have you <b>ever</b> tried durian? ✓ I have <b>never</b> been to Korea." },
    { h: "Present perfect or simple past?", html: "With a <b>finished time</b> (yesterday, last week, in 2019, two days ago), use the simple past.<br>✗ I have seen him yesterday. ✓ I <b>saw</b> him yesterday.<br>With no finished time, or with since/for/just/yet, use the present perfect." },
    { h: "Been or gone?", html: "<b>has gone</b> to Japan = he is there now.<br><b>has been</b> to Japan = he went and came back." }
  ],
  words: [],
  mistakes: [
    { wrong: "We have waited since two hours.", right: "We have waited for two hours.", why: "Two hours is a length of time → for." },
    { wrong: "She have finished her work.", right: "She has finished her work.", why: "She → has." },
    { wrong: "I have went to the library.", right: "I have gone to the library.", why: "After have, use the past participle: gone, not went." },
    { wrong: "I have visited Grandma last Sunday.", right: "I visited Grandma last Sunday.", why: "'Last Sunday' is a finished time → simple past." },
    { wrong: "Have you finished already your homework?", right: "Have you finished your homework yet?", why: "Already cannot go between finished and your homework. In questions we usually put yet at the end." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "I ___ my homework. Can I play now?", o: ["have finished","has finished","finished have"], a: 0, why: "I → have + finished. It matters now because I want to play." },
    { t: "mcq", lv: "A", q: "Mei ___ her lunch already.", o: ["has eaten","have eaten","has ate"], a: 0, why: "Mei = she → has. The past participle of eat is eaten." },
    { t: "mcq", lv: "A", q: "We have lived in this HDB flat ___ 2019.", o: ["since","for","ago"], a: 0, why: "2019 is a starting point → since." },
    { t: "mcq", lv: "A", q: "Dad has worked at the airport ___ ten years.", o: ["for","since","ago"], a: 0, why: "Ten years is a length of time → for." },
    { t: "mcq", lv: "A", q: "Look! I have ___ a tooth!", o: ["lost","lose","losed"], a: 0, why: "After have, use the past participle: lose → lost." },
    { t: "mcq", lv: "B", q: "Have you finished your project ___?", o: ["yet","ever","since","for"], a: 0, why: "In questions, yet goes at the end: Have you finished yet?" },
    { t: "mcq", lv: "B", q: "The train has ___ left. We missed it!", o: ["just","yet","since","ever"], a: 0, why: "Just = a very short time ago. It goes between has and the verb." },
    { t: "mcq", lv: "B", q: "Have you ___ tried durian?", o: ["ever","yet","since","for"], a: 0, why: "Ever asks about any time in your life: Have you ever...?" },
    { t: "mcq", lv: "B", q: "Raju has ___ his wallet. He cannot find it anywhere.", o: ["lost","lose","losed","losing"], a: 0, why: "Has + past participle: lost. It matters now because he cannot find it." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["I have seen that film last week.","I saw that film last week.","I have saw that film last week.","I seen that film last week."], a: 1, why: "'Last week' is a finished time, so we use the simple past: saw." },
    { t: "mcq", lv: "B", q: "Oh no, she has ___ the window.", o: ["broke","broken","break","breaked"], a: 1, why: "After has, use the past participle: break → broken." },
    { t: "mcq", lv: "B", q: "The pupils have ___ to the hall for assembly.", o: ["gone","went","go","going"], a: 0, why: "After have, use the past participle: gone. Went is the simple past." },
    { t: "mcq", lv: "B", q: "Hui Min ___ in the choir since Primary 2.", o: ["has been","have been","was","is"], a: 0, why: "Since + starting point → present perfect. Hui Min = she → has been." },
    { t: "mcq", lv: "B", q: "It has rained ___ two hours.", o: ["for","since","ago","yet"], a: 0, why: "Two hours is a length of time → for." },
    { t: "mcq", lv: "B", q: "We have ___ finished our lunch, so we can go out now.", o: ["just","yet","ever","since"], a: 0, why: "Just = a moment ago. Yet goes at the end, not here." },
    { t: "mcq", lv: "B", q: "Wei Lun has not ___ his library book.", o: ["returned","return","returning","returns"], a: 0, why: "Has not + past participle: returned." },
    { t: "mcq", lv: "C", q: "I ___ Kelly since we were in kindergarten.", o: ["have known","know","knew","have knew"], a: 0, why: "Since → present perfect. Know → known: I have known." },
    { t: "mcq", lv: "C", q: "Mum has not cooked dinner ___.", o: ["yet","already","just","since"], a: 0, why: "In 'not' sentences, use yet at the end." },
    { t: "mcq", lv: "C", q: "My uncle ___ to Japan three times, and he wants to go again.", o: ["has been","has gone","have been","has went"], a: 0, why: "He went and came back, so he has been. Has gone would mean he is still there." },
    { t: "mcq", lv: "C", q: "How long ___ you had this bicycle?", o: ["have","has","did","do"], a: 0, why: "How long + still true now → present perfect. You → have." },
    { t: "fix", lv: "A", q: "Ming have finished his work.", err: "have", a: "has", why: "Ming = he → has." },
    { t: "fix", lv: "B", q: "I have live here since 2018.", err: "live", a: "lived", why: "After have, use the past participle: lived." },
    { t: "fix", lv: "B", q: "We have waited since two hours.", err: "since", a: "for", why: "Two hours is a length of time → for." },
    { t: "fix", lv: "B", q: "Have you ate your breakfast?", err: "ate", a: "eaten", why: "After have, use the past participle: eaten." },
    { t: "fix", lv: "C", q: "I have visited Grandma yesterday.", err: "have visited", a: "visited", why: "'Yesterday' is a finished time → simple past: visited." },
    { t: "fix", lv: "C", q: "Mr Wong has wrote three books.", err: "wrote", a: "written", why: "After has, use the past participle: write → written." },
    { t: "fill", lv: "A", q: "Aisha has ___ (do) all her sums.", a: ["done"], why: "Has + past participle: do → done." },
    { t: "fill", lv: "B", q: "They have ___ (be) friends for five years.", a: ["been"], why: "Have + past participle: be → been." },
    { t: "fill", lv: "B", q: "I have not ___ (see) the new film yet.", a: ["seen"], why: "Have not + past participle: see → seen." },
    { t: "fill", lv: "B", q: "Our class has ___ (win) the cleanest classroom award twice.", a: ["won"], why: "Has + past participle: win → won." },
    { t: "fill", lv: "C", q: "Kenji ___ (live) in Singapore since 2020.", a: ["has lived","has been living"], why: "Since + starting point → present perfect. Kenji = he → has lived." },
    { t: "trans", lv: "B", q: "Rewrite using 'for': Ravi started learning the drums two years ago. He is still learning them.", a: ["Ravi has learnt the drums for two years.","Ravi has learned the drums for two years.","Ravi has been learning the drums for two years."], why: "It started in the past and is still going on → has + past participle + for two years." },
    { t: "trans", lv: "C", q: "Rewrite using 'since': We moved to this flat in 2020 and we still live here.", a: ["We have lived in this flat since 2020.","We have been living in this flat since 2020."], why: "Still true now + starting point 2020 → have lived ... since 2020." }
  ]
});

window.VG.push({
  id: "en-g-pastperfect",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Past perfect and keeping tenses consistent in a story",
  lv: "C",
  intro: "When you write a story in the past, keep your verbs in the past all the way through. Use the past perfect (had + past participle) to show that one thing happened even earlier than another.",
  rules: [
    { h: "Keep the story in the past", html: "Once your story starts in the past, do not slip into the present.<br>✗ I opened the door and <b>see</b> a parcel.<br>✓ I opened the door and <b>saw</b> a parcel." },
    { h: "Past perfect: had + past participle", html: "Use <b>had + past participle</b> for the action that happened <b>first</b>.<br>✓ When we reached the cinema, the film <b>had</b> already <b>started</b>.<br>(First the film started. Then we reached.)" },
    { h: "Helpful words", html: "<b>after, before, by the time, when, already, because</b> often go with the past perfect.<br>✓ <b>By the time</b> Dad got home, we <b>had eaten</b> dinner.<br>✓ <b>After</b> she <b>had finished</b> her homework, she watched TV." },
    { h: "Explaining a reason in the past", html: "Use the past perfect to explain why something was so.<br>✓ Jun was sad because he <b>had lost</b> his pencil case.<br>✓ The ground was wet because it <b>had rained</b>." },
    { h: "Reporting what people said", html: "When we report speech, the tense usually moves one step back.<br>Sara said, 'I <b>have finished</b>.' → Sara said that she <b>had finished</b>.<br>Ali said, 'I <b>lost</b> my key.' → Ali said that he <b>had lost</b> his key." },
    { h: "Use the past participle after had", html: "✗ had ate, had went, had wrote<br>✓ had <b>eaten</b>, had <b>gone</b>, had <b>written</b>" }
  ],
  words: [],
  mistakes: [
    { wrong: "We went to the zoo and see the pandas.", right: "We went to the zoo and saw the pandas.", why: "The story is in the past, so keep all the verbs in the past." },
    { wrong: "When I reached the stop, the bus has left.", right: "When I reached the stop, the bus had left.", why: "The bus left first, before I reached → had left." },
    { wrong: "After she had wrote the card, she posted it.", right: "After she had written the card, she posted it.", why: "After had, use the past participle: written." },
    { wrong: "Suddenly, the lights go out and everyone screamed.", right: "Suddenly, the lights went out and everyone screamed.", why: "Do not jump from past to present in the middle of a story." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Yesterday I woke up late, so I ___ to school.", o: ["run","ran","runs"], a: 1, why: "The story is in the past (woke) → keep it past: ran." },
    { t: "mcq", lv: "A", q: "Last Saturday we went to the beach and ___ sandcastles.", o: ["build","built","builds"], a: 1, why: "Went is past, so the next verb is past too: built." },
    { t: "mcq", lv: "A", q: "The puppy was hungry, so it ___ all its food.", o: ["eats","ate","eat"], a: 1, why: "Was is past → keep it past: ate." },
    { t: "mcq", lv: "A", q: "Ali kicked the ball and it ___ into the goal.", o: ["goes","went","go"], a: 1, why: "Kicked is past → the ball went (past)." },
    { t: "mcq", lv: "B", q: "When we reached the cinema, the film ___ already started.", o: ["had","has","have","was"], a: 0, why: "The film started first, before we reached → had started." },
    { t: "mcq", lv: "B", q: "After Mei Ling ___ her homework, she watched TV.", o: ["had finished","has finished","finishes","have finished"], a: 0, why: "Homework came first, then TV → had finished." },
    { t: "mcq", lv: "B", q: "Jun was sad because he ___ his pencil case.", o: ["had lost","has lost","loses","have lost"], a: 0, why: "Losing it happened before he felt sad → had lost." },
    { t: "mcq", lv: "B", q: "By the time Dad got home, we ___ dinner.", o: ["had eaten","have eaten","eat","has eaten"], a: 0, why: "'By the time' → dinner was over before Dad came → had eaten." },
    { t: "mcq", lv: "B", q: "Which sentence keeps the tense the same?", o: ["Sam opened the door and sees a parcel.","Sam opened the door and saw a parcel.","Sam opens the door and saw a parcel.","Sam opened the door and seen a parcel."], a: 1, why: "Both verbs are in the past: opened and saw." },
    { t: "mcq", lv: "B", q: "The ground was wet because it ___ during the night.", o: ["had rained","has rained","rains","have rained"], a: 0, why: "The rain came first and explains why the ground was wet → had rained." },
    { t: "mcq", lv: "B", q: "Suddenly, the lights went out and everyone ___.", o: ["screams","screamed","scream","screaming"], a: 1, why: "Went is past → keep it past: screamed." },
    { t: "mcq", lv: "B", q: "Mr Lim was angry because nobody ___ the classroom.", o: ["had cleaned","has cleaned","cleans","have cleaned"], a: 0, why: "Nobody cleaned it before he came, so he was angry → had cleaned." },
    { t: "mcq", lv: "C", q: "Before Amir moved to Singapore, he ___ lived in Penang for five years.", o: ["had","has","have","was"], a: 0, why: "Living in Penang came before moving → had lived." },
    { t: "mcq", lv: "C", q: "Lucy told me that she ___ the book before.", o: ["had read","has read","reads","have read"], a: 0, why: "She read it before she told me → had read." },
    { t: "mcq", lv: "C", q: "The shop ___ when we arrived, so we went home.", o: ["had closed","has closed","closes","have closed"], a: 0, why: "The shop closed first, then we arrived → had closed." },
    { t: "mcq", lv: "C", q: "I recognised the girl because I ___ her at the CCA camp.", o: ["had met","have met","meet","has met"], a: 0, why: "Meeting her came first, so I recognised her later → had met." },
    { t: "mcq", lv: "C", q: "Which happened FIRST? 'When Ravi reached the bus stop, the bus had left.'", o: ["The bus left.","Ravi reached the bus stop.","Both happened at the same time.","We cannot tell."], a: 0, why: "Had left shows the earlier action: the bus left first." },
    { t: "mcq", lv: "C", q: "We could not enter the house because Mum ___ the keys inside.", o: ["had left","has left","leaves","have left"], a: 0, why: "Leaving the keys happened before we tried to enter → had left." },
    { t: "mcq", lv: "C", q: "Sara said, 'I have finished my work.' Choose the reported speech.", o: ["Sara said that she had finished her work.","Sara said that she has finished her work.","Sara said that I had finished my work.","Sara said that she finish her work."], a: 0, why: "In reported speech, move one step back (have finished → had finished) and change I → she." },
    { t: "fix", lv: "A", q: "Last night I watched TV and then I go to bed.", err: "go", a: "went", why: "Watched is past → keep it past: went." },
    { t: "fix", lv: "A", q: "We went to the zoo and see the pandas.", err: "see", a: "saw", why: "Went is past → keep it past: saw." },
    { t: "fix", lv: "B", q: "The boy fell down and starts to cry.", err: "starts", a: "started", why: "Fell is past → keep it past: started." },
    { t: "fix", lv: "B", q: "When I got to the hall, the concert has started.", err: "has", a: "had", why: "The concert started before I got there → had started." },
    { t: "fix", lv: "B", q: "Ahmad was tired because he has played football all afternoon.", err: "has", a: "had", why: "The football came before he felt tired → had played." },
    { t: "fix", lv: "C", q: "After she had wrote the letter, she posted it.", err: "wrote", a: "written", why: "After had, use the past participle: written." },
    { t: "fix", lv: "C", q: "Mei had already ate when I called her.", err: "ate", a: "eaten", why: "After had, use the past participle: eaten." },
    { t: "fill", lv: "A", q: "Last week, Grandma ___ (bake) a cake for me.", a: ["baked"], why: "'Last week' → simple past: baked." },
    { t: "fill", lv: "B", q: "The ice cream ___ (melt) before we got home.", a: ["had melted","melted"], why: "It melted before we got home. Had melted shows clearly it happened first." },
    { t: "fill", lv: "B", q: "By the time the firemen arrived, the fire ___ (spread) to the next flat.", a: ["had spread"], why: "'By the time' → the earlier action uses had + past participle: had spread." },
    { t: "fill", lv: "C", q: "Sam could not play because he ___ (forget) his racket.", a: ["had forgotten","forgot"], why: "Forgetting came first → had forgotten (forget → forgot → forgotten)." },
    { t: "fill", lv: "C", q: "Nobody knew that Peter ___ (take) the last piece of cake.", a: ["had taken","took"], why: "He took it before anyone found out → had taken." },
    { t: "trans", lv: "B", q: "Change into the past tense: Sita opens the gift and smiles.", a: ["Sita opened the gift and smiled."], why: "Both verbs change to the past: opened, smiled." },
    { t: "trans", lv: "C", q: "Join using 'after' and the past perfect: Lily brushed her teeth. Then she went to bed.", a: ["After Lily had brushed her teeth, she went to bed.","Lily went to bed after she had brushed her teeth."], why: "Brushing came first → had brushed. Going to bed stays in the simple past." }
  ]
});

window.VG.push({
  id: "en-g-future",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Talking about the future (will, going to, is about to)",
  lv: "A",
  intro: "English has a few ways to talk about the future. Will, going to and about to each have their own job, and they help you write plans, promises and exciting story moments.",
  rules: [
    { h: "will + plain verb", html: "Use <b>will</b> for predictions, promises, offers and decisions you make on the spot.<br>✓ I think it <b>will rain</b>. ✓ I <b>will help</b> you.<br>The verb after will has <b>no s, no -ing, no 'to'</b>.<br>✗ He will goes. ✗ He will to go. ✓ He <b>will go</b>." },
    { h: "going to: plans and clues", html: "<b>am / is / are going to + plain verb</b><br>For a plan you have already made: We <b>are going to visit</b> Grandma on Sunday.<br>For something you can see coming: Look at those clouds! It <b>is going to rain</b>." },
    { h: "about to: very, very soon", html: "<b>am / is / are about to + plain verb</b> = it will happen in a moment.<br>✓ Hurry! The train <b>is about to leave</b>.<br>Do not use it with times far away: ✗ He is about to retire next year." },
    { h: "Present continuous for fixed arrangements", html: "When something is already arranged with a time and place, we can use <b>am / is / are + -ing</b>.<br>✓ We <b>are flying</b> to Bangkok on Friday." },
    { h: "When and if + present", html: "After <b>when</b> and <b>if</b>, use the present tense even for the future.<br>✓ I will call you <b>when I reach</b> home. ✗ when I will reach home<br>✓ <b>If it rains</b>, we will stay in." },
    { h: "won't = will not", html: "✓ I <b>won't</b> forget. = I <b>will not</b> forget." }
  ],
  words: [],
  mistakes: [
    { wrong: "Tomorrow I will goes swimming.", right: "Tomorrow I will go swimming.", why: "After will, use the plain verb with no s." },
    { wrong: "We will to visit the museum.", right: "We will visit the museum.", why: "Do not put 'to' after will." },
    { wrong: "She going to sing.", right: "She is going to sing.", why: "Going to needs am/is/are in front of it." },
    { wrong: "I will tell you when I will know.", right: "I will tell you when I know.", why: "After when, use the present tense: when I know." },
    { wrong: "The bus is about to leaving.", right: "The bus is about to leave.", why: "After about to, use the plain verb." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Tomorrow, we ___ visit the Science Centre.", o: ["will","are","did"], a: 0, why: "Tomorrow is the future → will + visit." },
    { t: "mcq", lv: "A", q: "I think it ___ rain later.", o: ["will","is","was"], a: 0, why: "'I think' + future guess → will rain." },
    { t: "mcq", lv: "A", q: "Look at those dark clouds! It is going to ___.", o: ["rain","rains","raining"], a: 0, why: "After going to, use the plain verb: rain." },
    { t: "mcq", lv: "A", q: "Next week, Kumar ___ going to start swimming lessons.", o: ["is","are","will"], a: 0, why: "Kumar = he → is going to." },
    { t: "mcq", lv: "A", q: "Don't worry, I ___ help you carry the bags.", o: ["will","am","was"], a: 0, why: "An offer to help → will help." },
    { t: "mcq", lv: "A", q: "___ you come to my party next Sunday?", o: ["Will","Are","Did"], a: 0, why: "Next Sunday is in the future → Will you come...?" },
    { t: "mcq", lv: "A", q: "Dad ___ going to cook mee siam tonight.", o: ["is","are","am"], a: 0, why: "Dad = he → is going to." },
    { t: "mcq", lv: "B", q: "Hurry! The train is about ___.", o: ["to leave","leave","leaving","left"], a: 0, why: "The pattern is about to + plain verb: about to leave." },
    { t: "mcq", lv: "B", q: "We ___ our cousins this Saturday. We have already bought the tickets.", o: ["are going to visit","will visits","visited","visit to"], a: 0, why: "A plan made already → are going to visit." },
    { t: "mcq", lv: "B", q: "She will ___ the letter tomorrow.", o: ["post","posts","posted","posting"], a: 0, why: "After will, use the plain verb: post." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["He will goes to the market.","He will go to the market.","He will going to the market.","He wills go to the market."], a: 1, why: "Will + plain verb: will go. No s, no -ing." },
    { t: "mcq", lv: "B", q: "If it rains tomorrow, we ___ stay at home.", o: ["will","would","are","did"], a: 0, why: "If + present (rains), then will for the result." },
    { t: "mcq", lv: "B", q: "When I ___ up, I want to be a vet.", o: ["grow","will grow","grew","growing"], a: 0, why: "After when, use the present tense, even for the future: when I grow up." },
    { t: "mcq", lv: "B", q: "The phone is ringing. 'I ___ get it!' said Mum.", o: ["will","am","was","did"], a: 0, why: "Mum decides at that moment → I will (I'll) get it." },
    { t: "mcq", lv: "B", q: "Be careful! That vase is about to ___.", o: ["fall","falls","fell","falling"], a: 0, why: "About to + plain verb: fall." },
    { t: "mcq", lv: "B", q: "I promise I ___ forget your birthday.", o: ["won't","don't","didn't","am not"], a: 0, why: "A promise about the future → won't (will not)." },
    { t: "mcq", lv: "C", q: "Mr Tan ___ retire next year; he has already told the principal.", o: ["is going to","will to","going to","is about to"], a: 0, why: "A plan already made → is going to. About to is only for very soon, not next year." },
    { t: "mcq", lv: "C", q: "We ___ for Japan tomorrow morning; our flight is at 9 a.m.", o: ["are leaving","leave to","left","were leaving"], a: 0, why: "A fixed arrangement (the flight is booked) → present continuous: are leaving." },
    { t: "mcq", lv: "C", q: "Nadia is holding her nose and shutting her eyes. She ___ jump into the pool.", o: ["is about to","about to","will to","was about to"], a: 0, why: "It will happen in a moment → is about to jump." },
    { t: "fix", lv: "A", q: "Tomorrow I will goes to the library.", err: "goes", a: "go", why: "After will, use the plain verb: go." },
    { t: "fix", lv: "A", q: "We is going to play chess after school.", err: "is", a: "are", why: "We → are going to." },
    { t: "fix", lv: "A", q: "Next week, Sarah are going to sing at assembly.", err: "are", a: "is", why: "Sarah = she → is going to." },
    { t: "fix", lv: "B", q: "Next Sunday, my family will to visit Grandpa.", err: "will to visit", a: "will visit", why: "Do not put 'to' after will." },
    { t: "fix", lv: "B", q: "The bus is about to leaving.", err: "leaving", a: "leave", why: "About to + plain verb: leave." },
    { t: "fix", lv: "B", q: "Look at that boy on the wall! He going to fall.", err: "He going", a: "He is going", why: "Going to needs is in front of it: He is going to fall." },
    { t: "fix", lv: "C", q: "I will call you when I will reach home.", err: "will reach", a: "reach", why: "After when, use the present tense: when I reach home." },
    { t: "fill", lv: "A", q: "Tomorrow, Jia Hui ___ (be) ten years old.", a: ["will be","is going to be"], why: "Tomorrow is the future → will be." },
    { t: "fill", lv: "A", q: "Look! The baby is going to ___ (cry).", a: ["cry"], why: "After going to, use the plain verb: cry." },
    { t: "fill", lv: "B", q: "Quick, get the umbrella! It is about to ___ (pour).", a: ["pour"], why: "About to + plain verb: pour." },
    { t: "fill", lv: "B", q: "If you study hard, you ___ (pass) the test.", a: ["will pass","are going to pass"], why: "If + present (study), then will for the result: will pass." },
    { t: "fill", lv: "C", q: "We ___ (fly) to Bangkok next Friday. Mum has booked the tickets.", a: ["are flying","are going to fly","will fly"], why: "It is already arranged → are flying (or are going to fly)." },
    { t: "trans", lv: "B", q: "Rewrite using 'going to': I plan to read this book during the holidays.", a: ["I am going to read this book during the holidays.","I'm going to read this book during the holidays.","During the holidays, I am going to read this book."], why: "A plan → am going to + plain verb." }
  ]
});
