window.VG = window.VG || [];

/* ---------- 1. Synonyms ---------- */
window.VG.push({
  id: "en-v-synonyms",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Synonyms (words that mean the same)",
  lv: "A",
  intro: "Synonyms are words that mean the same or nearly the same, like big and large. Using synonyms makes your writing more interesting because you do not have to repeat the same word again and again.",
  rules: [
    { h: "What is a synonym?", html: "A synonym is a word that means the same or nearly the same as another word.<br><b>big</b> = <b>large</b> &nbsp; <b>quick</b> = <b>fast</b> &nbsp; <b>begin</b> = <b>start</b>" },
    { h: "Swap without changing the meaning", html: "If you can swap one word for another and the sentence still means the same, they are synonyms.<br>The bag is <b>big</b>. → The bag is <b>large</b>. ✓" },
    { h: "Some synonyms are stronger", html: "Some words are a stronger form of another word.<br><b>big</b> → <b>huge</b> → <b>enormous</b><br><b>tired</b> → <b>weary</b> (very tired)<br>Do not add <b>very</b> to a strong word: <b>very enormous</b> ✗ &nbsp; <b>enormous</b> ✓" },
    { h: "Keep the same kind of word", html: "A describing word needs a describing-word synonym.<br>The class was <b>silent</b>. ✓ &nbsp; The class was <b>silence</b>. ✗ (silence is a thing, not a describing word)" },
    { h: "Synonyms do not always fit everywhere", html: "Some words like to go with certain partners.<br>a <b>big</b> smile ✓ &nbsp; a <b>large</b> smile ✗<br>my <b>little</b> brother (younger) ✓ &nbsp; my <b>small</b> brother ✗" },
    { h: "Use synonyms to improve your writing", html: "Instead of using <b>said</b> or <b>nice</b> again and again, choose a word that shows more.<br>'Stop!' he <b>said</b> loudly. → 'Stop!' he <b>shouted</b>." }
  ],
  words: [
    { w: "glad", m: "happy; pleased", ex: "Mei Ling was glad to see her grandma at the void deck." },
    { w: "huge", m: "very big", ex: "A huge container ship sailed past Sentosa." },
    { w: "enormous", m: "extremely big", ex: "The enormous durian was too heavy for Jun to lift." },
    { w: "tiny", m: "very small", ex: "A tiny ant crawled across my lunch box." },
    { w: "quick", m: "fast", ex: "Aisyah took a quick shower before school." },
    { w: "begin", m: "start", ex: "The concert will begin at seven o'clock." },
    { w: "finish", m: "end; complete", ex: "Please finish your spelling before recess." },
    { w: "shout", m: "yell; say something very loudly", ex: "Do not shout in the library." },
    { w: "frightened", m: "scared; afraid", ex: "The kitten was frightened by the thunder." },
    { w: "clever", m: "smart; bright", ex: "Wei Jie is clever at solving maths puzzles." },
    { w: "weary", m: "very tired", ex: "After the long hike up Bukit Timah, we felt weary." },
    { w: "silent", m: "quiet; making no sound", ex: "The hall was silent during the exam." },
    { w: "difficult", m: "hard; not easy", ex: "The last question was quite difficult." },
    { w: "simple", m: "easy; not hard", ex: "Making a paper boat is simple." },
    { w: "gift", m: "present; something you give", ex: "Ravi gave his teacher a gift on Teachers' Day." },
    { w: "choose", m: "pick; select", ex: "You may choose any book from the shelf." },
    { w: "brave", m: "courageous; bold; not afraid", ex: "The brave boy helped the old man across the road." },
    { w: "noisy", m: "loud; full of noise", ex: "The hawker centre is noisy at lunchtime." }
  ],
  mistakes: [
    { wrong: "The elephant was very enormous.", right: "The elephant was enormous.", why: "Enormous already means very big, so do not add very." },
    { wrong: "My small brother is in K1.", right: "My little brother is in K1.", why: "We say little brother or little sister when we mean younger." },
    { wrong: "Jun Hao gave me a large smile.", right: "Jun Hao gave me a big smile.", why: "Big and large are synonyms, but we usually say a big smile, not a large smile." },
    { wrong: "The library was silence.", right: "The library was silent.", why: "After was, we need a describing word: silent. Silence is the name of a thing." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Which word means the same as 'big'?", o: ["large", "small", "thin"], a: 0, why: "Big and large both mean of great size. Small is the opposite." },
    { t: "mcq", lv: "A", q: "Which word means the same as 'begin'?", o: ["start", "stop", "finish"], a: 0, why: "Begin and start both mean to do the first part of something." },
    { t: "mcq", lv: "A", q: "Which word means the same as 'quick'?", o: ["slow", "fast", "late"], a: 1, why: "Quick and fast both mean moving at high speed. Slow is the opposite." },
    { t: "mcq", lv: "A", q: "Which word means the same as 'glad'?", o: ["sad", "happy", "angry"], a: 1, why: "Glad means happy or pleased." },
    { t: "mcq", lv: "A", q: "Which word means the same as 'shout'?", o: ["whisper", "yell", "sing"], a: 1, why: "Shout and yell both mean to say something very loudly. Whisper is the opposite." },
    { t: "mcq", lv: "A", q: "Which word means the same as 'tiny'?", o: ["huge", "very small", "tall"], a: 1, why: "Tiny means very small. Huge is the opposite." },
    { t: "mcq", lv: "A", q: "The gift from Aunty Rosnah was lovely. Which word can replace 'gift'?", o: ["present", "lesson", "ticket"], a: 0, why: "A gift is a present: something you give to someone." },
    { t: "mcq", lv: "A", q: "Please choose a book from the shelf. Which word can replace 'choose'?", o: ["pick", "drop", "read"], a: 0, why: "Choose and pick both mean to decide which one you want." },
    { t: "mcq", lv: "B", q: "The hawker centre was very noisy at lunchtime. Which word can replace 'noisy'?", o: ["loud", "empty", "clean", "cool"], a: 0, why: "Noisy and loud both mean full of sound." },
    { t: "mcq", lv: "B", q: "Ahmad was frightened of the thunder. Which word can replace 'frightened'?", o: ["scared", "excited", "proud", "bored"], a: 0, why: "Frightened means scared or afraid." },
    { t: "mcq", lv: "B", q: "The maths sum was difficult. Which word can replace 'difficult'?", o: ["easy", "hard", "short", "neat"], a: 1, why: "Difficult means hard, not easy. Easy is the opposite." },
    { t: "mcq", lv: "B", q: "After the long hike, Priya felt weary. Which word is closest in meaning to 'weary'?", o: ["very tired", "lively", "cheerful", "hungry"], a: 0, why: "Weary means very tired, the way you feel after a lot of walking." },
    { t: "mcq", lv: "B", q: "Which pair are synonyms?", o: ["hot – cold", "end – finish", "up – down", "open – shut"], a: 1, why: "End and finish mean the same. The other pairs are opposites." },
    { t: "mcq", lv: "B", q: "Which pair are NOT synonyms?", o: ["big – large", "quiet – silent", "brave – cowardly", "smart – clever"], a: 2, why: "Cowardly means easily scared, which is the opposite of brave." },
    { t: "mcq", lv: "B", q: "Wei Jie is the cleverest boy in his class. Which word can replace 'cleverest'?", o: ["brightest", "darkest", "tallest", "loudest"], a: 0, why: "Bright can also mean clever, so the brightest boy is the cleverest boy." },
    { t: "mcq", lv: "B", q: "The firefighter was brave. Which word means the same as 'brave'?", o: ["courageous", "careless", "nervous", "lazy"], a: 0, why: "Brave and courageous both mean not afraid to face danger." },
    { t: "mcq", lv: "B", q: "'Watch out!' Mum said loudly. Which ONE word can replace 'said loudly'?", o: ["shouted", "whispered", "mumbled", "sighed"], a: 0, why: "To shout is to say something loudly. Whispered and mumbled mean saying it softly." },
    { t: "mcq", lv: "C", q: "The ancient temple was enormous. Which word is closest in meaning to 'enormous'?", o: ["gigantic", "narrow", "modern", "crowded"], a: 0, why: "Enormous and gigantic both mean extremely big." },
    { t: "mcq", lv: "C", q: "The new rule is simple to follow. Which word is closest in meaning to 'simple'?", o: ["complicated", "straightforward", "strict", "unfair"], a: 1, why: "Simple and straightforward both mean easy to understand. Complicated is the opposite." },
    { t: "mcq", lv: "C", q: "Siti glanced at the clock. What does 'glanced' mean?", o: ["took a quick look", "looked for a long time", "closed her eyes", "searched for something lost"], a: 0, why: "To glance is to look very quickly. To stare is to look for a long time." },
    { t: "fix", lv: "A", q: "My small brother is in K1.", err: "small", a: "little", why: "We say little brother when we mean a younger brother." },
    { t: "fix", lv: "B", q: "The elephant at the zoo was very enormous.", err: "very enormous", a: "enormous", why: "Enormous already means very big, so we do not add very." },
    { t: "fix", lv: "B", q: "The library was so silence that I could hear the clock ticking.", err: "silence", a: "silent", why: "We need a describing word after so: silent. Silence is the name of a thing." },
    { t: "fix", lv: "B", q: "Jun Hao gave me a large smile.", err: "large", a: "big", why: "Big and large are synonyms, but we usually say a big smile, not a large smile." },
    { t: "fix", lv: "B", q: "Nurul felt very happiness when she won the prize.", err: "happiness", a: "happy", why: "After felt very, use a describing word: happy. Happiness is the name of a feeling." },
    { t: "fill", lv: "A", q: "Big and ___ are synonyms. (starts with l)", a: ["large"], why: "Large means the same as big." },
    { t: "fill", lv: "A", q: "Start means the same as ___ . (starts with b)", a: ["begin"], why: "Start and begin both mean to do the first part of something." },
    { t: "fill", lv: "A", q: "Finish means the same as ___ . (starts with e)", a: ["end"], why: "When you finish something, you come to the end of it." },
    { t: "fill", lv: "B", q: "A synonym for 'frightened' is ___ . (starts with s)", a: ["scared"], why: "Frightened and scared both mean afraid." },
    { t: "fill", lv: "B", q: "Very small means ___ . (starts with t)", a: ["tiny"], why: "Tiny means very small, like an ant." },
    { t: "fill", lv: "B", q: "Another word for a present is a ___ . (starts with g)", a: ["gift"], why: "A gift and a present are both things you give to someone." },
    { t: "fill", lv: "C", q: "A synonym for 'brave' is ___ . (starts with c)", a: ["courageous"], why: "Courageous means brave, not afraid of danger. Notice the spelling: courage + ous." }
  ]
});

/* ---------- 2. Antonyms ---------- */
window.VG.push({
  id: "en-v-antonyms",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Antonyms (opposites)",
  lv: "A",
  intro: "Antonyms are words with opposite meanings, like hot and cold. Knowing opposites helps you describe things clearly and compare them in your writing.",
  rules: [
    { h: "What is an antonym?", html: "An antonym is a word that means the opposite of another word.<br><b>hot</b> ↔ <b>cold</b> &nbsp; <b>early</b> ↔ <b>late</b> &nbsp; <b>push</b> ↔ <b>pull</b>" },
    { h: "Some opposites are made with a prefix", html: "Adding <b>un-</b>, <b>dis-</b>, <b>im-</b> or <b>in-</b> can make an opposite.<br><b>happy</b> → <b>unhappy</b> &nbsp; <b>like</b> → <b>dislike</b> &nbsp; <b>polite</b> → <b>impolite</b>" },
    { h: "One word, different opposites", html: "Some words have more than one meaning, so they have more than one opposite. Read the sentence first.<br>a <b>light</b> bag ↔ a <b>heavy</b> bag<br>a <b>light</b> colour ↔ a <b>dark</b> colour" },
    { h: "Keep the same kind of word", html: "The opposite of an action word is an action word; the opposite of a describing word is a describing word.<br><b>win</b> ↔ <b>lose</b> (actions) &nbsp; <b>safe</b> ↔ <b>dangerous</b> (describing)" },
    { h: "Watch out for tricky pairs", html: "<b>borrow</b> = take for a while; <b>lend</b> = give for a while.<br>Can you <b>lend</b> me your pen? ✓ &nbsp; Can you <b>borrow</b> me your pen? ✗<br><b>loose</b> (not tight) is different from <b>lose</b> (opposite of win or find)." }
  ],
  words: [
    { w: "early", m: "before the usual time (opposite: late)", ex: "We reached school early, before the gate opened." },
    { w: "empty", m: "with nothing inside (opposite: full)", ex: "The MRT carriage was almost empty at night." },
    { w: "heavy", m: "weighing a lot (opposite: light)", ex: "My school bag is heavy on Mondays." },
    { w: "loose", m: "not tight (opposite: tight)", ex: "My front tooth is loose." },
    { w: "arrive", m: "reach a place (opposite: leave)", ex: "The bus will arrive in three minutes." },
    { w: "remember", m: "keep something in your mind (opposite: forget)", ex: "Remember to bring your water bottle." },
    { w: "push", m: "move something away from you (opposite: pull)", ex: "Push the door to open it." },
    { w: "win", m: "come first in a game (opposite: lose)", ex: "Our class hopes to win the relay." },
    { w: "lend", m: "let someone use something of yours for a while (opposite: borrow)", ex: "Can you lend me your eraser?" },
    { w: "sell", m: "give something in exchange for money (opposite: buy)", ex: "The uncle sells fishball noodles." },
    { w: "polite", m: "having good manners (opposite: rude)", ex: "It is polite to say thank you." },
    { w: "generous", m: "happy to give and share (opposite: selfish)", ex: "Grandpa is generous with his time." },
    { w: "shallow", m: "not deep (opposite: deep)", ex: "The little children played in the shallow pool." },
    { w: "ancient", m: "very, very old (opposite: modern)", ex: "The museum has ancient coins from long ago." },
    { w: "victory", m: "a win (opposite: defeat)", ex: "The team cheered after their victory." },
    { w: "accept", m: "say yes to something offered (opposite: refuse)", ex: "Mr Tan accepted the invitation to our concert." },
    { w: "smooth", m: "flat with no bumps (opposite: rough)", ex: "The new running track is smooth." },
    { w: "safe", m: "not in danger (opposite: dangerous)", ex: "Always cross at a safe place." }
  ],
  mistakes: [
    { wrong: "Can you borrow me your ruler?", right: "Can you lend me your ruler?", why: "Borrow means take for a while. Lend means give for a while. Borrow and lend are opposites." },
    { wrong: "My shoes are too lose.", right: "My shoes are too loose.", why: "Loose (two o's) is the opposite of tight. Lose (one o) is the opposite of win or find." },
    { wrong: "Ben was unpolite to the cashier.", right: "Ben was impolite to the cashier.", why: "The opposite of polite is impolite (or rude), not unpolite." },
    { wrong: "This box of books is light, but that one is dark.", right: "This box of books is light, but that one is heavy.", why: "Here light means not heavy, so its opposite is heavy." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "What is the opposite of 'hot'?", o: ["warm", "cold", "wet"], a: 1, why: "Cold is the opposite of hot. Warm is only a little bit hot, not the opposite." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'early'?", o: ["late", "soon", "first"], a: 0, why: "If you are not early, you are late." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'empty'?", o: ["full", "open", "clean"], a: 0, why: "An empty cup has nothing in it; a full cup has as much as it can hold." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'push'?", o: ["pull", "kick", "press"], a: 0, why: "Push moves something away from you; pull moves it towards you." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'win'?", o: ["lose", "play", "beat"], a: 0, why: "In a game, one team wins and the other team loses." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'buy'?", o: ["pay", "sell", "shop"], a: 1, why: "The customer buys; the shopkeeper sells." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'up'?", o: ["over", "down", "under"], a: 1, why: "The lift goes up and down. Down is the opposite of up." },
    { t: "mcq", lv: "A", q: "What is the opposite of 'arrive'?", o: ["come", "reach", "leave"], a: 2, why: "You arrive when you reach a place and leave when you go away from it." },
    { t: "mcq", lv: "B", q: "The MRT train was crowded this morning. What is the opposite of 'crowded'?", o: ["packed", "empty", "noisy", "fast"], a: 1, why: "Crowded means full of people; empty means with no one or nothing inside. Packed is a synonym, not an opposite." },
    { t: "mcq", lv: "B", q: "Siti remembered to bring her water bottle. What is the opposite of 'remembered'?", o: ["forgot", "lost", "carried", "kept"], a: 0, why: "If you do not remember something, you forget it." },
    { t: "mcq", lv: "B", q: "The children played in the shallow pool. What is the opposite of 'shallow'?", o: ["deep", "wide", "cold", "clean"], a: 0, why: "Shallow water is not deep. Deep is its opposite." },
    { t: "mcq", lv: "B", q: "My uncle is generous and shares everything. What is the opposite of 'generous'?", o: ["kind", "selfish", "busy", "rich"], a: 1, why: "A generous person shares; a selfish person keeps things for himself." },
    { t: "mcq", lv: "B", q: "The new road was smooth. What is the opposite of 'smooth'?", o: ["flat", "rough", "long", "wet"], a: 1, why: "Smooth means with no bumps; rough means bumpy and uneven." },
    { t: "mcq", lv: "B", q: "Which pair are antonyms?", o: ["shut – close", "polite – rude", "quick – fast", "gift – present"], a: 1, why: "Polite and rude are opposites. The other pairs mean the same." },
    { t: "mcq", lv: "B", q: "This box of books is so light that I can carry it with one hand. What is the opposite of 'light' here?", o: ["dark", "heavy", "bright", "small"], a: 1, why: "Here light means not heavy, so the opposite is heavy." },
    { t: "mcq", lv: "B", q: "Ling wore a light blue dress. What is the opposite of 'light' here?", o: ["heavy", "dark", "bright", "pale"], a: 1, why: "Here light is about colour, so the opposite is dark: a dark blue dress." },
    { t: "mcq", lv: "B", q: "Mr Tan accepted the invitation. What is the opposite of 'accepted'?", o: ["took", "refused", "enjoyed", "sent"], a: 1, why: "To accept is to say yes; to refuse is to say no." },
    { t: "mcq", lv: "C", q: "The museum shows ancient tools. What is the opposite of 'ancient'?", o: ["old", "modern", "broken", "famous"], a: 1, why: "Ancient means very old; modern means new and of today." },
    { t: "mcq", lv: "C", q: "The team celebrated their victory. What is the opposite of 'victory'?", o: ["defeat", "prize", "match", "success"], a: 0, why: "A victory is a win; a defeat is a loss." },
    { t: "mcq", lv: "C", q: "The path was dangerous after the rain. What is the opposite of 'dangerous'?", o: ["risky", "safe", "slippery", "muddy"], a: 1, why: "Dangerous means you could get hurt; safe means you will not. Risky means the same as dangerous." },
    { t: "fix", lv: "A", q: "Can you borrow me your ruler?", err: "borrow", a: "lend", why: "You lend something to someone. You borrow something from someone." },
    { t: "fix", lv: "B", q: "My school shoes are too lose.", err: "lose", a: "loose", why: "Loose (two o's) means not tight. Lose means not win or not find." },
    { t: "fix", lv: "B", q: "Jia Hui was very unpolite to the cashier.", err: "unpolite", a: "impolite", why: "The opposite of polite is impolite. We do not say unpolite." },
    { t: "fix", lv: "B", q: "The lift was so empty that we could not squeeze in.", err: "empty", a: "full", why: "If we could not squeeze in, the lift had too many people. It was full, not empty." },
    { t: "fix", lv: "C", q: "Because it was raining heavily, the floor was dry and slippery.", err: "dry", a: "wet", why: "Rain makes the floor wet, and a wet floor is slippery." },
    { t: "fix", lv: "B", q: "Ali won his wallet on the bus and was very sad.", err: "won", a: "lost", why: "Won is the opposite of lost. Ali was sad because his wallet was gone, so he lost it." },
    { t: "fill", lv: "A", q: "The opposite of yes is ___ .", a: ["no"], why: "Yes and no are opposites." },
    { t: "fill", lv: "A", q: "Day and ___ are opposites.", a: ["night"], why: "Day is when it is bright; night is when it is dark." },
    { t: "fill", lv: "A", q: "The opposite of open is ___ .", a: ["closed", "shut", "close"], why: "A door is either open or closed (shut)." },
    { t: "fill", lv: "B", q: "The opposite of borrow is ___ .", a: ["lend"], why: "You borrow from someone; someone lends to you." },
    { t: "fill", lv: "B", q: "Happy and ___ are antonyms.", a: ["sad", "unhappy"], why: "Sad or unhappy is the opposite of happy." },
    { t: "fill", lv: "C", q: "The opposite of 'include' is ___ . (starts with ex)", a: ["exclude"], why: "Include means let someone in; exclude means leave someone out." }
  ]
});

/* ---------- 3. Prefixes ---------- */
window.VG.push({
  id: "en-v-prefixes",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Prefixes: un-, dis-, mis-, re-, pre-, im-, in-, non-",
  lv: "B",
  intro: "A prefix is a small group of letters added to the front of a word to change its meaning. If you know what the prefix means, you can work out many new words.",
  rules: [
    { h: "What is a prefix?", html: "A prefix goes at the <b>front</b> of a word and changes its meaning.<br><b>un</b> + <b>happy</b> = <b>unhappy</b> (not happy)" },
    { h: "Prefixes that mean 'not' or the opposite", html: "<b>un-</b>: unkind, unlock<br><b>dis-</b>: dislike, disagree, disappear<br><b>im-</b>: impossible, impatient, impolite<br><b>in-</b>: incorrect, invisible<br><b>non-</b>: nonstop, non-fiction" },
    { h: "im- or in-?", html: "Use <b>im-</b> before words starting with <b>m</b> or <b>p</b>: <b>im</b>mature, <b>im</b>possible, <b>im</b>patient.<br>Many other words take <b>in-</b>: <b>in</b>correct, <b>in</b>visible.<br>unpossible ✗ &nbsp; impossible ✓" },
    { h: "mis-, re- and pre-", html: "<b>mis-</b> = wrongly: misspell, misbehave, misunderstand<br><b>re-</b> = again: rewrite, reheat, retell<br><b>pre-</b> = before: preview, preheat, preschool" },
    { h: "Do not change the base word", html: "Just join the prefix and the word. Keep every letter.<br>mis + spell = <b>misspell</b> (two s) ✓ &nbsp; mispell ✗<br>dis + appear = <b>disappear</b> (one s) ✓ &nbsp; dissappear ✗" }
  ],
  words: [
    { w: "unkind", m: "not kind", ex: "It is unkind to laugh at someone who falls." },
    { w: "unlock", m: "open a lock", ex: "Dad unlocked the gate of our flat." },
    { w: "dislike", m: "not like", ex: "My brother dislikes bitter gourd." },
    { w: "disagree", m: "not agree; have a different idea", ex: "Amir and Sam disagreed about which game to play." },
    { w: "disappear", m: "go out of sight", ex: "The sun disappeared behind the clouds." },
    { w: "misspell", m: "spell wrongly", ex: "I often misspell the word 'necessary'." },
    { w: "misbehave", m: "behave badly", ex: "The puppy misbehaved and chewed my slipper." },
    { w: "misunderstand", m: "understand wrongly", ex: "Kumar misunderstood the question and gave the wrong answer." },
    { w: "rewrite", m: "write again", ex: "Please rewrite this sentence neatly." },
    { w: "reheat", m: "heat again", ex: "Grandma reheated the leftover chicken rice." },
    { w: "preview", m: "a look at something before the real thing (or to see it before others do)", ex: "Our class watched a preview of the school play." },
    { w: "preheat", m: "heat before using", ex: "Preheat the oven before you put the cake in." },
    { w: "impossible", m: "not possible", ex: "It is impossible to swim across the sea." },
    { w: "impatient", m: "not patient; not able to wait calmly", ex: "Lina grew impatient in the long queue." },
    { w: "incorrect", m: "not correct; wrong", ex: "Two of my answers were incorrect." },
    { w: "invisible", m: "not able to be seen", ex: "Air is invisible." },
    { w: "nonstop", m: "without stopping", ex: "It rained nonstop all weekend." },
    { w: "non-fiction", m: "writing about real facts, not made-up stories", ex: "I borrowed a non-fiction book about sharks." }
  ],
  mistakes: [
    { wrong: "It is unpossible.", right: "It is impossible.", why: "Words starting with p take im-: impossible." },
    { wrong: "I mispelled the word.", right: "I misspelled the word.", why: "mis + spell: keep both s's, so misspell has two s's." },
    { wrong: "The cat dissappeared.", right: "The cat disappeared.", why: "dis + appear: only one s, because appear starts with a." },
    { wrong: "Don't be unpolite.", right: "Don't be impolite.", why: "Polite starts with p, so we use im-: impolite." },
    { wrong: "Your answer is uncorrect.", right: "Your answer is incorrect.", why: "The opposite of correct is incorrect." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "What does 'unhappy' mean?", o: ["very happy", "not happy", "happy again"], a: 1, why: "un- means not, so unhappy means not happy." },
    { t: "mcq", lv: "A", q: "What does 'retell' mean?", o: ["tell again", "tell wrongly", "not tell"], a: 0, why: "re- means again, so retell means tell again." },
    { t: "mcq", lv: "A", q: "Which word is the opposite of 'lock'?", o: ["unlock", "dislock", "mislock"], a: 0, why: "We add un- to lock: unlock." },
    { t: "mcq", lv: "B", q: "What is the opposite of 'possible'?", o: ["unpossible", "impossible", "inpossible", "dispossible"], a: 1, why: "Possible starts with p, so we add im-: impossible." },
    { t: "mcq", lv: "B", q: "What is the opposite of 'agree'?", o: ["unagree", "misagree", "disagree", "nonagree"], a: 2, why: "We add dis- to agree: disagree." },
    { t: "mcq", lv: "B", q: "What does 'misbehave' mean?", o: ["behave well", "behave badly", "behave again", "behave before"], a: 1, why: "mis- means wrongly or badly, so misbehave means behave badly." },
    { t: "mcq", lv: "B", q: "What does 'preview' mean?", o: ["see before", "see again", "not see", "see wrongly"], a: 0, why: "pre- means before, so a preview is a look before the real thing." },
    { t: "mcq", lv: "B", q: "What is the opposite of 'correct'?", o: ["uncorrect", "incorrect", "miscorrect", "discorrect"], a: 1, why: "We add in- to correct: incorrect." },
    { t: "mcq", lv: "B", q: "What is the opposite of 'patient'?", o: ["unpatient", "dispatient", "impatient", "mispatient"], a: 2, why: "Patient starts with p, so we add im-: impatient." },
    { t: "mcq", lv: "B", q: "The recipe said to ___ the oven to 180 degrees before baking.", o: ["preheat", "reheat", "misheat", "unheat"], a: 0, why: "pre- means before. You heat the oven before you bake, so you preheat it." },
    { t: "mcq", lv: "B", q: "Grandma ___ the leftover chicken rice in the microwave.", o: ["preheated", "reheated", "misheated", "unheated"], a: 1, why: "The food was cooked before, so she heated it again: reheated." },
    { t: "mcq", lv: "B", q: "The express bus went ___ from Jurong East to Changi Airport.", o: ["nonstop", "unstop", "disstop", "restop"], a: 0, why: "non- means not or without. Nonstop means without stopping." },
    { t: "mcq", lv: "B", q: "Which prefix means 'wrongly'?", o: ["re-", "mis-", "pre-", "non-"], a: 1, why: "mis- means wrongly, as in misspell and misunderstand." },
    { t: "mcq", lv: "B", q: "Which prefix means 'again'?", o: ["re-", "un-", "dis-", "im-"], a: 0, why: "re- means again, as in redo and rewrite." },
    { t: "mcq", lv: "C", q: "The magician made the coin ___ .", o: ["unappear", "disappear", "misappear", "nonappear"], a: 1, why: "The opposite of appear is disappear." },
    { t: "mcq", lv: "C", q: "Which word is spelled correctly?", o: ["mispell", "misspell", "missspell", "misspel"], a: 1, why: "mis + spell = misspell. Keep all the letters of both parts." },
    { t: "mcq", lv: "C", q: "Which word is spelled correctly?", o: ["dissappoint", "disappoint", "disapoint", "dissapoint"], a: 1, why: "dis + appoint = disappoint: one s and two p's." },
    { t: "mcq", lv: "C", q: "Air is ___ ; we cannot see it.", o: ["unvisible", "invisible", "misvisible", "disvisible"], a: 1, why: "The opposite of visible is invisible." },
    { t: "mcq", lv: "C", q: "Kumar ___ the question and gave the wrong answer.", o: ["misunderstood", "ununderstood", "disunderstood", "reunderstood"], a: 0, why: "He understood it wrongly, so he misunderstood it." },
    { t: "mcq", lv: "C", q: "A ___ book is about real facts, not made-up stories.", o: ["non-fiction", "unfiction", "disfiction", "misfiction"], a: 0, why: "Fiction means made-up stories. Non-fiction means not made up: real facts." },
    { t: "fix", lv: "B", q: "It is unpossible to finish all this homework in ten minutes.", err: "unpossible", a: "impossible", why: "Possible starts with p, so the opposite is impossible." },
    { t: "fix", lv: "B", q: "My teacher told me to rewrite the sentence because I had mispelled two words.", err: "mispelled", a: "misspelled", why: "mis + spelled: keep both s's, so it is misspelled." },
    { t: "fix", lv: "B", q: "The rabbit dissappeared into the bushes.", err: "dissappeared", a: "disappeared", why: "dis + appeared: only one s, because appeared starts with a." },
    { t: "fix", lv: "B", q: "Please do not be unpolite to the bus captain.", err: "unpolite", a: "impolite", why: "Polite starts with p, so we use im-: impolite." },
    { t: "fix", lv: "C", q: "Lina was inpatient because the queue at the bubble tea shop was so long.", err: "inpatient", a: "impatient", why: "Not able to wait calmly is impatient, with im- because patient starts with p." },
    { t: "fix", lv: "C", q: "The answer is uncorrect, so please check it again.", err: "uncorrect", a: "incorrect", why: "The opposite of correct is incorrect." },
    { t: "fill", lv: "A", q: "Tie your shoelaces again: re + tie = ___", a: ["retie"], why: "re- means again, so tie again is retie." },
    { t: "fill", lv: "A", q: "un + kind = ___", a: ["unkind"], why: "un- means not. Unkind means not kind." },
    { t: "fill", lv: "B", q: "dis + honest = ___", a: ["dishonest"], why: "Just join them: dishonest means not honest." },
    { t: "fill", lv: "B", q: "mis + spell = ___", a: ["misspell"], why: "Keep every letter: mis + spell = misspell, with two s's." },
    { t: "fill", lv: "B", q: "Ivan did not obey his mother. He ___ her. (use dis-)", a: ["disobeyed"], why: "dis + obeyed = disobeyed, which means did not obey." },
    { t: "fill", lv: "C", q: "I did not understand the story, so I will read it again. I will ___ it. (use re-)", a: ["reread", "re-read"], why: "re- means again, so read again is reread." }
  ]
});

/* ---------- 4. Suffixes ---------- */
window.VG.push({
  id: "en-v-suffixes",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Suffixes: -ful, -less, -ness, -ment, -able, -ly, -er, -ous",
  lv: "B",
  intro: "A suffix is a group of letters added to the end of a word. It changes the meaning or the job of the word, for example care becomes careful, careless or carefully.",
  rules: [
    { h: "What is a suffix?", html: "A suffix goes at the <b>end</b> of a word.<br><b>help</b> + <b>ful</b> = <b>helpful</b> &nbsp; <b>kind</b> + <b>ness</b> = <b>kindness</b>" },
    { h: "-ful and -less", html: "<b>-ful</b> = full of: hopeful, careful, helpful (only <b>one l</b>!)<br><b>-less</b> = without: careless, fearless, homeless<br>carefull ✗ &nbsp; careful ✓" },
    { h: "-ness and -ment make naming words (nouns)", html: "<b>dark</b> → <b>darkness</b> &nbsp; <b>kind</b> → <b>kindness</b><br><b>enjoy</b> → <b>enjoyment</b> &nbsp; <b>pay</b> → <b>payment</b>" },
    { h: "-able and -ous make describing words", html: "<b>-able</b> = can be done: washable, readable, comfortable<br><b>-ous</b> = full of or having: dangerous, famous (fame → famous: drop the e)" },
    { h: "-ly tells how; -er names a person", html: "<b>-ly</b>: slow → slowly, careful → carefully. She sang <b>happily</b>.<br><b>-er</b>: a person who does it: teach → teacher, bake → baker, run → runner (double n)" },
    { h: "Spelling changes", html: "Change <b>y</b> to <b>i</b>: happy → happ<b>i</b>ness, happ<b>i</b>ly, beauty → beaut<b>i</b>ful<br>happyness ✗ &nbsp; beautyful ✗" }
  ],
  words: [
    { w: "helpful", m: "full of help; willing to help", ex: "The helpful boy carried Ah Ma's groceries." },
    { w: "careful", m: "taking care to avoid mistakes or danger", ex: "Be careful when you cross the road." },
    { w: "careless", m: "without care; not thinking about what you do", ex: "I lost marks for careless mistakes." },
    { w: "fearless", m: "without fear; very brave", ex: "The fearless climber reached the top of the wall." },
    { w: "kindness", m: "being kind", ex: "Thank you for your kindness to the new pupil." },
    { w: "darkness", m: "being dark", ex: "The torch lit up the darkness." },
    { w: "happiness", m: "being happy", ex: "Her face shone with happiness." },
    { w: "enjoyment", m: "the feeling of enjoying something", ex: "We watched the fireworks with great enjoyment." },
    { w: "payment", m: "money that you pay", ex: "The hawker took our payment by QR code." },
    { w: "washable", m: "can be washed", ex: "This school jacket is washable." },
    { w: "comfortable", m: "pleasant to sit in or wear; giving comfort", ex: "This sofa is very comfortable." },
    { w: "slowly", m: "in a slow way", ex: "The tortoise walked slowly across the grass." },
    { w: "happily", m: "in a happy way", ex: "The children sang happily at the concert." },
    { w: "teacher", m: "a person who teaches", ex: "Our teacher reads us a story every Friday." },
    { w: "baker", m: "a person who bakes bread and cakes", ex: "The baker starts work at four in the morning." },
    { w: "runner", m: "a person who runs", ex: "The fastest runner won a gold medal." },
    { w: "dangerous", m: "full of danger; could hurt you", ex: "Playing near the canal is dangerous." },
    { w: "famous", m: "known by many people", ex: "The Merlion is a famous landmark." }
  ],
  mistakes: [
    { wrong: "Please be carefull.", right: "Please be careful.", why: "The suffix -ful has only one l." },
    { wrong: "What beautyful orchids!", right: "What beautiful orchids!", why: "Change y to i before adding -ful: beauty → beautiful." },
    { wrong: "Her happyness made us smile.", right: "Her happiness made us smile.", why: "Change y to i before adding -ness: happy → happiness." },
    { wrong: "He ran quick to the bus stop.", right: "He ran quickly to the bus stop.", why: "To tell how someone did something, add -ly: quickly." },
    { wrong: "The fastest runer won.", right: "The fastest runner won.", why: "Run has one short vowel and ends in one consonant, so double the n: runner." },
    { wrong: "The Merlion is fameous.", right: "The Merlion is famous.", why: "Drop the e of fame before adding -ous: famous." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "What does 'helpful' mean?", o: ["full of help", "without help", "help again"], a: 0, why: "-ful means full of, so helpful means full of help." },
    { t: "mcq", lv: "A", q: "What does 'careless' mean?", o: ["full of care", "without care", "care again"], a: 1, why: "-less means without, so careless means without care." },
    { t: "mcq", lv: "A", q: "A person who teaches is a ___ .", o: ["teacher", "teachful", "teachness"], a: 0, why: "-er can mean a person who does something: teach → teacher." },
    { t: "mcq", lv: "B", q: "Which word is spelled correctly?", o: ["beautyful", "beautiful", "beautifull", "beautifel"], a: 1, why: "Change y to i, then add -ful with one l: beautiful." },
    { t: "mcq", lv: "B", q: "Which word is spelled correctly?", o: ["happyness", "happiness", "happines", "hapiness"], a: 1, why: "happy → change y to i → happi + ness = happiness (two p's, two s's)." },
    { t: "mcq", lv: "B", q: "Wen Xin walked ___ across the wet floor.", o: ["careful", "carefully", "careless", "carefulness"], a: 1, why: "We need a word that tells how she walked, so add -ly: carefully." },
    { t: "mcq", lv: "B", q: "The ___ of the night scared the little kitten.", o: ["dark", "darkly", "darken", "darkness"], a: 3, why: "After the, we need a naming word. dark + ness = darkness." },
    { t: "mcq", lv: "B", q: "Is this jacket ___ ? Can I put it in the washing machine?", o: ["washful", "washable", "washless", "washness"], a: 1, why: "-able means can be done. Washable means it can be washed." },
    { t: "mcq", lv: "B", q: "The hawker gave us our food after we made the ___ .", o: ["pay", "payable", "payment", "payful"], a: 2, why: "After the, we need a naming word. pay + ment = payment." },
    { t: "mcq", lv: "B", q: "Swimming in the sea during a storm is ___ .", o: ["danger", "dangerous", "dangerless", "dangerly"], a: 1, why: "After is, we need a describing word. danger + ous = dangerous." },
    { t: "mcq", lv: "B", q: "Which suffix means 'without'?", o: ["-ful", "-less", "-ness", "-er"], a: 1, why: "-less means without, as in homeless and fearless." },
    { t: "mcq", lv: "B", q: "The Merlion is a ___ landmark in Singapore.", o: ["fame", "famous", "famely", "fameful"], a: 1, why: "Drop the e of fame and add -ous: famous." },
    { t: "mcq", lv: "B", q: "My grandfather is a ___ ; he makes bread every morning.", o: ["baker", "bakery", "baking", "bakeful"], a: 0, why: "A baker is a person who bakes. A bakery is the shop, not the person." },
    { t: "mcq", lv: "B", q: "The fearless firefighter rushed into the burning flat. What does 'fearless' mean?", o: ["very scared", "not afraid", "full of fire", "very tired"], a: 1, why: "fear + less = without fear, so not afraid." },
    { t: "mcq", lv: "C", q: "The children sang ___ at the concert.", o: ["happy", "happily", "happiness", "happyly"], a: 1, why: "To tell how they sang, add -ly. Change y to i first: happily." },
    { t: "mcq", lv: "C", q: "We watched the show with great ___ .", o: ["enjoy", "enjoyable", "enjoyment", "enjoyed"], a: 2, why: "After great, we need a naming word: enjoyment." },
    { t: "mcq", lv: "C", q: "This new sofa is very ___ .", o: ["comfort", "comfortable", "comfortful", "comfortly"], a: 1, why: "After very, we need a describing word: comfortable." },
    { t: "mcq", lv: "C", q: "Thank you for your ___ to the new pupil.", o: ["kind", "kindness", "kindly", "kindful"], a: 1, why: "After your, we need a naming word: kindness." },
    { t: "mcq", lv: "C", q: "Which word has a suffix that makes a naming word (noun)?", o: ["hopeful", "sadness", "quickly", "useless"], a: 1, why: "-ness makes a noun: sadness. The others are describing words or a how word." },
    { t: "mcq", lv: "C", q: "The ___ won the 100-metre race.", o: ["run", "runer", "runner", "running"], a: 2, why: "Run + er: double the n to keep the short u sound, so runner." },
    { t: "fix", lv: "B", q: "Please be carefull when you cross the road.", err: "carefull", a: "careful", why: "The suffix -ful has only one l: careful." },
    { t: "fix", lv: "B", q: "Daniel answered the question correct.", err: "correct", a: "correctly", why: "To tell how he answered, add -ly: correctly." },
    { t: "fix", lv: "B", q: "The garden is full of beautyful orchids.", err: "beautyful", a: "beautiful", why: "Change y to i before adding -ful: beautiful." },
    { t: "fix", lv: "B", q: "My room was a mess because I was very careful with my things.", err: "careful", a: "careless", why: "A messy room comes from not taking care, so the word is careless (without care)." },
    { t: "fix", lv: "C", q: "Her happyness made everyone smile.", err: "happyness", a: "happiness", why: "Change y to i before adding -ness: happiness." },
    { t: "fix", lv: "C", q: "The movie was so enjoyment that we watched it twice.", err: "enjoyment", a: "enjoyable", why: "After so, we need a describing word: enjoyable. Enjoyment is a naming word." },
    { t: "fill", lv: "A", q: "hope + ful = ___", a: ["hopeful"], why: "Just add -ful with one l: hopeful." },
    { t: "fill", lv: "A", q: "slow + ly = ___", a: ["slowly"], why: "Add -ly to tell how: slowly." },
    { t: "fill", lv: "B", q: "A person who sings is a ___ .", a: ["singer"], why: "-er names the person who does it: singer." },
    { t: "fill", lv: "B", q: "Without a home: home + less = ___", a: ["homeless"], why: "-less means without, so homeless means without a home." },
    { t: "fill", lv: "B", q: "(sad) Tears ran down her face in ___ .", a: ["sadness"], why: "After in, we need a naming word: sad + ness = sadness." },
    { t: "fill", lv: "C", q: "(danger) The busy road is ___ for small children.", a: ["dangerous"], why: "After is, we need a describing word: danger + ous = dangerous." }
  ]
});

/* ---------- 5. Word forms ---------- */
window.VG.push({
  id: "en-v-wordforms",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Word forms: decide, decision, decisive",
  lv: "C",
  intro: "Many words belong to a family, like decide (action), decision (thing) and decisive (describing). In exams you often have to change the word in brackets into the right form, so it helps to know how families work.",
  rules: [
    { h: "Word families", html: "One idea can have different forms.<br>Action (verb): <b>decide</b><br>Thing (noun): <b>decision</b><br>Describing (adjective): <b>decisive</b><br>How (adverb): <b>decisively</b>" },
    { h: "Clue 1: after a, an, the, my, her, his, their → a noun", html: "(decide) Her <b>decision</b> surprised us. ✓<br>(arrive) We waited for the <b>arrival</b> of the train. ✓" },
    { h: "Clue 2: after is, was, very, so, a ... before a noun → an adjective", html: "(pride) He was very <b>proud</b>. ✓<br>(succeed) Mr Goh is a <b>successful</b> businessman. ✓" },
    { h: "Clue 3: telling HOW something is done → an adverb (-ly)", html: "(anger) Tom slammed the door <b>angrily</b>. ✓<br>(patient) Grandpa waited <b>patiently</b>. ✓" },
    { h: "Clue 4: after to, will, can, must, please → a verb", html: "(strong) Exercise helps to <b>strengthen</b> your muscles. ✓<br>(choice) Please <b>choose</b> one book. ✓" },
    { h: "Common endings", html: "Nouns: <b>-tion, -sion, -ment, -ness, -ance, -ship, -ity</b><br>Adjectives: <b>-ful, -ous, -ive, -able, -al, -y</b><br>Adverbs: <b>-ly</b><br>Verbs: <b>-en, -ise, en-</b> (strengthen, apologise, encourage)" },
    { h: "Watch the spelling", html: "explain → expl<b>a</b>nation (no i) &nbsp; describe → descri<b>p</b>tion<br>courage → courage<b>ous</b> (keep the e) &nbsp; anger → angr<b>i</b>ly" }
  ],
  words: [
    { w: "decide / decision / decisive", m: "choose / the choice you make / able to choose quickly and firmly", ex: "The captain was decisive: she made her decision in seconds." },
    { w: "succeed / success / successful / successfully", m: "do well / a good result / having done well / in a way that works", ex: "The show was a success, and everyone said it ended successfully." },
    { w: "arrive / arrival", m: "reach a place / the act of reaching a place", ex: "The arrival of the new pupils was announced at assembly." },
    { w: "invite / invitation", m: "ask someone to come / a card or message asking you to come", ex: "I received an invitation to Mei's party." },
    { w: "explain / explanation", m: "make something clear / words that make something clear", ex: "Mrs Lee gave a clear explanation of fractions." },
    { w: "describe / description", m: "say what something is like / words that say what something is like", ex: "Write a description of your favourite place." },
    { w: "behave / behaviour", m: "act in a certain way / the way you act", ex: "The class was praised for good behaviour." },
    { w: "know / knowledge", m: "have information in your mind / what you know", ex: "Reading improves your general knowledge." },
    { w: "choose / choice", m: "pick / the thing you pick", ex: "You must make a choice between chess and robotics." },
    { w: "anger / angry / angrily", m: "a strong cross feeling / feeling cross / in a cross way", ex: "He shouted angrily because he was angry." },
    { w: "pride / proud / proudly", m: "a good feeling about what you did / feeling pride / in a proud way", ex: "Dad smiled proudly at my prize." },
    { w: "strong / strength / strengthen", m: "having power / power / make stronger", ex: "Swimming strengthens your arms." },
    { w: "friend / friendly / friendship", m: "a person you like / kind and pleasant / being friends", ex: "Their friendship began in Primary 1." },
    { w: "imagine / imagination / imaginative", m: "picture in your mind / the power to picture things / full of new ideas", ex: "Her imaginative story had a flying HDB block." },
    { w: "agree / agreement", m: "have the same idea / a plan that people agree on", ex: "The two teams reached an agreement." },
    { w: "patience / patient / patiently", m: "being able to wait calmly / able to wait calmly / in a calm, waiting way", ex: "Ah Ma waited patiently for the bus." },
    { w: "courage / courageous / encourage", m: "bravery / brave / give someone hope to try", ex: "Her courageous act encouraged everyone." },
    { w: "beauty / beautiful / beautifully", m: "being lovely to look at or hear / lovely / in a lovely way", ex: "Jasmine sang beautifully at the concert." }
  ],
  mistakes: [
    { wrong: "We were surprised by his decide.", right: "We were surprised by his decision.", why: "After his, we need a noun: decision." },
    { wrong: "Mum was angrily when I broke the vase.", right: "Mum was angry when I broke the vase.", why: "After was, we need a describing word: angry. Angrily tells how someone does something." },
    { wrong: "The weightlifter showed great strong.", right: "The weightlifter showed great strength.", why: "After great, we need a noun: strength." },
    { wrong: "Please choice one book.", right: "Please choose one book.", why: "After please, we need an action word: choose. Choice is a noun." },
    { wrong: "He gave a clear explaination.", right: "He gave a clear explanation.", why: "Explanation drops the i of explain: expl-a-nation." }
  ],
  items: [
    { t: "mcq", lv: "B", q: "Her ___ surprised us.", o: ["decide", "decision", "decisive", "decisively"], a: 1, why: "After her, we need a noun (a thing): decision." },
    { t: "mcq", lv: "B", q: "Wei Ming was very ___ when he won the medal.", o: ["pride", "proud", "proudly", "prides"], a: 1, why: "After was very, we need a describing word: proud." },
    { t: "mcq", lv: "B", q: "The guests' ___ was delayed by the heavy rain.", o: ["arrive", "arrival", "arrives", "arrived"], a: 1, why: "After the guests', we need a noun: arrival." },
    { t: "mcq", lv: "B", q: "Please ___ the picture in your own words.", o: ["description", "describe", "descriptive", "descriptively"], a: 1, why: "After please, we need an action word (verb): describe." },
    { t: "mcq", lv: "B", q: "Hassan spoke ___ to the little girl who was lost.", o: ["kind", "kindly", "kindness", "kinder"], a: 1, why: "We need a word that tells how he spoke: kindly." },
    { t: "mcq", lv: "B", q: "The teacher praised the class for their good ___ .", o: ["behave", "behaviour", "behaved", "behaving"], a: 1, why: "After their good, we need a noun: behaviour (British spelling with -our)." },
    { t: "mcq", lv: "B", q: "I received an ___ to Mei's birthday party.", o: ["invitation", "invited", "inviting", "invitingly"], a: 0, why: "After an, we need a noun: invitation." },
    { t: "mcq", lv: "C", q: "The coach made a quick, ___ choice.", o: ["decide", "decision", "decisive", "decisively"], a: 2, why: "Before the noun choice, we need a describing word: decisive." },
    { t: "mcq", lv: "C", q: "Our team worked hard, and the project was a big ___ .", o: ["succeed", "success", "successful", "successfully"], a: 1, why: "After a big, we need a noun: success." },
    { t: "mcq", lv: "C", q: "She finished the race ___ despite her sore leg.", o: ["success", "succeed", "successful", "successfully"], a: 3, why: "We need a word that tells how she finished: successfully." },
    { t: "mcq", lv: "C", q: "Reading widely improves your general ___ .", o: ["know", "knowledge", "known", "knowing"], a: 1, why: "After your general, we need a noun: knowledge." },
    { t: "mcq", lv: "C", q: "Grandpa waited ___ for the bus in the hot sun.", o: ["patience", "patient", "patiently", "patients"], a: 2, why: "We need a word that tells how he waited: patiently." },
    { t: "mcq", lv: "C", q: "The firefighter's ___ saved the family.", o: ["courage", "courageous", "courageously", "encourage"], a: 0, why: "After the firefighter's, we need a noun: courage." },
    { t: "mcq", lv: "C", q: "Mrs Lim ___ us to try again after we lost the match.", o: ["courage", "courageous", "encouraged", "courageously"], a: 2, why: "We need an action word in the past: encouraged." },
    { t: "mcq", lv: "C", q: "The story was very ___ ; it had dragons and talking trees.", o: ["imagine", "imagination", "imaginative", "imaginatively"], a: 2, why: "After was very, we need a describing word: imaginative." },
    { t: "mcq", lv: "C", q: "The two schools signed an ___ to share the sports field.", o: ["agree", "agreement", "agreeable", "agreed"], a: 1, why: "After an, we need a noun: agreement." },
    { t: "mcq", lv: "C", q: "Which word is the noun form of 'explain'?", o: ["explanation", "explaination", "explained", "explainful"], a: 0, why: "The noun is explanation. Notice there is no i after the a." },
    { t: "fix", lv: "B", q: "We were all surprised by his decide to quit the team.", err: "decide", a: "decision", why: "After his, we need a noun: decision." },
    { t: "fix", lv: "C", q: "Mum was angrily when I broke the vase.", err: "angrily", a: "angry", why: "After was, use the describing word angry. Angrily tells how someone does something." },
    { t: "fix", lv: "C", q: "The weightlifter showed great strong.", err: "strong", a: "strength", why: "After great, we need a noun: strength." },
    { t: "fix", lv: "C", q: "Ali and Ravi have a strong friendly.", err: "friendly", a: "friendship", why: "After a strong, we need a noun: friendship." },
    { t: "fix", lv: "C", q: "Jasmine sang beauty at the concert.", err: "beauty", a: "beautifully", why: "We need a word that tells how she sang: beautifully." },
    { t: "fix", lv: "B", q: "Please choice one book from the box.", err: "choice", a: "choose", why: "After please, we need an action word: choose." },
    { t: "fill", lv: "B", q: "(decide) Her ___ surprised us.", a: ["decision"], why: "After her, we need a noun: decision." },
    { t: "fill", lv: "B", q: "(arrive) We waited for the ___ of the train.", a: ["arrival"], why: "After the, we need a noun: arrival." },
    { t: "fill", lv: "B", q: "(friend) The shopkeeper at our HDB block is very ___ .", a: ["friendly"], why: "After very, we need a describing word: friendly." },
    { t: "fill", lv: "B", q: "(anger) Tom slammed the door ___ .", a: ["angrily"], why: "This tells how he slammed the door. anger → angry → angrily." },
    { t: "fill", lv: "C", q: "(succeed) Mr Goh is a ___ businessman.", a: ["successful"], why: "Before the noun businessman, we need a describing word: successful." },
    { t: "fill", lv: "C", q: "(explain) The teacher gave a clear ___ of the sum.", a: ["explanation"], why: "After a clear, we need a noun: explanation (no i after the a)." },
    { t: "fill", lv: "C", q: "(imagine) Writers need a lot of ___ .", a: ["imagination"], why: "After a lot of, we need a noun: imagination." },
    { t: "fill", lv: "C", q: "(proud) Mum smiled ___ when I received my certificate.", a: ["proudly"], why: "This tells how she smiled: proudly." },
    { t: "fill", lv: "C", q: "(strong) Exercise helps to ___ your muscles.", a: ["strengthen"], why: "After to, we need an action word: strengthen (make stronger)." },
    { t: "fill", lv: "C", q: "(describe) Write a short ___ of your best friend.", a: ["description"], why: "After a short, we need a noun: description (b changes to p)." },
    { t: "fill", lv: "C", q: "(choose) You have to make a ___ between the two CCAs.", a: ["choice"], why: "After a, we need a noun: choice." }
  ]
});

/* ---------- 6. Words with more than one meaning ---------- */
window.VG.push({
  id: "en-v-multi",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Words with more than one meaning",
  lv: "B",
  intro: "Some words are spelled the same but have different meanings, like a bat that flies and a bat you hit a ball with. You must read the whole sentence to know which meaning is used.",
  rules: [
    { h: "Same spelling, different meaning", html: "A <b>bat</b> can be a flying animal or a stick to hit a ball.<br>A <b>bank</b> can keep your money or be the land beside a river." },
    { h: "Use the clues in the sentence", html: "Look at the other words to find the meaning.<br>The dog began to <b>bark</b>. → a sound (dog is the clue)<br>The <b>bark</b> of the tree is rough. → the skin of a tree (tree is the clue)" },
    { h: "It can be an action or a thing", html: "Some words can be a naming word or an action word.<br>I wear a <b>watch</b>. (thing) &nbsp; I <b>watch</b> TV. (action)<br>The <b>train</b> is late. (thing) &nbsp; Swimmers <b>train</b> hard. (action)" },
    { h: "Sound-alike words are different", html: "Some words sound the same but are spelled differently. Do not mix them up.<br>bus <b>fare</b> (money) ✓ &nbsp; bus <b>fair</b> ✗<br>a dog's <b>tail</b> ✓ &nbsp; a dog's <b>tale</b> ✗ (a tale is a story)" },
    { h: "Check the dictionary", html: "A dictionary gives each meaning a number: 1, 2, 3. Choose the one that makes sense in your sentence." }
  ],
  words: [
    { w: "bat", m: "1. a flying animal that comes out at night 2. a stick for hitting a ball", ex: "A bat flew past while Kiran swung his cricket bat." },
    { w: "bank", m: "1. a place that keeps money 2. the land along the side of a river", ex: "We sat on the bank of the river near the old bank building." },
    { w: "bark", m: "1. the sound a dog makes 2. the outer covering of a tree", ex: "The dog began to bark at the squirrel on the tree bark." },
    { w: "light", m: "1. not heavy 2. something that helps us see 3. pale in colour", ex: "Switch on the light. This light blue bag is light to carry." },
    { w: "fair", m: "1. right and equal for everyone 2. a funfair 3. pale (hair or skin)", ex: "It is not fair that only Ken got a ride at the fair." },
    { w: "ring", m: "1. a band you wear on your finger 2. the sound of a bell 3. a circle", ex: "I heard the doorbell ring while I looked for Mum's ring." },
    { w: "watch", m: "1. a small clock worn on the wrist 2. look at something for a while", ex: "Grandpa checked his watch before we sat down to watch the show." },
    { w: "wave", m: "1. a moving ridge of water in the sea 2. move your hand to say hello or goodbye", ex: "Su Lin gave a wave as a big wave crashed on the beach." },
    { w: "match", m: "1. a game between two teams 2. a small stick that makes fire 3. go well together", ex: "Your socks do not match!" },
    { w: "ruler", m: "1. a tool for drawing straight lines 2. a king or queen who rules a country", ex: "The ruler of the kingdom had a golden ruler." },
    { w: "park", m: "1. a public garden 2. leave a car somewhere for a while", ex: "Dad parked the car near the park." },
    { w: "kind", m: "1. nice and caring 2. a type or sort", ex: "What kind of noodles do you like?" },
    { w: "left", m: "1. the opposite of right 2. remaining 3. went away", ex: "Turn left. There is one slice of cake left." },
    { w: "right", m: "1. the opposite of left 2. correct", ex: "You got the right answer." },
    { w: "spring", m: "1. the season after winter 2. jump up suddenly 3. a coil of metal 4. a place where water comes out of the ground", ex: "The cat will spring onto the table." },
    { w: "train", m: "1. a vehicle that runs on rails 2. practise hard for a sport or skill", ex: "The swimmers train every morning before they take the train to school." },
    { w: "rock", m: "1. a stone 2. move gently from side to side", ex: "Mum rocked the baby to sleep." },
    { w: "fare", m: "the money you pay to travel (sounds like fair)", ex: "The bus fare is paid by tapping your card." }
  ],
  mistakes: [
    { wrong: "The bus fair is cheap.", right: "The bus fare is cheap.", why: "Fare is the money you pay for a ride. Fair means equal for everyone." },
    { wrong: "The dog wagged its tale.", right: "The dog wagged its tail.", why: "A tail is part of an animal. A tale is a story." },
    { wrong: "Turn write at the junction.", right: "Turn right at the junction.", why: "Right is a direction. Write is what you do with a pencil." },
    { wrong: "In 'Turn left at the light', left means 'remaining'.", right: "In 'Turn left at the light', left means 'the opposite of right'.", why: "Turn is the clue: it is about direction." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "The dog started to bark at the postman. What does 'bark' mean here?", o: ["the sound a dog makes", "the outside of a tree", "a small boat"], a: 0, why: "Dog is the clue. Here bark is the sound a dog makes." },
    { t: "mcq", lv: "A", q: "The bark of the old tree was rough. What does 'bark' mean here?", o: ["the sound a dog makes", "the outer covering of a tree", "a type of leaf"], a: 1, why: "Tree is the clue. Bark is the rough skin of a tree." },
    { t: "mcq", lv: "A", q: "Mum put money in the bank. What does 'bank' mean here?", o: ["a place that keeps money", "the side of a river", "a pile of sand"], a: 0, why: "Money is the clue. A bank keeps money safe." },
    { t: "mcq", lv: "B", q: "We had a picnic on the bank of the river. What does 'bank' mean here?", o: ["a place that keeps money", "the land along the side of a river", "a big rock", "a bridge"], a: 1, why: "River is the clue. The bank is the land beside a river." },
    { t: "mcq", lv: "B", q: "This bag is light; I can carry it easily. What does 'light' mean here?", o: ["bright", "not heavy", "a lamp", "pale in colour"], a: 1, why: "Carry it easily is the clue. Light here means not heavy." },
    { t: "mcq", lv: "B", q: "Please wave to Grandma from the window. What does 'wave' mean here?", o: ["a moving ridge of water", "move your hand to say hello or goodbye", "a curl in your hair", "a loud noise"], a: 1, why: "We wave our hand to greet someone." },
    { t: "mcq", lv: "B", q: "Does your watch tell the right time? What does 'watch' mean here?", o: ["look at something", "a small clock worn on the wrist", "guard something", "a TV show"], a: 1, why: "Tell the right time is the clue. A watch is a small clock on your wrist." },
    { t: "mcq", lv: "B", q: "It is not fair that Ken got two turns. What does 'fair' mean here?", o: ["a funfair", "light in colour", "right and equal for everyone", "the cost of a bus ride"], a: 2, why: "Two turns is the clue. Fair here means everyone gets the same." },
    { t: "mcq", lv: "B", q: "Turn left at the traffic light. What does 'left' mean here?", o: ["went away", "the opposite of right", "remaining", "forgot"], a: 1, why: "Turn is the clue. Left here is a direction." },
    { t: "mcq", lv: "B", q: "There is only one slice of cake left. What does 'left' mean here?", o: ["the opposite of right", "remaining", "went away", "wrong"], a: 1, why: "Only one slice is still there, so left here means remaining." },
    { t: "mcq", lv: "B", q: "We need a match to light the candle. What does 'match' mean here?", o: ["a game between two teams", "a small stick that makes fire", "things that look the same", "a friend"], a: 1, why: "Light the candle is the clue. A match is a small stick that makes fire." },
    { t: "mcq", lv: "B", q: "Our school won the football match. What does 'match' mean here?", o: ["a small stick that makes fire", "a game between two teams", "a pair", "a lighter"], a: 1, why: "Won and football are the clues. A match here is a game." },
    { t: "mcq", lv: "B", q: "In which sentence does 'ring' mean a sound?", o: ["She wears a gold ring.", "I heard the doorbell ring.", "The children sat in a ring.", "The ring was too big for my finger."], a: 1, why: "Heard and doorbell are the clues: ring is the sound a bell makes." },
    { t: "mcq", lv: "B", q: "In which sentence does 'kind' mean 'type'?", o: ["Aunty Mary is very kind.", "What kind of noodles do you like?", "Be kind to animals.", "It was kind of you to help."], a: 1, why: "What kind of noodles means what type of noodles." },
    { t: "mcq", lv: "C", q: "In which sentence does 'spring' mean a season?", o: ["The spring in the bed is broken.", "Flowers bloom in spring.", "The cat will spring onto the table.", "We drank water from a mountain spring."], a: 1, why: "Flowers bloom in spring, the season after winter." },
    { t: "mcq", lv: "C", q: "In which sentence is 'train' an action word?", o: ["The train was full.", "We took the train to Jurong.", "The swimmers train every morning.", "I left my bag on the train."], a: 2, why: "The swimmers train means they practise. In the others, a train is a vehicle." },
    { t: "mcq", lv: "C", q: "Please park the car near the lift lobby. What does 'park' mean here?", o: ["a garden with playgrounds", "leave a vehicle somewhere for a while", "a zoo", "walk slowly"], a: 1, why: "The car is the clue. To park is to leave a car in a place." },
    { t: "mcq", lv: "C", q: "That was the right answer. What does 'right' mean here?", o: ["the opposite of left", "correct", "a turn", "straight up"], a: 1, why: "Answer is the clue. A right answer is a correct answer." },
    { t: "mcq", lv: "C", q: "Which word fits BOTH sentences? 'I hit the ball with a ___.' 'A ___ flew out of the cave.'", o: ["stick", "bat", "bird", "racket"], a: 1, why: "A bat can be a stick for hitting a ball and a flying animal that lives in caves." },
    { t: "mcq", lv: "C", q: "Which word fits BOTH sentences? 'A big ___ crashed onto the beach.' 'Su Lin gave us a friendly ___.'", o: ["wave", "tide", "smile", "shell"], a: 0, why: "A wave can be water in the sea or a movement of your hand." },
    { t: "mcq", lv: "C", q: "Which word fits BOTH sentences? 'Draw a straight line with your ___.' 'The ___ of the country lives in a palace.'", o: ["pencil", "king", "ruler", "leader"], a: 2, why: "A ruler can be a tool for lines or a person who rules a country." },
    { t: "fix", lv: "B", q: "The bus fair from Bedok to Tampines is cheap.", err: "fair", a: "fare", why: "Fare is the money you pay to travel. Fair means equal for everyone." },
    { t: "fix", lv: "B", q: "Turn write at the next junction.", err: "write", a: "right", why: "Right is a direction. Write is what you do with a pen." },
    { t: "fix", lv: "B", q: "The dog wagged its tale when Lily came home.", err: "tale", a: "tail", why: "A tail is part of a dog. A tale is a story." },
    { t: "fix", lv: "B", q: "Mum asked me to by some bread from the bakery.", err: "by", a: "buy", why: "Buy means pay money for something. By is a small word like 'next to'." },
    { t: "fix", lv: "C", q: "We went to East Coast Park to watch the waives.", err: "waives", a: "waves", why: "The water in the sea comes in waves. Waives is a different word." },
    { t: "fill", lv: "A", q: "One word means BOTH 'a small clock on your wrist' AND 'to look at something for a while': ___", a: ["watch"], why: "I wear a watch. I watch TV." },
    { t: "fill", lv: "B", q: "One word means BOTH 'the sound a dog makes' AND 'the outside of a tree': ___", a: ["bark"], why: "Dogs bark. A tree is covered in bark." },
    { t: "fill", lv: "B", q: "One word means BOTH 'jewellery for your finger' AND 'the sound a bell makes': ___", a: ["ring"], why: "She wears a ring. I heard the bell ring." },
    { t: "fill", lv: "B", q: "One word means BOTH 'not heavy' AND 'something that helps us see in the dark': ___", a: ["light"], why: "A light bag is easy to carry. Switch on the light." },
    { t: "fill", lv: "B", q: "One word means BOTH 'a flying animal that comes out at night' AND 'a stick used to hit a ball': ___", a: ["bat"], why: "A bat flies at night. You hit a ball with a bat." },
    { t: "fill", lv: "C", q: "One word means BOTH 'a game between two teams' AND 'a small stick that makes fire': ___", a: ["match"], why: "We won the match. Light the candle with a match." },
    { t: "fill", lv: "C", q: "One word means BOTH 'the season after winter' AND 'to jump up suddenly': ___", a: ["spring"], why: "Flowers bloom in spring. A frog can spring into the air." }
  ]
});

/* ---------- 7. Make, do, take, have, give ---------- */
window.VG.push({
  id: "en-v-collocations",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Make, do, take, have, give",
  lv: "B",
  intro: "Some words like to go together, such as make a mistake and do homework. These partners are called collocations. Learning them as chunks makes your English sound natural.",
  rules: [
    { h: "Words that go together", html: "In English we say <b>make</b> a mistake, not <b>do</b> a mistake. There is not always a reason; learn each pair as one chunk." },
    { h: "MAKE: create or produce something", html: "<b>make</b> a mistake, a decision, a cake, friends, noise, a wish, an effort<br>I <b>made</b> a mistake. ✓ &nbsp; I <b>did</b> a mistake. ✗" },
    { h: "DO: tasks, jobs and work", html: "<b>do</b> homework, the dishes, the laundry, your best, exercise, someone a favour<br>Please <b>do</b> your homework. ✓ &nbsp; Please <b>make</b> your homework. ✗" },
    { h: "TAKE: photos, turns, transport, tests", html: "<b>take</b> a photo, turns, the bus, the MRT, an exam, a seat<br>Can you <b>take</b> a photo? ✓ &nbsp; Can you <b>do</b> a photo? ✗" },
    { h: "HAVE: meals, fun, experiences", html: "<b>have</b> breakfast, lunch, dinner, fun, a good time, a nap, a party<br>We <b>had</b> fun at Sentosa. ✓" },
    { h: "GIVE: speeches, advice, help", html: "<b>give</b> a speech, a talk, advice, a hand (help), someone a call<br>Can you <b>give</b> me a hand? ✓" }
  ],
  words: [
    { w: "make a mistake", m: "do something wrong by accident", ex: "It is all right to make a mistake when you are learning." },
    { w: "make a decision", m: "decide; choose", ex: "Philip made a decision to join the band." },
    { w: "make friends", m: "start new friendships", ex: "Aisha made friends quickly at her new school." },
    { w: "make noise", m: "cause loud sounds", ex: "Please don't make noise in the library." },
    { w: "make an effort", m: "try hard", ex: "Make an effort to write neatly." },
    { w: "do homework", m: "complete the work given by a teacher", ex: "I do my homework after dinner." },
    { w: "do the dishes", m: "wash the plates and bowls", ex: "My brother does the dishes on weekends." },
    { w: "do your best", m: "try as hard as you can", ex: "Just do your best in the exam." },
    { w: "do someone a favour", m: "help someone with something", ex: "Could you do me a favour and water my plants?" },
    { w: "do exercise", m: "move your body to keep fit", ex: "Grandpa does exercise at the void deck every morning." },
    { w: "take a photo", m: "use a camera to make a picture", ex: "Let's take a photo at the Merlion." },
    { w: "take turns", m: "do something one after another", ex: "We take turns on the swing." },
    { w: "take the MRT", m: "travel on the MRT", ex: "We take the MRT to school." },
    { w: "take an exam", m: "sit for a test", ex: "P6 pupils take the PSLE at the end of primary school." },
    { w: "have breakfast", m: "eat the morning meal", ex: "We have breakfast at the kopitiam on Sundays." },
    { w: "have fun", m: "enjoy yourself", ex: "We had fun at the birthday party." },
    { w: "have a nap", m: "sleep for a short time in the day", ex: "The baby has a nap after lunch." },
    { w: "give a speech", m: "talk to an audience", ex: "The principal gave a speech at assembly." },
    { w: "give advice", m: "tell someone what you think they should do", ex: "My aunt gave me good advice about making friends." },
    { w: "give someone a hand", m: "help someone", ex: "Can you give me a hand with these bags?" }
  ],
  mistakes: [
    { wrong: "I did a mistake.", right: "I made a mistake.", why: "We always say make a mistake." },
    { wrong: "I will make my homework now.", right: "I will do my homework now.", why: "Homework is a task, and we do tasks." },
    { wrong: "Can you do a photo of us?", right: "Can you take a photo of us?", why: "We always say take a photo." },
    { wrong: "The boys were doing a lot of noise.", right: "The boys were making a lot of noise.", why: "Noise is something you produce, so we say make noise." },
    { wrong: "Let's make turns.", right: "Let's take turns.", why: "We say take turns." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Please don't ___ noise in the library.", o: ["make", "do", "take"], a: 0, why: "We say make noise." },
    { t: "mcq", lv: "A", q: "I ___ my homework after dinner.", o: ["make", "do", "give"], a: 1, why: "Homework is a task. We do homework." },
    { t: "mcq", lv: "A", q: "Can I ___ a photo of the Merlion?", o: ["make", "do", "take"], a: 2, why: "We say take a photo." },
    { t: "mcq", lv: "A", q: "We ___ breakfast at the hawker centre every Sunday.", o: ["have", "do", "give"], a: 0, why: "For meals we say have: have breakfast, have lunch." },
    { t: "mcq", lv: "B", q: "Oops! I ___ a mistake in my spelling.", o: ["did", "made", "took", "gave"], a: 1, why: "We say make a mistake, so in the past it is made a mistake." },
    { t: "mcq", lv: "B", q: "The principal will ___ a speech at assembly.", o: ["do", "give", "take", "have"], a: 1, why: "We say give a speech." },
    { t: "mcq", lv: "B", q: "Could you ___ me a favour and hold the door?", o: ["make", "do", "take", "have"], a: 1, why: "We say do someone a favour." },
    { t: "mcq", lv: "B", q: "Let's ___ turns on the swing.", o: ["make", "do", "take", "give"], a: 2, why: "We say take turns." },
    { t: "mcq", lv: "B", q: "Ravi always tries to ___ his best in exams.", o: ["make", "do", "take", "have"], a: 1, why: "We say do your best." },
    { t: "mcq", lv: "B", q: "We ___ the MRT to school every day.", o: ["take", "make", "do", "give"], a: 0, why: "For buses and trains we say take: take the MRT." },
    { t: "mcq", lv: "B", q: "Did you ___ fun at the birthday party?", o: ["make", "do", "have", "give"], a: 2, why: "We say have fun." },
    { t: "mcq", lv: "B", q: "My aunt ___ me good advice about making friends.", o: ["made", "did", "gave", "took"], a: 2, why: "We say give advice, so in the past it is gave advice." },
    { t: "mcq", lv: "B", q: "It is easy to ___ friends at a new CCA.", o: ["do", "make", "take", "give"], a: 1, why: "We say make friends." },
    { t: "mcq", lv: "B", q: "After lunch, Ah Ma ___ the dishes.", o: ["made", "did", "took", "gave"], a: 1, why: "Washing dishes is a job. We say do the dishes." },
    { t: "mcq", lv: "C", q: "Which phrase is correct?", o: ["make an exam", "do a photo", "take an exam", "give a mistake"], a: 2, why: "We take an exam. We make a mistake and take a photo." },
    { t: "mcq", lv: "C", q: "Which phrase is correct?", o: ["do a decision", "make a decision", "say a decision", "bring a decision"], a: 1, why: "We say make a decision." },
    { t: "mcq", lv: "C", q: "Could you ___ me a hand with these heavy bags?", o: ["give", "make", "do", "take"], a: 0, why: "Give someone a hand means help them." },
    { t: "mcq", lv: "C", q: "The baby needs to ___ a nap.", o: ["make", "do", "have", "give"], a: 2, why: "We say have a nap." },
    { t: "mcq", lv: "C", q: "Which phrase is WRONG?", o: ["make a cake", "do the laundry", "take a seat", "make your homework"], a: 3, why: "Homework is a task, so we do our homework, not make it." },
    { t: "mcq", lv: "C", q: "Which phrase is WRONG?", o: ["have lunch", "give a talk", "do a noise", "take a bus"], a: 2, why: "We make noise, not do noise." },
    { t: "fix", lv: "B", q: "I did a mistake in my maths sum.", err: "did", a: "made", why: "We say make a mistake, so the past is made." },
    { t: "fix", lv: "B", q: "Please make your homework before you play.", err: "make", a: "do", why: "Homework is a task, so we do it." },
    { t: "fix", lv: "B", q: "Can you do a photo of us at Gardens by the Bay?", err: "do", a: "take", why: "We say take a photo." },
    { t: "fix", lv: "B", q: "The children were doing a lot of noise in the corridor.", err: "doing", a: "making", why: "We say make noise, so it is making a lot of noise." },
    { t: "fix", lv: "C", q: "Our form teacher made us useful advice before the exam.", err: "made", a: "gave", why: "We say give advice, so the past is gave." },
    { t: "fix", lv: "C", q: "Let's make turns to use the computer.", err: "make", a: "take", why: "We say take turns." },
    { t: "fill", lv: "A", q: "(make / do) Please ___ the dishes after dinner.", a: ["do"], why: "Washing the dishes is a job. We do the dishes." },
    { t: "fill", lv: "A", q: "(make / take) Smile! I will ___ a photo.", a: ["take"], why: "We say take a photo." },
    { t: "fill", lv: "B", q: "(make / do) Everyone can ___ a mistake sometimes.", a: ["make"], why: "We say make a mistake." },
    { t: "fill", lv: "B", q: "(have / make) Did you ___ a good time at Sentosa?", a: ["have"], why: "We say have a good time." },
    { t: "fill", lv: "B", q: "(make / do) Please ___ your best in the race.", a: ["do"], why: "We say do your best." },
    { t: "fill", lv: "C", q: "(give / take) The volunteers always ___ a helping hand at the old folks' home.", a: ["give"], why: "Give someone a hand means help them." }
  ]
});

/* ---------- 8. Phrasal verbs 1 ---------- */
window.VG.push({
  id: "en-v-phrasal1",
  lang: "en",
  kind: "vocab",
  group: "Word power",
  title: "Phrasal verbs 1: look after, give up, run out of, put off, set off…",
  lv: "B",
  intro: "A phrasal verb is an action word plus a small word, like look after or give up. Together they make a new meaning, so you need to learn them as a whole.",
  rules: [
    { h: "What is a phrasal verb?", html: "An action word + a small word (up, off, on, after, out...) = a new meaning.<br><b>give</b> + <b>up</b> = stop trying &nbsp; <b>look</b> + <b>after</b> = take care of" },
    { h: "The small word changes everything", html: "<b>look after</b> = take care of<br><b>look for</b> = try to find<br><b>look up</b> = find in a dictionary<br><b>turn on</b> = start a machine &nbsp; <b>turn off</b> = stop it" },
    { h: "With it, them, me: put it in the middle", html: "Some phrasal verbs can be split. With <b>it, them, me, him, her</b>, the small word goes in the middle.<br>Turn <b>it</b> off. ✓ &nbsp; Turn off it. ✗<br>Pick <b>me</b> up at six. ✓ &nbsp; Pick up me. ✗" },
    { h: "Three-word phrasal verbs", html: "<b>run out of</b> = have none left: We have run out of milk.<br><b>look forward to</b> = feel happy about something coming. Use <b>-ing</b> after it:<br>I look forward to <b>seeing</b> you. ✓ &nbsp; I look forward to see you. ✗" },
    { h: "Change the tense of the action word", html: "Only the first word changes.<br>give up → <b>gave</b> up &nbsp; run out of → <b>ran</b> out of &nbsp; set off → <b>set</b> off (same)" }
  ],
  words: [
    { w: "look after", m: "take care of", ex: "Ah Ma looks after my baby brother when Mum is at work." },
    { w: "look for", m: "try to find", ex: "I am looking for my eraser." },
    { w: "look up", m: "find information in a dictionary or book", ex: "Look up the new word in the dictionary." },
    { w: "look forward to", m: "feel happy about something that will happen", ex: "I'm looking forward to the school holidays." },
    { w: "give up", m: "stop trying; stop doing a habit", ex: "Don't give up! You can finish the race." },
    { w: "give back", m: "return something", ex: "Please give back the book by Friday." },
    { w: "run out of", m: "have none left", ex: "We have run out of rice." },
    { w: "put off", m: "move to a later time", ex: "The match was put off because of the rain." },
    { w: "put on", m: "start wearing", ex: "Put on your jacket; the cinema is cold." },
    { w: "put away", m: "put something back in its place", ex: "Put away your toys before dinner." },
    { w: "set off", m: "start a journey", ex: "We set off for the airport at 5 a.m." },
    { w: "take off", m: "1. leave the ground (a plane) 2. remove clothes", ex: "Take off your shoes before you enter the flat." },
    { w: "turn on", m: "start a machine or light", ex: "Turn on the fan, please." },
    { w: "turn off", m: "stop a machine or light", ex: "Turn off the lights when you leave." },
    { w: "turn down", m: "make quieter or lower", ex: "Please turn down the TV." },
    { w: "find out", m: "discover information", ex: "Let's find out what time the library closes." },
    { w: "get up", m: "get out of bed", ex: "I get up at six on school days." },
    { w: "come across", m: "find by chance", ex: "I came across an old photo in my drawer." },
    { w: "carry on", m: "continue", ex: "Carry on reading until the bell rings." },
    { w: "break down", m: "stop working (a machine or car)", ex: "Our car broke down on the expressway." },
    { w: "pick up", m: "collect someone or something", ex: "Dad will pick me up after CCA." }
  ],
  mistakes: [
    { wrong: "It's dark. Turn on it.", right: "It's dark. Turn it on.", why: "With it, put it in the middle: turn it on." },
    { wrong: "I look forward to see you.", right: "I look forward to seeing you.", why: "After look forward to, use the -ing form." },
    { wrong: "Yesterday we run out of milk.", right: "Yesterday we ran out of milk.", why: "Yesterday means past, so change run to ran." },
    { wrong: "Who looks after for your dog?", right: "Who looks after your dog?", why: "Look after already has its small word. Do not add for." },
    { wrong: "We set up for Malaysia at 6 a.m.", right: "We set off for Malaysia at 6 a.m.", why: "Set off means start a journey. Set up means put something in place." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Please ___ the lights when you leave the room.", o: ["turn off", "turn up", "turn into"], a: 0, why: "Turn off means stop a light or machine. We save electricity when we leave." },
    { t: "mcq", lv: "A", q: "Ah Ma ___ my baby brother when Mum is at work.", o: ["looks after", "looks up", "looks out"], a: 0, why: "Look after means take care of." },
    { t: "mcq", lv: "A", q: "It is cold in the cinema. ___ your jacket.", o: ["Put on", "Put off", "Put out"], a: 0, why: "Put on means start wearing clothes." },
    { t: "mcq", lv: "B", q: "We have ___ milk. Can you buy some?", o: ["run out of", "run into", "run away", "run over"], a: 0, why: "Run out of means have none left." },
    { t: "mcq", lv: "B", q: "Don't ___ ! You can finish the race.", o: ["give up", "give back", "give out", "give away"], a: 0, why: "Give up means stop trying." },
    { t: "mcq", lv: "B", q: "The match was ___ until next week because of the heavy rain.", o: ["put off", "put on", "put away", "put up"], a: 0, why: "Put off means move to a later time." },
    { t: "mcq", lv: "B", q: "We ___ for the airport at 5 a.m.", o: ["set off", "set up", "set down", "set back"], a: 0, why: "Set off means start a journey." },
    { t: "mcq", lv: "B", q: "I can't find my eraser. Can you help me ___ it?", o: ["look for", "look after", "look up", "look out"], a: 0, why: "Look for means try to find." },
    { t: "mcq", lv: "B", q: "If you don't know a word, you can ___ in the dictionary.", o: ["look it up", "look up it", "look it after", "look it for"], a: 0, why: "Look up means find information. With it, put it in the middle: look it up." },
    { t: "mcq", lv: "B", q: "The plane will ___ in ten minutes.", o: ["take off", "take on", "take after", "take in"], a: 0, why: "A plane takes off when it leaves the ground." },
    { t: "mcq", lv: "B", q: "Please ___ the fan. It's so hot!", o: ["turn on", "turn off", "turn down", "turn over"], a: 0, why: "It is hot, so we want the fan to start: turn on." },
    { t: "mcq", lv: "B", q: "Our car ___ on the expressway, so we called for help.", o: ["broke down", "broke up", "broke in", "broke out"], a: 0, why: "Break down means a machine or car stops working." },
    { t: "mcq", lv: "B", q: "Wake up! It's time to ___ .", o: ["get up", "get on", "get off", "get over"], a: 0, why: "Get up means get out of bed." },
    { t: "mcq", lv: "B", q: "Please ___ your toys before dinner.", o: ["put away", "put off", "put on", "put up"], a: 0, why: "Put away means put things back in their place." },
    { t: "mcq", lv: "C", q: "I'm looking forward to ___ my cousins in December.", o: ["see", "seeing", "saw", "seen"], a: 1, why: "After look forward to, use the -ing form: seeing." },
    { t: "mcq", lv: "C", q: "Hui Min ___ an old photo while she was cleaning her drawer.", o: ["came across", "came up", "came over", "came back"], a: 0, why: "Come across means find by chance." },
    { t: "mcq", lv: "C", q: "Can you ___ what time the library closes?", o: ["find out", "find up", "find in", "find off"], a: 0, why: "Find out means discover information." },
    { t: "mcq", lv: "C", q: "Even though he was tired, Arjun ___ running.", o: ["carried on", "carried out", "carried off", "carried away"], a: 0, why: "Carry on means continue." },
    { t: "mcq", lv: "C", q: "Mum will ___ from school at 6 p.m.", o: ["pick me up", "pick up me", "pick me on", "pick me out"], a: 0, why: "Pick up means collect. With me, put it in the middle: pick me up." },
    { t: "mcq", lv: "C", q: "Kai's music was too loud, so Dad asked him to ___ .", o: ["turn it down", "turn down it", "turn it over", "turn it up"], a: 0, why: "Turn down means make quieter. With it, put it in the middle: turn it down." },
    { t: "mcq", lv: "C", q: "Please ___ the library book by Friday.", o: ["give back", "give up", "give away", "give out"], a: 0, why: "Give back means return something. You return a library book; you do not give it away or give it out." },
    { t: "fix", lv: "B", q: "It's dark in here. Please turn on it.", err: "turn on it", a: "turn it on", why: "With it, the small word goes after it: turn it on." },
    { t: "fix", lv: "B", q: "Yesterday we run out of bread.", err: "run", a: "ran", why: "Yesterday is the past, so change only the action word: ran out of." },
    { t: "fix", lv: "C", q: "I look forward to see you at the party.", err: "see", a: "seeing", why: "After look forward to, use the -ing form: seeing." },
    { t: "fix", lv: "B", q: "Who looks after for your dog when you travel?", err: "looks after for", a: "looks after", why: "Look after already has its small word. Do not add for." },
    { t: "fix", lv: "B", q: "We set up for Malaysia early in the morning.", err: "set up", a: "set off", why: "Set off means start a journey." },
    { t: "fix", lv: "C", q: "The concert was put on until next week because the singer was ill.", err: "put on", a: "put off", why: "Put off means move to a later time. Put on means wear something, or hold a show." },
    { t: "fix", lv: "B", q: "My grandpa gave off smoking ten years ago.", err: "gave off", a: "gave up", why: "Give up means stop a habit." },
    { t: "fill", lv: "A", q: "The tap is dripping. Please ___ it off.", a: ["turn"], why: "Turn off means stop. With it in the middle: turn it off." },
    { t: "fill", lv: "B", q: "We have run out ___ sugar.", a: ["of"], why: "Run out of has three words: run, out, of." },
    { t: "fill", lv: "B", q: "Please look ___ your little sister and keep her safe while I cook.", a: ["after"], why: "Look after means take care of." },
    { t: "fill", lv: "B", q: "Don't give ___ . Keep trying!", a: ["up", "in"], why: "Give up (or give in) means stop trying." },
    { t: "fill", lv: "C", q: "The plane took ___ on time.", a: ["off"], why: "A plane takes off when it leaves the ground." },
    { t: "fill", lv: "C", q: "I came ___ a two-dollar coin on the floor of the MRT train.", a: ["across", "upon"], why: "Come across (or come upon) means find by chance." }
  ]
});
