window.VG = window.VG || [];

window.VG.push({
  id: "en-g-pronouns",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Pronouns (I/me, he/him, mine, myself)",
  lv: "A",
  intro: "Pronouns are short words that stand in for names, like I, me, she, them and mine. Using the right one stops your writing from repeating names and makes it sound correct.",
  rules: [
    { h: "Doer or receiver?", html: "Use <b>I, he, she, we, they</b> for the one <b>doing</b> the action. Use <b>me, him, her, us, them</b> for the one <b>receiving</b> it.<br>✓ <b>She</b> helped <b>me</b>.  ✗ <b>Her</b> helped <b>I</b>." },
    { h: "The cover-up trick", html: "When there are two people, cover the other name and listen.<br>Mei Ling and ___ went home. → <b>I</b> went home. ✓ Mei Ling and <b>I</b> went home.<br>Grandma hugged Ali and ___. → Grandma hugged <b>me</b>. ✓ Grandma hugged Ali and <b>me</b>." },
    { h: "Be polite: others first", html: "Put the other person first and yourself last.<br>✓ <b>My sister and I</b> went swimming.  ✗ <b>Me and my sister</b> went swimming." },
    { h: "Owning words", html: "<b>my, your, his, her, its, our, their</b> come before a noun: <b>my</b> bag.<br><b>mine, yours, his, hers, ours, theirs</b> stand alone: The bag is <b>mine</b>.<br>They never take an apostrophe: ✓ yours, hers, its  ✗ your's, her's, it's (it's means it is)." },
    { h: "-self and -selves", html: "Use <b>myself, yourself, himself, herself, itself, ourselves, yourselves, themselves</b> when the doer does something to itself, or to say 'with no help'.<br>✓ Ravi hurt <b>himself</b>. ✓ I did it <b>myself</b>.<br>✗ hisself, theirselves, themself." },
    { h: "Don't use -self instead of I or me", html: "✗ Mum and <b>myself</b> cooked dinner. ✓ Mum and <b>I</b> cooked dinner.<br>✗ Please call Ken or <b>myself</b>. ✓ Please call Ken or <b>me</b>." }
  ],
  words: [],
  mistakes: [
    { wrong: "Me and my brother went to the zoo.", right: "My brother and I went to the zoo.", why: "We are the doers, so use I, and put the other person first." },
    { wrong: "The teacher praised Ken and I.", right: "The teacher praised Ken and me.", why: "Cover 'Ken and': 'praised me' sounds right. Receivers take me." },
    { wrong: "This seat is your's.", right: "This seat is yours.", why: "Owning words like yours and hers never take an apostrophe." },
    { wrong: "The boys blamed theirselves.", right: "The boys blamed themselves.", why: "There is no word 'theirselves'. The correct word is themselves." },
    { wrong: "The dog wagged it's tail.", right: "The dog wagged its tail.", why: "It's means 'it is'. For owning, use its with no apostrophe." },
    { wrong: "Mum and myself will bring the food.", right: "Mum and I will bring the food.", why: "Myself is only for when you do something to yourself. As a doer, use I." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Mei Ling and ___ walked to the MRT station.", o: ["me", "I", "myself"], a: 1, why: "Cover 'Mei Ling and': 'I walked' is right. I is used for the doer." },
    { t: "mcq", lv: "A", q: "Grandma gave ___ a red packet.", o: ["me", "I", "mine"], a: 0, why: "Grandma is the giver. I am the receiver, so use me." },
    { t: "mcq", lv: "A", q: "This pencil case is not yours. It is ___.", o: ["my", "me", "mine"], a: 2, why: "No noun comes after the blank, so use the stand-alone owning word mine." },
    { t: "mcq", lv: "A", q: "Ravi hurt ___ when he fell off his bicycle.", o: ["him", "himself", "his"], a: 1, why: "Ravi hurt Ravi, the same person, so use himself." },
    { t: "mcq", lv: "A", q: "Look at the kittens! ___ are so cute.", o: ["They", "It", "Them"], a: 0, why: "Kittens are more than one and they are the doers here, so use They." },
    { t: "mcq", lv: "A", q: "Ah Ma cooked noodles for Wei Jie and ___.", o: ["I", "myself", "me"], a: 2, why: "Cover 'Wei Jie and': 'for me' sounds right. After for, use me." },
    { t: "mcq", lv: "A", q: "Is this water bottle ___, Siti?", o: ["yours", "your", "you"], a: 0, why: "No noun follows the blank, so use the stand-alone word yours." },
    { t: "mcq", lv: "A", q: "This is Nurul. ___ is my best friend.", o: ["Her", "She", "Hers"], a: 1, why: "Nurul is the subject of the sentence (the one who is), so use She." },
    { t: "mcq", lv: "A", q: "My brother and I share a room. It is ___ room.", o: ["our", "ours", "us"], a: 0, why: "The noun 'room' comes right after the blank, so use our." },
    { t: "mcq", lv: "B", q: "The twins did the project by ___.", o: ["themself", "theirselves", "themselves", "them"], a: 2, why: "By themselves means with no help. For more than one person, the word is themselves." },
    { t: "mcq", lv: "B", q: "Between you and ___, I think the quiz was easy.", o: ["me", "I", "myself", "mine"], a: 0, why: "After between, use me, just like 'between us'." },
    { t: "mcq", lv: "B", q: "Our class won the cleanest classroom award. The trophy is ___.", o: ["our", "our's", "ours", "us"], a: 2, why: "No noun follows, so use ours. It never has an apostrophe." },
    { t: "mcq", lv: "B", q: "The dog wagged ___ tail.", o: ["it's", "its", "their", "it"], a: 1, why: "The tail belongs to the dog, so use its. It's means 'it is'." },
    { t: "mcq", lv: "B", q: "Priya and ___ are in the same CCA.", o: ["I", "me", "myself", "mine"], a: 0, why: "Cover 'Priya and': 'I am in the CCA'. Doers take I." },
    { t: "mcq", lv: "B", q: "Mr Tan told Hafiz and ___ to stack the chairs.", o: ["I", "myself", "mine", "me"], a: 3, why: "Mr Tan told me. I am the receiver, so use me." },
    { t: "mcq", lv: "B", q: "We enjoyed ___ at the Chingay parade.", o: ["us", "ourself", "ourselves", "our"], a: 2, why: "We enjoyed the same 'we', so use ourselves (more than one person, -selves)." },
    { t: "mcq", lv: "B", q: "Aisha left her umbrella here. Is this umbrella ___?", o: ["her", "hers", "her's", "she"], a: 1, why: "No noun follows the blank, so use hers, with no apostrophe." },
    { t: "mcq", lv: "B", q: "Jun Hao bought a gift for his mother. He will give it to ___ on Mother's Day.", o: ["she", "herself", "hers", "her"], a: 3, why: "His mother receives the gift. After to, use her." },
    { t: "mcq", lv: "C", q: "___ pupils must line up quietly at the canteen.", o: ["Us", "We", "Ourselves", "Them"], a: 1, why: "Cover 'pupils': 'We must line up'. The doers take We, not Us or Them." },
    { t: "mcq", lv: "C", q: "The principal ___ handed out the prizes.", o: ["hisself", "him", "himself", "his"], a: 2, why: "Himself here means 'he did it in person'. Hisself is not a real word." },
    { t: "fix", lv: "A", q: "Me and my sister went to the library.", err: "Me and my sister", a: "My sister and I", why: "We are the doers, so use I, and put the other person first to be polite." },
    { t: "fix", lv: "A", q: "Him is my cousin from Johor Bahru.", err: "Him", a: "He", why: "The subject of the sentence takes He, not Him." },
    { t: "fix", lv: "A", q: "The teacher smiled at Ken and I.", err: "Ken and I", a: "Ken and me", why: "Cover 'Ken and': 'smiled at me'. After at, use me." },
    { t: "fix", lv: "B", q: "This seat is your's.", err: "your's", a: "yours", why: "Owning words like yours never take an apostrophe." },
    { t: "fix", lv: "B", q: "The boys blamed theirselves for losing the match.", err: "theirselves", a: "themselves", why: "Theirselves is not a word. Use themselves." },
    { t: "fix", lv: "B", q: "The cat licked it's paw.", err: "it's", a: "its", why: "It's means 'it is'. The paw belongs to the cat, so use its." },
    { t: "fix", lv: "C", q: "Mum and myself will bring the food.", err: "myself", a: "I", why: "Cover 'Mum and': 'I will bring'. Myself is not used as a doer." },
    { t: "fill", lv: "A", q: "Mei and Ali are my neighbours. I play with ___ every evening.", a: ["them"], why: "Mei and Ali are two people receiving the action, so use them." },
    { t: "fill", lv: "A", q: "I tied my shoelaces all by ___.", a: ["myself"], why: "By myself means with no help from anyone." },
    { t: "fill", lv: "A", q: "That blue bicycle belongs to me. It is ___.", a: ["mine"], why: "No noun follows, so use the owning word mine." },
    { t: "fill", lv: "B", q: "The children behaved ___ during the school assembly. (Use a -selves word.)", a: ["themselves"], why: "Behave yourself means be good. The children are more than one, so use themselves." },
    { t: "fill", lv: "B", q: "Kumar lost his wallet, but a kind auntie returned it to ___.", a: ["him"], why: "Kumar is the receiver. After to, use him." },
    { t: "fill", lv: "B", q: "Did you make this kite ___, Farah?", a: ["yourself"], why: "Talking to one person, 'with no help' is yourself." },
    { t: "trans", lv: "B", q: "Rewrite using pronouns so the name is not repeated: Amy said Amy would bring Amy's camera.", a: ["Amy said she would bring her camera.", "Amy said that she would bring her camera."], why: "Keep the name once, then use she (doer) and her (owner) so it does not sound repetitive." }
  ]
});

window.VG.push({
  id: "en-g-relative",
  lang: "en",
  kind: "grammar",
  group: "Joining ideas",
  title: "Who, which, whose, whom, that",
  lv: "B",
  intro: "Who, which, whose, whom and that are joining words that tell us more about a noun. They help you join two short sentences into one smooth sentence.",
  rules: [
    { h: "who for people", html: "Use <b>who</b> for people.<br>✓ The girl <b>who</b> sits beside me is Hui Min.<br>✗ The girl <b>which</b> sits beside me..." },
    { h: "which for animals and things", html: "Use <b>which</b> for animals and things.<br>✓ This is the cake <b>which</b> Mum baked.<br>✗ The durian <b>who</b> fell..." },
    { h: "whose for owning", html: "Use <b>whose</b> to show something belongs to someone (or something).<br>✓ I have a friend <b>whose</b> dog can do tricks. (the friend's dog)<br>✗ <b>who's</b> means 'who is'." },
    { h: "whom for the receiver", html: "Use <b>whom</b> for a person who <b>receives</b> the action, especially after words like <b>to, with, for</b>.<br>✓ The man <b>to whom</b> I gave the map...<br>✓ Mrs Lim, <b>whom</b> we met at the library, ..." },
    { h: "that", html: "<b>that</b> can replace who or which when there are <b>no commas</b>.<br>✓ The book <b>that</b> I borrowed is long.<br>✗ Sentosa, <b>that</b> is an island, ... (after a comma, use which or who)<br>✗ after a preposition: the man to <b>that</b> ..." },
    { h: "Don't repeat the noun", html: "The joining word already stands for the noun, so do not add it or him or her again.<br>✗ The book which I borrowed <b>it</b> was long.<br>✓ The book which I borrowed was long." }
  ],
  words: [],
  mistakes: [
    { wrong: "The boy which won the race is my cousin.", right: "The boy who won the race is my cousin.", why: "A boy is a person, so use who." },
    { wrong: "That is the girl who's bag is pink.", right: "That is the girl whose bag is pink.", why: "Who's means 'who is'. For owning, use whose." },
    { wrong: "This is the book which I borrowed it.", right: "This is the book which I borrowed.", why: "Which already stands for the book. Do not add 'it'." },
    { wrong: "My grandfather, that is eighty, still jogs.", right: "My grandfather, who is eighty, still jogs.", why: "After a comma, do not use that. Use who for people." },
    { wrong: "The coach to who we spoke was kind.", right: "The coach to whom we spoke was kind.", why: "After a word like to, use whom for people." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "The girl ___ sits beside me is called Hui Min.", o: ["who", "which", "whose"], a: 0, why: "The girl is a person, so use who." },
    { t: "mcq", lv: "A", q: "This is the cake ___ Mum baked for my birthday.", o: ["who", "which", "whose"], a: 1, why: "A cake is a thing, so use which." },
    { t: "mcq", lv: "A", q: "I have a friend ___ dog can do tricks.", o: ["who", "whose", "which"], a: 1, why: "The dog belongs to the friend, so use whose." },
    { t: "mcq", lv: "A", q: "I like stories ___ have happy endings.", o: ["who", "which", "whose"], a: 1, why: "Stories are things, so use which." },
    { t: "mcq", lv: "B", q: "The bus driver, ___ was very patient, waited for the old man.", o: ["who", "which", "whose", "that"], a: 0, why: "A bus driver is a person, and after a comma we cannot use that. So use who." },
    { t: "mcq", lv: "B", q: "Our school hall, ___ was built last year, has a big stage.", o: ["that", "which", "who", "whose"], a: 1, why: "A hall is a thing, and after a comma we use which, not that." },
    { t: "mcq", lv: "B", q: "The boy ___ bicycle was stolen made a police report.", o: ["who", "whom", "whose", "which"], a: 2, why: "The bicycle belonged to the boy, so use whose." },
    { t: "mcq", lv: "B", q: "The hawker ___ sells chicken rice opens at seven.", o: ["which", "who", "whom", "whose"], a: 1, why: "The hawker is a person doing the action (selling), so use who." },
    { t: "mcq", lv: "B", q: "The parrot ___ my uncle keeps can say 'hello'.", o: ["who", "whose", "which", "whom"], a: 2, why: "A parrot is an animal, so use which." },
    { t: "mcq", lv: "B", q: "Do you know the pupil ___ won the spelling bee?", o: ["who", "which", "whose", "whom"], a: 0, why: "The pupil is a person who did the winning, so use who." },
    { t: "mcq", lv: "B", q: "The MRT train, ___ was very crowded, arrived late.", o: ["who", "that", "which", "whose"], a: 2, why: "A train is a thing, and after a comma use which." },
    { t: "mcq", lv: "B", q: "I met a lady ___ son is in my CCA.", o: ["who", "whose", "whom", "which"], a: 1, why: "The son belongs to the lady, so use whose." },
    { t: "mcq", lv: "B", q: "Singapore is a country ___ has many cultures.", o: ["who", "whom", "which", "whose"], a: 2, why: "A country is a place, not a person, so use which." },
    { t: "mcq", lv: "B", q: "The kitten ___ we found near the void deck is now our pet.", o: ["who", "whom", "which", "whose"], a: 2, why: "A kitten is an animal, so use which." },
    { t: "mcq", lv: "C", q: "The man to ___ I gave the map was a tourist.", o: ["who", "whom", "which", "that"], a: 1, why: "After to, use whom for a person." },
    { t: "mcq", lv: "C", q: "Mrs Lim, ___ we met at the library, is my piano teacher.", o: ["whom", "whose", "which", "that"], a: 0, why: "We met her, so Mrs Lim is the receiver. After a comma, use whom (not that)." },
    { t: "mcq", lv: "C", q: "The friends with ___ I went camping were from Scouts.", o: ["who", "whom", "which", "whose"], a: 1, why: "After with, use whom for people." },
    { t: "mcq", lv: "C", q: "The tree, ___ leaves had turned yellow, was cut down.", o: ["which", "whose", "who", "that"], a: 1, why: "The leaves belong to the tree. Whose can show owning for things too." },
    { t: "mcq", lv: "C", q: "The pupils, most of ___ were tired, slept on the bus.", o: ["who", "whom", "which", "them"], a: 1, why: "After of, use whom for people. 'Them' would make two sentences joined by a comma." },
    { t: "fix", lv: "B", q: "The boy which won the race is my cousin.", err: "which", a: "who", why: "A boy is a person, so use who." },
    { t: "fix", lv: "B", q: "The durian who fell from the tree was huge.", err: "who", a: "which", why: "A durian is a thing, so use which." },
    { t: "fix", lv: "B", q: "That is the girl who's bag is pink.", err: "who's", a: "whose", why: "Who's means 'who is'. For owning, use whose." },
    { t: "fix", lv: "C", q: "My grandfather, that is eighty, still jogs every morning.", err: "that", a: "who", why: "After a comma, do not use that. Grandfather is a person, so use who." },
    { t: "fix", lv: "C", q: "This is the book which I borrowed it from the library.", err: "borrowed it", a: "borrowed", why: "Which already stands for the book, so drop the extra 'it'." },
    { t: "fix", lv: "C", q: "The coach to who we spoke was very kind.", err: "who", a: "whom", why: "After to, use whom for a person." },
    { t: "fill", lv: "A", q: "The man ___ fixed our aircon was friendly.", a: ["who", "that"], why: "The man is a person, so use who (or that, since there are no commas)." },
    { t: "fill", lv: "A", q: "This is the toy ___ I bought at the pasar malam.", a: ["which", "that"], why: "A toy is a thing, so use which (or that)." },
    { t: "fill", lv: "B", q: "Mei Ling is the girl ___ mother is a doctor.", a: ["whose"], why: "The mother belongs to Mei Ling, so use whose." },
    { t: "fill", lv: "B", q: "Sentosa, ___ is an island, has many beaches.", a: ["which"], why: "Sentosa is a place, and after a comma use which." },
    { t: "fill", lv: "B", q: "Mr Rahman, ___ teaches us Science, loves plants.", a: ["who"], why: "Mr Rahman is a person doing the teaching. After a comma, use who." },
    { t: "fill", lv: "C", q: "The man ___ the police were looking for was caught.", a: ["whom", "who", "that"], why: "The police were looking for him, so he is the receiver. Whom is the most careful choice." },
    { t: "trans", lv: "B", q: "Combine using 'who': I have a cousin. She lives in Tampines.", a: ["I have a cousin who lives in Tampines."], why: "Who replaces 'she', so do not keep 'she' in the new sentence." },
    { t: "trans", lv: "B", q: "Combine using 'whose': That is the boy. His kite got stuck in the tree.", a: ["That is the boy whose kite got stuck in the tree."], why: "Whose replaces 'his' to show the kite belongs to the boy." },
    { t: "trans", lv: "C", q: "Combine using 'which': The museum was very interesting. We visited it on Saturday.", a: ["The museum which we visited on Saturday was very interesting.", "The museum, which we visited on Saturday, was very interesting."], why: "Put the 'which' part right after 'museum', and drop 'it'." },
    { t: "trans", lv: "C", q: "Combine using 'whom': The lady was kind. I helped her across the road.", a: ["The lady whom I helped across the road was kind."], why: "Whom replaces 'her', the person who received the help. Place it right after 'lady'." }
  ]
});

window.VG.push({
  id: "en-g-quantifiers",
  lang: "en",
  kind: "grammar",
  group: "Nouns, articles and pronouns",
  title: "Each, every, all, both, either, neither",
  lv: "B",
  intro: "These words tell us how many people or things we mean. Some go with one thing and some with many, so they change the verb too.",
  rules: [
    { h: "each and every: one by one", html: "<b>each</b> and <b>every</b> take a <b>singular</b> noun and a <b>singular</b> verb.<br>✓ <b>Every pupil has</b> a name tag. ✓ <b>Each</b> child <b>gets</b> a sticker.<br>✗ Every pupil<b>s</b> have..." },
    { h: "each of the + plural noun", html: "After <b>each of</b>, the noun is plural but the verb stays singular.<br>✓ <b>Each of the boys has</b> a locker.<br>Note: say <b>each of</b>, never <b>every of</b>." },
    { h: "all: the whole group", html: "<b>all</b> takes a <b>plural</b> noun and verb.<br>✓ <b>All the pupils were</b> clapping. ✗ All pupil must..." },
    { h: "both: two together", html: "<b>both</b> is for <b>two</b> things together, with a plural noun and verb.<br>✓ <b>Both</b> my hands <b>are</b> dirty. ✓ <b>Both</b> Ahmad <b>and</b> Ben <b>are</b> in the choir." },
    { h: "either and neither: one of two", html: "<b>either</b> = one or the other. <b>neither</b> = not one and not the other.<br>Both take a <b>singular</b> verb.<br>✓ <b>Neither</b> of the answers <b>is</b> correct.<br>✓ You can take <b>either</b> bus." },
    { h: "Don't double the 'not'", html: "<b>neither</b> is already negative.<br>✗ I don't like <b>neither</b>. ✓ I don't like <b>either</b>. ✓ I like <b>neither</b>." },
    { h: "either…or, neither…nor", html: "The verb agrees with the person or thing <b>nearer</b> to it.<br>✓ Neither Siti nor her <b>brothers are</b> at home.<br>✓ Either the pupils or the <b>teacher waters</b> the plants." }
  ],
  words: [],
  mistakes: [
    { wrong: "Every pupils must bring a water bottle.", right: "Every pupil must bring a water bottle.", why: "Every is followed by one thing: pupil, not pupils." },
    { wrong: "Each of the girls have a locker.", right: "Each of the girls has a locker.", why: "Each means one at a time, so the verb is singular: has." },
    { wrong: "Neither of the answers are correct.", right: "Neither of the answers is correct.", why: "Neither means not one, so use a singular verb: is." },
    { wrong: "I don't like neither of these shirts.", right: "I don't like either of these shirts.", why: "Don't + neither makes a double negative. Use either after not." },
    { wrong: "Both of the book are on the shelf.", right: "Both of the books are on the shelf.", why: "Both means two, so the noun must be plural: books." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "___ child in the class has a name tag.", o: ["Every", "All", "Both"], a: 0, why: "Child is singular and has is singular, so use Every." },
    { t: "mcq", lv: "A", q: "I have dirt on ___ my hands.", o: ["every", "each", "both"], a: 2, why: "We have two hands, so use both for two together." },
    { t: "mcq", lv: "A", q: "___ the pupils clapped loudly.", o: ["Every", "All", "Each"], a: 1, why: "'The pupils' is plural, so use All. Every and each need one thing." },
    { t: "mcq", lv: "A", q: "___ my friends like ice cream.", o: ["All", "Every", "Each"], a: 0, why: "Friends is plural and like is plural, so use All." },
    { t: "mcq", lv: "B", q: "Each of the boys ___ a packet of milk.", o: ["get", "gets", "are getting", "have got"], a: 1, why: "Each means one at a time, so use a singular verb: gets." },
    { t: "mcq", lv: "B", q: "Every pupil ___ to wear a school uniform.", o: ["have", "are having", "has", "were having"], a: 2, why: "Every pupil is one pupil at a time, so use has." },
    { t: "mcq", lv: "B", q: "I have two pens. You can borrow ___ one; I don't mind which.", o: ["every", "either", "all", "both"], a: 1, why: "Either means one or the other of two, and 'one' is singular." },
    { t: "mcq", lv: "B", q: "Neither of the twins ___ spicy food.", o: ["like", "likes", "are liking", "have liked"], a: 1, why: "Neither means not one, so it takes a singular verb: likes." },
    { t: "mcq", lv: "B", q: "There are trees on ___ side of the road.", o: ["either", "every", "all", "both"], a: 0, why: "A road has two sides, and 'side' is singular. Either side means on each of the two sides." },
    { t: "mcq", lv: "B", q: "___ of my parents can drive, so we always take the MRT.", o: ["Either", "Neither", "Both", "Each"], a: 1, why: "They take the MRT because no parent can drive. Neither means not one and not the other." },
    { t: "mcq", lv: "B", q: "Both Ahmad and Ben ___ in the school choir.", o: ["is", "are", "was", "has"], a: 1, why: "Both … and means two people together, so use the plural verb are." },
    { t: "mcq", lv: "B", q: "___ of the four friends brought a different snack.", o: ["Each", "Every", "Both", "Either"], a: 0, why: "There are four friends, so not both or either. We say each of, never every of." },
    { t: "mcq", lv: "B", q: "I like ___ kind of fruit except durian.", o: ["all", "every", "both", "either"], a: 1, why: "'Kind' is singular and there are many kinds, so use every." },
    { t: "mcq", lv: "B", q: "We visit our grandparents ___ Sunday.", o: ["all", "every", "both", "each of"], a: 1, why: "Sunday is singular and it happens again and again, so use every." },
    { t: "mcq", lv: "B", q: "Both of the cups ___ broken.", o: ["is", "are", "was", "has"], a: 1, why: "Both means two, so the verb is plural: are." },
    { t: "mcq", lv: "C", q: "Neither Siti nor her brothers ___ at home.", o: ["is", "was", "are", "has"], a: 2, why: "With neither … nor, the verb agrees with the nearer noun. Brothers is plural, so use are." },
    { t: "mcq", lv: "C", q: "Either the teacher or the pupils ___ the plants every day.", o: ["waters", "water", "is watering", "has watered"], a: 1, why: "The verb agrees with the nearer noun, pupils (plural), so use water." },
    { t: "mcq", lv: "C", q: "___ of the two answers is correct, so try again.", o: ["Either", "Neither", "Both", "All"], a: 1, why: "You must try again because no answer is right. Neither means not one of the two." },
    { t: "mcq", lv: "C", q: "There are thirty of us. The teacher gave a sticker to ___ of us.", o: ["every", "each", "both", "either"], a: 1, why: "Thirty is more than two, so not both or either. We say each of, never every of." },
    { t: "fix", lv: "A", q: "Every pupils must bring a water bottle.", err: "pupils", a: "pupil", why: "Every is followed by one thing, so use pupil." },
    { t: "fix", lv: "B", q: "All pupil must line up at the canteen.", err: "pupil", a: "pupils", why: "All means the whole group, so the noun is plural: pupils." },
    { t: "fix", lv: "B", q: "Each of the girls have a locker.", err: "have", a: "has", why: "Each means one at a time, so use has." },
    { t: "fix", lv: "B", q: "Both of the book are on the shelf.", err: "book", a: "books", why: "Both means two, so use the plural books." },
    { t: "fix", lv: "B", q: "Neither of the answers are correct.", err: "are", a: "is", why: "Neither means not one, so it takes a singular verb: is." },
    { t: "fix", lv: "C", q: "I don't like neither of these shirts.", err: "neither", a: "either", why: "Don't is already negative. After not, use either." },
    { t: "fill", lv: "A", q: "I washed ___ my hands before lunch.", a: ["both"], why: "We have two hands, so use both." },
    { t: "fill", lv: "A", q: "___ the children in the playground were laughing.", a: ["All"], why: "Children is plural and were is plural, so use All." },
    { t: "fill", lv: "B", q: "We can take the bus or the MRT. ___ way is fine with me.", a: ["Either"], why: "Either means one or the other of two choices." },
    { t: "fill", lv: "B", q: "___ of the two shops was open, so we went home hungry.", a: ["Neither"], why: "They went home hungry because no shop was open. Neither means not one of the two." },
    { t: "fill", lv: "B", q: "The teacher checked ___ single pupil's homework carefully.", a: ["every"], why: "Every single means each one, with nobody missed out. We say every single, not each single." },
    { t: "fill", lv: "C", q: "You can sit on ___ side of me, the left or the right. (either / both)", a: ["either"], why: "Either means one or the other of two. Side is singular, so both (which needs sides) does not fit." },
    { t: "trans", lv: "B", q: "Combine using 'neither … nor': Ali does not like durian. Ben does not like durian.", a: ["Neither Ali nor Ben likes durian."], why: "Neither … nor already means 'not', so drop 'does not'. The nearer noun, Ben, is singular, so use likes." },
    { t: "trans", lv: "B", q: "Combine using 'both … and': Mei can swim. Lina can swim.", a: ["Both Mei and Lina can swim.", "Mei and Lina can both swim."], why: "Both … and joins two people who do the same thing." }
  ]
});

window.VG.push({
  id: "en-g-tags",
  lang: "en",
  kind: "grammar",
  group: "Questions and speech",
  title: "Question tags",
  lv: "B",
  intro: "A question tag is a short question at the end of a sentence, like 'isn't it?' or 'can you?'. We use it to check something or to ask someone to agree.",
  rules: [
    { h: "Flip it", html: "A <b>positive</b> sentence gets a <b>negative</b> tag. A <b>negative</b> sentence gets a <b>positive</b> tag.<br>✓ You are hungry, <b>aren't you</b>?<br>✓ Tom is not here, <b>is he</b>?" },
    { h: "Use the helping verb", html: "Copy the helping verb (is, are, was, can, will, have, should...).<br>✓ Mei <b>can</b> swim, <b>can't</b> she?<br>✓ You <b>have</b> finished, <b>haven't</b> you?" },
    { h: "No helping verb? Use do, does or did", html: "✓ You <b>like</b> chicken rice, <b>don't</b> you?<br>✓ He <b>plays</b> football, <b>doesn't</b> he?<br>✓ They <b>went</b> out, <b>didn't</b> they?" },
    { h: "Use a pronoun in the tag", html: "Change the name to a pronoun.<br>✓ <b>Ravi</b> likes cats, doesn't <b>he</b>?<br><b>this/that</b> → <b>it</b>; <b>there is</b> → <b>isn't there</b>; <b>everyone/nobody</b> → <b>they</b>." },
    { h: "Hidden negative words", html: "<b>never, hardly, nobody, nothing</b> make the sentence negative, so the tag is positive.<br>✓ He <b>never</b> eats vegetables, <b>does</b> he?<br>✓ <b>Nobody</b> called, <b>did</b> they?" },
    { h: "Special ones", html: "I am → <b>aren't I</b>? ✓ I am late, aren't I?<br>Let's → <b>shall we</b>? ✓ Let's go, shall we?<br>Orders → <b>will you</b>? ✓ Close the door, will you?" },
    { h: "Never 'isn't it' for everything", html: "✗ Ravi likes cats, <b>isn't it</b>?<br>✓ Ravi likes cats, <b>doesn't he</b>?<br>Match the tag to the verb and the person." }
  ],
  words: [],
  mistakes: [
    { wrong: "Ravi likes cats, isn't it?", right: "Ravi likes cats, doesn't he?", why: "Likes has no helping verb, so use does. Ravi is a boy, so use he." },
    { wrong: "It is raining, is it?", right: "It is raining, isn't it?", why: "A positive sentence needs a negative tag." },
    { wrong: "You went to school yesterday, don't you?", right: "You went to school yesterday, didn't you?", why: "Went is past tense, so the tag uses did." },
    { wrong: "I am your partner, amn't I?", right: "I am your partner, aren't I?", why: "We say aren't I. Amn't is not used." },
    { wrong: "He never eats vegetables, doesn't he?", right: "He never eats vegetables, does he?", why: "Never already makes it negative, so the tag is positive." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "You are hungry, ___?", o: ["are you", "aren't you", "isn't it"], a: 1, why: "Positive sentence (are) → negative tag: aren't you." },
    { t: "mcq", lv: "A", q: "Mei can swim, ___?", o: ["can she", "isn't she", "can't she"], a: 2, why: "Copy the helping verb can and flip it: can't she." },
    { t: "mcq", lv: "A", q: "Tom is not here, ___?", o: ["is he", "isn't he", "does he"], a: 0, why: "Negative sentence (is not) → positive tag: is he." },
    { t: "mcq", lv: "B", q: "Your brother plays football, ___?", o: ["doesn't he", "isn't he", "don't he", "didn't he"], a: 0, why: "Plays has no helping verb and it is now, for one person, so use doesn't he." },
    { t: "mcq", lv: "B", q: "They went to the zoo yesterday, ___?", o: ["don't they", "didn't they", "weren't they", "did they"], a: 1, why: "Went is past tense with no helping verb, so use didn't they." },
    { t: "mcq", lv: "B", q: "You have finished your homework, ___?", o: ["didn't you", "don't you", "haven't you", "have you"], a: 2, why: "Copy the helping verb have and flip it: haven't you." },
    { t: "mcq", lv: "B", q: "She won't be late, ___?", o: ["won't she", "will she", "isn't she", "does she"], a: 1, why: "Won't is negative, so the tag is positive: will she." },
    { t: "mcq", lv: "B", q: "We should recycle more, ___?", o: ["shouldn't we", "should we", "don't we", "aren't we"], a: 0, why: "Copy should and flip it: shouldn't we." },
    { t: "mcq", lv: "B", q: "There is a pool in your condo, ___?", o: ["isn't it", "is there", "isn't there", "doesn't it"], a: 2, why: "There is → isn't there. Keep 'there' in the tag." },
    { t: "mcq", lv: "B", q: "This is your pencil, ___?", o: ["isn't this", "isn't it", "is it", "doesn't it"], a: 1, why: "This becomes it in a tag, and positive → negative: isn't it." },
    { t: "mcq", lv: "B", q: "The children were noisy, ___?", o: ["were they", "weren't they", "didn't they", "aren't they"], a: 1, why: "Copy were, flip it, and change 'the children' to they: weren't they." },
    { t: "mcq", lv: "B", q: "Grandpa can't hear well, ___?", o: ["can he", "can't he", "does he", "is he"], a: 0, why: "Can't is negative, so the tag is positive: can he." },
    { t: "mcq", lv: "B", q: "You like chicken rice, ___?", o: ["do you", "aren't you", "don't you", "didn't you"], a: 2, why: "Like has no helping verb and it is now, so use don't you." },
    { t: "mcq", lv: "C", q: "I am in Group A, ___?", o: ["am not I", "aren't I", "isn't I", "am I"], a: 1, why: "The special tag for I am is aren't I." },
    { t: "mcq", lv: "C", q: "Let's go to the hawker centre, ___?", o: ["shall we", "will we", "don't we", "let's we"], a: 0, why: "Sentences starting with Let's take the tag shall we." },
    { t: "mcq", lv: "C", q: "Close the window, ___?", o: ["do you", "will you", "don't you", "are you"], a: 1, why: "An order or request takes the tag will you." },
    { t: "mcq", lv: "C", q: "Nobody saw the accident, ___?", o: ["did they", "didn't they", "did he", "didn't he"], a: 0, why: "Nobody is negative, so the tag is positive. Nobody becomes they: did they." },
    { t: "mcq", lv: "C", q: "He never eats vegetables, ___?", o: ["doesn't he", "does he", "didn't he", "is he"], a: 1, why: "Never makes the sentence negative, so the tag is positive: does he." },
    { t: "mcq", lv: "C", q: "Everyone enjoyed the concert, ___?", o: ["didn't they", "didn't he", "did they", "wasn't it"], a: 0, why: "Everyone becomes they in a tag. Positive past sentence → didn't they." },
    { t: "mcq", lv: "C", q: "She hardly ever cries, ___?", o: ["doesn't she", "does she", "isn't she", "did she"], a: 1, why: "Hardly makes the sentence negative, so the tag is positive: does she." },
    { t: "fix", lv: "A", q: "It is raining, is it?", err: "is it?", a: "isn't it?", why: "The sentence is positive, so the tag must be negative: isn't it." },
    { t: "fix", lv: "B", q: "Ravi likes cats, isn't it?", err: "isn't it", a: "doesn't he", why: "Likes has no helping verb, so use does. Ravi is he, not it." },
    { t: "fix", lv: "B", q: "You went to school yesterday, don't you?", err: "don't you", a: "didn't you", why: "Went is past tense, so the tag uses did: didn't you." },
    { t: "fix", lv: "B", q: "They aren't coming, aren't they?", err: "aren't they", a: "are they", why: "The sentence is negative, so the tag must be positive: are they." },
    { t: "fix", lv: "C", q: "I am your partner, amn't I?", err: "amn't I", a: "aren't I", why: "The tag for I am is aren't I." },
    { t: "fix", lv: "C", q: "Let's play chess, will we?", err: "will we", a: "shall we", why: "Let's always takes shall we." },
    { t: "fill", lv: "A", q: "Mum is at work, ___ she?", a: ["isn't"], why: "Positive sentence with is → negative tag: isn't she." },
    { t: "fill", lv: "A", q: "You can't whistle, ___ you?", a: ["can"], why: "Can't is negative, so the tag is positive: can you." },
    { t: "fill", lv: "B", q: "Kai Xin lives in Bedok, ___ she?", a: ["doesn't"], why: "Lives has no helping verb and is for one person now, so use doesn't." },
    { t: "fill", lv: "B", q: "We saw a rainbow this morning, ___ we?", a: ["didn't"], why: "Saw is past tense, so use didn't." },
    { t: "fill", lv: "B", q: "The cats have been fed, ___ they?", a: ["haven't"], why: "Copy the helping verb have and flip it: haven't." },
    { t: "fill", lv: "C", q: "Nobody wants to be left out, ___ they?", a: ["do"], why: "Nobody is negative, so the tag is positive. Nobody becomes they, so use do." },
    { t: "trans", lv: "B", q: "Add a question tag: You will help me.", a: ["You will help me, won't you?", "You'll help me, won't you?"], why: "Copy will and flip it to won't. Put a comma before the tag and a question mark at the end." }
  ]
});

window.VG.push({
  id: "en-g-prepositions",
  lang: "en",
  kind: "grammar",
  group: "Prepositions",
  title: "Prepositions of time and place (in, on, at, by, since, for, during…)",
  lv: "A",
  intro: "Prepositions are small words like in, on and at that tell us when or where something happens. Choosing the right one makes your sentences clear.",
  rules: [
    { h: "Time: at, on, in", html: "<b>at</b> + clock time and night: <b>at</b> 7.30 a.m., <b>at</b> night<br><b>on</b> + days and dates: <b>on</b> Monday, <b>on</b> 25 December<br><b>in</b> + months, years, seasons, parts of the day: <b>in</b> May, <b>in</b> 2019, <b>in</b> winter, <b>in</b> the morning" },
    { h: "Place: at, on, in", html: "<b>at</b> a point or spot: <b>at</b> the bus stop<br><b>on</b> a surface or a floor: <b>on</b> the table, <b>on</b> the tenth floor<br><b>in</b> inside something, or a city or country: <b>in</b> the drawer, <b>in</b> Australia" },
    { h: "since and for", html: "<b>since</b> + the starting point: <b>since</b> 2019, <b>since</b> Monday<br><b>for</b> + how long: <b>for</b> three days, <b>for</b> two hours<br>✗ since three years ✓ <b>for</b> three years" },
    { h: "during", html: "<b>during</b> + an event or a period: something happens inside that time.<br>✓ Nobody talked <b>during</b> the test.<br>✗ <b>during</b> two hours (use for)" },
    { h: "by and until", html: "<b>by</b> = not later than: Hand it in <b>by</b> Friday.<br><b>until</b> = all the time up to then: We waited <b>until</b> six.<br><b>by</b> can also mean beside: a house <b>by</b> the river." }
  ],
  words: [],
  mistakes: [
    { wrong: "I have known Jia Hui since three years.", right: "I have known Jia Hui for three years.", why: "Three years is how long, so use for. Since needs a starting point." },
    { wrong: "Mum has worked there for 2015.", right: "Mum has worked there since 2015.", why: "2015 is the starting point, so use since." },
    { wrong: "The shop is closed in Sundays.", right: "The shop is closed on Sundays.", why: "Days take on." },
    { wrong: "I was born on 2017.", right: "I was born in 2017.", why: "Years take in." },
    { wrong: "You must finish the book until Monday.", right: "You must finish the book by Monday.", why: "By means not later than. Until means all the time up to then." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "My birthday is ___ May.", o: ["on", "in", "at"], a: 1, why: "Months take in: in May." },
    { t: "mcq", lv: "A", q: "School starts ___ 7.30 a.m.", o: ["in", "on", "at"], a: 2, why: "Clock times take at." },
    { t: "mcq", lv: "A", q: "We have PE ___ Tuesday.", o: ["on", "in", "at"], a: 0, why: "Days of the week take on." },
    { t: "mcq", lv: "A", q: "The cat is sleeping ___ the sofa.", o: ["on", "at", "into"], a: 0, why: "The cat is lying on top of the sofa's surface, so use on." },
    { t: "mcq", lv: "A", q: "Dad keeps the keys ___ the drawer.", o: ["on", "in", "at"], a: 1, why: "The keys are inside the drawer, so use in." },
    { t: "mcq", lv: "A", q: "I will meet you ___ the bus stop.", o: ["at", "in", "on"], a: 0, why: "A bus stop is a meeting point, so use at." },
    { t: "mcq", lv: "A", q: "Owls hunt ___ night.", o: ["in", "on", "at"], a: 2, why: "We say at night (but in the morning)." },
    { t: "mcq", lv: "A", q: "The fish swim ___ the pond.", o: ["in", "on", "at"], a: 0, why: "The fish are inside the water, so use in." },
    { t: "mcq", lv: "B", q: "We have lived in this HDB flat ___ 2019.", o: ["for", "since", "during", "in"], a: 1, why: "2019 is the starting point and we still live there, so use since." },
    { t: "mcq", lv: "B", q: "Grandma has been in hospital ___ three days.", o: ["since", "for", "during", "by"], a: 1, why: "Three days is how long, so use for." },
    { t: "mcq", lv: "B", q: "Please hand in your forms ___ Friday.", o: ["by", "since", "during", "at"], a: 0, why: "By Friday means not later than Friday." },
    { t: "mcq", lv: "B", q: "Nobody talked ___ the spelling test.", o: ["for", "since", "during", "on"], a: 2, why: "The test is an event, and the silence was inside that time, so use during." },
    { t: "mcq", lv: "B", q: "There are fireworks ___ New Year's Eve.", o: ["in", "on", "at", "by"], a: 1, why: "New Year's Eve is a special day, and days take on." },
    { t: "mcq", lv: "B", q: "We go to the beach ___ the afternoon.", o: ["at", "on", "in", "by"], a: 2, why: "Parts of the day take in: in the afternoon." },
    { t: "mcq", lv: "B", q: "My cousin lives ___ Australia.", o: ["at", "on", "in", "by"], a: 2, why: "Countries take in." },
    { t: "mcq", lv: "B", q: "Wait for me ___ the entrance of the MRT station.", o: ["at", "in", "on", "during"], a: 0, why: "The entrance is a meeting point, so use at." },
    { t: "mcq", lv: "B", q: "Our flat is ___ the tenth floor.", o: ["in", "at", "on", "by"], a: 2, why: "Floors of a building take on." },
    { t: "mcq", lv: "B", q: "The concert is ___ 15 August.", o: ["in", "on", "at", "during"], a: 1, why: "A date is a day, so use on." },
    { t: "mcq", lv: "C", q: "We waited ___ six o'clock, but nobody came.", o: ["by", "until", "since", "during"], a: 1, why: "We kept waiting all the time up to six, so use until." },
    { t: "mcq", lv: "C", q: "Our house is ___ the river; we can see boats from the window.", o: ["by", "during", "since", "until"], a: 0, why: "By can mean beside or next to." },
    { t: "mcq", lv: "C", q: "I fell asleep ___ the movie.", o: ["for", "during", "since", "by"], a: 1, why: "Falling asleep happened inside the time of the movie, so use during." },
    { t: "fix", lv: "A", q: "I was born on 2017.", err: "on", a: "in", why: "Years take in: in 2017." },
    { t: "fix", lv: "A", q: "We have lunch in 12 noon.", err: "in", a: "at", why: "Clock times take at: at 12 noon." },
    { t: "fix", lv: "B", q: "I have known Jia Hui since three years.", err: "since", a: "for", why: "Three years is how long, so use for." },
    { t: "fix", lv: "B", q: "Mum has worked there for 2015.", err: "for", a: "since", why: "2015 is the starting point, so use since." },
    { t: "fix", lv: "B", q: "The shop is closed in Sundays.", err: "in", a: "on", why: "Days take on: on Sundays." },
    { t: "fix", lv: "B", q: "Ben fell asleep for the long speech.", err: "for", a: "during", why: "The speech is an event, and Ben fell asleep inside that time, so use during." },
    { t: "fix", lv: "C", q: "You must finish the book until Monday.", err: "until", a: "by", why: "By means not later than. You must be done by Monday." },
    { t: "fill", lv: "A", q: "Christmas is ___ 25 December.", a: ["on"], why: "Dates take on." },
    { t: "fill", lv: "A", q: "I brush my teeth ___ night before bed. (in / on / at)", a: ["at"], why: "We say at night." },
    { t: "fill", lv: "A", q: "The pencils are ___ the box, so please close the lid.", a: ["in", "inside"], why: "The pencils are inside the box (that is why we close the lid), so use in." },
    { t: "fill", lv: "B", q: "Wei Ming has been learning the piano ___ he was six.", a: ["since"], why: "'He was six' is the starting point, so use since." },
    { t: "fill", lv: "B", q: "We stayed in Malacca ___ four days.", a: ["for"], why: "Four days is how long, so use for." },
    { t: "fill", lv: "B", q: "Snow falls ___ winter in Japan.", a: ["in", "during"], why: "Seasons take in (during also works for a period of time)." },
    { t: "trans", lv: "B", q: "Rewrite as one sentence using 'since': I started living in Punggol in 2020. I still live there.", a: ["I have lived in Punggol since 2020.", "I have been living in Punggol since 2020."], why: "Since + the starting point, with 'have lived' because it is still true now." }
  ]
});
