window.VG = window.VG || [];

window.VG.push({
  id: "en-g-conjunctions",
  lang: "en",
  kind: "grammar",
  group: "Joining ideas",
  title: "Joining words: and, but, or, so, because, although, unless, while, when, before, after",
  lv: "A",
  intro: "Joining words (conjunctions) link two ideas into one longer sentence. Picking the right one shows HOW the ideas are linked: adding, contrasting, giving a reason or showing time.",
  rules: [
    { h: "and, but, or", html: "<b>and</b> adds: I like rice <b>and</b> noodles.<br><b>but</b> shows a surprise or contrast: I like rice, <b>but</b> I do not like porridge.<br><b>or</b> gives a choice: Do you want rice <b>or</b> noodles?" },
    { h: "so and because", html: "<b>so</b> tells the RESULT: It rained, <b>so</b> we stayed in.<br><b>because</b> tells the REASON: We stayed in <b>because</b> it rained.<br>Use only one of them. ✗ <i>Because it rained, so we stayed in.</i>" },
    { h: "although = even though", html: "<b>although</b> shows contrast, like but. Never use both together.<br>✓ <b>Although</b> it was late, we kept playing.<br>✗ <i>Although it was late, but we kept playing.</i>" },
    { h: "unless = if not", html: "You will be late <b>unless</b> you hurry. (= if you do not hurry)<br>Do not add another not: ✗ <i>unless you don't hurry</i>." },
    { h: "Time words: when, while, before, after", html: "<b>when</b> = at the time something happens: Call me <b>when</b> you reach.<br><b>while</b> = during the same time: Dad sang <b>while</b> he cooked.<br><b>before</b> = earlier: Wash your hands <b>before</b> you eat.<br><b>after</b> = later: We played <b>after</b> we ate." },
    { h: "A because-part cannot stand alone", html: "✗ <i>Because I was hungry.</i> (only half a sentence)<br>✓ I ate a bun <b>because</b> I was hungry." },
    { h: "Commas", html: "When the joining word starts the sentence, put a comma after the first part:<br><b>Although</b> it was raining<b>,</b> we went out." }
  ],
  words: [],
  mistakes: [
    { wrong: "Although it rained, but we still played.", right: "Although it rained, we still played.", why: "Although already shows contrast. Do not add but." },
    { wrong: "Because I was tired, so I slept early.", right: "Because I was tired, I slept early.", why: "Use because OR so, not both." },
    { wrong: "Because it was hot.", right: "We stayed indoors because it was hot.", why: "A because-part needs a main idea to hang on." },
    { wrong: "You will fail unless you don't study.", right: "You will fail unless you study.", why: "Unless already means 'if not'." },
    { wrong: "Ali was hungry, but he ate two buns.", right: "Ali was hungry, so he ate two buns.", why: "Eating is the result of being hungry, so use so." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "I like apples ___ bananas.", o: ["and","but","so"], a: 0, why: "You like both, so you are adding one more thing: and." },
    { t: "mcq", lv: "A", q: "Mei Ling was tired, ___ she went to bed early.", o: ["so","but","or"], a: 0, why: "Going to bed early is the result of being tired: so." },
    { t: "mcq", lv: "A", q: "Do you want rice ___ noodles?", o: ["or","so","because"], a: 0, why: "It is a choice between two things: or." },
    { t: "mcq", lv: "A", q: "Ravi wanted to play outside, ___ it was raining.", o: ["but","so","or"], a: 0, why: "The rain spoils his plan. That is a contrast: but." },
    { t: "mcq", lv: "A", q: "We stayed at home ___ it was raining.", o: ["because","but","or"], a: 0, why: "The rain is the reason we stayed home: because." },
    { t: "mcq", lv: "A", q: "Wash your hands ___ you eat.", o: ["before","but","or"], a: 0, why: "Washing comes first, then eating: before." },
    { t: "mcq", lv: "A", q: "Siti brushed her teeth ___ she had eaten breakfast.", o: ["after","or","so"], a: 0, why: "Breakfast came first, then brushing: after." },
    { t: "mcq", lv: "A", q: "Would you like to sit at the front ___ at the back?", o: ["or","and","because"], a: 0, why: "You can only pick one seat. A choice needs or." },
    { t: "mcq", lv: "B", q: "___ he was feeling ill, Arjun still went to school.", o: ["Although","Because","Unless","So"], a: 0, why: "Feeling ill but still going is a surprise. Although shows that contrast." },
    { t: "mcq", lv: "B", q: "You will miss the MRT ___ you hurry.", o: ["unless","because","and","after"], a: 0, why: "Unless = if not. You will miss it if you do not hurry." },
    { t: "mcq", lv: "B", q: "Dad hummed a song ___ he was washing the dishes.", o: ["while","unless","although","or"], a: 0, why: "Both things happened at the same time: while." },
    { t: "mcq", lv: "B", q: "Call me ___ you reach the hawker centre.", o: ["when","although","unless","but"], a: 0, why: "Call at the time you arrive: when." },
    { t: "mcq", lv: "B", q: "Jun Wei did not study, ___ he failed the spelling test.", o: ["so","because","although","unless"], a: 0, why: "Failing is the result of not studying: so." },
    { t: "mcq", lv: "B", q: "Priya practised the piano every day ___ she wanted to do well in her exam.", o: ["because","although","unless","or"], a: 0, why: "Wanting to do well is her reason: because." },
    { t: "mcq", lv: "B", q: "You cannot go to the playground ___ you finish your homework.", o: ["unless","because","although","while"], a: 0, why: "Unless = if you do not. No homework done, no playground." },
    { t: "mcq", lv: "B", q: "The shop was closed, ___ we bought our snacks at the minimart instead.", o: ["so","because","although","unless"], a: 0, why: "Going to the minimart is the result of the shop being closed: so." },
    { t: "mcq", lv: "B", q: "Kumar played chess ___ he had finished his homework.", o: ["after","unless","although","or"], a: 0, why: "Homework came first, chess came later: after." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["Because I was hungry.","I ate a sandwich because I was hungry.","I was hungry because so I ate.","Because hungry, I ate a sandwich."], a: 1, why: "A because-part must join onto a full idea (I ate a sandwich). Never use because and so together." },
    { t: "mcq", lv: "C", q: "___ the queue at the chicken rice stall was long, we decided to wait.", o: ["Although","Because","Unless","So"], a: 0, why: "A long queue usually makes people leave, but we stayed. That surprise needs although." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["Although it was late, but we kept playing.","Although it was late, we kept playing.","Although it was late, so we kept playing.","It was late although, we kept playing."], a: 1, why: "Although does the contrast job alone. Do not add but or so." },
    { t: "mcq", lv: "C", q: "Hui Min likes swimming, ___ her brother prefers cycling.", o: ["while","unless","because","so"], a: 0, why: "While can show a contrast between two people: she likes one thing, he likes another." },
    { t: "fix", lv: "A", q: "Ali was hungry, but he ate two plates of nasi lemak.", err: "but", a: "so", why: "Eating is the result of being hungry, so use so." },
    { t: "fix", lv: "A", q: "We took an umbrella so it was raining.", err: "so", a: "because", why: "The rain is the reason for the umbrella. A reason needs because." },
    { t: "fix", lv: "A", q: "Is your birthday in May and in June?", err: "and", a: "or", why: "Your birthday can only be in one month. A choice needs or." },
    { t: "fix", lv: "B", q: "Put on your shoes after you go out.", err: "after", a: "before", why: "Shoes go on first, then you go out: before." },
    { t: "fix", lv: "B", q: "Mum will be angry because you tidy your room.", err: "because", a: "unless", why: "Mum is angry if you do NOT tidy. If not = unless." },
    { t: "fix", lv: "B", q: "Because the test was hard, Nurul got full marks.", err: "Because", a: "Although", why: "Getting full marks on a hard test is a surprise. Use although for contrast." },
    { t: "fill", lv: "A", q: "I wanted to buy the toy, ___ I did not have enough money. (contrast)", a: ["but","yet"], why: "Not having money spoils the plan. Contrast: but." },
    { t: "fill", lv: "A", q: "We can play badminton ___ table tennis. (choice)", a: ["or"], why: "Pick one of two games: or." },
    { t: "fill", lv: "A", q: "The floor was wet, ___ Ben slipped. (result)", a: ["so"], why: "Slipping is what happened because of the wet floor: so." },
    { t: "fill", lv: "A", q: "Lin cried ___ she had lost her water bottle. (reason)", a: ["because","as","since"], why: "Losing the bottle is the reason she cried: because (as or since also give a reason)." },
    { t: "fill", lv: "B", q: "I will not go to the party ___ you come with me. (if not)", a: ["unless"], why: "Unless means 'if not': I will not go if you do not come." },
    { t: "fill", lv: "B", q: "Turn off the lights ___ you leave the room. (time)", a: ["before","when"], why: "Switch off first, then leave (before), or at the moment you leave (when)." },
    { t: "trans", lv: "B", q: "Join using 'because': Sarah stayed at home. She had a fever.", a: ["Sarah stayed at home because she had a fever.","Because she had a fever, Sarah stayed at home."], why: "Because goes in front of the reason (she had a fever)." },
    { t: "trans", lv: "B", q: "Join using 'before': Jia Hui finished her homework. Then she watched TV.", a: ["Jia Hui finished her homework before she watched TV.","Before she watched TV, Jia Hui finished her homework.","Jia Hui finished her homework before watching TV."], why: "Before goes in front of the later action. Drop 'then' because before already shows the order." },
    { t: "trans", lv: "C", q: "Join using 'although': The durian smelt strong. Wei Jie loved it.", a: ["Although the durian smelt strong, Wei Jie loved it.","Wei Jie loved the durian although it smelt strong."], why: "Although shows the surprise. Do not add but. Put a comma after the first part if although starts the sentence." },
    { t: "trans", lv: "C", q: "Join using 'unless': You will be late. You leave now.", a: ["You will be late unless you leave now.","Unless you leave now, you will be late."], why: "Think: you will be late if you do NOT leave now. If not = unless." },
    { t: "trans", lv: "C", q: "Join using 'while': Daniel was reading. The lights went out.", a: ["The lights went out while Daniel was reading.","While Daniel was reading, the lights went out."], why: "While shows the lights went out during the reading time." }
  ]
});

window.VG.push({
  id: "en-g-adjectives",
  lang: "en",
  kind: "grammar",
  group: "Describing words",
  title: "Adjectives: comparing (bigger, biggest, more/most, good/better/best) and order",
  lv: "A",
  intro: "Adjectives describe nouns. When we compare things we change the adjective (big, bigger, biggest), and when we use a few adjectives together they go in a set order.",
  rules: [
    { h: "Two things: -er + than", html: "Compare TWO things with <b>-er</b> and <b>than</b>.<br>A bus is <b>longer than</b> a car." },
    { h: "Three or more: the -est", html: "Pick the top one of a group with <b>the -est</b>.<br>Hafiz is <b>the tallest</b> boy in the class." },
    { h: "Spelling changes", html: "Short word, one vowel + one consonant: double it. big → bi<b>gg</b>er → bi<b>gg</b>est, hot → ho<b>tt</b>er.<br>Ends in y: change y to i. happy → happ<b>ier</b> → happ<b>iest</b>.<br>Ends in e: just add r / st. nice → nicer → nicest." },
    { h: "Long words: more / most", html: "Long adjectives use <b>more</b> and <b>most</b>.<br>difficult → <b>more</b> difficult → <b>the most</b> difficult.<br>Never use both: ✗ <i>more bigger</i>, ✗ <i>most cheapest</i>." },
    { h: "Special words", html: "good → <b>better</b> → <b>best</b><br>bad → <b>worse</b> → <b>worst</b><br>many / much → <b>more</b> → <b>most</b><br>little → <b>less</b> → <b>least</b>" },
    { h: "Order of adjectives", html: "Number → opinion → size → age → shape → colour → where from → material → noun.<br>✓ two <b>lovely big old round red Chinese wooden</b> boxes (we rarely use so many!)<br>✓ a <b>big blue</b> umbrella ✗ <i>a blue big umbrella</i>" }
  ],
  words: [],
  mistakes: [
    { wrong: "My sister is more taller than me.", right: "My sister is taller than me.", why: "Taller already compares. Do not add more." },
    { wrong: "This is the most cheapest shop.", right: "This is the cheapest shop.", why: "Cheapest already means 'top one'. Do not add most." },
    { wrong: "Your answer is gooder than mine.", right: "Your answer is better than mine.", why: "Good is special: good, better, best." },
    { wrong: "Today is hoter than yesterday.", right: "Today is hotter than yesterday.", why: "Hot ends in vowel + consonant, so double the t." },
    { wrong: "She has a blue big umbrella.", right: "She has a big blue umbrella.", why: "Size comes before colour." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "An elephant is ___ than a dog.", o: ["bigger","biggest","more big"], a: 0, why: "Two animals → -er + than. Big doubles the g: bigger." },
    { t: "mcq", lv: "A", q: "Mount Everest is the ___ mountain in the world.", o: ["highest","higher","most high"], a: 0, why: "It is the top one of ALL mountains → the -est: highest." },
    { t: "mcq", lv: "A", q: "My bag is ___ than yours.", o: ["heavier","heavyer","more heavy"], a: 0, why: "Heavy ends in y → change y to i and add -er: heavier." },
    { t: "mcq", lv: "A", q: "That was the ___ joke I have ever heard!", o: ["funniest","funnyest","funnier"], a: 0, why: "The best of ALL jokes → the -est. Funny: y becomes i, then -est." },
    { t: "mcq", lv: "A", q: "Lina's drawing is good, but Kai's drawing is ___.", o: ["better","gooder","best"], a: 0, why: "Comparing two drawings: good → better. 'Gooder' is not a word." },
    { t: "mcq", lv: "A", q: "This is the ___ storm we have had this year.", o: ["worst","baddest","worse"], a: 0, why: "The top one of all the storms → bad, worse, worst." },
    { t: "mcq", lv: "A", q: "A kitten is ___ than a cat.", o: ["smaller","smallest","more small"], a: 0, why: "Two animals → -er + than: smaller." },
    { t: "mcq", lv: "B", q: "The MRT is ___ than the bus.", o: ["faster","fastest","more fast","fast"], a: 0, why: "Two things compared with than → -er: faster." },
    { t: "mcq", lv: "B", q: "This puzzle is ___ than the last one.", o: ["more difficult","difficulter","most difficult","more difficulter"], a: 0, why: "Difficult is a long word, so use more. Never add -er as well." },
    { t: "mcq", lv: "B", q: "Of all the stalls in the hawker centre, this one sells the ___ chicken rice.", o: ["most delicious","deliciousest","more delicious","most deliciousest"], a: 0, why: "Top one of all the stalls, long word → the most delicious." },
    { t: "mcq", lv: "B", q: "My room is ___ than my sister's.", o: ["more bigger","biggest","bigger","most biggest"], a: 2, why: "Two rooms → bigger. 'More' is not needed because -er already compares." },
    { t: "mcq", lv: "B", q: "Of the three sisters, Amy is the ___.", o: ["tallest","taller","most tall","tall"], a: 0, why: "Three or more → the -est: tallest." },
    { t: "mcq", lv: "B", q: "Which of the two shirts is ___?", o: ["cheaper","cheapest","most cheap","more cheaper"], a: 0, why: "Only TWO shirts → -er: cheaper." },
    { t: "mcq", lv: "B", q: "I have ___ marbles than Tom.", o: ["more","most","many","much"], a: 0, why: "Comparing two people with than → many becomes more." },
    { t: "mcq", lv: "B", q: "Siti spent the ___ money of all of us on snacks.", o: ["least","less","little","littlest"], a: 0, why: "Smallest amount of ALL of us → little, less, least." },
    { t: "mcq", lv: "B", q: "Jamal is ___ at chess than his brother.", o: ["worse","worst","badder","more bad"], a: 0, why: "Two people with than → bad becomes worse." },
    { t: "mcq", lv: "B", q: "Which is in the right order?", o: ["a small round red ball","a red round small ball","a round small red ball","a small red round ball"], a: 0, why: "Size → shape → colour: small, round, red." },
    { t: "mcq", lv: "B", q: "Which is in the right order?", o: ["a lovely old wooden box","a wooden old lovely box","an old lovely wooden box","a lovely wooden old box"], a: 0, why: "Opinion → age → material: lovely, old, wooden." },
    { t: "mcq", lv: "C", q: "Which is in the right order?", o: ["a beautiful long silk dress","a silk long beautiful dress","a long beautiful silk dress","a beautiful silk long dress"], a: 0, why: "Opinion → size → material: beautiful, long, silk." },
    { t: "mcq", lv: "C", q: "Which is in the right order?", o: ["two big black dogs","big two black dogs","two black big dogs","black two big dogs"], a: 0, why: "Number first, then size, then colour." },
    { t: "mcq", lv: "C", q: "Which is in the right order?", o: ["a new blue plastic bottle","a plastic new blue bottle","a blue new plastic bottle","a new plastic blue bottle"], a: 0, why: "Age → colour → material: new, blue, plastic." },
    { t: "mcq", lv: "C", q: "The second test was ___ than the first, so more pupils failed it.", o: ["harder","hardest","more hard","easier"], a: 0, why: "More pupils failed, so it was more difficult. Two tests → harder." },
    { t: "fix", lv: "A", q: "Today is hoter than yesterday.", err: "hoter", a: "hotter", why: "Hot has one vowel + one consonant, so double the t: hotter." },
    { t: "fix", lv: "A", q: "Your answer is gooder than mine.", err: "gooder", a: "better", why: "Good is special: good, better, best." },
    { t: "fix", lv: "B", q: "My sister is more taller than me.", err: "more taller", a: "taller", why: "Taller already compares. Do not add more." },
    { t: "fix", lv: "B", q: "This is the most cheapest shop in the mall.", err: "most cheapest", a: "cheapest", why: "Cheapest already means the top one. Do not add most." },
    { t: "fix", lv: "B", q: "Ahmad is the taller boy in our class.", err: "taller", a: "tallest", why: "A whole class is more than two people → the -est: tallest." },
    { t: "fix", lv: "B", q: "She has a blue big umbrella.", err: "blue big", a: "big blue", why: "Size comes before colour: big blue." },
    { t: "fix", lv: "B", q: "This is the baddest cough I have ever had.", err: "baddest", a: "worst", why: "Bad is special: bad, worse, worst." },
    { t: "fill", lv: "A", q: "A bus is ___ (long) than a car.", a: ["longer"], why: "Two things + than → add -er: longer." },
    { t: "fill", lv: "A", q: "Ken is the ___ (thin) boy in the team.", a: ["thinnest"], why: "Top of a group → -est. Thin doubles the n: thinnest." },
    { t: "fill", lv: "A", q: "This is the ___ (easy) question on the page.", a: ["easiest"], why: "Easy ends in y → change y to i, then add -est." },
    { t: "fill", lv: "B", q: "My grandmother is the ___ (old) person in our family.", a: ["oldest","eldest"], why: "Top of the whole family → the -est: oldest (or eldest for family members)." },
    { t: "fill", lv: "B", q: "The library is ___ (quiet) than the canteen.", a: ["quieter"], why: "Two places + than → -er: quieter." },
    { t: "fill", lv: "B", q: "This film is ___ (exciting) than the last one.", a: ["more exciting"], why: "Exciting is a long word, so use more: more exciting." },
    { t: "fill", lv: "B", q: "Which of the two bags is ___ (good)?", a: ["better"], why: "Two bags → good becomes better." },
    { t: "trans", lv: "B", q: "Put the adjectives in the right order: a (cotton, white, soft) towel", a: ["a soft white cotton towel"], why: "Opinion/feel → colour → material: soft, white, cotton." },
    { t: "trans", lv: "C", q: "Rewrite using 'than': The bus is not as fast as the MRT.", a: ["The MRT is faster than the bus.","The bus is slower than the MRT."], why: "Not as fast as = slower than. Or flip it round: the MRT is faster." },
    { t: "trans", lv: "C", q: "Rewrite using the -est form: No other pupil in the class is as tall as Hafiz.", a: ["Hafiz is the tallest pupil in the class.","Hafiz is the tallest in the class."], why: "If nobody is as tall as Hafiz, he is the top one: the tallest." }
  ]
});

window.VG.push({
  id: "en-g-adverbs",
  lang: "en",
  kind: "grammar",
  group: "Describing words",
  title: "Adverbs, and too / enough / very",
  lv: "B",
  intro: "Adverbs tell us more about a verb: how, when, where or how often something happens. Too, enough and very change how strong a describing word is.",
  rules: [
    { h: "What adverbs tell us", html: "<b>How</b>: She sang <b>softly</b>.<br><b>When</b>: We will go <b>tomorrow</b>.<br><b>Where</b>: The children played <b>outside</b>.<br><b>How often</b>: I <b>usually</b> take the bus." },
    { h: "Making -ly adverbs", html: "Most: add -ly. quick → quick<b>ly</b>, careful → careful<b>ly</b>.<br>Ends in y: y → i. happy → happ<b>ily</b>, easy → eas<b>ily</b>.<br>Ends in -le: drop e, add y. gentle → gent<b>ly</b>." },
    { h: "Adjective or adverb?", html: "Adjective describes a noun: He is a <b>quick</b> runner.<br>Adverb describes a verb: He runs <b>quickly</b>.<br>Special: good → <b>well</b>. fast → <b>fast</b>, hard → <b>hard</b>.<br>✗ <i>She sings good.</i> ✓ She sings <b>well</b>." },
    { h: "How-often words: where they go", html: "Before the action word: I <b>always</b> walk to school.<br>After is / am / are / was / were: He <b>is always</b> late." },
    { h: "very, too, enough", html: "<b>very</b> = a lot (no problem): The tea is <b>very</b> hot, but I like it.<br><b>too</b> = more than OK (a problem): The tea is <b>too</b> hot <b>to</b> drink.<br><b>enough</b> = as much as needed. It goes AFTER an adjective: tall <b>enough</b>, but BEFORE a noun: <b>enough</b> chairs." },
    { h: "Comparing adverbs", html: "fast → faster → fastest<br>carefully → <b>more</b> carefully → <b>most</b> carefully<br>well → better → best" }
  ],
  words: [],
  mistakes: [
    { wrong: "She sings good.", right: "She sings well.", why: "Good describes nouns. For an action, use well." },
    { wrong: "He answered quick.", right: "He answered quickly.", why: "Describing how he answered → adverb with -ly." },
    { wrong: "Kai is enough strong to lift it.", right: "Kai is strong enough to lift it.", why: "Enough goes after the adjective." },
    { wrong: "The tea is very hot to drink.", right: "The tea is too hot to drink.", why: "When it causes a problem (you cannot drink it), use too ... to." },
    { wrong: "I go always to the library.", right: "I always go to the library.", why: "How-often words go before the action word." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "The tortoise walked ___.", o: ["slowly","slow","slowest"], a: 0, why: "It tells HOW the tortoise walked → adverb: slowly." },
    { t: "mcq", lv: "A", q: "Please speak ___ in the library.", o: ["quietly","quiet","quieter"], a: 0, why: "It tells HOW to speak → adverb with -ly: quietly." },
    { t: "mcq", lv: "A", q: "The bird sang ___.", o: ["sweetly","sweet","sweeter"], a: 0, why: "How did it sing? Sweetly. Add -ly to make the adverb." },
    { t: "mcq", lv: "B", q: "Rahul plays the violin very ___.", o: ["well","good","goodly","best"], a: 0, why: "Describing an action (plays) → good becomes well." },
    { t: "mcq", lv: "B", q: "Mdm Tan drove ___ because the road was wet.", o: ["carefully","careful","carefuly","care"], a: 0, why: "How did she drive? careful + ly = carefully (two l's)." },
    { t: "mcq", lv: "B", q: "The baby slept ___ in her cot.", o: ["peacefully","peaceful","peacefuly","peace"], a: 0, why: "peaceful + ly = peacefully. Keep both l's." },
    { t: "mcq", lv: "B", q: "Which word is an adverb? 'Amir quickly packed his bag.'", o: ["quickly","packed","bag","his"], a: 0, why: "Quickly tells HOW Amir packed. That is an adverb." },
    { t: "mcq", lv: "B", q: "In 'We will visit Grandma tomorrow', the adverb tells us ___.", o: ["when","how","where","how often"], a: 0, why: "Tomorrow tells WHEN we will visit." },
    { t: "mcq", lv: "B", q: "In 'The children played outside', the adverb tells us ___.", o: ["where","when","how","how often"], a: 0, why: "Outside tells WHERE they played." },
    { t: "mcq", lv: "B", q: "Which word tells how often? 'I usually take the MRT to school.'", o: ["usually","take","MRT","school"], a: 0, why: "Usually tells how often I take the MRT." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["Lily is always late.","Lily always is late.","Always is Lily late.","Lily late is always."], a: 0, why: "With is / am / are, the how-often word comes after it: is always." },
    { t: "mcq", lv: "B", q: "The box is too heavy ___ me to lift.", o: ["for","to","enough","very"], a: 0, why: "Pattern: too + adjective + for + person + to + action." },
    { t: "mcq", lv: "B", q: "Jayden is not old ___ to watch that film.", o: ["enough","too","very","so"], a: 0, why: "Enough comes after the adjective: old enough." },
    { t: "mcq", lv: "B", q: "The soup is ___ hot to drink. Let it cool first.", o: ["too","very","enough","much"], a: 0, why: "It causes a problem (you cannot drink it yet) → too ... to." },
    { t: "mcq", lv: "B", q: "We do not have ___ chairs for everyone.", o: ["enough","too","very","much"], a: 0, why: "Enough goes before a noun: enough chairs." },
    { t: "mcq", lv: "B", q: "It is ___ windy today, but we can still fly our kite.", o: ["very","too","enough","much"], a: 0, why: "Very windy is no problem here. Too would mean we could NOT fly the kite." },
    { t: "mcq", lv: "B", q: "The water is not deep ___ for diving.", o: ["enough","too","very","much"], a: 0, why: "Enough comes after the adjective: deep enough." },
    { t: "mcq", lv: "B", q: "Of all the runners, Faizal ran the ___.", o: ["fastest","most fast","fastly","faster"], a: 0, why: "Top of all the runners → fastest. Fast never takes -ly." },
    { t: "mcq", lv: "C", q: "Sarah writes ___ than her brother.", o: ["more neatly","neatlier","more neat","neatlyer"], a: 0, why: "-ly adverbs compare with more: more neatly." },
    { t: "mcq", lv: "C", q: "He worked ___ to finish the project on time.", o: ["hard","hardly","hardy","hardest"], a: 0, why: "Hard is already an adverb. Hardly means 'almost not', which is the opposite!" },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["Ali is tall enough to reach the shelf.","Ali is enough tall to reach the shelf.","Ali is too tall enough to reach the shelf.","Ali is very tall to reach the shelf."], a: 0, why: "Enough goes after the adjective: tall enough to ..." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["The bag is too heavy for me to carry.","The bag is very heavy for me to carry it.","The bag is enough heavy for me to carry.","The bag is too heavy to me carry."], a: 0, why: "Pattern: too + adjective + for + person + to + action." },
    { t: "fix", lv: "A", q: "Mei Ling sang beautiful at the concert.", err: "beautiful", a: "beautifully", why: "It tells HOW she sang → adverb: beautifully." },
    { t: "fix", lv: "B", q: "You did good in your test!", err: "good", a: "well", why: "Describing an action (did) → well, not good." },
    { t: "fix", lv: "B", q: "The nurse spoke gentle to the child.", err: "gentle", a: "gently", why: "How did she speak? gentle → gently (drop e, add y)." },
    { t: "fix", lv: "B", q: "He answered the question correct.", err: "correct", a: "correctly", why: "How did he answer? Add -ly: correctly." },
    { t: "fix", lv: "B", q: "Kai is enough strong to carry the box.", err: "enough strong", a: "strong enough", why: "Enough goes after the adjective." },
    { t: "fix", lv: "B", q: "I go always to the library on Saturdays.", err: "go always", a: "always go", why: "How-often words go before the action word." },
    { t: "fix", lv: "C", q: "The tea is very hot to drink now.", err: "very", a: "too", why: "You cannot drink it, so it is a problem → too ... to." },
    { t: "fill", lv: "A", q: "Grandpa walked ___ (slow) up the stairs.", a: ["slowly"], why: "How did he walk? slow + ly = slowly." },
    { t: "fill", lv: "B", q: "The baby laughed ___ (happy).", a: ["happily"], why: "Happy ends in y → change to i, then add -ly." },
    { t: "fill", lv: "B", q: "Please hold the kitten ___ (gentle).", a: ["gently"], why: "Words ending in -le: drop e, add y → gently." },
    { t: "fill", lv: "B", q: "Zara ___ (easy) climbed the rope.", a: ["easily"], why: "Easy → easily (y becomes i, then -ly)." },
    { t: "fill", lv: "B", q: "Wei Ming did very ___ (good) in the swimming race.", a: ["well"], why: "For actions, good becomes well." },
    { t: "fill", lv: "B", q: "This bag is too small ___ hold all my books.", a: ["to"], why: "Pattern: too + adjective + to + action." },
    { t: "fill", lv: "B", q: "Are you tall ___ to ride the roller coaster?", a: ["enough"], why: "As tall as needed → tall enough." },
    { t: "trans", lv: "C", q: "Join using 'too ... to': The box was very heavy. Tim could not lift it.", a: ["The box was too heavy for Tim to lift."], why: "Too ... to already says he could not, so drop 'could not'. Do not add 'it' at the end." },
    { t: "trans", lv: "C", q: "Join using 'enough': Leela is very tall. She can reach the top shelf.", a: ["Leela is tall enough to reach the top shelf."], why: "Adjective + enough + to + action." },
    { t: "trans", lv: "B", q: "Rewrite using an adverb: Ken is a careful writer.", a: ["Ken writes carefully."], why: "Careful writer (adjective + noun) → writes carefully (verb + adverb)." }
  ]
});

window.VG.push({
  id: "en-g-reported",
  lang: "en",
  kind: "grammar",
  group: "Questions and speech",
  title: "Direct and reported speech",
  lv: "C",
  intro: "Direct speech gives the exact words inside speech marks. Reported speech tells someone what was said, without speech marks, and some words move a step back in time.",
  rules: [
    { h: "Direct vs reported", html: "Direct: Lisa said, <b>“I am tired.”</b><br>Reported: Lisa said <b>that she was tired</b>.<br>No speech marks in reported speech. 'that' is often added." },
    { h: "Move the tense one step back", html: "am / is → <b>was</b>, are → <b>were</b><br>will → <b>would</b>, can → <b>could</b><br>like → <b>liked</b>, am reading → <b>was reading</b><br>lost / have lost → <b>had lost</b>" },
    { h: "Change the people words", html: "I → he / she, my → his / her, we → they, our → their, you → I / me (depends who is listening).<br>Nina said, “<b>My</b> brother is ill.” → Nina said that <b>her</b> brother was ill." },
    { h: "Change time and place words", html: "today → <b>that day</b>, tomorrow → <b>the next day</b><br>yesterday → <b>the day before</b>, now → <b>then</b><br>here → <b>there</b>, this → <b>that</b>, next week → <b>the following week</b>" },
    { h: "Reporting questions", html: "Yes/no questions: <b>asked if / whether</b>. Wh- questions: keep the question word.<br>Use normal statement order and end with a full stop.<br>“Where do you live?” → She asked me <b>where I lived.</b> ✗ <i>where did I live?</i>" },
    { h: "Reporting orders", html: "Use <b>told / asked</b> + person + <b>to</b> + action.<br>“Close your books.” → The teacher told us <b>to close</b> our books.<br>“Don't run.” → He told us <b>not to run</b>." },
    { h: "said or told?", html: "<b>told</b> needs a person after it: Sam <b>told me</b> that ...<br><b>said</b> does not: Sam <b>said</b> that ..." }
  ],
  words: [],
  mistakes: [
    { wrong: "Mum told that she was busy.", right: "Mum said that she was busy.", why: "Told needs a person after it. Without a person, use said." },
    { wrong: "She asked me where did I live.", right: "She asked me where I lived.", why: "In reported questions, use normal order (I lived) and no did." },
    { wrong: "Jamal said that he can swim.", right: "Jamal said that he could swim.", why: "Move the tense back: can → could." },
    { wrong: "Sara asked if I wanted some cake?", right: "Sara asked if I wanted some cake.", why: "A reported question is not a real question any more, so end with a full stop." },
    { wrong: "The teacher told us to sat down.", right: "The teacher told us to sit down.", why: "After to, use the base form of the verb: to sit." }
  ],
  items: [
    { t: "mcq", lv: "B", q: "Which sentence is in direct speech?", o: ["“I am hungry,” said Ben.","Ben said that he was hungry.","Ben told me he was hungry.","Ben said he felt hungry."], a: 0, why: "Direct speech shows the exact words inside speech marks." },
    { t: "mcq", lv: "B", q: "Which sentence has the speech marks in the right place?", o: ["“Let's go to the park,” said Hana.","“Let's go to the park, said Hana.”","Let's go to the park, “said Hana.”","“Let's go” to the park, said Hana."], a: 0, why: "Speech marks go only around the words Hana spoke, with the comma inside." },
    { t: "mcq", lv: "C", q: "Lisa said, “I am tired.” → Lisa said that she ___ tired.", o: ["was","is","am","were"], a: 0, why: "Move back a step: am → was. She takes was." },
    { t: "mcq", lv: "C", q: "Tom said, “I will help you.” → Tom said that he ___ help me.", o: ["would","will","can","shall"], a: 0, why: "Move back a step: will → would." },
    { t: "mcq", lv: "C", q: "Mum said, “I can see the bus.” → Mum said that she ___ see the bus.", o: ["could","can","will","would"], a: 0, why: "Move back a step: can → could." },
    { t: "mcq", lv: "C", q: "Ravi said, “I lost my wallet.” → Ravi said that he ___ his wallet.", o: ["had lost","has lost","loses","will lose"], a: 0, why: "Past moves further back: lost → had lost." },
    { t: "mcq", lv: "C", q: "Aisha said, “I am reading a book.” → Aisha said that she ___ a book.", o: ["was reading","is reading","am reading","reads"], a: 0, why: "am reading → was reading." },
    { t: "mcq", lv: "C", q: "“We are going to the zoo tomorrow,” said the children. → The children said that they were going to the zoo ___.", o: ["the next day","tomorrow","yesterday","the day before"], a: 0, why: "In reported speech, tomorrow → the next day." },
    { t: "mcq", lv: "C", q: "Dad said, “I bought this cake yesterday.” → Dad said that he had bought that cake ___.", o: ["the day before","yesterday","tomorrow","the next day"], a: 0, why: "In reported speech, yesterday → the day before." },
    { t: "mcq", lv: "C", q: "Grandma said, “I live here.” → Grandma said that she lived ___.", o: ["there","here","this","that place here"], a: 0, why: "Here → there in reported speech." },
    { t: "mcq", lv: "C", q: "Ken said, “I have seen this film.” → Ken said that he had seen ___ film.", o: ["that","this","these","those"], a: 0, why: "This → that. (These/those are for more than one.)" },
    { t: "mcq", lv: "C", q: "Nina said, “My brother is ill.” → Nina said that ___ brother was ill.", o: ["her","my","his","their"], a: 0, why: "Nina is a girl, so my → her." },
    { t: "mcq", lv: "C", q: "“We have finished our work,” said the boys. → The boys said that they ___ their work.", o: ["had finished","have finished","has finished","finish"], a: 0, why: "have finished → had finished." },
    { t: "mcq", lv: "C", q: "Mei asked, “Where do you live?” Which is the correct reported question?", o: ["Mei asked me where I lived.","Mei asked me where did I live.","Mei asked me where do I live?","Mei asked me that where I lived."], a: 0, why: "Normal order (I lived), no do/did, no question mark." },
    { t: "mcq", lv: "C", q: "Jun asked, “Are you coming?” Which is the correct reported question?", o: ["Jun asked if I was coming.","Jun asked was I coming.","Jun asked if I am coming?","Jun asked that I was coming."], a: 0, why: "Yes/no question → asked if. Move back: are → was. End with a full stop." },
    { t: "mcq", lv: "C", q: "Priya asked, “Can I borrow your ruler?” → Priya asked if she ___ borrow my ruler.", o: ["could","can","will","may can"], a: 0, why: "can → could." },
    { t: "mcq", lv: "C", q: "The teacher said, “Close your books.” Which is correct?", o: ["The teacher told us to close our books.","The teacher told us close your books.","The teacher said us to close our books.","The teacher told that we close our books."], a: 0, why: "Orders: told + person + to + action. Your → our." },
    { t: "mcq", lv: "C", q: "The coach said, “Don't run on the wet floor.” → The coach told us ___ on the wet floor.", o: ["not to run","to not running","don't run","not run"], a: 0, why: "A 'don't' order becomes not to + action." },
    { t: "mcq", lv: "C", q: "Sam ___ me that he was busy.", o: ["told","said","spoke","talked"], a: 0, why: "There is a person (me) after the gap, so use told." },
    { t: "mcq", lv: "C", q: "Sam ___ that he was busy.", o: ["said","told","spoke to","talked"], a: 0, why: "No person after the gap, so use said." },
    { t: "mcq", lv: "C", q: "Mr Lim said, “I am busy now.” → Mr Lim said that he was busy ___.", o: ["then","now","tomorrow","soon"], a: 0, why: "Now → then in reported speech." },
    { t: "fix", lv: "C", q: "Mum told that she was going to the market.", err: "told", a: "said", why: "Told needs a person after it. With no person, use said." },
    { t: "fix", lv: "C", q: "Jamal said that he can swim.", err: "can", a: "could", why: "Move the tense back: can → could." },
    { t: "fix", lv: "C", q: "Ali said that he will come to my party.", err: "will", a: "would", why: "Move the tense back: will → would." },
    { t: "fix", lv: "C", q: "The girl asked me where was the toilet.", err: "where was the toilet", a: "where the toilet was", why: "Reported questions use statement order: where the toilet was." },
    { t: "fix", lv: "C", q: "Dad asked me whether I have fed the dog.", err: "have fed", a: "had fed", why: "have fed → had fed in reported speech." },
    { t: "fix", lv: "C", q: "Sara asked if I wanted some cake?", err: "cake?", a: "cake.", why: "A reported question ends with a full stop, not a question mark." },
    { t: "fix", lv: "C", q: "The teacher told us to sat down.", err: "sat", a: "sit", why: "After to, use the base verb: to sit." },
    { t: "fill", lv: "C", q: "Amy said, “I like durians.” → Amy said that she ___ durians.", a: ["liked"], why: "like → liked (one step back)." },
    { t: "fill", lv: "C", q: "Tom said, “I will phone you.” → Tom said that he ___ phone me.", a: ["would"], why: "will → would." },
    { t: "fill", lv: "C", q: "Hui said, “I saw a snake.” → Hui said that she ___ a snake.", a: ["had seen"], why: "saw → had seen (past moves further back)." },
    { t: "fill", lv: "C", q: "Raj asked, “Is it raining?” → Raj asked ___ it was raining.", a: ["if","whether"], why: "Yes/no questions are reported with if or whether." },
    { t: "fill", lv: "B", q: "“Sit down,” the teacher told Ming. → The teacher told Ming ___ sit down.", a: ["to"], why: "Orders: told + person + to + action." },
    { t: "fill", lv: "B", q: "Siti said, “We are happy.” → Siti said that ___ were happy.", a: ["they"], why: "We → they when you report it." },
    { t: "trans", lv: "C", q: "Change to reported speech: Farah said, “I am feeling sleepy.”", a: ["Farah said that she was feeling sleepy.","Farah said she was feeling sleepy."], why: "No speech marks; I → she; am → was." },
    { t: "trans", lv: "C", q: "Change to reported speech: Ken said, “I will finish it tomorrow.”", a: ["Ken said that he would finish it the next day.","Ken said that he would finish it the following day.","Ken said he would finish it the next day."], why: "I → he; will → would; tomorrow → the next day." },
    { t: "trans", lv: "C", q: "Change to reported speech: The librarian said to us, “Please return the books by Friday.”", a: ["The librarian asked us to return the books by Friday.","The librarian told us to return the books by Friday."], why: "A request or order: asked/told + us + to + action." },
    { t: "trans", lv: "C", q: "Change to reported speech: Mum asked me, “Have you eaten your lunch?”", a: ["Mum asked me if I had eaten my lunch.","Mum asked me whether I had eaten my lunch.","Mum asked if I had eaten my lunch."], why: "Yes/no question → if; have eaten → had eaten; your → my; full stop at the end." },
    { t: "trans", lv: "C", q: "Change to reported speech: Ms Goh asked, “Who broke this window?”", a: ["Ms Goh asked who had broken that window.","Ms Goh asked who had broken the window."], why: "Keep who; broke → had broken; this → that; no question mark." },
    { t: "trans", lv: "C", q: "Change to direct speech: Dev told his sister that he was going to the library.", a: ["“I am going to the library,” Dev told his sister.","Dev said to his sister, “I am going to the library.”","Dev told his sister, “I am going to the library.”"], why: "Use Dev's exact words in speech marks: he → I, was → am." }
  ]
});

window.VG.push({
  id: "en-g-passive",
  lang: "en",
  kind: "grammar",
  group: "Verbs and tenses",
  title: "Active and passive voice",
  lv: "C",
  intro: "In an active sentence the doer comes first. In a passive sentence the thing that the action happens to comes first. The passive is useful when we do not know, or do not care, who did it.",
  rules: [
    { h: "Active: the doer first", html: "<b>The cat</b> broke the vase. (The cat did it.)" },
    { h: "Passive: the thing first", html: "<b>The vase</b> was broken by the cat.<br>Recipe: <b>be</b> + <b>past participle</b> (broken, eaten, written, cleaned) + <b>by</b> + doer." },
    { h: "Change 'be' for the tense", html: "Present: is / are cleaned<br>Past: was / were cleaned<br>Future: will be cleaned<br>Present perfect: has / have been cleaned<br>Happening now: is / are being cleaned" },
    { h: "Singular or plural?", html: "Match 'be' with the new subject.<br>The window <b>is</b> cleaned. The windows <b>are</b> cleaned." },
    { h: "When to use the passive", html: "When we do not know who did it: My bike <b>was stolen</b>.<br>When the doer is not important: English <b>is spoken</b> here.<br>Then you can leave out 'by ...'." },
    { h: "Tricky past participles", html: "write → <b>written</b>, eat → <b>eaten</b>, break → <b>broken</b>, steal → <b>stolen</b>, give → <b>given</b>, catch → <b>caught</b>, build → <b>built</b>, sing → <b>sung</b>" },
    { h: "Not every verb can be passive", html: "The verb needs something it acts on (an object). <i>sleep, arrive, cry</i> cannot be made passive." }
  ],
  words: [],
  mistakes: [
    { wrong: "The letter was wrote by Amir.", right: "The letter was written by Amir.", why: "Passive uses the past participle: written, not wrote." },
    { wrong: "The windows is cleaned every week.", right: "The windows are cleaned every week.", why: "Windows is plural, so use are." },
    { wrong: "The cake will baked tomorrow.", right: "The cake will be baked tomorrow.", why: "Future passive needs will be + past participle." },
    { wrong: "The trees were planted from the pupils.", right: "The trees were planted by the pupils.", why: "The doer is introduced with by." },
    { wrong: "The thief was catch by the police.", right: "The thief was caught by the police.", why: "Use the past participle: caught." }
  ],
  items: [
    { t: "mcq", lv: "B", q: "Which sentence is passive?", o: ["The cake was eaten by the children.","The children ate the cake.","The children are eating the cake.","The children will eat the cake."], a: 0, why: "The cake (the thing) comes first, with was + eaten + by." },
    { t: "mcq", lv: "B", q: "Which sentence is active?", o: ["Mr Tan painted the fence.","The fence was painted by Mr Tan.","The fence is being painted.","The fence has been painted."], a: 0, why: "The doer (Mr Tan) comes first and does the action." },
    { t: "mcq", lv: "B", q: "The door was ___ by the wind.", o: ["opened","open","opening","opens"], a: 0, why: "Passive = was + past participle: opened." },
    { t: "mcq", lv: "C", q: "The window ___ by the ball yesterday.", o: ["was broken","was broke","is broken","broke"], a: 0, why: "Yesterday → past: was + broken (past participle)." },
    { t: "mcq", lv: "C", q: "English ___ in many countries.", o: ["is spoken","is speak","spoke","is spoke"], a: 0, why: "A general fact → present passive: is + spoken." },
    { t: "mcq", lv: "C", q: "These letters ___ by my grandfather many years ago.", o: ["were written","was written","were wrote","are written"], a: 0, why: "Letters is plural and it is the past: were + written." },
    { t: "mcq", lv: "C", q: "The new MRT line ___ next year.", o: ["will be opened","will open by","will be open by","is opened"], a: 0, why: "Future passive: will be + past participle." },
    { t: "mcq", lv: "C", q: "The hawker centre ___ every night.", o: ["is cleaned","are cleaned","cleans","is cleaning"], a: 0, why: "One hawker centre, a habit → is cleaned. It cannot clean itself!" },
    { t: "mcq", lv: "C", q: "My bicycle ___. I cannot find it anywhere!", o: ["has been stolen","has stolen","has been stole","have been stolen"], a: 0, why: "Present perfect passive: has been + stolen. Bicycle is singular → has." },
    { t: "mcq", lv: "C", q: "The classroom ___ right now, so please wait outside.", o: ["is being painted","is painting","was painted","has painted"], a: 0, why: "Happening now → is being + painted." },
    { t: "mcq", lv: "C", q: "The cakes ___ by Auntie Rose.", o: ["were baked","was baked","were bake","baked"], a: 0, why: "Cakes is plural → were + baked." },
    { t: "mcq", lv: "C", q: "Prizes ___ to the winners at the end of the race.", o: ["were given","was given","were gave","gave"], a: 0, why: "Prizes is plural, past → were + given." },
    { t: "mcq", lv: "C", q: "The homework ___ by Friday.", o: ["must be handed in","must hand in","must be hand in","must handed in"], a: 0, why: "must + be + past participle: must be handed in." },
    { t: "mcq", lv: "C", q: "Rice ___ in many parts of Asia.", o: ["is grown","is grew","grows by","are grown"], a: 0, why: "Rice is uncountable (singular) → is + grown." },
    { t: "mcq", lv: "C", q: "Active: The dog chased the cat. Which is the passive?", o: ["The cat was chased by the dog.","The cat chased the dog.","The cat is chased by the dog.","The dog was chased by the cat."], a: 0, why: "The cat comes first, keep the past tense (was chased), the dog goes after by." },
    { t: "mcq", lv: "C", q: "Active: Mum cooks dinner every day. Which is the passive?", o: ["Dinner is cooked by Mum every day.","Dinner was cooked by Mum every day.","Dinner cooks Mum every day.","Mum is cooked dinner every day."], a: 0, why: "Cooks is present, so use is cooked. Dinner moves to the front." },
    { t: "mcq", lv: "C", q: "Active: The pupils will plant the trees. Which is the passive?", o: ["The trees will be planted by the pupils.","The trees will plant by the pupils.","The trees are planted by the pupils.","The trees will be plant by the pupils."], a: 0, why: "Future passive: will be + planted." },
    { t: "mcq", lv: "C", q: "Passive: The song was sung by the choir. Which is the active?", o: ["The choir sang the song.","The choir sings the song.","The song sang the choir.","The choir was singing by the song."], a: 0, why: "The doer (choir) moves to the front. Was sung is past → sang." },
    { t: "mcq", lv: "C", q: "In 'The parcel was delivered by a postman', who did the action?", o: ["a postman","the parcel","nobody","we do not know"], a: 0, why: "The doer comes after by: a postman." },
    { t: "mcq", lv: "C", q: "Why is the passive used in 'My wallet was stolen'?", o: ["We do not know who stole it.","The wallet stole something.","It happened in the future.","It is a question."], a: 0, why: "The passive is handy when the doer is unknown." },
    { t: "mcq", lv: "C", q: "Which verb cannot be made passive?", o: ["sleep","eat","write","build"], a: 0, why: "You cannot sleep something, so there is no object to move to the front." },
    { t: "fix", lv: "C", q: "The letter was wrote by Amir.", err: "wrote", a: "written", why: "Passive needs the past participle: written." },
    { t: "fix", lv: "C", q: "The windows is cleaned every week.", err: "is", a: "are", why: "Windows is plural → are." },
    { t: "fix", lv: "C", q: "The thief was catch by the police.", err: "catch", a: "caught", why: "Past participle of catch is caught." },
    { t: "fix", lv: "C", q: "The food were eaten by the guests.", err: "were", a: "was", why: "Food is uncountable (singular) → was." },
    { t: "fix", lv: "C", q: "My homework has been finish.", err: "finish", a: "finished", why: "has been + past participle: finished." },
    { t: "fix", lv: "C", q: "The cake will baked by Dad tomorrow.", err: "will baked", a: "will be baked", why: "Future passive: will be + baked." },
    { t: "fix", lv: "C", q: "The trees were planted from the pupils.", err: "from", a: "by", why: "The doer comes after by." },
    { t: "fill", lv: "C", q: "The story was ___ (write) by a famous author.", a: ["written"], why: "was + past participle: written." },
    { t: "fill", lv: "C", q: "The cups were ___ (break) by the cat.", a: ["broken"], why: "were + past participle: broken." },
    { t: "fill", lv: "C", q: "The football match ___ (watch) by thousands of fans last night.", a: ["was watched"], why: "Last night → past. One match → was watched." },
    { t: "fill", lv: "C", q: "Tomorrow, the school hall ___ (decorate) for Racial Harmony Day.", a: ["will be decorated","is going to be decorated"], why: "Tomorrow → future passive: will be decorated." },
    { t: "fill", lv: "C", q: "The pupils ___ (give) a talk by a firefighter yesterday.", a: ["were given"], why: "Pupils is plural, past → were given." },
    { t: "fill", lv: "C", q: "Our flat ___ (paint) right now.", a: ["is being painted"], why: "Right now → is being + painted." },
    { t: "trans", lv: "C", q: "Change to the passive: The cat broke the vase.", a: ["The vase was broken by the cat."], why: "The vase moves to the front: was + broken + by the cat." },
    { t: "trans", lv: "C", q: "Change to the passive: Mrs Lee teaches the class.", a: ["The class is taught by Mrs Lee."], why: "Present → is taught. The class comes first." },
    { t: "trans", lv: "C", q: "Change to the passive: The workers will build a new playground.", a: ["A new playground will be built by the workers.","A new playground will be built."], why: "Future → will be built. The playground comes first." },
    { t: "trans", lv: "C", q: "Change to the passive: Someone has taken my pencil case.", a: ["My pencil case has been taken.","My pencil case has been taken by someone."], why: "has taken → has been taken. 'By someone' adds nothing, so you can leave it out." },
    { t: "trans", lv: "C", q: "Change to the active: The kite was flown by Hassan.", a: ["Hassan flew the kite."], why: "The doer (Hassan) goes first. Was flown is past → flew." },
    { t: "trans", lv: "C", q: "Change to the active: The cookies are being baked by Gran.", a: ["Gran is baking the cookies."], why: "Are being baked (happening now) → is baking." }
  ]
});

window.VG.push({
  id: "en-g-punct",
  lang: "en",
  kind: "grammar",
  group: "Sentences and punctuation",
  title: "Punctuation: capitals, full stops, commas, speech marks, question and exclamation marks",
  lv: "A",
  intro: "Punctuation marks are like road signs for readers. They show where a sentence starts and stops, when someone is speaking and how a sentence should sound.",
  rules: [
    { h: "Capital letters", html: "Use a capital letter to start every sentence, for <b>I</b>, and for names of people, places, days, months and festivals.<br>✓ On <b>M</b>onday <b>I</b> went to <b>S</b>entosa with <b>A</b>ida." },
    { h: "Full stop, question mark, exclamation mark", html: "Telling sentence → full stop <b>.</b><br>Asking sentence → question mark <b>?</b><br>Strong feeling (surprise, shock, excitement) → exclamation mark <b>!</b> What a big cake<b>!</b>" },
    { h: "Commas in a list", html: "Put commas between items. Use <b>and</b> (no comma) before the last one.<br>I bought apples<b>,</b> oranges and pears." },
    { h: "Other commas", html: "After a starting phrase: After school<b>,</b> we played.<br>After yes / no: Yes<b>,</b> I am ready.<br>Before or after a name you are talking to: Hurry up<b>,</b> Ali." },
    { h: "Speech marks", html: "Put “ ” around the exact words spoken. The comma, question mark or exclamation mark goes INSIDE.<br>✓ “I am hungry<b>,</b>” said Leo.<br>✓ “Can I help you<b>?</b>” asked the shopkeeper.<br>The spoken words start with a capital: Mum said, “<b>D</b>inner is ready.”" },
    { h: "Split speech", html: "If the sentence carries on: “If it rains,” said Mum, “<b>w</b>e will stay at home.” (small w)<br>If a new sentence starts: “I have finished,” said Ravi<b>.</b> “<b>M</b>ay I go out?”" }
  ],
  words: [],
  mistakes: [
    { wrong: "my brother and i like durian.", right: "My brother and I like durian.", why: "Start a sentence with a capital, and I is always a capital." },
    { wrong: "We went there on sunday.", right: "We went there on Sunday.", why: "Days of the week start with a capital." },
    { wrong: "Where is the canteen.", right: "Where is the canteen?", why: "An asking sentence ends with a question mark." },
    { wrong: "“Watch out” shouted Dad!", right: "“Watch out!” shouted Dad.", why: "The exclamation mark belongs to the spoken words, inside the speech marks." },
    { wrong: "I need eggs flour and sugar.", right: "I need eggs, flour and sugar.", why: "Use a comma between items in a list." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Which sentence is correct?", o: ["My friend lives in Tampines.","my friend lives in Tampines.","My friend lives in tampines."], a: 0, why: "A sentence starts with a capital, and place names need a capital too." },
    { t: "mcq", lv: "A", q: "Which sentence is correct?", o: ["On Monday we went to the zoo.","On monday we went to the zoo.","on Monday we went to the zoo."], a: 0, why: "Capital for the first word AND for days of the week." },
    { t: "mcq", lv: "A", q: "Which sentence is correct?", o: ["Today is Friday.","today is Friday.","Today is friday."], a: 0, why: "Start with a capital; days of the week have capitals." },
    { t: "mcq", lv: "A", q: "Which sentence is correct?", o: ["Ben and i played football.","Ben and I played football.","ben and I played football."], a: 1, why: "I is always a capital, and names like Ben need one too." },
    { t: "mcq", lv: "A", q: "Which mark ends this sentence? 'Where is my water bottle'", o: ["?",".","!"], a: 0, why: "It is asking something, so it needs a question mark." },
    { t: "mcq", lv: "A", q: "Which mark ends this sentence? 'What a beautiful rainbow'", o: ["!","?",","], a: 0, why: "'What a ...' shows strong feeling, so use an exclamation mark." },
    { t: "mcq", lv: "A", q: "Which mark ends this sentence? 'My cat is three years old'", o: [".","?",","], a: 0, why: "It tells us something, so it ends with a full stop." },
    { t: "mcq", lv: "A", q: "Which sentence needs a question mark?", o: ["Do you like durian","I like durian","Durian smells strong"], a: 0, why: "'Do you ...' is asking, so it needs a question mark." },
    { t: "mcq", lv: "B", q: "Which word needs a capital letter? 'My birthday is in june.'", o: ["june","birthday","is","in"], a: 0, why: "Months of the year always start with a capital: June." },
    { t: "mcq", lv: "B", q: "Which word needs a capital letter? 'My best friend siti lives in Bedok.'", o: ["siti","friend","lives","best"], a: 0, why: "Siti is a person's name, so it needs a capital." },
    { t: "mcq", lv: "B", q: "What is missing? 'We went to Sentosa on Saturday and we had fun'", o: ["a full stop at the end","a question mark at the end","a comma after We","speech marks"], a: 0, why: "It is a telling sentence, so it needs a full stop at the end." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["I bought apples, oranges and pears.","I bought apples oranges, and pears.","I bought, apples, oranges and pears.","I bought apples, oranges, and, pears."], a: 0, why: "Commas go between the items, with and before the last one." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["Yes, I would like some tea.","Yes I, would like some tea.","Yes I would, like some tea.","Yes, I would, like some tea."], a: 0, why: "Put a comma straight after yes or no." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["After school, we went to the library.","After, school we went to the library.","After school we, went to the library.","After school we went, to the library."], a: 0, why: "The comma comes after the whole starting phrase 'After school'." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["“Can I help you?” asked the shopkeeper.","“Can I help you,” asked the shopkeeper?","“Can I help you?” Asked the shopkeeper.","Can I help you? “asked the shopkeeper.”"], a: 0, why: "The question mark goes inside the speech marks. 'asked' does not need a capital." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["“Watch out!” shouted Dad.","“Watch out,” shouted Dad!","Watch out! “shouted Dad.”","“Watch out” shouted Dad!"], a: 0, why: "The exclamation mark belongs to Dad's words, so it goes inside. End with a full stop." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["Mum said, “Dinner is ready.”","Mum said “dinner is ready.”","Mum said, “dinner is ready”.","Mum said, Dinner is ready."], a: 0, why: "Comma before the speech, capital to start the spoken words, full stop inside." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["“Hurry up, Ali,” said his sister.","“Hurry up Ali,” said his sister.","“Hurry up, Ali” said his sister.","“Hurry up, Ali,” Said his sister."], a: 0, why: "Comma before the name you are talking to, and a comma inside the speech marks." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["“Where are you going?” asked Grandpa.","“Where are you going?”, asked Grandpa.","“Where are you going,” asked Grandpa?","“Where are you going.” asked Grandpa."], a: 0, why: "The question mark goes inside. Do not add a comma after it." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["“If it rains,” said Mum, “we will stay at home.”","“If it rains,” said Mum, “We will stay at home.”","“If it rains” said Mum “we will stay at home.”","“If it rains,” said Mum. “we will stay at home.”"], a: 0, why: "It is one sentence split in two, so use commas and a small w." },
    { t: "mcq", lv: "C", q: "Which is correct?", o: ["“I have finished,” said Ravi. “May I go out to play?”","“I have finished,” said Ravi, “May I go out to play?”","“I have finished” said Ravi. “may I go out to play?”","“I have finished,” said Ravi. “May I go out to play.”"], a: 0, why: "Two separate sentences: full stop after Ravi, capital M, and a question mark for the question." },
    { t: "fix", lv: "A", q: "my teacher is kind.", err: "my", a: "My", why: "Every sentence starts with a capital letter." },
    { t: "fix", lv: "A", q: "My brother and i love ice kacang.", err: "and i", a: "and I", why: "I is always a capital letter." },
    { t: "fix", lv: "A", q: "We went to the beach on sunday.", err: "sunday", a: "Sunday", why: "Days of the week start with a capital." },
    { t: "fix", lv: "A", q: "Where is the nearest MRT station.", err: "station.", a: "station?", why: "It is a question, so end with a question mark." },
    { t: "fix", lv: "B", q: "What a huge cake?", err: "cake?", a: "cake!", why: "'What a ...' shows surprise, not a question. Use an exclamation mark." },
    { t: "fix", lv: "B", q: "Last week we visited Grandma in malaysia.", err: "malaysia", a: "Malaysia", why: "Names of countries start with a capital." },
    { t: "fix", lv: "B", q: "I need eggs flour and sugar.", err: "eggs flour", a: "eggs, flour", why: "Put a comma between items in a list." },
    { t: "fill", lv: "A", q: "Is it time for recess___", a: ["?"], why: "It is asking something → question mark." },
    { t: "fill", lv: "A", q: "Ouch___ That hurts!", a: ["!"], why: "Ouch shows a strong feeling → exclamation mark." },
    { t: "fill", lv: "A", q: "We live in ___ (singapore).", a: ["Singapore"], why: "Names of countries start with a capital." },
    { t: "fill", lv: "A", q: "My birthday is in ___ (december).", a: ["December"], why: "Months always start with a capital." },
    { t: "fill", lv: "B", q: "I like red, blue___ green and yellow.", a: [","], why: "Put a comma between items in a list (but not before and)." },
    { t: "fill", lv: "B", q: "Yes___ I have finished my homework.", a: [","], why: "Put a comma after yes or no at the start." },
    { t: "trans", lv: "B", q: "Rewrite with the correct capitals and full stop: jia hui and i went to the singapore zoo on tuesday", a: ["Jia Hui and I went to the Singapore Zoo on Tuesday."], why: "Capitals for the first word, names (Jia Hui, Singapore Zoo), I and days (Tuesday). Full stop at the end." },
    { t: "trans", lv: "B", q: "Add speech marks and punctuation: I am hungry said Leo", a: ["“I am hungry,” said Leo.","\"I am hungry,\" said Leo."], why: "Speech marks around Leo's words, a comma inside them, and a full stop at the end." },
    { t: "trans", lv: "C", q: "Add the missing punctuation and capital: what time does the movie start asked Mum", a: ["“What time does the movie start?” asked Mum.","\"What time does the movie start?\" asked Mum."], why: "Capital W, a question mark inside the speech marks, and a full stop at the end." }
  ]
});
