window.VG = window.VG || [];

/* 1. Contrast */
window.VG.push({
  id: "en-g-syn-contrast",
  lang: "en",
  kind: "grammar",
  group: "Synthesis and transformation",
  title: "Combining sentences: although, though, despite, in spite of, but, however",
  lv: "B",
  intro: "Sometimes two ideas seem to fight each other: it was raining, but we still played. These joining words help you show that surprise in one smooth sentence.",
  rules: [
    { h: "But joins two ideas that clash", html: "Put <b>but</b> in the middle.<br>✓ It was late, <b>but</b> the shop was still open." },
    { h: "Although / though + a full sentence", html: "<b>Although</b> and <b>though</b> are followed by a subject and a verb.<br>✓ <b>Although</b> it was raining, we went out.<br>✓ We went out <b>though</b> it was raining." },
    { h: "Never use although and but together", html: "One joining word is enough.<br>✗ Although it was hot, <b>but</b> we played.<br>✓ Although it was hot, we played." },
    { h: "Despite / in spite of + a noun or -ing word", html: "<b>Despite</b> and <b>in spite of</b> are NOT followed by a full sentence.<br>✓ <b>Despite the rain</b>, we went out.<br>✓ <b>In spite of being tired</b>, she finished.<br>✗ Despite it was raining, we went out.<br>Tip: you may say <b>despite the fact that</b> + a full sentence." },
    { h: "However starts a new sentence", html: "Use a full stop (or a semicolon) before <b>however</b> and a comma after it.<br>✓ The test was hard. <b>However,</b> Mei passed." },
    { h: "Keep the meaning the same", html: "When you rewrite, check that the same person did the same thing. Change <b>she was tired</b> to <b>being tired</b> or <b>her tiredness</b>, not to a new idea." }
  ],
  words: [],
  mistakes: [
    { wrong: "Although it was raining, but we went to the park.", right: "Although it was raining, we went to the park.", why: "Although already joins the two ideas, so drop 'but'." },
    { wrong: "Despite it was raining, we went to the park.", right: "Despite the rain, we went to the park.", why: "Despite needs a noun or an -ing word, not a full sentence." },
    { wrong: "In spite the noise, the baby slept.", right: "In spite of the noise, the baby slept.", why: "It is always 'in spite of'. Do not forget 'of'." },
    { wrong: "The test was hard, however Mei passed.", right: "The test was hard. However, Mei passed.", why: "However starts a new sentence and has a comma after it." },
    { wrong: "Despite of the traffic, we were on time.", right: "Despite the traffic, we were on time.", why: "Say 'despite' or 'in spite of', never 'despite of'." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "I wanted to play outside, ___ it was raining.", o: ["but", "and", "so", "because"], a: 0, why: "Wanting to play and rain clash, so we use 'but'." },
    { t: "fill", lv: "A", q: "The box was heavy, ___ Ali carried it upstairs.", a: ["but", "yet"], why: "Heavy but still carried: 'but' shows the surprise." },
    { t: "trans", lv: "B", q: "Combine using 'but': Mei Ling was tired. She finished her homework.", a: ["Mei Ling was tired but she finished her homework.", "Mei Ling was tired, but she finished her homework."], why: "Put 'but' between the two ideas that clash." },
    { t: "trans", lv: "B", q: "Combine using 'but': The durian smelt strong. Jun Hao loved it.", a: ["The durian smelt strong but Jun Hao loved it.", "The durian smelt strong, but Jun Hao loved it."], why: "A strong smell, yet he loved it: 'but' shows the contrast." },
    { t: "trans", lv: "B", q: "Combine using 'although': It was raining. We played football at the void deck.", a: ["Although it was raining, we played football at the void deck.", "We played football at the void deck although it was raining."], why: "Although + a full sentence. Do not add 'but'." },
    { t: "trans", lv: "B", q: "Combine using 'although': Siti studied hard. She did not pass the test.", a: ["Although Siti studied hard, she did not pass the test.", "Siti did not pass the test although she studied hard."], why: "Put 'although' in front of the idea that makes the result surprising (she studied hard)." },
    { t: "trans", lv: "B", q: "Combine using 'though': The MRT train was crowded. Ravi found a seat.", a: ["Though the MRT train was crowded, Ravi found a seat.", "Ravi found a seat though the MRT train was crowded."], why: "Though works just like although: it is followed by a full sentence." },
    { t: "trans", lv: "B", q: "Combine using 'though': Hui Min is only eight. She can swim 200 metres.", a: ["Though Hui Min is only eight, she can swim 200 metres.", "Hui Min can swim 200 metres though she is only eight."], why: "Though + full sentence. Use a comma when the 'though' part comes first." },
    { t: "trans", lv: "B", q: "Rewrite using 'however': The queue at the chicken rice stall was long. Dad waited patiently.", a: ["The queue at the chicken rice stall was long. However, Dad waited patiently.", "The queue at the chicken rice stall was long; however, Dad waited patiently.", "The queue at the chicken rice stall was long. Dad, however, waited patiently."], why: "However starts the second sentence and is followed by a comma." },
    { t: "trans", lv: "B", q: "Rewrite using 'however': The test was difficult. Most pupils passed.", a: ["The test was difficult. However, most pupils passed.", "The test was difficult; however, most pupils passed."], why: "Keep two sentences. Put 'However,' at the start of the second one." },
    { t: "trans", lv: "B", q: "Rewrite, beginning with 'Although': Ahmad was afraid of the dark, but he walked down the corridor alone.", a: ["Although Ahmad was afraid of the dark, he walked down the corridor alone."], why: "Once you use 'although', remove 'but'." },
    { t: "mcq", lv: "B", q: "___ he was hungry, Daniel shared his bun with his friend.", o: ["Although", "Despite", "However", "But"], a: 0, why: "'He was hungry' is a full sentence, so we need 'although'. Despite cannot be followed by a full sentence." },
    { t: "mcq", lv: "B", q: "___ the rain, we went to the zoo.", o: ["Despite", "Although", "However", "Though"], a: 0, why: "'The rain' is just a noun, so we use 'despite'." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["Although it was hot, but we played outside.", "Although it was hot, we played outside.", "Although it was hot, however we played outside.", "Despite it was hot, we played outside."], a: 1, why: "Use only one joining word. Despite cannot be followed by 'it was hot'." },
    { t: "mcq", lv: "B", q: "The cake looked delicious. ___, it tasted terrible.", o: ["However", "Although", "Despite", "Because"], a: 0, why: "At the start of a new sentence with a comma, 'However' shows the contrast." },
    { t: "fill", lv: "B", q: "___ the hawker centre was crowded, we found a table quickly.", a: ["Although", "Though", "Even though"], why: "A full sentence follows, so use although or though." },
    { t: "fill", lv: "B", q: "My brother is clever. ___, he is careless.", a: ["However", "Nevertheless"], why: "A new sentence with a comma after the gap needs 'However'." },
    { t: "mcq", lv: "C", q: "In spite ___ the noise, the baby slept soundly.", o: ["of", "to", "that", "with"], a: 0, why: "The phrase is always 'in spite of'." },
    { t: "mcq", lv: "C", q: "Despite ___ the bus, Farah reached school on time.", o: ["missing", "she missed", "missed", "to miss"], a: 0, why: "After despite, use a noun or an -ing word: missing." },
    { t: "fill", lv: "C", q: "In ___ of the rain, the parade went on.", a: ["spite"], why: "In spite of + noun: in spite of the rain." },
    { t: "fill", lv: "C", q: "Despite ___ (feel) sleepy, Priya finished her book.", a: ["feeling"], why: "After despite, change the verb into its -ing form." },
    { t: "trans", lv: "C", q: "Combine using 'despite': It rained heavily. The sports day carried on.", a: ["Despite the heavy rain, the sports day carried on.", "The sports day carried on despite the heavy rain."], why: "Change 'it rained heavily' into a noun phrase: the heavy rain." },
    { t: "trans", lv: "C", q: "Combine using 'in spite of': Grandma has a bad knee. She walks to the market every morning.", a: ["In spite of her bad knee, Grandma walks to the market every morning.", "Grandma walks to the market every morning in spite of her bad knee.", "In spite of having a bad knee, Grandma walks to the market every morning."], why: "In spite of + noun (her bad knee) or + -ing (having a bad knee)." },
    { t: "trans", lv: "C", q: "Combine using 'despite': Wei Jie was ill. He went for his piano exam.", a: ["Despite being ill, Wei Jie went for his piano exam.", "Despite his illness, Wei Jie went for his piano exam.", "Wei Jie went for his piano exam despite being ill."], why: "'Was ill' becomes 'being ill' or 'his illness' after despite." },
    { t: "trans", lv: "C", q: "Combine using 'in spite of': The pupils were tired. They cleaned the classroom cheerfully.", a: ["In spite of being tired, the pupils cleaned the classroom cheerfully.", "In spite of their tiredness, the pupils cleaned the classroom cheerfully.", "The pupils cleaned the classroom cheerfully in spite of being tired."], why: "'Were tired' becomes 'being tired' after in spite of." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'Despite': Although Nurul was nervous, she sang well at the concert.", a: ["Despite being nervous, Nurul sang well at the concert.", "Despite her nervousness, Nurul sang well at the concert."], why: "Despite needs 'being nervous' or 'her nervousness'. Move Nurul's name into the main part." },
    { t: "trans", lv: "C", q: "Rewrite using 'although': Despite the long walk, the children were not tired.", a: ["Although the walk was long, the children were not tired.", "The children were not tired although the walk was long.", "Although it was a long walk, the children were not tired."], why: "Although needs a full sentence, so 'the long walk' becomes 'the walk was long'." },
    { t: "trans", lv: "C", q: "Rewrite using 'however': Although the shoes were expensive, Mum bought them.", a: ["The shoes were expensive. However, Mum bought them.", "The shoes were expensive; however, Mum bought them."], why: "Remove 'although', make two sentences, and start the second with 'However,'." },
    { t: "trans", lv: "C", q: "Combine using 'in spite of': The traffic was heavy. We reached Changi Airport on time.", a: ["In spite of the heavy traffic, we reached Changi Airport on time.", "We reached Changi Airport on time in spite of the heavy traffic."], why: "'The traffic was heavy' becomes the noun phrase 'the heavy traffic'." },
    { t: "trans", lv: "C", q: "Combine using 'despite': Kumar had a sprained ankle. He completed the race.", a: ["Despite his sprained ankle, Kumar completed the race.", "Despite having a sprained ankle, Kumar completed the race.", "Kumar completed the race despite his sprained ankle."], why: "Despite + his sprained ankle, or despite + having a sprained ankle." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'In spite of': Though it was late, the hawker centre was still busy.", a: ["In spite of the late hour, the hawker centre was still busy.", "In spite of it being late, the hawker centre was still busy."], why: "In spite of needs a noun phrase such as 'the late hour'." },
    { t: "trans", lv: "C", q: "Combine using 'despite the fact that': The fan was on. The room was still hot.", a: ["Despite the fact that the fan was on, the room was still hot.", "The room was still hot despite the fact that the fan was on."], why: "'Despite the fact that' can be followed by a full sentence." }
  ]
});

/* 2. Paired conjunctions */
window.VG.push({
  id: "en-g-syn-pairs",
  lang: "en",
  kind: "grammar",
  group: "Synthesis and transformation",
  title: "Not only…but also, neither…nor, either…or, both…and",
  lv: "C",
  intro: "Some joining words come in pairs, like two shoes. They help you join two people or two things in one neat sentence, but you must choose the right verb.",
  rules: [
    { h: "Both…and = the two together (plural)", html: "✓ <b>Both</b> Ali <b>and</b> Ben <b>like</b> satay.<br>Two people, so the verb is plural." },
    { h: "Either…or = one or the other", html: "✓ You can take <b>either</b> the MRT <b>or</b> the bus." },
    { h: "Neither…nor = not this and not that", html: "<b>Neither…nor</b> already means 'not', so do not add another 'not'.<br>✓ Ravi brought <b>neither</b> his cap <b>nor</b> his bottle.<br>✗ Ravi did not bring neither his cap nor his bottle." },
    { h: "Not only…but also = this, and that too", html: "✓ The library is <b>not only</b> quiet <b>but also</b> comfortable.<br>At the start of a sentence, turn the verb around: <b>Not only did</b> Hui Min win…, <b>but she also</b> won…" },
    { h: "The verb agrees with the NEARER subject", html: "With <b>either…or</b>, <b>neither…nor</b> and <b>not only…but also</b>, look at the subject closest to the verb.<br>✓ Neither the boys nor their <b>mother was</b> home.<br>✓ Neither the teacher nor the <b>pupils were</b> ready." },
    { h: "Keep the pair balanced", html: "Put the same kind of word after each half.<br>✓ Mei can <b>both sing and dance</b>.<br>✓ We can go on <b>either Saturday or Sunday</b>." }
  ],
  words: [],
  mistakes: [
    { wrong: "Neither Siti or her sister can swim.", right: "Neither Siti nor her sister can swim.", why: "Neither goes with nor. Either goes with or." },
    { wrong: "Ravi did not bring neither his cap nor his bottle.", right: "Ravi brought neither his cap nor his bottle.", why: "Neither already means 'not', so do not add 'did not'." },
    { wrong: "Neither the boys nor their mother were at home.", right: "Neither the boys nor their mother was at home.", why: "The verb agrees with the nearer subject: mother (one) → was." },
    { wrong: "Both Ali and Ben likes satay.", right: "Both Ali and Ben like satay.", why: "Both…and means two people, so use the plural verb." },
    { wrong: "Not only Hui Min won the spelling bee, but she also won the art competition.", right: "Not only did Hui Min win the spelling bee, but she also won the art competition.", why: "When a sentence starts with 'Not only', add did/does and turn the verb around." }
  ],
  items: [
    { t: "fill", lv: "A", q: "___ Mum and Dad came to my concert.", a: ["Both"], why: "Both goes with and: both Mum and Dad." },
    { t: "mcq", lv: "B", q: "You can have ___ the red cup or the blue one.", o: ["either", "neither", "both", "not only"], a: 0, why: "Either goes with or, meaning one or the other." },
    { t: "mcq", lv: "B", q: "___ Faridah nor her brother likes spicy food.", o: ["Neither", "Either", "Both", "Not only"], a: 0, why: "Nor always pairs with neither." },
    { t: "mcq", lv: "B", q: "Both my cousins ___ in Tampines.", o: ["live", "lives", "is living", "living"], a: 0, why: "Both cousins = two people, so the plural verb 'live'." },
    { t: "mcq", lv: "B", q: "Neither Tom nor Jerry ___ the answer.", o: ["knows", "know", "are knowing", "knowing"], a: 0, why: "The nearer subject is Jerry (one person), so 'knows'." },
    { t: "fill", lv: "B", q: "You can either walk ___ cycle to the park.", a: ["or"], why: "Either pairs with or." },
    { t: "fill", lv: "B", q: "Neither the lift ___ the escalator was working.", a: ["nor"], why: "Neither pairs with nor." },
    { t: "trans", lv: "B", q: "Combine using 'both…and': Ali likes satay. Ben likes satay.", a: ["Both Ali and Ben like satay."], why: "Two people share the same liking, so use both…and with the plural verb 'like'." },
    { t: "trans", lv: "B", q: "Combine using 'both…and': Mei can sing. Mei can dance.", a: ["Mei can both sing and dance."], why: "Put both and and in front of the two actions: both sing and dance." },
    { t: "trans", lv: "B", q: "Combine using 'either…or': You can take the MRT. You can take the bus.", a: ["You can take either the MRT or the bus.", "You can either take the MRT or take the bus."], why: "Only one choice will happen, so use either…or." },
    { t: "trans", lv: "B", q: "Combine using 'either…or': You may have rice. You may have noodles.", a: ["You may have either rice or noodles."], why: "One or the other: either rice or noodles." },
    { t: "trans", lv: "B", q: "Combine using 'neither…nor': Siti cannot swim. Her sister cannot swim.", a: ["Neither Siti nor her sister can swim."], why: "Neither…nor already means 'not', so 'cannot' becomes 'can'." },
    { t: "trans", lv: "B", q: "Combine using 'neither…nor': Ravi did not bring his water bottle. Ravi did not bring his cap.", a: ["Ravi brought neither his water bottle nor his cap."], why: "Remove 'did not' and change 'bring' to 'brought', because neither…nor is already negative." },
    { t: "mcq", lv: "C", q: "Neither the boys nor their mother ___ at home.", o: ["was", "were", "are", "have"], a: 0, why: "The nearer subject is 'their mother' (one person), so 'was'." },
    { t: "mcq", lv: "C", q: "Either the twins or Sam ___ going to carry the drum.", o: ["is", "are", "were", "be"], a: 0, why: "The nearer subject is Sam (one person), so 'is'." },
    { t: "mcq", lv: "C", q: "Not only the pupils but also the principal ___ excited.", o: ["was", "were", "are", "have"], a: 0, why: "The nearer subject is 'the principal' (one person), so 'was'." },
    { t: "mcq", lv: "C", q: "Lily is not only clever ___ hard-working.", o: ["but also", "and also", "or", "nor"], a: 0, why: "Not only always pairs with but also." },
    { t: "fill", lv: "C", q: "Not only did Dinesh score a goal, ___ he also helped his teammates.", a: ["but"], why: "Not only…but also. Here 'also' comes after 'he', so only 'but' goes in the gap." },
    { t: "fill", lv: "C", q: "Neither Priya nor her friends ___ (be) at the MRT station yet.", a: ["are", "were"], why: "The nearer subject is 'her friends' (more than one), so use are/were." },
    { t: "trans", lv: "C", q: "Combine using 'not only…but also': Jun Hao plays the violin. He plays the piano.", a: ["Jun Hao plays not only the violin but also the piano.", "Not only does Jun Hao play the violin, but he also plays the piano.", "Jun Hao not only plays the violin but also plays the piano."], why: "Put 'not only' before the first thing and 'but also' before the second." },
    { t: "trans", lv: "C", q: "Combine using 'not only…but also': The library is quiet. It is comfortable.", a: ["The library is not only quiet but also comfortable."], why: "Both describing words follow the pair: not only quiet but also comfortable." },
    { t: "trans", lv: "C", q: "Combine using 'neither…nor': The teacher was not in the classroom. The pupils were not in the classroom.", a: ["Neither the teacher nor the pupils were in the classroom."], why: "The nearer subject is 'the pupils' (plural), so 'were'." },
    { t: "trans", lv: "C", q: "Combine using 'either…or': Mum will fetch me. Dad will fetch me.", a: ["Either Mum or Dad will fetch me."], why: "Only one of them will come, so use either…or." },
    { t: "trans", lv: "C", q: "Combine using 'neither…nor': My brothers did not eat the kueh. My sister did not eat the kueh.", a: ["Neither my brothers nor my sister ate the kueh."], why: "Drop 'did not' and use 'ate', because neither…nor is already negative." },
    { t: "trans", lv: "C", q: "Rewrite using 'neither…nor': Aisha does not like durian and she does not like jackfruit either.", a: ["Aisha likes neither durian nor jackfruit."], why: "'Does not like' becomes 'likes', because neither…nor carries the 'not'." },
    { t: "trans", lv: "C", q: "Rewrite using 'both…and': Not only Kumar but also Peter was late.", a: ["Both Kumar and Peter were late."], why: "Both…and joins two people, so the verb becomes plural: were." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'Not only': Hui Min won the spelling bee and the art competition.", a: ["Not only did Hui Min win the spelling bee, but she also won the art competition.", "Not only did Hui Min win the spelling bee but she also won the art competition."], why: "After 'Not only' at the start, use 'did' + base verb (did…win), then 'but she also won'." },
    { t: "trans", lv: "C", q: "Combine using 'neither…nor': Lina did not finish her homework. Her friend did not finish her homework either.", a: ["Neither Lina nor her friend finished her homework.", "Neither Lina nor her friend finished their homework."], why: "The nearer subject is 'her friend' (one), and 'did not finish' becomes 'finished'." },
    { t: "trans", lv: "C", q: "Combine using 'either…or': We can go to Sentosa on Saturday. We can go on Sunday.", a: ["We can go to Sentosa on either Saturday or Sunday.", "We can go to Sentosa either on Saturday or on Sunday."], why: "Keep the pair balanced: either Saturday or Sunday." },
    { t: "trans", lv: "C", q: "Combine using 'not only…but also': The pupils cleaned the classroom. The teacher cleaned the classroom.", a: ["Not only the pupils but also the teacher cleaned the classroom."], why: "Put the two subjects inside the pair, then the action once." },
    { t: "trans", lv: "C", q: "Combine using 'both…and': The hawker centre is cheap. It is clean.", a: ["The hawker centre is both cheap and clean."], why: "Both + first describing word + and + second describing word." },
    { t: "trans", lv: "C", q: "Rewrite using 'not only…but also': Wei Ling is both kind and generous.", a: ["Wei Ling is not only kind but also generous."], why: "Swap both…and for not only…but also; the meaning stays the same." },
    { t: "trans", lv: "C", q: "Combine using 'neither…nor': The shop does not sell bread. It does not sell milk.", a: ["The shop sells neither bread nor milk."], why: "'Does not sell' becomes 'sells', because neither…nor already means 'not'." }
  ]
});

/* 3. Result: too…to, so…that, such…that, enough */
window.VG.push({
  id: "en-g-syn-result",
  lang: "en",
  kind: "grammar",
  group: "Synthesis and transformation",
  title: "Too…to, so…that, such…that, enough to",
  lv: "C",
  intro: "These patterns tell us what happens because something is very hot, very big or very fast. They are common in synthesis questions, so learn the small traps.",
  rules: [
    { h: "Too…to = so much that you cannot", html: "<b>Too</b> + describing word + <b>to</b> + verb. It already means 'cannot'.<br>✓ Ben is <b>too young to</b> ride the roller coaster.<br>✗ Ben is too young to not ride…" },
    { h: "Do not repeat the thing at the end", html: "✓ The box is too heavy for me to lift.<br>✗ The box is too heavy for me to lift <b>it</b>.<br>The box is already the subject, so no 'it'." },
    { h: "So + describing word + that", html: "✓ The soup was <b>so hot that</b> I could not drink it.<br>✓ There were <b>so many</b> people <b>that</b>…" },
    { h: "Such + (a/an) + describing word + noun + that", html: "<b>Such</b> comes before a noun.<br>✓ It was <b>such a funny film that</b> we laughed.<br>No 'a' for uncountable or plural nouns: ✓ <b>such hot weather</b>, <b>such kind neighbours</b>." },
    { h: "Describing word + enough + to", html: "<b>Enough</b> comes AFTER the describing word.<br>✓ Mei is <b>tall enough to</b> reach the shelf.<br>✗ Mei is enough tall to reach the shelf.<br>For a 'cannot' meaning: not + describing word + enough." },
    { h: "Use could / could not after a past 'that'", html: "✓ The water was so cold that we <b>could not</b> swim." }
  ],
  words: [],
  mistakes: [
    { wrong: "The box is too heavy for me to lift it.", right: "The box is too heavy for me to lift.", why: "The box is already mentioned at the start, so do not add 'it'." },
    { wrong: "It was so a funny film that we laughed.", right: "It was such a funny film that we laughed.", why: "Before a/an + noun, use 'such', not 'so'." },
    { wrong: "Mei is enough tall to reach the shelf.", right: "Mei is tall enough to reach the shelf.", why: "Enough comes after the describing word." },
    { wrong: "It was such a hot weather that we stayed indoors.", right: "It was such hot weather that we stayed indoors.", why: "Weather is uncountable, so do not use 'a'." },
    { wrong: "The soup was too hot that I could not drink it.", right: "The soup was so hot that I could not drink it.", why: "Too goes with 'to'; so goes with 'that'." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "The tea is too hot ___ drink.", o: ["to", "for", "that"], a: 0, why: "Too…to: too hot to drink." },
    { t: "fill", lv: "A", q: "The shelf is too high for me ___ reach.", a: ["to"], why: "Too high for me to reach." },
    { t: "mcq", lv: "B", q: "Ali was ___ tired that he fell asleep on the bus.", o: ["so", "such", "too", "enough"], a: 0, why: "Describing word + that → so tired that." },
    { t: "mcq", lv: "B", q: "It was ___ a long walk that our legs ached.", o: ["such", "so", "too", "very"], a: 0, why: "Before 'a long walk' (a + noun) we use such." },
    { t: "mcq", lv: "B", q: "Is the water warm ___ to swim in?", o: ["enough", "too", "so", "such"], a: 0, why: "Describing word + enough + to: warm enough to swim in." },
    { t: "fill", lv: "B", q: "Hui Min sang ___ beautifully that the audience clapped loudly.", a: ["so"], why: "So + describing word + that." },
    { t: "fill", lv: "B", q: "Peter is not old ___ to watch that film.", a: ["enough"], why: "Not old enough to = too young to." },
    { t: "trans", lv: "B", q: "Combine using 'too…to': Ben is very young. He cannot ride the roller coaster.", a: ["Ben is too young to ride the roller coaster."], why: "Too…to already means 'cannot', so drop 'cannot'." },
    { t: "trans", lv: "B", q: "Combine using 'too…to': The box is very heavy. I cannot lift it.", a: ["The box is too heavy for me to lift."], why: "Add 'for me' to show who cannot lift it, and drop 'it' at the end." },
    { t: "trans", lv: "B", q: "Combine using 'too…to': The bag was very expensive. Mum did not buy it.", a: ["The bag was too expensive for Mum to buy."], why: "Too expensive for Mum to buy. Do not add 'it' at the end." },
    { t: "trans", lv: "B", q: "Combine using 'so…that': The soup was very hot. I could not drink it.", a: ["The soup was so hot that I could not drink it."], why: "Replace 'very' with 'so' and join with 'that'." },
    { t: "trans", lv: "B", q: "Combine using 'so…that': Ravi ran very fast. He won the race.", a: ["Ravi ran so fast that he won the race."], why: "So fast that + the result." },
    { t: "trans", lv: "B", q: "Combine using 'enough': Mei Ling is tall. She can reach the top shelf.", a: ["Mei Ling is tall enough to reach the top shelf."], why: "Tall enough to + verb. Enough comes after 'tall'." },
    { t: "mcq", lv: "C", q: "The box was too heavy for me to ___.", o: ["carry", "carry it", "carrying", "carried"], a: 0, why: "The box is already named, so just 'carry' without 'it'." },
    { t: "mcq", lv: "C", q: "Which sentence is correct?", o: ["It was such a hot day that we went to the pool.", "It was so a hot day that we went to the pool.", "It was such hot day that we went to the pool.", "It was too hot day that we went to the pool."], a: 0, why: "Such + a + describing word + noun + that." },
    { t: "mcq", lv: "C", q: "Mr Tan is ___ to move the cupboard alone.", o: ["not strong enough", "not enough strong", "too strong", "so strong"], a: 0, why: "Enough goes after the describing word: not strong enough to." },
    { t: "mcq", lv: "C", q: "They had ___ fun at the party that they did not want to leave.", o: ["such", "so", "too", "enough"], a: 0, why: "Fun is a noun, so use such (no 'a' because fun is uncountable)." },
    { t: "fill", lv: "C", q: "It was ___ a boring talk that some pupils yawned.", a: ["such"], why: "Before 'a boring talk' (a + noun), use such." },
    { t: "fill", lv: "C", q: "The tea was ___ sweet for Grandpa to drink.", a: ["too"], why: "Too sweet for Grandpa to drink." },
    { t: "trans", lv: "C", q: "Combine using 'such…that': It was a funny film. We laughed all the way home.", a: ["It was such a funny film that we laughed all the way home."], why: "Such + a + describing word + noun + that." },
    { t: "trans", lv: "C", q: "Combine using 'such…that': The weather was hot. We stayed indoors.", a: ["It was such hot weather that we stayed indoors."], why: "Weather is uncountable, so no 'a': such hot weather." },
    { t: "trans", lv: "C", q: "Rewrite using 'too…to': The water was so cold that we could not swim in it.", a: ["The water was too cold for us to swim in.", "The water was too cold to swim in."], why: "Too…to replaces 'could not', and 'it' is dropped at the end. Keep 'in'." },
    { t: "trans", lv: "C", q: "Rewrite using 'so…that': Jun Hao was too tired to finish his homework.", a: ["Jun Hao was so tired that he could not finish his homework."], why: "With so…that, you must add 'could not' to keep the meaning." },
    { t: "trans", lv: "C", q: "Rewrite using 'enough': The rope was so short that it could not reach the ground.", a: ["The rope was not long enough to reach the ground."], why: "So short that it could not = not long enough to." },
    { t: "trans", lv: "C", q: "Rewrite using 'such…that': The test was so easy that everyone passed.", a: ["It was such an easy test that everyone passed."], why: "Such + an + easy + test. Use 'an' before a vowel sound." },
    { t: "trans", lv: "C", q: "Rewrite using 'so…that': They were such kind neighbours that everyone liked them.", a: ["The neighbours were so kind that everyone liked them.", "They were so kind that everyone liked them."], why: "So comes before the describing word alone: so kind that." },
    { t: "trans", lv: "C", q: "Combine using 'enough': Siti is old. She can take the bus alone.", a: ["Siti is old enough to take the bus alone."], why: "Old enough to + verb." },
    { t: "trans", lv: "C", q: "Rewrite using 'too…to': The shirt is so small that Dad cannot wear it.", a: ["The shirt is too small for Dad to wear."], why: "Too small for Dad to wear. No 'it' at the end." },
    { t: "trans", lv: "C", q: "Combine using 'so…that': There were many people at the MRT station. We could not get on the first train.", a: ["There were so many people at the MRT station that we could not get on the first train."], why: "So many + plural noun + that." },
    { t: "trans", lv: "C", q: "Combine using 'such…that': Grandma tells interesting stories. We never get bored.", a: ["Grandma tells such interesting stories that we never get bored."], why: "Stories is plural, so no 'a': such interesting stories." },
    { t: "trans", lv: "C", q: "Rewrite using 'enough': The hall was so big that it could hold the whole school.", a: ["The hall was big enough to hold the whole school."], why: "So big that it could = big enough to." },
    { t: "trans", lv: "C", q: "Rewrite using 'too…to': The noise was so loud that Aisha could not sleep.", a: ["The noise was too loud for Aisha to sleep."], why: "Too loud for Aisha to sleep. Too…to already means 'could not'." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'It was such': The rain was so heavy that the match was cancelled.", a: ["It was such heavy rain that the match was cancelled."], why: "Rain is uncountable here, so no 'a': such heavy rain." }
  ]
});

/* 4. Time and condition */
window.VG.push({
  id: "en-g-syn-time",
  lang: "en",
  kind: "grammar",
  group: "Synthesis and transformation",
  title: "Unless, if…not, as soon as, no sooner…than, before, after, having",
  lv: "C",
  intro: "These words join two actions to show when something happens or what must happen first. They make your writing flow instead of sounding like a list.",
  rules: [
    { h: "Before and after show order", html: "✓ I brushed my teeth <b>before</b> I went to bed.<br>✓ <b>After</b> Mei finished her homework, she watched TV.<br>You can also use -ing: <b>before going</b>, <b>after finishing</b>." },
    { h: "As soon as = immediately after", html: "✓ <b>As soon as</b> the bell rang, the pupils ran out.<br>For the future, use the present tense after it: I will call you as soon as I <b>reach</b> home." },
    { h: "Unless = if…not", html: "<b>Unless</b> already contains 'not'.<br>✓ <b>Unless</b> you hurry, you will be late.<br>✓ <b>If</b> you do <b>not</b> hurry, you will be late.<br>✗ Unless you do not hurry…" },
    { h: "No sooner had…than", html: "Turn the verb around and use <b>than</b> (not then or when).<br>✓ <b>No sooner had</b> Dad reached home <b>than</b> it started to pour." },
    { h: "Having + past participle", html: "Shows the first action is finished. The person in both parts must be the same.<br>✓ <b>Having finished</b> her lunch, Siti went out to play." }
  ],
  words: [],
  mistakes: [
    { wrong: "Unless you do not hurry, you will miss the bus.", right: "Unless you hurry, you will miss the bus.", why: "Unless already means 'if not', so do not add another 'not'." },
    { wrong: "No sooner had we sat down then the food came.", right: "No sooner had we sat down than the food came.", why: "No sooner goes with 'than', not 'then'." },
    { wrong: "No sooner Ali had opened the gate than the dog ran out.", right: "No sooner had Ali opened the gate than the dog ran out.", why: "After 'No sooner', put 'had' before the person." },
    { wrong: "I will call you as soon as I will reach home.", right: "I will call you as soon as I reach home.", why: "After 'as soon as', use the present tense for a future action." },
    { wrong: "Having finish her lunch, Siti went out to play.", right: "Having finished her lunch, Siti went out to play.", why: "Having + past form: having finished." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "Put on your shoes ___ you go out.", o: ["before", "after", "unless"], a: 0, why: "Shoes go on first, then you go out: before." },
    { t: "fill", lv: "A", q: "We had dinner ___ we watched TV. (First dinner, then TV.)", a: ["before"], why: "Dinner came first, so 'before' we watched TV." },
    { t: "mcq", lv: "B", q: "You will be late ___ you hurry.", o: ["unless", "if", "as soon as", "after"], a: 0, why: "Unless = if not: you will be late if you do not hurry." },
    { t: "mcq", lv: "B", q: "___ the rain stopped, the children ran outside.", o: ["As soon as", "Unless", "Despite", "No sooner"], a: 0, why: "The children ran out immediately after the rain stopped: as soon as." },
    { t: "mcq", lv: "B", q: "Which sentence is correct?", o: ["If you do not hurry, you will miss the bus.", "Unless you do not hurry, you will miss the bus.", "If you not hurry, you will miss the bus.", "Unless you will hurry, you will miss the bus."], a: 0, why: "If…not needs 'do not'. Unless never takes another 'not'." },
    { t: "fill", lv: "B", q: "I will call you as soon as I ___ (reach) home.", a: ["reach"], why: "After 'as soon as', use the present tense even for the future." },
    { t: "fill", lv: "B", q: "___ you finish your vegetables, you cannot have dessert.", a: ["Unless"], why: "Unless = if you do not finish." },
    { t: "trans", lv: "B", q: "Combine using 'before': I brushed my teeth. Then I went to bed.", a: ["I brushed my teeth before I went to bed.", "Before I went to bed, I brushed my teeth.", "I brushed my teeth before going to bed."], why: "Before shows which action came first. Drop 'then'." },
    { t: "trans", lv: "B", q: "Combine using 'after': Mei finished her homework. Then she watched TV.", a: ["After Mei finished her homework, she watched TV.", "Mei watched TV after she finished her homework.", "After finishing her homework, Mei watched TV."], why: "After + the first action. Use a comma if the 'after' part comes first." },
    { t: "trans", lv: "B", q: "Combine using 'as soon as': The bell rang. The pupils ran to the canteen.", a: ["As soon as the bell rang, the pupils ran to the canteen.", "The pupils ran to the canteen as soon as the bell rang."], why: "As soon as + the action that happened first." },
    { t: "trans", lv: "B", q: "Combine using 'as soon as': Aisha saw her grandmother. She hugged her.", a: ["As soon as Aisha saw her grandmother, she hugged her.", "Aisha hugged her grandmother as soon as she saw her."], why: "Seeing came first, so put 'as soon as' before it." },
    { t: "trans", lv: "B", q: "Combine using 'if…not': You must hurry. Otherwise you will miss the bus.", a: ["If you do not hurry, you will miss the bus.", "You will miss the bus if you do not hurry."], why: "'Otherwise' means 'if you do not', so use if…not." },
    { t: "trans", lv: "B", q: "Combine using 'unless': You must water the plant. Otherwise it will die.", a: ["Unless you water the plant, it will die.", "The plant will die unless you water it."], why: "Unless = if not. No extra 'not' after unless." },
    { t: "mcq", lv: "C", q: "No sooner had we sat down ___ the waiter brought our food.", o: ["than", "then", "when", "that"], a: 0, why: "No sooner always pairs with than." },
    { t: "mcq", lv: "C", q: "No sooner ___ the gate than the dog ran out.", o: ["had Ali opened", "Ali had opened", "did Ali opened", "Ali opened"], a: 0, why: "After 'No sooner', 'had' comes before the person: had Ali opened." },
    { t: "mcq", lv: "C", q: "___ finished her homework, Mei Ling went to bed.", o: ["Having", "Had", "After", "Have"], a: 0, why: "Having + finished shows the first action was complete." },
    { t: "mcq", lv: "C", q: "Unless you ___ quietly, the baby will wake up.", o: ["speak", "do not speak", "will speak", "spoke"], a: 0, why: "Unless already means 'if not', so just 'speak'." },
    { t: "fill", lv: "C", q: "No sooner had the bell rung ___ the pupils rushed out.", a: ["than"], why: "No sooner…than." },
    { t: "fill", lv: "C", q: "___ (eat) his dinner, Ahmad washed the dishes.", a: ["Having eaten"], why: "Having + past participle: having eaten." },
    { t: "trans", lv: "C", q: "Rewrite using 'unless': If you do not study, you will not pass.", a: ["Unless you study, you will not pass.", "You will not pass unless you study."], why: "Unless replaces 'if…not', so remove 'do not'." },
    { t: "trans", lv: "C", q: "Rewrite using 'if…not': Unless it rains, we will go cycling at East Coast Park.", a: ["If it does not rain, we will go cycling at East Coast Park.", "We will go cycling at East Coast Park if it does not rain."], why: "Unless it rains = if it does not rain." },
    { t: "trans", lv: "C", q: "Rewrite using 'unless': You cannot enter the pool if you do not wear a swimming cap.", a: ["You cannot enter the pool unless you wear a swimming cap.", "Unless you wear a swimming cap, you cannot enter the pool."], why: "Swap 'if you do not wear' for 'unless you wear'." },
    { t: "trans", lv: "C", q: "Rewrite using 'unless': If the weather is not fine, the sports day will be postponed.", a: ["Unless the weather is fine, the sports day will be postponed.", "The sports day will be postponed unless the weather is fine."], why: "If…not fine = unless…fine." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'No sooner': As soon as Dad reached home, it started to pour.", a: ["No sooner had Dad reached home than it started to pour."], why: "No sooner had + person + past participle + than." },
    { t: "trans", lv: "C", q: "Combine, beginning with 'No sooner': The teacher left the room. The class became noisy at once.", a: ["No sooner had the teacher left the room than the class became noisy."], why: "The first action goes after 'No sooner had'; the second after 'than'." },
    { t: "trans", lv: "C", q: "Combine, beginning with 'No sooner': Ravi reached the platform. The train doors closed at once.", a: ["No sooner had Ravi reached the platform than the train doors closed."], why: "Ravi reached first, so 'No sooner had Ravi reached…than the doors closed'." },
    { t: "trans", lv: "C", q: "Rewrite using 'as soon as': No sooner had the movie started than the lights went out.", a: ["As soon as the movie started, the lights went out.", "The lights went out as soon as the movie started."], why: "As soon as the movie started: use the simple past, no 'had'." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'Having': Siti finished her lunch. She went out to play.", a: ["Having finished her lunch, Siti went out to play."], why: "Having finished = after she had finished. Put Siti's name in the main part." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'Having': After Jun Hao had packed his bag, he left for school.", a: ["Having packed his bag, Jun Hao left for school."], why: "Having packed replaces 'after he had packed'." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'Having': Peter had seen the film before, so he did not want to watch it again.", a: ["Having seen the film before, Peter did not want to watch it again."], why: "Having seen gives the reason; drop 'so'." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'After': Having watered the plants, Grandma made some tea.", a: ["After Grandma had watered the plants, she made some tea.", "After watering the plants, Grandma made some tea.", "After Grandma watered the plants, she made some tea."], why: "After + the first action, then the second action." },
    { t: "trans", lv: "C", q: "Rewrite, beginning with 'Before': Lina switched off the fan and then she left the room.", a: ["Before Lina left the room, she switched off the fan.", "Before leaving the room, Lina switched off the fan."], why: "Before + the later action, then the earlier action." },
    { t: "trans", lv: "C", q: "Combine using 'before': Kumar locked the gate. Then he went upstairs.", a: ["Kumar locked the gate before he went upstairs.", "Before going upstairs, Kumar locked the gate.", "Kumar locked the gate before going upstairs."], why: "Before shows which action happened first." }
  ]
});

/* 5. Relative pronouns, reported speech, passive */
window.VG.push({
  id: "en-g-syn-relative",
  lang: "en",
  kind: "grammar",
  group: "Synthesis and transformation",
  title: "Joining with who, which, whose (and with reported speech and passive)",
  lv: "C",
  intro: "Who, which and whose let you join two sentences about the same person or thing. Reported speech and the passive are two more ways to rewrite a sentence without changing its meaning.",
  rules: [
    { h: "Who for people, which for things and animals", html: "✓ I have a friend <b>who</b> speaks three languages.<br>✓ Dad bought a car <b>which</b> is red." },
    { h: "Whose shows belonging", html: "<b>Whose</b> replaces his, her, its or their.<br>That is the girl. <b>Her</b> cat went missing.<br>✓ That is the girl <b>whose</b> cat went missing." },
    { h: "Do not repeat the person or thing", html: "✗ The boy <b>who he</b> is wearing a cap is my cousin.<br>✓ The boy <b>who</b> is wearing a cap is my cousin." },
    { h: "Reported speech: move back one tense", html: "Remove the quotation marks, add <b>that</b> if you like, and change the tense and pronouns.<br>is → <b>was</b>, will → <b>would</b>, saw → <b>had seen</b>, can → <b>could</b><br>✓ Ravi said, \"I am hungry.\" → Ravi said that <b>he was</b> hungry.<br>Time words change too: tonight → that night, yesterday → the day before." },
    { h: "Reported commands and questions", html: "Commands: <b>told + person + to</b> (or <b>not to</b>).<br>✓ The teacher told us <b>to close</b> our books.<br>Questions: no question mark; normal word order; use <b>if/whether</b> for yes/no questions.<br>✓ Siti asked me where the library <b>was</b>." },
    { h: "Passive: the thing comes first", html: "Object + <b>be</b> + past participle + <b>by</b> + doer.<br>✓ The cat broke the vase. → The vase <b>was broken by</b> the cat.<br>Keep the same tense: is taught, is being painted, has been stolen." }
  ],
  words: [],
  mistakes: [
    { wrong: "The boy who he is wearing a cap is my cousin.", right: "The boy who is wearing a cap is my cousin.", why: "'Who' already stands for the boy, so drop 'he'." },
    { wrong: "That is the boy who's bicycle was stolen.", right: "That is the boy whose bicycle was stolen.", why: "Whose shows belonging. Who's means 'who is'." },
    { wrong: "Siti asked me where was the library.", right: "Siti asked me where the library was.", why: "In reported questions, use normal order: the library was." },
    { wrong: "The teacher said us to close our books.", right: "The teacher told us to close our books.", why: "Use 'told + person + to' for commands." },
    { wrong: "The vase was broke by the cat.", right: "The vase was broken by the cat.", why: "The passive needs the past participle: broken." }
  ],
  items: [
    { t: "mcq", lv: "A", q: "The girl ___ sits next to me is kind.", o: ["who", "which", "whose"], a: 0, why: "The girl is a person, so use who." },
    { t: "mcq", lv: "B", q: "This is the bag ___ I bought at the mall.", o: ["which", "who", "whose", "whom"], a: 0, why: "A bag is a thing, so use which." },
    { t: "fill", lv: "B", q: "The man ___ car is parked outside is my uncle.", a: ["whose"], why: "The car belongs to the man, so use whose." },
    { t: "trans", lv: "B", q: "Combine using 'who': I have a friend. She can speak three languages.", a: ["I have a friend who can speak three languages."], why: "Who replaces 'she', so do not keep 'she'." },
    { t: "trans", lv: "B", q: "Combine using 'which': Dad bought a car. It is red.", a: ["Dad bought a car which is red.", "The car which Dad bought is red."], why: "Which replaces 'it' for things." },
    { t: "trans", lv: "B", q: "Combine using 'who': The boy is my cousin. He is wearing a blue cap.", a: ["The boy who is wearing a blue cap is my cousin."], why: "Put 'who' right after 'the boy', then finish the main sentence." },
    { t: "trans", lv: "B", q: "Combine using 'which': The book is on the table. It belongs to Mei.", a: ["The book which is on the table belongs to Mei.", "The book which belongs to Mei is on the table."], why: "Which comes right after 'the book'." },
    { t: "trans", lv: "B", q: "Change to the passive: Ali kicked the ball.", a: ["The ball was kicked by Ali."], why: "The ball comes first + was kicked + by Ali." },
    { t: "mcq", lv: "C", q: "That is the boy ___ bicycle was stolen.", o: ["whose", "who", "which", "who's"], a: 0, why: "The bicycle belongs to the boy, so use whose. Who's means 'who is'." },
    { t: "mcq", lv: "C", q: "She said, \"I am tired.\" → She said that she ___ tired.", o: ["was", "is", "am", "were"], a: 0, why: "Move back one tense: am → was." },
    { t: "mcq", lv: "C", q: "The windows ___ by the cleaner every Friday.", o: ["are cleaned", "clean", "are cleaning", "cleaned"], a: 0, why: "Passive in the present: are + cleaned." },
    { t: "mcq", lv: "C", q: "Our teacher asked us ___ quiet.", o: ["to be", "be", "being", "we are"], a: 0, why: "Asked/told + person + to: asked us to be quiet." },
    { t: "fill", lv: "C", q: "The cake was baked ___ my sister.", a: ["by"], why: "In the passive, 'by' tells us who did the action." },
    { t: "fill", lv: "C", q: "Mum told me ___ tidy my room.", a: ["to"], why: "Told + person + to + verb." },
    { t: "fill", lv: "C", q: "Wei asked, \"Are you ready?\" → Wei asked ___ I was ready.", a: ["if", "whether"], why: "Yes/no questions are reported with if or whether." },
    { t: "trans", lv: "C", q: "Combine using 'whose': That is the girl. Her cat went missing.", a: ["That is the girl whose cat went missing."], why: "Whose replaces 'her'." },
    { t: "trans", lv: "C", q: "Combine using 'whose': Mr Lim is our neighbour. His son plays football for the school.", a: ["Mr Lim is our neighbour whose son plays football for the school.", "Mr Lim, whose son plays football for the school, is our neighbour."], why: "Whose replaces 'his'." },
    { t: "trans", lv: "C", q: "Combine using 'whose': The pupil has been given a prize. Her essay was the best.", a: ["The pupil whose essay was the best has been given a prize."], why: "Put 'whose essay was the best' straight after 'the pupil'." },
    { t: "trans", lv: "C", q: "Combine using 'who': The lady lives on the tenth floor. She sells nasi lemak at the hawker centre.", a: ["The lady who lives on the tenth floor sells nasi lemak at the hawker centre.", "The lady who sells nasi lemak at the hawker centre lives on the tenth floor."], why: "Who replaces 'she' and comes right after 'the lady'." },
    { t: "trans", lv: "C", q: "Combine using 'which': We visited the Botanic Gardens. They are very beautiful.", a: ["We visited the Botanic Gardens, which are very beautiful."], why: "Which replaces 'they' for places and things." },
    { t: "trans", lv: "C", q: "Combine using 'who' or 'whom': I met the doctor. Mum spoke to him yesterday.", a: ["I met the doctor who Mum spoke to yesterday.", "I met the doctor whom Mum spoke to yesterday.", "I met the doctor to whom Mum spoke yesterday."], why: "Who/whom replaces 'him', so drop 'him'." },
    { t: "trans", lv: "C", q: "Change to reported speech: Ravi said, \"I am hungry.\"", a: ["Ravi said that he was hungry.", "Ravi said he was hungry."], why: "I → he, am → was." },
    { t: "trans", lv: "C", q: "Change to reported speech: Mum said, \"I will cook curry tonight.\"", a: ["Mum said that she would cook curry that night.", "Mum said she would cook curry that night."], why: "will → would, tonight → that night." },
    { t: "trans", lv: "C", q: "Change to reported speech: Kumar said, \"I saw a monitor lizard yesterday.\"", a: ["Kumar said that he had seen a monitor lizard the day before.", "Kumar said that he had seen a monitor lizard the previous day.", "Kumar said he had seen a monitor lizard the day before."], why: "saw → had seen, yesterday → the day before." },
    { t: "trans", lv: "C", q: "Change to reported speech: The teacher said to us, \"Close your books.\"", a: ["The teacher told us to close our books."], why: "A command becomes told + person + to. Your → our." },
    { t: "trans", lv: "C", q: "Change to reported speech: \"Don't run along the corridor,\" the prefect told the boys.", a: ["The prefect told the boys not to run along the corridor."], why: "A 'don't' command becomes 'not to'." },
    { t: "trans", lv: "C", q: "Change to reported speech: Siti asked me, \"Where is the library?\"", a: ["Siti asked me where the library was."], why: "No question mark; normal order (the library was); is → was." },
    { t: "trans", lv: "C", q: "Change to reported speech: Ben asked me, \"Can I borrow your ruler?\"", a: ["Ben asked me if he could borrow my ruler.", "Ben asked me whether he could borrow my ruler."], why: "Yes/no question → if/whether. can → could, I → he, your → my." },
    { t: "trans", lv: "C", q: "Change to the passive: The cat broke the vase.", a: ["The vase was broken by the cat."], why: "Past tense passive: was + broken." },
    { t: "trans", lv: "C", q: "Change to the passive: Mrs Tan teaches our class.", a: ["Our class is taught by Mrs Tan."], why: "Present tense passive: is + taught." },
    { t: "trans", lv: "C", q: "Change to the passive: Workers are painting the HDB block.", a: ["The HDB block is being painted by workers.", "The HDB block is being painted."], why: "Are painting → is being painted (the block is one thing)." },
    { t: "trans", lv: "C", q: "Change to the passive: Someone has stolen my bicycle.", a: ["My bicycle has been stolen.", "My bicycle has been stolen by someone."], why: "Has stolen → has been stolen. 'By someone' can be left out." },
    { t: "trans", lv: "C", q: "Change to the active: The letter was posted by Aisha.", a: ["Aisha posted the letter."], why: "The doer (Aisha) comes first, and the verb goes back to 'posted'." }
  ]
});

/* 6. Editing */
window.VG.push({
  id: "en-g-editing",
  lang: "en",
  kind: "grammar",
  group: "Sentences and punctuation",
  title: "Editing: spot and fix grammar and spelling mistakes",
  lv: "B",
  intro: "Good writers always check their work. In editing, each sentence has one mistake: it may be a spelling slip or a grammar slip. Find it and fix it.",
  rules: [
    { h: "Read slowly, word by word", html: "Point to each word. Say it in your head. Many mistakes hide in small words like <b>is/are</b> and <b>was/were</b>." },
    { h: "Check the verb and its subject", html: "One person or thing → <b>he goes</b>, <b>she has</b>, <b>it was</b>.<br>More than one → <b>they go</b>, <b>we were</b>.<br>✗ He go to school. ✓ He <b>goes</b> to school." },
    { h: "Check the tense", html: "Look for time words: <b>yesterday</b> → past; <b>every day</b> → present.<br>✗ Yesterday Ravi buyed a pen. ✓ Yesterday Ravi <b>bought</b> a pen." },
    { h: "Spelling tricks", html: "<b>i before e except after c</b>: friend, believe, but <b>receive</b>.<br>Double letters: <b>tomorrow</b> (one m, two r), <b>difficult</b>, <b>beginning</b>.<br>Silent or tricky letters: <b>because</b>, <b>beautiful</b>, <b>Wednesday</b>." },
    { h: "Tricky words to remember", html: "Each / everyone / neither of → <b>singular</b> verb.<br><b>news</b> is singular: The news <b>is</b> good.<br>Do not use <b>more</b> with -er: ✗ more taller ✓ taller." }
  ],
  words: [],
  mistakes: [
    { wrong: "He go to school by bus.", right: "He goes to school by bus.", why: "He is one person, so the verb needs -es: goes." },
    { wrong: "I recieved a letter.", right: "I received a letter.", why: "After c, write e before i: receive." },
    { wrong: "Yesterday, Ravi buyed a pen.", right: "Yesterday, Ravi bought a pen.", why: "Buy is irregular: buy → bought." },
    { wrong: "Everyone in the class have a library card.", right: "Everyone in the class has a library card.", why: "Everyone is singular, so use has." },
    { wrong: "My sister is more taller than me.", right: "My sister is taller than me.", why: "Taller already means 'more tall', so drop 'more'." }
  ],
  items: [
    { t: "fix", lv: "A", q: "He go to school by bus every day.", err: "go", a: "goes", why: "He is one person, so add -es: goes." },
    { t: "fix", lv: "A", q: "I recieved a letter from my grandmother.", err: "recieved", a: "received", why: "i before e, except after c: received." },
    { t: "fix", lv: "A", q: "She have two brothers.", err: "have", a: "has", why: "She is one person, so use has." },
    { t: "fix", lv: "A", q: "We saw three mouses in the store room.", err: "mouses", a: "mice", why: "The plural of mouse is mice." },
    { t: "mcq", lv: "A", q: "Which word is spelt correctly?", o: ["Wednesday", "Wensday", "Wednsday"], a: 0, why: "Wednesday has a silent d: Wed-nes-day." },
    { t: "fill", lv: "A", q: "Yesterday, we ___ (swim) in the pool.", a: ["swam"], why: "Yesterday means past tense: swim → swam." },
    { t: "fix", lv: "B", q: "Yesterday, Ravi buyed a new pencil case.", err: "buyed", a: "bought", why: "Buy is irregular: buy → bought." },
    { t: "fix", lv: "B", q: "My freind lives in Bedok.", err: "freind", a: "friend", why: "Friend: i before e. Remember 'a fri-END to the END'." },
    { t: "fix", lv: "B", q: "The children was playing at the playground.", err: "was", a: "were", why: "Children is plural, so use were." },
    { t: "fix", lv: "B", q: "Mum went to the hawker centre becuase she was hungry.", err: "becuase", a: "because", why: "Because: Big Elephants Can Always Understand Small Elephants." },
    { t: "fix", lv: "B", q: "Aisha and me went to the library after school.", err: "me", a: "I", why: "Aisha and I did the action, so use I. (Try it alone: I went, not me went.)" },
    { t: "fix", lv: "B", q: "We was late for the school assembly.", err: "was", a: "were", why: "We is plural, so use were." },
    { t: "fix", lv: "B", q: "I am going to the dentist tommorow.", err: "tommorow", a: "tomorrow", why: "Tomorrow has one m and two r's." },
    { t: "fix", lv: "B", q: "There is many people at the MRT station.", err: "is", a: "are", why: "Many people is plural, so use are." },
    { t: "fix", lv: "B", q: "Jun Hao runned all the way home.", err: "runned", a: "ran", why: "Run is irregular: run → ran." },
    { t: "fix", lv: "B", q: "The teacher gave us a dificult question.", err: "dificult", a: "difficult", why: "Difficult has double f." },
    { t: "fix", lv: "B", q: "Everyone in the class have a library card.", err: "have", a: "has", why: "Everyone is singular, so use has." },
    { t: "fix", lv: "B", q: "My sister is more taller than me.", err: "more taller", a: "taller", why: "Taller already means 'more tall', so drop 'more'." },
    { t: "fix", lv: "B", q: "He did not finished his homework.", err: "finished", a: "finish", why: "After did / did not, use the base verb: finish." },
    { t: "fix", lv: "B", q: "Grandpa enjoys to walk in the park.", err: "to walk", a: "walking", why: "After enjoy, use the -ing form: enjoys walking." },
    { t: "fix", lv: "B", q: "It was a beatiful morning at East Coast Park.", err: "beatiful", a: "beautiful", why: "Beautiful: b-e-a-u. Big Elephants Are Ugly." },
    { t: "mcq", lv: "B", q: "Which sentence has no mistakes?", o: ["My brother plays football every Saturday.", "My brother play football every Saturday.", "My brother plays footbal every Saturday.", "My brother playing football every Saturday."], a: 0, why: "One brother → plays, and football has double l." },
    { t: "mcq", lv: "B", q: "Which word is spelt correctly?", o: ["necessary", "neccessary", "necesary", "neccesary"], a: 0, why: "Necessary: one collar (c), two sleeves (ss)." },
    { t: "fill", lv: "B", q: "Fix the spelling: begining → ___", a: ["beginning"], why: "Begin + ing: double the n because the stress is on 'gin'." },
    { t: "fill", lv: "B", q: "Mei Ling ___ (watch) TV every evening.", a: ["watches"], why: "One person, every evening → present tense with -es: watches." },
    { t: "fix", lv: "C", q: "Neither of the boys were ready for the test.", err: "were", a: "was", why: "Neither of = not one of them, so it is singular: was." },
    { t: "fix", lv: "C", q: "The pupils were seperated into four groups.", err: "seperated", a: "separated", why: "Separate has 'a rat' in it: sep-a-rat-e." },
    { t: "fix", lv: "C", q: "If I was you, I would apologise to her.", err: "was", a: "were", why: "For an imagined situation, we say 'If I were you'." },
    { t: "fix", lv: "C", q: "She has went to the market already.", err: "went", a: "gone", why: "After has/have, use the past participle: gone." },
    { t: "fix", lv: "C", q: "The team was dissapointed when they lost the final.", err: "dissapointed", a: "disappointed", why: "Disappointed: dis + appoint, so one s and double p." },
    { t: "fix", lv: "C", q: "The news are shocking.", err: "are", a: "is", why: "News is singular even though it ends in s." },
    { t: "fix", lv: "C", q: "The museum was full of intresting exhibits.", err: "intresting", a: "interesting", why: "Interesting: in-ter-est-ing. Do not drop the e." },
    { t: "mcq", lv: "C", q: "Which sentence has no mistakes?", o: ["Neither Ali nor his friends were at the void deck.", "Neither Ali nor his friends was at the void deck.", "Neither Ali or his friends were at the void deck.", "Niether Ali nor his friends were at the void deck."], a: 0, why: "Neither…nor, the nearer subject (friends) is plural → were, and neither is spelt e-i." }
  ]
});
